### ISSUE TITLE
Delete Case

### ISSUE THREAD

**Issue by CodyBr** [TheHive-Project/TheHive#100]
### Request Type
Simple question

### Problem Description
Hi everybody,

I saw that it was possible with the curl command to delete a case.
In that case, where is he going? Can we find him somewhere? If we click on the case in the logs to rights we arrive on it so it is always present?
Can I delete a case with ui or only in command mode?

Regards.

**Comment by nadouani** [comment]
We do soft delete, the case status is marked as DELETED, but the data is not removed.

Currently, the cases cannot be deleted from the UI. We will probably add this feature

Thanks

**Comment by bullerdude** [comment]
Team, how do you perform the soft delete?

Without the ability to delete cases it make it hard to test the system after upgrade/changes as those test cases will appear as real cases.

An alternative would be to add a close type of 'test' that would ensure the case is clearly marked as test and not used in any metric calculations etc.

**Comment by nadouani** [comment]
We will provide a feature to "Delete a case" from the UI, but as I said, it's just "marking the case with a special DELETED status". This status should be taken into account everywhere in the app, and we need to make sure DELETED cases are ignored.

**Comment by mthlvt** [comment]
Hi @nadouani and team,

Is there any plan to manage Deleted cases? So far the "deleted" cases are not ignored in the app, especially in the stats.

Thanks !!

**Comment by nadouani** [comment]
@mthlvt Hello, if you think that the "Deleted" cases are not ignored in the stats, please fill in an issue, because it should not.

**Comment by mthlvt** [comment]
it is not ignored in version 2.12.1, see issue #317

**Comment by woifi** [comment]
I think this is an important feature request - please put it on the roadmap! :)
