### ISSUE TITLE
API not recognizing the attribute 'sighted' of artifacts on alert creation

### ISSUE THREAD

**Issue by mgabriel-silva** [TheHive-Project/TheHive#1003]
### Request Type
Enhancement

### Problem Description
API returning AttributeCheckingError when using the attribute "sighted" in artifacts on alert creation.
Error:
```
{"tableName":"alert","type":"AttributeCheckingError","errors":[{"name":"alert.artifacts","type":"UnknownAttributeError","message":"Unknown attribute alert.artifacts: {\"type\":\"JsonInputValue\",\"value\":{\"dataType\":\"ip\",\"data\":\"127.0.0.1\",\"message\":\"localhost\",\"ioc\":true,\"sighted\":true}}","value":{"type":"JsonInputValue","value":{"dataType":"ip","data":"127.0.0.1","message":"localhost","ioc":true,"sighted":true}}}]}
```

**Comment by nadouani** [comment]
`sighted` is probably not an attribute of `Alert` artifact in fact. We could allow it.

**Comment by mgabriel-silva** [comment]
I did a new test. Actually is more serious than that
In addition to not shoing on 'IOCs', it is not counting towards 'Observables' [0% (0/1)] of the similar case (as show in the screenshots)

![alert](https://user-images.githubusercontent.com/38086610/59372871-cf6be200-8d1e-11e9-8c40-81b1896768e4.JPG)
![case](https://user-images.githubusercontent.com/38086610/59372872-d0047880-8d1e-11e9-9378-2d22212e60ad.JPG)
