### ISSUE TITLE
[Webhooks] Add an event of Alert Artifact Creation

### ISSUE THREAD

**Issue by mgabriel-silva** [TheHive-Project/TheHive#1009]
### Request Type
Feature Request

### Problem Description
Add a webhooks event of Alert Artifact Creation (and Update?)
Needs #1005

**Comment by nadouani** [comment]
Alert artifacts are not handles like case observables, they dont exist in their own table, but are part of the alert definition. So there is no event related to the `Alert Artifact Creation`, it's part of the `Alert Update` event.

Events are generated by the lowest  layer of the backend architecture: database access, and not API layer. So even if we add an API to make this artifact creation possible, it will just make an Alert update.
