### ISSUE TITLE
Webhook for observable marked as IOC

### ISSUE THREAD

**Issue by mpotgieter** [TheHive-Project/TheHive#1012]
### Feature Request
It would be useful to have webhook for when an observable is marked as an IOC. I see there is a webhook for CaseArtifactUpdate, so maybe its already possible, but then one would have to filter all artifact updates and look for IOC change (if that information is actually returned).

Use cases would include:
- adding artifact to some sort of threatintel platform (if MISP is not in use)
- doing automated retrospective search for newly identified IOC.
- Trigger some other response action based on if the IOC is sighted.

**Comment by crackytsi** [comment]
Hi!
I Think to much webhooks will slow down the system.
This should be included in caseartifactcreate and ...update.
So it's just applying a filter to get what you want.

**Comment by mpotgieter** [comment]
I didn't understand that web hooks will have such an impact on performance. There are also some other options to get this done. Probably better if efforts are focused on more important features.
Thanks for input!

**Comment by nadouani** [comment]
> I didn't understand that web hooks will have such an impact on performance

Why Webhooks would have a performance impact?

To check "Artifact Marked As IOC" event, you just have to listen to `CaseArtifactUpdate` and check if the `event.details.ioc` is defined. That's it.

**Comment by nadouani** [comment]
Closing the issue, if there is any other question related to it, please feel free to ask, and I'll reopen it.

Thanks
