### ISSUE TITLE
Using Cortex within TheHive

### ISSUE THREAD

**Issue by martinacen** [TheHive-Project/TheHive#1017]
### Request Type
Feature Request

### Work Environment
Ubuntu 18.04.2 LTS
TheHive installed by DEB
Cortex installed by DEB

### Problem Description
I installed TheHive in order to have more information about files analyzed by Cortex (even if I have a problem with starting TheHive but I wrote a separate post for it). 
I know how to use Cortex but, I have not understand how to use TheHive within Cortex in order to show its reports in a better view. Unfortunately, I haven't found any guide or tutorial about it.

### Complementary information
As Cortex analyzers I need to use Virus Share and Hybrid Analysis.

Thank you for your help!

**Comment by saadkadhi** [comment]
@martinacen this is not a feature request but a usage question which should be answered in our existing documentation.

You cannot use TheHive within Cortex. It's the other way around. TheHive relies on Cortex for analysis and active response. If you want to use the VirusShare and HybridAnalysis analyzers:

1. Make sure you have fullfilled the [requirements](https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md#virusshare) for the Virusshare analyzer
2. Make you sure you [do the same](https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md#hybridanalysis) for HybridAnalysis
3. [Configure](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#6-cortex) TheHive to use your Cortex instance

You should then see, in TheHive, both analyzers when selecting observables which datatypes correspond to those expected by Virusshare and HybridAnalysis and running analyzers on them.
