### ISSUE TITLE
TheHive to IBM i2 (API, theHive4py, Analyzer or Responders)

### ISSUE THREAD

**Issue by minhanh1234** [TheHive-Project/TheHive#1019]
Have anyone have any experience pushing theHive data to IBM i2?
using API, theHive4py, Analyzer, Python Scritp or Responders

**Comment by crackytsi** [comment]
I haven't, but I think is strongly depends on your business case.
TheHive is quite open, as you can use webooks, API  (wrapped by TheHive4py, go etc.) or even al layer above extracting data directly from Elastic-search and push it to your system.
So I don't think that there is a solution that exactly maches your business needs.

**Comment by nadouani** [comment]
Hello, there is no native integration between TheHive and IBM i2, and as said by @crackytsi things depend on what you want to achieve. You can play with TheHive apis as you want.

**Comment by veeral-patel** [comment]
@minhanh1234 Hey - tell me more about your use case, if you don't mind!

I'm curious to learn why you want to push to IBM I2, which seems like a SIEM; most people want to create cases in TheHive for their alerts in their SIEM.
