### ISSUE TITLE
can't add custom fields to case in 3.4.0-RC1

### ISSUE THREAD

**Issue by github-pba** [TheHive-Project/TheHive#1026]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu
| OS version (client)       |  Win 7
| TheHive version / git hash   | 3.4RC1
| Package Type              |  DEB

### Problem Description
In 3.4.0-RC1, the plus sign to edit a case's additional information is gone. As a result, a user can't add custom fields

### Steps to Reproduce
1. Screenshot 3.3.0
![330](https://user-images.githubusercontent.com/50981940/60323285-ebf45500-9981-11e9-8616-2a6c7e8a9b82.png)

1. Screenshot 3.4.0-RC1
![340RC1](https://user-images.githubusercontent.com/50981940/60323313-062e3300-9982-11e9-9d15-b8d8b6f3c897.png)

**Comment by nadouani** [comment]
Thanks for catching this, I'll take a look on it.

**Comment by nadouani** [comment]
It looks like you don't have any custom field defined, ready to be added to your case :no_good: :relaxed:

Can you confirm this?

**Comment by github-pba** [comment]
Oh. My. God.

You're right. My fault. If I define a custom field, the plus sign to add it is there.

![2019-06-28_174637](https://user-images.githubusercontent.com/50981940/60354552-c04a8c80-99cc-11e9-89c4-c08318c3e3cb.png)

There is probably no way we can delete this entire issue, so nobody ever gets aware of my failure?

I apologize for wasting your time!

**Comment by nadouani** [comment]
Don't worry, that happens to all of us 👍
