### ISSUE TITLE
thehive prints error messages on first run ("Authentication failure" / "user init not found")

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/TheHive#1027]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | -
| OS version (client)       | -
| TheHive version / git hash   | -
| Package Type              | Docker
| Browser type & version    | -

### Problem Description
TheHive prints several errors on the first run. I cannot determine whethere these are actual errors, or error messages for things that shouldn't be errors.

### Steps to Reproduce
1. Download docker-compose file from official docs, apply fix for https://github.com/TheHive-Project/Cortex/issues/203
2. `docker-compose up`
3. Wait until elastic, thehive and cortex have started
4. Open localhost:9000 in your browser, click "Update Database", wait
5. Register a user

### Complementary information
[docker-compose output](http://pastebin.com/raw/5YGe4mm3)

**Comment by To-om** [comment]
The issue is solved by thehive-project/elastic4play#90
