### ISSUE TITLE
sample hive does not connect to cortex and prints no helpful error message

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/TheHive#1028]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | -
| OS version (client)       | -
| TheHive version / git hash   | -
| Package Type              | Docker
| Browser type & version    | -

### Problem Description
If you use the [sampe docker-compose.yml](https://hub.docker.com/r/thehiveproject/thehive/), thehive fails to talk to cortex ("about" page says "AUTH_ERROR"), and prints no helpful error messages. The sample files should work, and thehive should emit meaningful error messages if it fails to establish a connection.

### Steps to Reproduce
1. Download docker-compose file from official docs, apply fix for https://github.com/TheHive-Project/Cortex/issues/203
2. `docker-compose up`
3. Wait until elastic, thehive and cortex have started
4. Open localhost:9000 in your browser, click "Update Database", wait, register
5. Open localhost:9001 in your browser, click "Update Database", wait
6. Wait a bit, check thehive's about page and observe its output

### Complementary information
[docker-compose output](http://pastebin.com/raw/G6KY5d2Y)

**Comment by To-om** [comment]
TheHive can use Cortex if you create an account in Cortex and configure TheHive with it:
 - after database update, go to Cortex administration page, create an organization and a user with, at least "analyze" role. Create an API key for that user.
 - update your docker-compose.yml and add `command: --cortex-key **KEY**` in thehive section (under "image: thehiveproject/thehive"). Obviously replace **KEY** by the key from Cortex.
 - restart services and it should work.
