### ISSUE TITLE
Alerts imported as cases using templates doesn't get the template's severity, TLP and PAP

### ISSUE THREAD

**Issue by mgabriel-silva** [TheHive-Project/TheHive#1029]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3.0-1

### Problem Description
Alerts imported as cases using templates doesn't get the template's severity, TLP and PAP

### Steps to Reproduce
1. Create an alert with TLP and PAP amber, and severity M
2. Import the alert using a template with TLP and PAP green, and severity L (example)
3. The new case is TLP and PAP amber, and severity M instead of template's.

**Comment by nadouani** [comment]
What are the TLP and PAP values of you Alert? Is the new case getting the TLP and PAP of the Alert?

**Comment by mgabriel-silva** [comment]
The alert was TLP and PAP amber.
The case is getting the TLP, PAP and severity from the alert.
But it seems to me that it should get them from the template and not from the alert.
I think the template should define the case attributes, the alert is only a generic... well... alert.

**Comment by crackytsi** [comment]
From my point of vie the alert is more specific than a (generic) can be.

**Comment by nadouani** [comment]
@crackytsi +1

The template is used as default, but the Alert attributes are more important. If you have a Phishing Alert with TLP:RED, you want it to stay RED instead of the default case template TLP
