### ISSUE TITLE
Customizing TheHive JVM options

### ISSUE THREAD

**Issue by christophetd** [TheHive-Project/TheHive#1031]
# Customizing TheHive JVM options
### Request Type

Question

### Work Environment

Docker

### Problem Description

Is it possible to customize JVM arguments used to run TheHive? Especially `Xmx` and `Xms`

### Possible Solutions

Change the entrypoint (https://github.com/TheHive-Project/TheHive/blob/master/package/docker/entrypoint) to allow for custom JVM options

**Comment by nadouani** [comment]
What about providing a custom value for `JAVA_OPTS` env variable?

**Comment by christophetd** [comment]
Works like a charm, thank you.
