### ISSUE TITLE
No Synchronization on Thehive with MISP

### ISSUE THREAD

**Issue by ananth07reddy** [TheHive-Project/TheHive#1032]
I have configured MISP in the hive application config and I see the green circle as configured well but I don't see any alerts in the hive dashboard. Am I missing something here? Please help me out.

I am using MISP- 2.4.109  and the hive 3.0.0-RC3 versions. My MISP config as follows

play.modules.enabled += connectors.misp.MispConnector

    misp {
      # Interval between consecutive MISP event imports in hours (h) or
      # minutes (m).
      "misp-server-id" {
        url = "https://********************"
        key = "**********"
      # Name of the case template in TheHive that shall be used to import
      # MISP events as cases by default.
        caseTemplate = "MISP-Events"
        tags = ["misp"]
      #  # Optional tags to add to each observable  imported  from  an  event
      #  # available on this instance.
      } 

      interval = 1h
    }

**Comment by nadouani** [comment]
Does your MISP user have the `sync` permission?

**Comment by ananth07reddy** [comment]
> Does your MISP user have the `sync` permission?

Yes. I am using admin token because when I create a user with only sync permission, it is not synchronizing well. For now, I am using admin token which has all the permissions. I don't know what went wrong.

**Comment by nadouani** [comment]
Do you have published events? TheHive will pick only published events

**Comment by ananth07reddy** [comment]
> Do you have published events? TheHive will pick only published events

Yes. I have published events in the MISP in recent days too. And also I have tried to change max-age = 7days but I don't see any alerts.

**Comment by nadouani** [comment]
Do you see any errors in the logs? something that can help investigate, because I don't know how we can troubleshoot this without a better context

**Comment by ananth07reddy** [comment]
> Do you see any errors in the logs? something that can help investigate, because I don't know how we can troubleshoot this without a better context

I see that the log saying "MISP sync is failed" but in thehive it is **green**. Please find the logs as below:

[info] c.m.MispConnection - Add MISP connection misp-server-id
  url:              http://***************
  proxy:            None
  case template:    MISP-EVENT
  artifact tags:    misp
  filters:
    max age:        <not set>
    max attributes: <not set>
    max size:       <not set>
    excluded orgs:  
    excluded tags:  
    whitelist tags: 
  purpose:          ImportAndExport
 [warn] o.e.c.RestClient - request [HEAD http://*******************/the-hive_15] returned 1 warnings: [299 Elasticsearch-6.8.0-65b6179 "[types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."]
[info] c.m.MispSynchro - Update of MISP events is starting ...
[info] play.api.Play - Application started (Prod)
[info] c.c.s.CortexAnalyzerSrv - 0 jobs found
[info] c.m.MispSynchro - Last synchronization of MISP misp-server-id is Thu Jan 01 00:00:00 UTC 1970, synchronize from Thu Jan 01 00:00:00 UTC 1970
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000
[info] c.m.MispSynchro - **Misp synchronization failed**
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'upstream': was expecting ('true', 'false' or 'null')
 at [Source: (String)"upstream request timeout"; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:679)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:272)
	at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:16)

**Comment by nadouani** [comment]
The green button means TheHive can reach MISP from a connectivity and authentication perspective.

The error says: `upstream request timeout`, TheHive is expecting a JSON response from the MISP api call but it's getting `upstream request timeout` response body?

Any logs on MISP side?

**Comment by nadouani** [comment]
Do you have a reverse proxy in front of MISP, which can return a Timeout error?

**Comment by ananth07reddy** [comment]
> The green button means TheHive can reach MISP from a connectivity and authentication perspective.
> 
> The error says: `upstream request timeout`, TheHive is expecting a JSON response from the MISP api call but it's getting `upstream request timeout` response body?
> 
> Any logs on MISP side?

I don't see error logs in MISP.

**Comment by ananth07reddy** [comment]
> Do you have a reverse proxy in front of MISP, which can return a Timeout error?

Yes. I have ambassador gateway and changed the timeout to 60000 ms

**Comment by nadouani** [comment]
So that's the entity that fires the timeout. You have the solution. 

I'll let you close the issue when your problem is solved 

Cheers

**Comment by ananth07reddy** [comment]
Now, I don't see any errors and failures but still not getting alerts to thehive

[info] c.m.MispConnection - Add MISP connection misp-server-id
  url:              http://*******************
  proxy:            None
  case template:    MISP-EVENT
  artifact tags:    misp
  filters:
    max age:        <not set>
    max attributes: <not set>
    max size:       <not set>
    excluded orgs:  
    excluded tags:  
    whitelist tags: 
  purpose:          ImportAndExport
 [warn] o.e.c.RestClient - request [HEAD http:/*********************/the-hive_15] returned 1 warnings: [299 Elasticsearch-6.8.0-65b6179 "[types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."]
[info] c.m.MispSynchro - Update of MISP events is starting ...
[info] c.c.s.CortexAnalyzerSrv - 0 jobs found
[info] c.m.MispSynchro - Last synchronization of MISP misp-server-id is Thu Jan 01 00:00:00 UTC 1970, synchronize from Thu Jan 01 00:00:00 UTC 1970
[info] play.api.Play - Application started (Prod)
[info] c.m.MispSynchro - **Misp synchronization completed**
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000

**Comment by nadouani** [comment]
Can you update `/etc/thehive/logback.xml` and add the following line:

```
<logger name="connectors.misp" level="DEBUG" />
```

to make the misp connector more verbose and see what is happening?

**Comment by saadkadhi** [comment]
Have you tried with the latest stable version of TheHive (3.3.1)? You are using an old beta...

**Comment by ananth07reddy** [comment]
> Have you tried with the latest stable version of TheHive (3.3.1)? You are using an old beta...

I am using thehive version 3.4.0-RC1

**Comment by ananth07reddy** [comment]
I have changed the permissions of the application.conf volume mounts config and it worked. Now I see the alerts in thehive.

Thanks for your assistance.

**Comment by ashmaind** [comment]
Hi ananth07reddy, can you please elaborate what steps you followed. I am getting same issue.

**Comment by duyviet21** [comment]
> Hi ananth07reddy, can you please elaborate what steps you followed. I am getting same issue.

hi, did you solve the problem? can you show me what steps you followed? Thank you
