### ISSUE TITLE
Update case owner field validation to handle null value

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#1036]
### Request Type
Bug

### Problem Description
Via the case creation API, if the owner is provided with a `null` value, the API handles it as not specified and throws a `Attribute owner is missing`.

The API needs to be fixed handle the `null` value and set the API caller as owner.

**Comment by crackytsi** [comment]
@nadouani Note that we have the same issue for tasks, but tasks should (for my option) be able to get/keep the status "unassigned"

**Comment by nadouani** [comment]
Working on it, the tasks related issue is a UI issue
