### ISSUE TITLE
Adding attachments to the Case directly

### ISSUE THREAD

**Issue by pdux** [TheHive-Project/TheHive#1043]
### Request Type
Feature Request

### Problem Description
There is a possibility of adding attachments to the task (with small bug, describes in another issue). Attachment is visible and can be opened directly from the Case Details tab (very good), but it would be good to have the possibility to add attachment to the Case without any task being created. For example, if I have a case, where the user got phishing email and he will send the original message to me, the orig message can be added directly to the case, otherwise a task have to be created (no clue what can be the task name, as the orig message is connected with the case).

### Possible Solutions
I like the way the attachments are presented now (below the Details tab), but in the case  there will be more attachments (some cases might have tens of them), it may be a good idea to have separate Attachments tab? 
Also when attachment is added without task being created, there should be possibility (obligatory) to add description/note about file being attached.

**Comment by crackytsi** [comment]
From my point of view this Issue is identical to https://github.com/TheHive-Project/TheHive/issues/380
