### ISSUE TITLE
indices:data/write/update]), retrying

### ISSUE THREAD

**Issue by medtemo** [TheHive-Project/TheHive#1053]
## EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
(select Bug or Feature Request and **remove this part**)
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7.0
| TheHive version / git hash   | 3.3.1-1 
| Package Type              | RPM
| Browser type & version    | If applicable

### Problem Description
Describe the problem/bug as clearly as possible.
when I run Analysis from TheHive this error occur is it normal or something is wrong?
 
[WARN] from org.elastic4play.utils.Retry in application-akka.actor.default-dispatcher-7 - An error occurs ([K2kToHs][x.x.x.x:9300][indices:data/write/update]), retrying (4)

**Comment by nadouani** [comment]
This is a WARNING not an error.
