### ISSUE TITLE
Task log entry all concatenated on one line after clicking add log

### ISSUE THREAD

**Issue by k41zen** [TheHive-Project/TheHive#1054]
When typing plain text into the task log text box with newlines in it, after you click "add log" the lines of text are all displayed on one single line rather than showing how it was formatted when entered.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| TheHive version / git hash   | 3.3.1-1
| Package Type              | RPM
| Browser type & version    | Chrome

### Problem Description
As described in the above text if you enter the text shown below in to a task log entry, after you click the "add log" button the text shown is all concatenated on to one line.

### Steps to Reproduce
1. Create new task log entry
2. Add this text to the text box:
line 1
line 2
line 3

<img width="379" alt="hive-task-log-entry" src="https://user-images.githubusercontent.com/43755140/61279568-48db7200-a7ae-11e9-8bc8-2fe4b6070e01.png">

After you click on the "add log" button the text is shown like this:
line 1 line 2 line 3

<img width="198" alt="hive-task-log-display" src="https://user-images.githubusercontent.com/43755140/61279567-4842db80-a7ae-11e9-84ad-c6b04db56845.png">

**Comment by nadouani** [comment]
Task logs use markdown, so please refer to the Markdown syntax.

**Comment by nadouani** [comment]
If you want unformatted text, you can wrap it with triple backquotes

**Comment by k41zen** [comment]
I appreciate its markdown syntax but want the ability to place plain text in there as pasting from lots of different source.
