### ISSUE TITLE
Same here for Docker (see https://github.com/TheHive-Project/TheHive/issues/1051 )

### ISSUE THREAD

**Issue by kindsjay** [TheHive-Project/TheHive#1056]
Steps : updating the database --> ERROR

[error] o.e.d.DBConfiguration - ElasticSearch request failure: GET:/_cluster/health/the_hive_15?
=> ElasticError(security_exception,missing authentication token for REST request [/_cluster/health/the_hive_15],None,None,None,List(ElasticError(security_exception,missing authentication token for REST request [/_cluster/health/the_hive_15],None,None,None,null,None)),None)

**Comment by nadouani** [comment]
Hello, if it's the same issue, please use the existing issue to comment.
