### ISSUE TITLE
Logout does not destroy session on server-side, only client-side

### ISSUE THREAD

**Issue by Oxeeql** [TheHive-Project/TheHive#1058]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 4.9.168-1 (2019-04-12)
| OS version (client)       | Windows 10 Pro
| TheHive version / git hash   | 3.3.1-1
| Package Type              | DEB
| Browser type & version    | Not Browser-related, Firefox and Chrome

### Problem Description
Describe the problem/bug as clearly as possible.
After logging out, the application tells the browser to delete the session-cookie ( THE_HIVE_SESSION) by overwriting it, however the session is not invalidated on the server-side and can be accessed later, after logging out, when saving the cookie value.

### Steps to Reproduce
1. Log in, write down the session cookie value ( THE_HIVE_SESSION)
2. Log out
3. Set the cookie value of  THE_HIVE_SESSION to the previously saved value
4. Access e.g. the dashboard with http://host/index.html#/cases
5. Youre logged in and can use the application like normal (e.g. open new links). This means the session was not destroyed on the server and is still running.

This is mostly security-related, if an attacker can access the cookie value from the victim, he can take over the session. This scenario here is relevant for the rare case of shared clients. 

### Possible Solutions
the session should be destroyed on the server-side as well. 

### Complementary information
Response after GET /api/logout:

HTTP/1.1 200 OK
Set-Cookie: THE_HIVE_SESSION=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/; HTTPOnly
Date: Tue, 16 Jul 2019 15:38:28 GMT
Connection: close
Content-Length: 0

Here we see the server telling the browser to destroy the cookie of the session.

**Comment by nadouani** [comment]
Hello, TheHive is stateless, there is no session cookie on the server side.

**Comment by Oxeeql** [comment]
Hey, thanks for the quick response!
The session cookie from the browser has to correlate to a session on the server somehow, because you have different users. What I meant is, if a user logs out, the session, in which form it is stored on the server, should be invalidated. I'm not a developer and tried to browse the source code, but my lack of understanding on how that works is limited...

**Comment by nadouani** [comment]
The cookie you are talking about, can be verified by the server, and contains enough details to recognize the corresponding user. We don't store session cookies on the server. It also contains an expiration date.

If you try to forge a cookie it will not be valid.

That is how it works.
