### ISSUE TITLE
Want Task Log Entry to accept plain text as well as markdown

### ISSUE THREAD

**Issue by k41zen** [TheHive-Project/TheHive#1059]
This is a feature request to ask for the task log entries to accept both plain text and markdown syntax. We're pasting information from lots of sources or just simply writing an entry of steps taken or observations seen.

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| TheHive version / git hash   | 3.3.1-1
| Package Type              | RPM

### Problem Description
See issue: https://github.com/TheHive-Project/TheHive/issues/1054

**Comment by github-pba** [comment]
What do you think how to differentiate markdown from plain text? Do you think about a checkbox to switch modes? Do you think about autodetection (then: how? Markdown is plain text, too ...)

**Comment by rriclet** [comment]
Task logs use markdown, so please refer to the Markdown syntax.
If you want unformatted text, you can wrap it with triple backquotes.
