### ISSUE TITLE
CONNECTOR: Export closed case from TheHive to MISP fails

### ISSUE THREAD

**Issue by b00lpy** [TheHive-Project/TheHive#1063]
# Export closed case from TheHive to MISP fails with unexpected error

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu Server 18.04 LTS
| OS version (client)       | Ubuntu 18.04/Win 10
| TheHive version / git hash   | 3.4.0-RC1
| Package Type              |  Docker
| Browser type & version    | Firefox/Chrome

### Problem Description   
When I try to export a closed case from TheHive to MISP i cant get it working.
The error happens both with command "Share" in TheHive interface and also calling the API connector method.

### Steps to Reproduce  
1. Close a case  
2. Share case to MISP

### Complementary information
IMAGE:

![Thehive-to-misp-export-error](https://user-images.githubusercontent.com/50588190/61451436-a95ae280-a959-11e9-8ffe-8952797cc7bf.PNG)

  
LOG:
```
[info] c.m.MispExport - Exporting case 4 to MISP local-misp
[info] o.e.ErrorHandler - POST /api/connector/misp/export/2qlFwWsBqk6_P7d1T91l/local-misp returned 500
org.elastic4play.InternalError: Unexpected MISP response: 200 OK
[
    {
        "id": "15",
        "org_id": "2",
        "date": "2019-07-15",
```
Followed with a list of all events inside of MISP

**Comment by github-pba** [comment]
Can't confirm here.

I had a closed case with observables, and I was able to share it with MISP without any problem. 
![Share1](https://user-images.githubusercontent.com/50981940/61619901-09120000-ac70-11e9-857f-3adb3db5441b.png)
![Share2](https://user-images.githubusercontent.com/50981940/61619906-0d3e1d80-ac70-11e9-8343-10f891d67134.png)

My Observables were not transferred, which is probably normal, as none of it was marked as an IOC. I have to dig deeper here.

**BUT ...**

Once I deleted the event in MISP and tried to re-share it, it won't show up again. I'm not sure if this is by intension.

Did you export the event once successfully, deleted it in MISP, and tried to re-share it?

**Comment by b00lpy** [comment]
Hi @github-pba , I know that only IoC are exported into MISP so what happens to you is normal. No I'm still not able to do that.

**Comment by github-pba** [comment]
Hm. Strange.

1) is the role of the MISP user who's key is in thehive/application.conf of type `sync`?
2) can you successfully publish events in MISP which show up as alerts in TheHive?

**Comment by b00lpy** [comment]
1. Yes, I tried both with the default role "Sync User" and with a custom with all permissions but admin. Nothing happen
2. No, TheHive can see MISP because the green logo on the bottom, but can't receive events as alert. I've got timeout set on `1 minute ` in application.conf file. Tried to publish an event 15 minutes ago but nothin...
3. I upgraded to latest 2.4.111 the day i opened this issue
4. Obviously not, same error for the closed one

I think i should have done some misconfiguration somewhere, but i'm using containers given directly from thehiveproject docker repo and I installed MISP with their installer script and follow all the guides provided. Don't know what can be actually.

**Comment by github-pba** [comment]
Whoo-hooo. I'm not familiar with the Docker installation.

I assume a misconfiguration, too. You have the sync permission in MISP, good. For reference and comparison, here is my application.conf:

```
play.http.secret.key="***secret***"

search {
  index = the_hive
  uri = "http://127.0.0.1:9200"
  search.ssl.enabled = false
}

cluster {
  name = hive
}

auth {
		 provider = [local]
		 ad {
		 }
		 ldap {
		 }
}

session {
  warning = 5m
  inactivity = 1h
}
play.http.parser.maxMemoryBuffer= 1M
play.http.parser.maxDiskBuffer = 1G

play.modules.enabled += connectors.cortex.CortexConnector

cortex {
  "cortex1" {
    url = "http://127.0.0.1:9001"
    key = "***cortex-key****"
    ws {}
  }
}

play.modules.enabled += connectors.misp.MispConnector

misp {
  interval = 5m

  "MISP" {
    url = "https://misp.domain.com"
    key = "***key-with-sync-access***"
  
 caseTemplate = "MISPimport"
  max-attributes = 1000
  max-size = 1 MiB
  max-age = 7 days
}
```

You might want to compare your settings to mine, which work for TH 3.4.0RC1 and MISP 2.4.111

**Comment by b00lpy** [comment]
Actually TheHive runs inside a container and MISP is real process inside the host machine, but they can communicate each other otherwise i should have the red logo in misp webgui.

I sadly have to say that I have the same configuration you posted ( my max-age is two weeks but doesn't matter ).
In the next days i'll try to do a clean install on machine, everything as an actual process ( saw docker is too much unstable ) and keep you updated.

**Comment by github-pba** [comment]
OK, good luck then.

What makes me wonder are the two conflicting HTTP status codes from your first post:
> POST /api/connector/misp/export/2qlFwWsBqk6_P7d1T91l/local-misp returned 500
> org.elastic4play.InternalError: Unexpected MISP response: 200 OK

Are you willing to try something weird? I can't reach my test environment due to an outage at my service provider right now, so I can't test it in my environment, but I remember from the bottom of my brain I had an issue with the MISP server configuration, if I remember correctly.

Change
```
  "MISP" {
    url = "https://misp.domain.com"
    key = "***key-with-sync-access***"
 ```
to 

```
  "CORPORAGE-MISP" {
    url = "https://misp.domain.com"
    key = "***key-with-sync-access***"
 ```
and restart TheHive (my configuration code was modified at this configuration item). I'm not sure if this was my problem ... too long ago ...

**Comment by github-pba** [comment]
Just for completeness, you could check your MISP installation by running `create_events.py` from PyMISP's [examples](https://github.com/MISP/PyMISP)

This should be exec'd from the Docker container with TheHive in it, and - of course - with the same key you have in your application.conf. If this works, you can quite clearly say neither the access rights nor the communication path is the problem.

**Comment by b00lpy** [comment]
> 
> 
> OK, good luck then.
> 
> What makes me wonder are the two conflicting HTTP status codes from your first post:
> 
> > POST /api/connector/misp/export/2qlFwWsBqk6_P7d1T91l/local-misp returned 500
> > org.elastic4play.InternalError: Unexpected MISP response: 200 OK

I don't know why I have the first 500 and then the 200 followed with a big JSON file containing ALL misp events (published or not).

I'm trying to use PyMISP from a windows client and i don't have any kind of problem (just a warning for certificate but it's not an error tough).  Now i'll try from the inside of TheHive container.

**Comment by github-pba** [comment]
If you'd like to test-connect your TH to my Test-MISP, drop me an e-mail to "{my-github-user} at itserv.de". I'd then generate a test account and tell you the result of your export.

**Comment by syedkhizarulhaq-cis** [comment]
Howdy,

Any luck with this issue?

Thanks
