### ISSUE TITLE
Analyzers and Responders in Cortex not visible after the installation

### ISSUE THREAD

**Issue by imran3668** [TheHive-Project/TheHive#1064]
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat, ...
| OS version (client)       | 10
| TheHive version / git hash   | 3.x, hash of the commit
| Package Type              | RPM
| Browser type & version    | If applicable

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. Initial installation of cortex, followed the installation guide.
2. Installed cortex and elastic search.
3. Compiled the analyzers.
4. Analyzers dont show up in the UI
5. Attaching the configuration file and the log file..

[application.zip](https://github.com/TheHive-Project/TheHive/files/3407067/application.zip)

**Comment by nadouani** [comment]
Hello,

Please read the https://github.com/TheHive-Project/CortexDocs/blob/master/admin/quick-start.md if you didn't yet done it. It explains how to start using Cortex.

Once things are working in Cortex, connect it to TheHive and everything should work as expected.

**Comment by nadouani** [comment]
This sounds like you didn't enable any analyzer

**Comment by imran3668** [comment]
Actually i am not able to view any analyzers in the analyzer config area, hence not able to enable or disable them....

**Comment by imran3668** [comment]
Below is my app conf settings..

## ANALYZERS
#
analyzer {
  # Absolute path where you have pulled the Cortex-Analyzers repository.
  path = [ "/root/analyzers/Cortex-Analyzers/analyzers/" ]
 # urls = ["/root/analyzers/Cortex-Analyzers/analyzers"]

  # Sane defaults. Do not change unless you know what you are doing.
  fork-join-executor {

    # Min number of threads available for analysis.
    parallelism-min = 2

    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0

    # Max number of threads available for analysis.
    parallelism-max = 4
  }
}

responder {
  # Directory that holds responders
   path = [ "/root/analyzers/Cortex-Analyzers/responders/" ]

  fork-join-executor {
    # Min number of threads available for analyze
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor)
    parallelism-factor = 2.0
    # Max number of threads available for analyze
    parallelism-max = 4
  }
}

**Comment by imran3668** [comment]
Issue was resolved, it was due to permission issue at the root of the directory, all the lower level directories were having the permission but the top most was left out which caused this issue, thank you for your help
