### ISSUE TITLE
Cosmetic Bug: wrong number of exported observables displayed

### ISSUE THREAD

**Issue by github-pba** [TheHive-Project/TheHive#1071]
### Request Type
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Windows
| TheHive version / git hash   | 3.4.0-RC1
| Package Type              | RPM

### Problem Description
When exporting a case to MISP, the message after a successful export to MISP is always "The case has been successfully exported with 1 observable(s)", no matter how many observables are connected to the case and no matter wether or not they are IoCs and/or seen.

The message always says: "1 observable(s)"

The Event is correctly created in MISP.

### Steps to Reproduce
1. create a case with zero or more observables
1. Hit Share -> Export to MISP
1. Look at the green success message in the bottom-left corner.

**TheHive Screenshot:**
![export](https://user-images.githubusercontent.com/50981940/61689135-ed1d6580-ad26-11e9-809b-5226c69c63f1.png)

**Event created in MISP:**
![export2](https://user-images.githubusercontent.com/50981940/61689505-9cf2d300-ad27-11e9-9a72-5f364c3a728b.png)

**Comment by nadouani** [comment]
Are you sure you did the export just one time? or did you export a first time, then added another IOC and exported again? The number `1` in this case is the number of IOC that has been exported during the last export action.

**Comment by github-pba** [comment]
I re-tried it, twice, with different results.

1) created a new case, added three observables, exported to MISP -> Message `exported with 1 observable`, no observables in MISP (as they were not marked as IOC in TH)

2) created a new case, added three observables, marked each of them as IoC and sighted, exported to MISP -> Message `exported with 1 observable`, three observables in MISP

Yes, my bug report is still correct :-)

**Comment by github-pba** [comment]
Just a quick guess:

In [CaseExportDialogCtrl.js](https://github.com/TheHive-Project/TheHive/blob/master/ui/app/scripts/controllers/case/CaseExportDialogCtrl.js)

![Snag_483e7b81](https://user-images.githubusercontent.com/50981940/63408835-2f9e9480-c3f0-11e9-89c4-c7a5984bfbc0.png)

**Comment by nadouani** [comment]
The issue seems to be `angular.isObject([])` who is returning `true`, where it was returning `false` before :)
