### ISSUE TITLE
Domain observables not matching linking on different cases

### ISSUE THREAD

**Issue by kasdf26** [TheHive-Project/TheHive#1072]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu docker image on CentOS
| OS version (client)       | Windows 10
| TheHive version          | 3.3.1-1
| Package Type              |  Docker
| Browser type & version    | chrome but N/A

### Problem Description
Domain observables are not linked when they are pasted in with "[.]" already in the domain for one observable entry and not another

### Steps to Reproduce
1. create a case
2. add domain observable "example.com"
3. create a second case
4. add domain obserable "example[.]com" 

observables are not linked

**Comment by github-pba** [comment]
Makes perfect sense to me. The strings `example[.]com` and `example.com` are different.

This is more kind of a missing input validation. But hey, you can also enter an IP observable with the value "hello world!".

By the way: `example[.]com` is no valid domain name, as you know. Why would somebody want enter it?

**Comment by nadouani** [comment]
`example[.]com` is not a domain, we don't defang the input. We store whatever you put as observable data?
