### ISSUE TITLE
Cosmetic Bug: Admin menu not shown on slim screens

### ISSUE THREAD

**Issue by github-pba** [TheHive-Project/TheHive#1076]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       |  Windows 7
| TheHive version / git hash   | 3.4.0-RC2
| Package Type              | DEB
| Browser                      | Chrome, IE 11

### Problem Description
If the screen gets small, the admin and user profile drop-down menus are not rendered correctly.

### Steps to Reproduce
1. log in as Administrator
1. open case template management (it can be seen there very good)
1. horizontally shrink the window.

The very moment the left sidebar (current templates) gets removed, the Admin menu is no longer displayed correctly. Only the item right under the mouse pointer is shown:
![AdminMenuDead](https://user-images.githubusercontent.com/50981940/61870452-72974600-aede-11e9-915d-4dca256adddb.png)

### Possible Solutions
Do CSS magic. :-)

Disableing `color:inherit` as shown below fixes the problem, but I have no idea what this will break.
![css](https://user-images.githubusercontent.com/50981940/61870815-5a73f680-aedf-11e9-8d18-86e757f73c5c.png)

**Comment by nadouani** [comment]
Fixed in #1290
