### ISSUE TITLE
Cosmetic Bug: no ☰ menu  shown on very slim screens

### ISSUE THREAD

**Issue by github-pba** [TheHive-Project/TheHive#1077]
### Request Type
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       |  Windows 7
| TheHive version / git hash   | 3.4.0-RC2
| Package Type              | DEB
| Browser                      | Chrome, IE 11

### Problem Description
on very slim screens, when the menu bar is no longer shown, a "hamburger" symbol (&#9776;) should be displayed to show the user where to access the menu

### Steps to Reproduce
1. horizontally shrink the window size until the navbar collapses
1. see nothing. See no &#9776;. You have to guess where the menu is.

![Navbar](https://user-images.githubusercontent.com/50981940/61871717-d111f380-aee1-11e9-880d-c6775b41bd21.png)

**Comment by nadouani** [comment]
Fixed in #1290
