### ISSUE TITLE
[3.4.0-RC2] Observables  are lost during Alarm to Case import

### ISSUE THREAD

**Issue by presianbg** [TheHive-Project/TheHive#1079]
### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7.6.1810 (Core)
| OS version (client)       |  Solus 
| TheHive version / git hash   | 3.4.0-RC2
| Package Type              | RPM
| Browser type & version    | Vivaldi - latest

### Problem Description
I'm using a logstash pipline to import alerts via Thehive's API. 
The alarms are created successfully wtih 10  observables:

![image](https://user-images.githubusercontent.com/2163486/61894229-a2633f80-af18-11e9-8887-865bb1ab74b0.png)

 but when importing the alarm into an Empty case only 8 out of 10  observables are kept:
 
![image](https://user-images.githubusercontent.com/2163486/61894379-fc640500-af18-11e9-9821-2847370e84cd.png)

**Comment by presianbg** [comment]
Also not sure if related, but I found another issue with observables  (maybe worth to open separate Github issue for it):

Create an observable with "nil" for value like this:

```
{
         "source" => "MON01",
           "date" => 1564043661165,
          "title" => "ET SCAN Potential SSH Scan",
       "severity" => 2,
    "description" => "Attempted Information Leak %{metadata} %{alarm_message}",
      "artifacts" => [
        [0] {
                "data" => "80.82.78.104",
             "message" => "Source IP",
            "dataType" => "ip"
        },
        [1] {
                "data" => "10.22.255.2",
             "message" => "Destination IP",
            "dataType" => "ip"
        },
        [2] {
                "data" => "22",
             "message" => "Dest Port",
            "dataType" => "dest_port"
        },
        [3] {
                "data" => "43322",
             "message" => "Src Port",
            "dataType" => "src_port"
        },
        [4] {
                "data" => "TCP",
             "message" => "L4 proto",
            "dataType" => "proto"
        },
        [5] {
                "data" => **nil,**
             "message" => "L7 proto",
            "dataType" => "app_proto"
        },
        [6] {
                "data" => "",
             "message" => "packet payload",
            "dataType" => "payload"
        },
        [7] {
                "data" => **nil,**
             "message" => "FQDN",
            "dataType" => "domain"
        },
        [8] {
                "data" => **nil,**
             "message" => "URL",
            "dataType" => "uri_path"
        },
        [9] {
                "data" => **nil,**
             "message" => "UA",
            "dataType" => "user-agent"
        }
    ],
           "type" => "STAMUS IDS",
      "sourceRef" => "1963404857"
}

```
Then import this alarm into case and when viewing the  "Observables" tab it will be **empty**.

**Comment by github-pba** [comment]
I'm running the same config, and all works well.

As far as I know, you can only import observables if the type is defined in Admin -> Observables.

You try to import data of type app_proto. Is this defined?

Check out the application log (typically `/var/log/thehive/application.log`) during import. You will probably see an error message like this (look at the first line):

```
2019-07-26 08:25:58,915 [WARN] from services.AlertSrv in application-akka.actor.default-dispatcher-16 - Create artifact error
org.elastic4play.AttributeCheckingError: [Invalid format for case_artifact.dataType: JsonInputValue("user"), expected enumeration]
		 at org.elastic4play.services.FieldsSrv.$anonfun$parse$7(FieldsSrv.scala:33)
		 at org.scalactic.Bad.transform(Or.scala:1386)
		 at org.elastic4play.services.FieldsSrv.parse(FieldsSrv.scala:33)
		 at org.elastic4play.services.CreateSrv.create(CreateSrv.scala:105)
		 at org.elastic4play.services.CreateSrv.$anonfun$apply$7(CreateSrv.scala:95)
		 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
		 at scala.collection.immutable.List.foreach(List.scala:389)
		 at scala.collection.TraversableLike.map(TraversableLike.scala:234)
		 at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
		 at scala.collection.immutable.List.map(List.scala:295)
		 at org.elastic4play.services.CreateSrv.apply(CreateSrv.scala:93)
		 at services.ArtifactSrv.create(ArtifactSrv.scala:86)
		 at services.AlertSrv.importArtifacts(AlertSrv.scala:312)
		 at services.AlertSrv.$anonfun$createCase$4(AlertSrv.scala:224)
		 at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
		 at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
		 at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
		 at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
		 at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
		 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
		 at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
		 at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
		 at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
		 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
		 at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
		 at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
		 at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
		 at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

You must create the observable types prior to importing.

**Comment by saadkadhi** [comment]
Indeed, it seems you have several datatypes that are not included. in the stock install of TheHive. You'll have to create them as suggested by @github-pba.

**Comment by presianbg** [comment]
@saadkadhi and @github-pba you are awesome! 
It turned out that I have those custom datatypes defined by me, but they were with typos :( 

Shall I open a new issue for the **NULL** value problem described in my  [comment](https://github.com/TheHive-Project/TheHive/issues/1079#issuecomment-515134654) or it's a know issue ?

**Comment by github-pba** [comment]
Thank you for the complement.

I think it would be the best to open a new issue on the other thing. And to be honest: I didn't understand it. It would be helpful to provide sample code that generates the problem.

Please, don't forget to close this issue (#1079).

**Comment by github-pba** [comment]
Oh, now I understand your problem.

We can handle this here, I think.

Would you please explain what sense it makes to create observables of some type but without any value?

(Still I think there is really a problem, I saw a weird thing).

**Comment by github-pba** [comment]
Please checkout [Issue 1080](https://github.com/TheHive-Project/TheHive/issues/1080) I have just opened. I think this exactly describes what you encoutered.

**Comment by presianbg** [comment]
> Oh, now I understand your problem.
> 
> We can handle this here, I think.
> 
> Would you please explain what sense it makes to create observables of some type but without any value?
> 
> (Still I think there is really a problem, I saw a weird thing).

So my alerts are coming from suricata IDS and the jsons are not consistent.
For convenience I'm using logstash http output to ship them to  TheHive's API. 
My parsing is not dynamic - I'm not checking if such key/value exists in the original suricata alarm, instead the artifacts are constructed like this:

```
  ruby {
        code => '
          event.set("artifacts", [{"dataType" => "ip", "data" => event.get("src_ip"), "message" => "Source IP"},
                                  {"dataType" => "ip", "data" => event.get("dest_ip"), "message" => "Destination IP"},
                                  {"dataType" => "dest_port", "data" => event.get("dest_port"), "message" => "Dest Port"},
                                  {"dataType" => "src_port", "data" => event.get("src_port"), "message" => "Src Port"},
                                  {"dataType" => "proto", "data" => event.get("proto"), "message" => "L4 proto"},
                                  {"dataType" => "app_proto", "data" => event.get("app_proto"), "message" => "L7 proto"},
                                  {"dataType" => "payload", "data" => event.get("payload_printable"), "message" => "packet payload"},
                                  {"dataType" => "domain", "data" => event.get("[hostname_info][domain]"), "message" => "FQDN"},
                                  {"dataType" => "url_path", "data" => event.get("[http][url]"), "message" => "url path"},
                                  {"dataType" => "url", "data" => event.get("[http][hostname]") + event.get("[http][url]"), "message" => "uri + url"},
                                  {"dataType" => "other", "data" => event.get("metadata"), "message" => "metadata"},
                                  {"dataType" => "other", "data" => event.get("alarm_message"), "message" => "alarm_message"},
                                  {"dataType" => "signature_id", "data" => event.get("[alert][signature_id]"), "message" => "Signature ID"},
                                  {"dataType" => "user-agent", "data" => event.get("[http][http_user_agent]"), "message" => "UA"}])
        '
      }
```
This is not the optimal solution, but it saves a lot of pain which dynamic constructor will require. 

Where key is missing, let's say:
```
{"dataType" => "payload", "data" => event.get("payload_printable"), "message" => "packet payload"},
```
logstash is putting "nil" value for key "payload", fair enough.
Alarms are created successfully and a observable with nil value is displayed as empty in "Alerts Preview", but when this alert is imported into case, all observables are hidden despite that the counter shows X observables for this case.

**Comment by presianbg** [comment]
> Please checkout [Issue 1080](https://github.com/TheHive-Project/TheHive/issues/1080) I have just opened. I think this exactly describes what you encoutered.

Exactly! Thanks for testing this for me. I'm still a newbie regarding this project.
