### ISSUE TITLE
Msg_Parser report to observables

### ISSUE THREAD

**Issue by ramocha** [TheHive-Project/TheHive#1086]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive version / git hash   | 3.3.1-1

### Problem Description
I make this request to know if i can make observables from selected items of msg_parser report. I would like take the header of the mail to make an responder and analyze or take the subject or "from" to search in my mail management to know the destinataries.

**Comment by github-pba** [comment]
If I get you right, you don't have a feature request, but a question about if something is possible or not.

Unfortunatly, I don't understand what you want. Can you please explain again?

**Comment by ramocha** [comment]
@github-pba you're correct is more a question what an request 

i try to explain better...

i have an msg file and i try to get the body, header, from and subject of this email so i run the analyzer msg_parser and parse ok but don't give me any observables. i put this variables in the observables list in TheHive but not modify nothing...
My principal idea is get this observables and run some other analyzers or responder... i don't know if i'm wrong because i'm newby with TheHive and Cortex... i'd like automate some tasks for phishing analysis.

![image](https://user-images.githubusercontent.com/32308463/62307553-3160e200-b45a-11e9-8dc6-ef127011ea55.png)

![image](https://user-images.githubusercontent.com/32308463/62307636-535a6480-b45a-11e9-937b-e1d6847bc4ba.png)

Regards

**Comment by github-pba** [comment]
Ok, now I understand. I wasn't aware of the existence of MsgParser :-)

You want the analyzer to cut out elements of the E-Mail and put it into new observables. I'm currently not sure how Analyzers generate new observables, but I'll take a look on it over the weekend - something to learn for me :-)

While I do this, what would you like to have extracted as observables? And how could the analyzer identifiy this information?

For example, do you think the analyzer should run through the text and find all URLs, returning them? What more observables do you see in an e-mail?

**Comment by github-pba** [comment]
OK, the problem is simple: MsgParser does not support extracting observables. As this is open source, you are encouraged to enhance the analyser, or post a feature request on enhancing it. In this case you should exactly describe which observables should be extracted.

If you want an example how the extractions of observables works, enable the TorBlutmagie analyzer and throw him an ip-address from (the service provider) [http://blutmagie.de/]. After analysis, you have the possibility to review the found observables and selectively import them:

![Observables](https://user-images.githubusercontent.com/50981940/62350948-8ce7aa00-b504-11e9-9937-786eef4d90cc.png)

**Comment by github-pba** [comment]
I start to think I said dumb stuff about MsgParser is not able to extract observables ... still evaluating and learning.

**Comment by github-pba** [comment]
OK, now I'm totally sure my answer was wrong. There seems to be not "support for extraction" - it is done automagically by cortexutils.

**Comment by ramocha** [comment]
@github-pba i'm sorry in last days i have to much work what i cant send you an answer. i've read in some post what the cortexutils is the answer but i not be sure.

**Comment by mgabriel-silva** [comment]
@ramocha 
If you know Python, you can use TheHiveHooks + TheHive API (or thehive4py) to extract the informations on the report.
You'll need to use the event 'CaseArtifactJobUpdate'

**Comment by ramocha** [comment]
> @ramocha
> If you know Python, I think you could use TheHiveHooks + TheHive API (or thehive4py) to extract the informations on the report with the event 'CaseArtifactJobUpdate'

i'm not be a good developer but i can try. I had no knowledge of these libraries or functions i will investigate

**Comment by ramocha** [comment]
Hi after some days of burning my mind i got what i need maybe is useful for someone so i upload the file

[MsgParser.zip](https://github.com/TheHive-Project/TheHive/files/3498343/MsgParser.zip)
