### ISSUE TITLE
Selective display of cases based on user-related criteria

### ISSUE THREAD

**Issue by janwychowaniak** [TheHive-Project/TheHive#1088]
Feature Request

Hello.
Is it possible within a Hive instance with multiple users in it, to put a restriction on which case a particular user is ever able to see. I am not meaning case filtering. I'm rather thinking of a situation, in which e.g. user A is only ever able/allowed to see cases created by themselves (or tagged "userA" or something), and not by user B, and vice versa.
The only form of privilege control that I was able to discover in theHive so far is to set, whether a user is able to only read, or also to write and admin. But even if the user has only the permission to read, he or she can read everything, which is not what I'm intending.
I would be very glad to learn, if such configuration is at all possible in theHive. Or if not, whether such thing is planned.
Thank you.

**Comment by github-pba** [comment]
I'm no developer, just a user.

As far as I know you're right: there is no possibility to restrict users beyond what you described. Everybody who can login, can at least read everything. Which is actually a problem when it comes to restrictive TLP levels. An analyst hunting a TLP:RED issue is by definition not allowed to share his information with other analysts ... but in TheHive, everybody sees what he does and records.

For plans changing this, I don't have any information. Hopefully @saadkadhi and/or @nadouani or one of the other developers responds (names listed here to draw their attention :-) ).

**Comment by veeral-patel** [comment]
Hey @janwychowaniak - TheHive does not have this functionality at the moment, unfortunately :(

**Comment by janwychowaniak** [comment]
Ok, thank you very much for your answers and clarifications. I thought that something like this could have been hard to accomplish anyway. Good to have some additional insight. Thanks.

**Comment by veeral-patel** [comment]
@janwychowaniak while we wait for TheHive to implement this functionality, you can check out a similar tool I wrote that implements it - https://tryincidents.com

TheHive was missing this feature was a major reason I wrote this tool, actually.
