### ISSUE TITLE
Unable to login to The Hive

### ISSUE THREAD

**Issue by kp625544** [TheHive-Project/TheHive#1090]
Hello,
So I simply downloaded the docker compose file and did docker-compose up. It downloaded everything and when I tried to access localhost:9000 it simply redirects me to login credentials. But as the login credentials are not set there is nothing I can do.
I even tried looking at the error where the hive is running. Even in the error it says no index found in elasticsearch. still it redirects me to login screen. :(
![Screenshot_20190803_013622](https://user-images.githubusercontent.com/18206620/62395867-278ccb00-b58f-11e9-8dc6-0367bd0e8b00.png)

**Comment by axpatito** [comment]
Just login to the elastic search instance and delete the the_hive_X indexes, since this is a new instance, there is no need to backup anything. Try to access the web page again and you will be asked to reconfigure the service, including credentials.

**Comment by kp625544** [comment]
I have cleared all indexes that were present in elasticsearch. Still the same issue.

**Comment by github-pba** [comment]
After you deleted the index, browse to the login page. Normally you should be forwarded to a maintenence page, but I have seen login pages quite a few times. Wait some 10 seconds, then press F5 to reload the page. This should guide you to the page where you create the admin account.

**Comment by crackytsi** [comment]
Are you using 3.4 rc2?
I also noticed that there is an issue related to Migration and Login Dialog as it is influencing each vorher. 3.3 stable should work or 3.4 rc1 ;-)

**Comment by kp625544** [comment]
I m using docker-compose file as it is. Do i have to make changes in it :O

**Comment by billmurrin** [comment]
You'll likely have to update TheHive application.conf to update elasticsearch. You can use the service name from the docker compose file. You could also bind the application.conf from your server to the container so the .conf file can be modified and updated by restarting thehive container. If you `down` it by mistake, at least you don't lose your config.

**application.conf example**
```
# Elasticsearch
search {
  ## Basic configuration
  # Index name.
  index = the_hive
  # ElasticSearch instance address.
  uri = "http://elasticsearch:9200/"
```

**Docker-compose binding example**
```
 thehive:
  thehive:
    image: thehiveproject/thehive:3.4.0-RC2
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - ./application.conf:/etc/thehive/application.conf
```

**Comment by kp625544** [comment]
Its solved. closing the issue.
I started an elasticsearch instance in one docker and the hive in another docker and then it started well
