### ISSUE TITLE
MISP-Thehive sync

### ISSUE THREAD

**Issue by dominik335** [TheHive-Project/TheHive#1096]
### Request Type
Bug 

### Work Environment
Helm chart with 3 containters: elasticsearch as TheHive backend, TheHive 3.3.0-1 and MISP 2.4.103

### Problem Description
MISP and TheHive work great separately but when I try to synchronize MISP event I they don't get fetched and:
-  in logs I get:
![obraz](https://user-images.githubusercontent.com/11310995/62955690-c7e5b980-bdf1-11e9-915c-497f1107ed5f.png)
- in TheHive UI circle around MISP logo stays red
- in admin -> About I get 
![obraz](https://user-images.githubusercontent.com/11310995/62955806-fcf20c00-bdf1-11e9-8cbb-aa0d060492f1.png)

TheHive config (relevant parts):

```
play.ws.ssl.loose.acceptAnyCertificate = true
play.modules.enabled += connectors.misp.MispConnector
MISP {
  "misp1" {
    url = "https://misp2-service:8888" 
    key = "*****"
    tags = ["MISP"]
    caseTemplate = "MISP"
  }
  interval = 1m
}
```
Am I using correct MISP user? Yup, it's admin's key.
Does conectivity between containers work? Yes - I checked it with curl from inside the TheHive containter.
Do I have published MISP events? Yes - quite recent ones.

Any idea on how can I get this working?

**Comment by github-pba** [comment]
is the configured key a MISP user of type `sync`? Probably not, since you say it's the admin's key.

It must be sync.

**Comment by github-pba** [comment]
If the circle is red, you don't have a connection.

Double-Check
a) your key does not include a space character (this quickly happens with copy/paste)
b) the URL https://misp2-service:8888 can be used with a regular browser
c) the https certificate if from a known authority from the point of view of TheHive

**Comment by github-pba** [comment]
One last idea: I think a MISP event must have at least one attribute=observable. Without any attributes, TheHive does not create an alert.

**Comment by dominik335** [comment]
> a) your key does not include a space character (this quickly happens with copy/paste)
It does not.
> b) the URL https://misp2-service:8888 can be used with a regular browser
I don't have a browser inside of a container but executing this:

![obraz](https://user-images.githubusercontent.com/11310995/63014284-793a2d00-be8e-11e9-8930-f42717349bc4.png)
Gives the data.

> c) the https certificate if from a known authority from the point of view of TheHive (execute `openssl s_client -connect misp2-service:8888` )

That gives
```
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify error:num=18:self signed certificate
verify return:1
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify return:1
---
Certificate chain
 0 s:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
   i:/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
```
And that makes sense because in MISP docker image there is a self-signed cert, that's why I used 
```
play.ws.ssl.loose.acceptAnyCertificate = true
```
In my config.

> Can you eventually for testing fall back to HTTP instead of HTTPS?

I'll try to.

**Comment by github-pba** [comment]
I did not mean to only change the HTTPS to HTTP in the URL string - I'm sure you have to make MISP available for HTTP, too (modifiy webserver).

I *think* the message `Misp synchronization completed` does only mean the job has been *executed*, nothing more. If you don't have the green circle for MISP, you won't get any results.

Did you make sure your shared events im MISP do have attributes?

**Comment by dominik335** [comment]
> Did you make sure your shared events im MISP do have attributes?

Yes, I've got ~20 events there, only with id=20 is published and that's why it got fetched in curl query above.

**Comment by github-pba** [comment]
That was not the question. 

Does this event have attributes (such as ip-addresses, URLs, hashes, ...)?

**Comment by dominik335** [comment]
> That was not the question.
> 
> Does this event have attributes (such as ip-addresses, URLs, hashes, ...)?

Yes, you could see them here
![obraz](https://user-images.githubusercontent.com/11310995/63014284-793a2d00-be8e-11e9-8930-f42717349bc4.png)

**Comment by github-pba** [comment]
Good. 

By the way, I just changed my MISP-Hive-Connection to force an error (non-existing MIPS host), and the message from the log reads `Misp synchronization failed`.

So I understand your problem: why the hell do you get a red MISP icon, but `Misp synchronization completed` ???

**Comment by github-pba** [comment]
Do you see any anomalies in `/var/www/MISP/app/tmp/logs/error.log`?

**Comment by dominik335** [comment]
> So I understand your problem: why the hell do you get a red MISP icon, but `Misp synchronization completed` ???

Exactly ;) And why there's no status in web UI for MISP ;) I also tested integration with Cortex so I know that should be there.

**Comment by dominik335** [comment]
Well,
![obraz](https://user-images.githubusercontent.com/11310995/63022736-ce346e00-bea3-11e9-80a0-811db958a4e3.png)

but still
```
play.ws.ssl.loose.acceptAnyCertificate = true
```

**Comment by billmurrin** [comment]
You can try adding the MISP crt file to a truststore JKS and add the truststore to the MISP configuration section in TheHIve.

**Comment by dominik335** [comment]
I figured out something else. I get `[info] c.m.MispSynchro - Misp synchronization completed` every time when `play.modules.enabled += connectors.misp.MispConnector` is not commented out, even when the whole `MISP` section is commented. Is there any kind of MISP config caching?

**Comment by dominik335** [comment]
Well, that should be
`misp {
  "misp1" {`

instead of

`MISP {
  "misp1" {`
....
And it worked... Funny thing aside is that even when I set logging level to debug in logback.xml, there was nothing about MISP, like misp plugin would stop processing when did not encounter "misp" section in config. Don't understand why it did not print error message instead of `Misp synchronization completed` like on successful sync.
