### ISSUE TITLE
ZScaler ZIA Cortex Analyzer

### ISSUE THREAD

**Issue by xg5-simon** [TheHive-Project/TheHive#1101]
### Request Type
Feature Request

Write an analyzer that queries the Zscaler ZIA API. 

- The analyzer will send a URL or Domain dataType the ZIA API and return a categorization.
- The analyzer needs to be configurable to support suspicious and malicious categories 

https://github.com/xg5-simon/Zscaler-Cortex-Analyzer

**Comment by axpatito** [comment]
There is a separate repo for this request: https://github.com/TheHive-Project/Cortex-Analyzers

**Comment by xg5-simon** [comment]
Forgot that I had already opened a request for this. Pro-tip: Don't open github issues late on Friday nights!

https://github.com/TheHive-Project/Cortex-Analyzers/issues/424
