### ISSUE TITLE
Observable search not returning results for uri_path observables when querying for a substring of the uri_path.

### ISSUE THREAD

**Issue by s3p1a** [TheHive-Project/TheHive#1114]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu 18.04
| OS version (client)       | 10
| TheHive version / git hash   | 3.4.0-RC2
| Package Type              | DEB
| Browser type & version    | Chrome 76.0.3809.132 (Official Build) (64-bit)

### Problem Description
Observable search not returning results for uri_path observables on search page when querying for a substring of the uri_path. Search does seem to match some items in the description field, but not all. For example, the observable [URI_PATH]: /jexinv4/jexinv4[.]jsp? is not found when querying for 'jexinv'.

### Steps to Reproduce
1. Add a uri_path observable to a case
2. Navigate to search page, then query all observables using a * wildcard - should see the observable in question listed
3. Query for the contents (substring) of that uri_path from the search page - does not return results

### Complementary information
Screenshots attached
![jexinv](https://user-images.githubusercontent.com/5479599/64381503-94610e00-cff0-11e9-9e6a-40409df0c1ff.JPG)
![wildcard](https://user-images.githubusercontent.com/5479599/64381504-94610e00-cff0-11e9-9a2e-bcfc134a61c6.png)
![http](https://user-images.githubusercontent.com/5479599/64381506-94610e00-cff0-11e9-898e-b9167bdea9ca.png)

**Comment by github-pba** [comment]
Can't confirm.

Add an asterisk to the search, and the observable will be found. Instead of `jexinv`, search for `jexinv*`

![Snag_19d2ba9f](https://user-images.githubusercontent.com/50981940/64588914-10b67100-d3a4-11e9-8c40-cbf073d692b9.png)

**Comment by s3p1a** [comment]
D'oh! Thank you.
