### ISSUE TITLE
New Type Requests

### ISSUE THREAD

**Issue by b00lpy** [TheHive-Project/TheHive#1116]
It would be awesome if new `dataType` will be inserted, specially for whom are related to file description. Something like:
- **filename**
- **source-code**

**Comment by github-pba** [comment]
Do you know you can add your own "data types"?

Simply choose `Observables` from the Admin menu.

![Snag_19cc87ad](https://user-images.githubusercontent.com/50981940/64588584-1eb7c200-d3a3-11e9-9f79-e94a2196fcd3.png)

**Comment by nadouani** [comment]
You can in fact your own data types as answered by @github-pba

**Comment by b00lpy** [comment]
Feeling quite stupid now, but I'll try to save my reputation :)  
When the case is exported into MISP how does it works? backend tries to convert it and if nothing matches with my own dataType(s) it simply gives error right?

**Comment by github-pba** [comment]
I'm sorry, but I cant answer this.

Unfortunatly, @nadouani already closed this issue, so it would propably the best if you post a new support question.

**Comment by nadouani** [comment]
It will put the "other" attribute type in misp and let you change it as you need
