### ISSUE TITLE
Can not view or delete alert when delete the case that created by Import Alert

### ISSUE THREAD

**Issue by vnStrawHat** [TheHive-Project/TheHive#1123]
# Can not view or delete alert when delete the case that created by Import Alert

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Windows 10
| TheHive version    |  3.4.0-1
| Package Type              | DEB
| Browser type & version    | Chrome, EDGE chromium

### Problem Description
Alert can not delete after imported to new case and delete this case opened

### Steps to Reproduce
1. Create new Alert
2. Click to Preview and Import
3. in "Import alert as" ->  select "empty case" -> select "Yes, Import"
4. Delete case created in step 3
5. Go to the Alert menu and select alert created in step 1 -> alert can not view or delete. Menu delete disappear

### Possible Solutions
We assume its a bug in the current version

**Comment by nadouani** [comment]
I think that removing the `Case`, should unlink it from the corresponding `Alert`. Thanks for catching

**Comment by vnStrawHat** [comment]
> I think that removing the `Case`, should unlink it from the corresponding `Alert`. Thanks for catching

Ya. I think that is root cause. Please fix this bug in the next RC or Release version
