### ISSUE TITLE
Configuring TheHive to listen on a public IP

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/TheHive#1127]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7
| OS version (client)       |  Windows
| TheHive version / git hash   | c44df9d83e734377ab526f75014046f79a9f2a0f
| Package Type              | From source
| Browser type & version    | Any

### Problem Description
I need to have TheHive listen on a public IP address during testing. I assume that I can add some type of Play configuration to the application.conf.

### Steps to Reproduce

Default sbt build.

**Comment by github-pba** [comment]
TheHive listens on the public address of the host, port 9000. So if you enter `http://host.example.com:9000`, you should be on your hive host.

**Comment by tlp-red** [comment]
Hi. As @github-pba wrote, default is listening on all interfaces. However, if you need to be more specific (restriction to a single interface), you can do it with the following directive in `application.conf`:

> http.address = "A.B.C.D"

See [Single Sign-On on TheHive with X.509 Certificates](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/certauth.md) and maybe also [Configuring the Akka HTTP server backend](https://www.playframework.com/documentation/2.7.x/SettingsAkkaHttp)
