### ISSUE TITLE
Feature Request: Show cancelled tasks after case is closed

### ISSUE THREAD

**Issue by aacgood** [TheHive-Project/TheHive#1128]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| TheHive version / git hash   | 3.4.0, c44df9d
| Package Type              | DEB
| Browser type & version    | N/A

### Problem Description
If a task has content added to it, but the task is not actually closed, the task becomes invisible after the case has been closed.  The data is being captured within the Elasticsearch DB but with a status of "Cancel".  The only way to then see any content that has been added to the task after this is to interrogate the ElasticsearchDB or use the API.

### Steps to Reproduce
1. Create new case from a template that contains associated tasks
2. Enter content into the task of the case but do not close it
3. Close the case without closing the task
4. The cases tasks become hidden

### Possible Solutions
1. Dont allow a case to be closed while there are open/non started tasks associated to it
2. Have an option within the case to "show cancelled tasks"

**Comment by github-pba** [comment]
Sorry, I can't confirm your experience.

When I close a case which has tasks that were started, enriched with data (Task logs added, Task description changed), but not yet finished, TH offers me to cancel or Close the Tasks and, after that, the case:

![2019-10-02 10_48_09-Microsoft Edge](https://user-images.githubusercontent.com/50981940/66030755-52998980-e502-11e9-8df2-8d4cba8c223f.jpg)

Doing so and after that, reviewing the case, all changes to the case are shown: i see added observables, I see the Task which I did not Close by myself but which has been closedd by TH, the Task description I changed is here as well as all Task log entries.

If I get you right, this is the behaviour expected by you.

**Comment by github-pba** [comment]
Or do you refer to tasks that were NOT started?

**Comment by aacgood** [comment]
The scenario im running against is that an analyst will add notes into a task but not actually click `start` on the task.  When the case is wrapped up they close the case off (and presses `Close tasks and case` as per your screenshot above).  That seems to make the tasks disappear from TheHive.

The task data is retained in Elasticsearch so its possible to read it out direct from there.

**Comment by github-pba** [comment]
OK, got it.

Just for curiosity: why do your analysts add information to tasks without starting them? This is certainly not the way of working as supposed by the engineers, so for the feature request you probably need a good reason for the RFE.

Don't get me wrong - I support your feature request, because I think if there _is_ a task - wether cancelled or not - it should be displayed in the closed case. And only for to show that there was an assigned task that hasn't been processed. This is something different than not having the task in the case.

**Comment by aacgood** [comment]
I honestly just think its overlooked.  They enter details but just forget to officially "start" the task.  So its an education thing.

**Comment by jeffrey-e** [comment]
+1 here :)

**Comment by jeromeleonard** [comment]
Hello. 

The current version of TheHive 4 makes the status of a task automatically set to "In progress" as soon as a user add  a worklog, even if the task has not been previously started.
