### ISSUE TITLE
Feature Request:  Organization like Cortex

### ISSUE THREAD

**Issue by V1D1AN** [TheHive-Project/TheHive#1143]
# Add Organization like Cortex

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 3.4
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
Can you add a management of Organization like Cortex but for the Hive.. A SOC manager have the view of all alarms but  users have the view of their events for a organization

**Comment by veeral-patel** [comment]
@V1D1AN Hey - thanks for your feature request! What's your use case for this?

**Comment by V1D1AN** [comment]
Hi,

With my team, we want to set up a SOC PDIS.
We want to use Thehive for incident management.
For the moment, the view segmentation functionality with TheHive is missing.

Example:
I have an information system "A" and I have an information system "B", each with a system "ElastAlert", ElastAlertA and ElastAlertB that go up in TheHive.

It would be nice if some users could see ElastAlertA's lifts and others could see ElastAlertB.

A SOC Manager could have the view of both ElastAlert.

A system like Cortex and its organizational system.

**Comment by veeral-patel** [comment]
@V1D1AN Thanks for your reply. A couple questions:

> With my team, we want to set up a SOC PDIS.

What is a SOC PDIS?

> For the moment, the view segmentation functionality with TheHive is missing.

Sorry I don't understand what "view segmentation" is, could you clarify? I didn't get the example you gave below.

> Example:
> I have an information system "A" and I have an information system "B", each with a system "ElastAlert", ElastAlertA and ElastAlertB that go up in TheHive.

> It would be nice if some users could see ElastAlertA's lifts and others could see ElastAlertB.

What is an information system? What is an ElastAlert? I've heard of ElastAlert the OSS tool, but I don't think that's what you mean. What is an ElastAlert lift?
