### ISSUE TITLE
thehive.service: Main process exited, code=exited, status=255/EXCEPTION

### ISSUE THREAD

**Issue by DevJho** [TheHive-Project/TheHive#1150]
Bug/Misconfiguration

Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| Package Type              |Binary

Problem Description

thehive.service - TheHive
   Loaded: loaded (/lib/systemd/system/thehive.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-10-25 05:59:01 EDT; 7s ago
     Docs: https://thehive-project.org
  Process: 2992 ExecStart=/opt/thehive/bin/thehive -Dconfig.file=/etc/thehive/application.conf -Dlogger.file=/et
 Main PID: 2992 (code=exited, status=255/EXCEPTION)

Oct 25 05:58:48 TheHive systemd[1]: Started TheHive.
**Oct 25 05:59:01 TheHive systemd[1]: thehive.service: Main process exited, code=exited, status=255/EXCEPTION
Oct 25 05:59:01 TheHive systemd[1]: thehive.service: Failed with result 'exit-code'.**

----------------------------------------------------------------------
I'm following the installation through Binary, and i got error in the above. does anyone know why?

Steps to Reproduce

sudo addgroup thehive
sudo adduser --system thehive
sudo cp /opt/thehive/package/thehive.service /usr/lib/systemd/system
sudo chown -R thehive:thehive /opt/thehive
sudo chgrp thehive /etc/thehive/application.conf
sudo chmod 640 /etc/thehive/application.conf
sudo systemctl enable thehive
sudo systemctl start thehive

-----------------------------------------------------------------

and re-run 
bin/thehive -Dconfig.file=/etc/thehive/application.conf
but still failed. here the log sample for the error.
[Thehive-log.txt](https://github.com/TheHive-Project/TheHive/files/3771580/Thehive-log.txt)

**Comment by github-pba** [comment]
Could you please post your `/etc/thehive/application.conf`. 

Redact passwords and such.

Thank you.

**Comment by jlecerf** [comment]
Hi,

I have the same error and I think it miss to CP command like this : 
sudo addgroup thehive
sudo adduser --system thehive
sudo cp /opt/thehive/package/thehive.service /usr/lib/systemd/system
sudo chown -R thehive:thehive /opt/thehive
**sudo cp /opt/thehive/conf/application.conf /etc/thehive/
sudo cp /opt/thehive/conf/logback.xml /etc/thehive/**
sudo chgrp thehive /etc/thehive/application.conf
sudo chmod 640 /etc/thehive/application.conf
sudo systemctl enable thehive
sudo systemctl start thehive

After this to CP command, it's work fine!

**Comment by nakagit** [comment]
I found the root cause of this issue, typo.

Please edit the following file:
**/etc/thehive/application.conf**
(Before)   play.modules.enabled += org.thp.thehive.connector.mi**ps**.MispModule
(After)     play.modules.enabled += org.thp.thehive.connector.mi**sp**.MispModule

Hope this help.  :)

**Comment by rriclet** [comment]
https://github.com/TheHive-Project/TheHive/issues/1595
