### ISSUE TITLE
[Bug] Analyzers that take more than 10 Minutes run into timeout

### ISSUE THREAD

**Issue by Tobrabo** [TheHive-Project/TheHive#1156]
We wrote some analyzers that take rather long to finisch (from minutes to several hours). They work and cortex shows their correct output once they are finished but TheHive waits only 10 minutes for them to finish and then shows and empty return field.

**To Reproduce**
run any analyzer that takes longer than 10 minutes. 
For example calculate hash for a big image file or run yara over an entire mounted image.

**Expected behavior**
It should just wait for the analyzer to finish just as cortex does.

**Work environment**
 - Client OS: linux
- Server OS: linux
 - Browse type and version: firefox 68
- Cortex version: 3.0

**Possible solutions**
Where do you change the timeout? can you edit timeouts for individual analyzers?

**Comment by 3c7** [comment]
To clarify:
The Analyzer completes successfully and Cortex displays the correct result. The real issue is TheHive running in some kind of timeout.

**Comment by KRUXLEX** [comment]
I have the same bug. It's very annoying. I wait for fix it.
**Workaround:**
In cortex-> analyzer->global configuration set a **job.cache** on more time (In my case it's a 60min). Then when you analyze the same observer again, Then hive gets a analyze from the same observer from last hour.

**Comment by maugertg** [comment]
Have this issue with an Analyzer I'm building as well. The Hive timeout is ~420 seconds (7 minutes) If you run an analyzer for 419 seconds it will sometimes succeed. ~420 seconds will return successful very rarely. 

I wrote a super basic analyzer that can reproduce the issue [here]((https://github.com/maugertg/the-hive-delay-error)
