### ISSUE TITLE
Support newline characters in Case Description

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1161]
Case Descriptions do not preserve the newline characters present in the the case creation form.

This can present problems if you have multilined data in your templates.

![image](https://user-images.githubusercontent.com/14067660/68432167-be59bc80-0168-11ea-8d48-3c14d1e91067.png)
![image](https://user-images.githubusercontent.com/14067660/68432339-185a8200-0169-11ea-8c9d-6f65dcaf7bdf.png)

**Comment by zpriddy** [comment]
With Markdown formatting you will need to do 2 new lines to have it show a new line.. 

I may be wrong about this but it’s my experience with The Hive 

Let me know if that works for you

**Comment by xg5-simon** [comment]
@zpriddy thats correct. Two break spaces or  to spaces to insert a <br/> as per the original markdown documentation. https://daringfireball.net/projects/markdown/syntax#p
