### ISSUE TITLE
Is there a working docker-compose configuration?

### ISSUE THREAD

**Issue by jadbaz** [TheHive-Project/TheHive#1163]
I've tried several docker-compose configurations including [pull/1144](https://github.com/TheHive-Project/TheHive/pull/1144)
I've encountered several errors
I actually just want to try thehive somehow to assess if it fits our incident management needs
Can anyone point me to a working docker-compose configuration for any version of thehive and any version elasticsearch and co just so I can try it out?

**Comment by milesflo** [comment]
@jadbaz There's some hacky fixes like deleting the default index for the ElasticSearch service, but you're better off using the host-based install method which has `thehive` and `cortex` exist as running services, with ES either host installed or in a container.

If you'd like to talk about it I invite you to check out the [gitter](https://gitter.im/TheHive-Project/TheHive) as it's been something we've been debugging for some time.
