### ISSUE TITLE
StreamSrv 504 Gateway Time-Out

### ISSUE THREAD

**Issue by eternalyperplxed** [TheHive-Project/TheHive#1164]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Docker
| OS version (client)       | MacOS Catalina
| TheHive version / git hash   | 3.4.0-1
| Package Type              | Docker
| Browser type & version    | All

### Problem Description
When using the default stream.longpolling settings, an error appears in the web UI every minute exactly with a StreamSrv 504 Gateway Time-Out pop-up (red box in bottom left corner of the browser window).

### Steps to Reproduce
1. Deploy The Hive/Cortex/Elasticsearch Docker Containers
2. Initialize the DB and applications
3. Wait for Error message to appear.  Happens every minute exactly.

**Comment by To-om** [comment]
TheHive frontend uses long pooling to retrieve updates from backend. By default, it keeps the connection at most 1 minute before closing it. You must configure your reverse proxy with a timeout higher than the configured long pooling refresh (`stream.longpolling.refresh` in application.conf).
