### ISSUE TITLE
Support for ES 7.x?

### ISSUE THREAD

**Issue by bowserkn** [TheHive-Project/TheHive#1165]
I'm having issues with hive's initial "update database." 

Before I spend any more time trying to troubleshoot, can someone confirm whether TheHive works with ES 7.x?

I saw this in the documentation, but I'm not sure how up to date it is:
"If, for some reason, you need to install Elasticsearch, it can be installed using a system package or a Docker image. Version 5.X must be used. From version 6, Elasticsearch drops mapping type."
https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#elasticsearch-installation

Thanks.

**Comment by milesflo** [comment]
Latest officially supported ES version is 6.8 to my knowledge.

They're working to replace the ES with a GraphQL database, so I would not anticipate support coming for ES 7.X.

**Comment by bowserkn** [comment]
Okay thank you. I scrapped the 7.x ES install, and I just got it working with 6.8.4.
