### ISSUE TITLE
TheHive-Cortext Integration issue (docker images)

### ISSUE THREAD

**Issue by Sylver-Dragon** [TheHive-Project/TheHive#1168]
# TheHive-Cortext integration issue 

### Request Type
Bug 

### Work Environment
TheHive: 3.4.0
Cortex: 3.0.0
Using docker images:
thehiveproject/thehive:3.4.0
thehiveproject/cortex:3.0.0
docker.elastic.co/elasticsearch/elasticsearch:6.8.4

This system was upgraded from:
TheHive: 3.3.0-1
Cortex: 2.1.3-1
ElasticSearch: 5.6.9
Previous version was also docker based.  

### Problem Description
After the upgrade I am no longer able to run Cortex analyzers from TheHive interface.  Attempting to "Run All" on an observable results in a selection dialog which does not list the connected Cortext server.

### Steps to Reproduce
1. Login to TheHive.
2. Open a Case with an Observable.
3. Select the Observables tab.
4. Select an Observable.  
5. Click "Run All".

### Complementary information
From the new environment:  
![image](https://user-images.githubusercontent.com/8031027/68977809-1b87ea80-07c7-11ea-8a39-657c3f9423d6.png)

This seems to indicate that "cortex01" (as defined in application.conf) is connected.  And old reports (prior to the upgrade) are available and can be viewed.  
If I click on "Run All":  
![image](https://user-images.githubusercontent.com/8031027/68977926-7a4d6400-07c7-11ea-8667-aacbecc1689c.png)

No Cortex servers are listed.   
I can login to Cortex directly and manually run an analyzer and receive a valid result.

I also do not have the option to run individual analyzers from TheHive interface:  
![image](https://user-images.githubusercontent.com/8031027/68978088-d4e6c000-07c7-11ea-8791-5db39e01b8d7.png)

I do see that a previous issue was resolved some time back:
https://github.com/TheHive-Project/TheHive/issues/727

**Comment by Sylver-Dragon** [comment]
This morning, I cloned my configuration and spun up docker instances of ElasticSearch 6.5.2, Cortex 3.0.0-1 and TheHive 3.4.0-1.  With this instance, I did not import my old data and instead built this as a fresh install.  After configuring everything, I was able to configure an analyzer, create a test case and observable and submit that observable to Cortex for analysis.  My issue seems to be tied to the data migration.

**Comment by Sylver-Dragon** [comment]
Ran a second test.  I migrated my data in TheHive; but, started with a fresh index for Cortex.  After configuring Cortex, I was able to run an analyzer from TheHive interface.  It appears that the issue is linked to the upgrade on my Cortex data.

**Comment by Sylver-Dragon** [comment]
After further testing, I believe I have determined the root cause of the issue and a way to work around it.  In Cortex 2.1.3-1 I have enabled the analyzers "FileInfo_5_0" and "URLhaus_1_1".  During the index upgrade from cortex_2 to cortex_4 I get the warnings:  

```
[warn] o.t.c.m.Migration - no definition found for worker URLhaus_1_1. You should probably have to disable and re-enable it  
[warn] o.t.c.m.Migration - no definition found for worker FileInfo_5_0. You should probably have to disable and re-enable it  

```

Once the upgrade is complete, both of these analyzers are gone from the list of analyzers available in Cortex under Organization->Analyzers.  However, I suspect they are still listed as enabled in the cortex_4 index itself.  When TheHive is attempting to enumerate what analyzers are available, I suspect that it is receiving some type of error and so stops trying to use that Cortex instance for the observable types associated with those analyzers.  Since I was testing hashes and domains, the URLHaus_1_1 analyzer was affecting all of my tests.  
In order to work around this issue, it is necessary to disable any analyzers from Cortex before upgrading.  In my case, I found that I could disable the two analyzers listed above and then do the upgrade.  TheHive still shows (and displays data from) previous scans by the two problematic analyzers; but, they can no longer be run.  However, the rest of the analyzers can now be run from TheHive interface.

**Comment by Sylver-Dragon** [comment]
I'm going to leave this issue open, as I feel that there is a bug in the upgrade process.  during the upgrade, the obsolete analyzers were identified; but, it appears that they were left in a state which interfered with normal operation and also unable to be disabled, leaving us without a way to correct the problem through the Cortex interface.  
I see two options for a fix:  
1. Disable the analyzers during the upgrade, so that they don't interfere with normal operation after the upgrade.  
2. Display the analyzers in the new interface with some type of warning to allow the user to manually disable them.

**Comment by To-om** [comment]
This is a Cortex issue. If the problem is still present in the last version, please create an issue on the Cortex repository.
