### ISSUE TITLE
Add auto complete to bulk tag option

### ISSUE THREAD

**Issue by TheDr1ver** [TheHive-Project/TheHive#1176]
# Add auto complete to bulk tag option. 

### Request Type
Feature Request

When attempting to bulk-tag multiple observables from the observables tags, TheHive does not currently auto-complete suggested existing tags as it does in all other aspects of the software. Request that this input allows for auto-complete as well.

![image](https://user-images.githubusercontent.com/6147794/69561521-867db200-0f7b-11ea-8c94-0407ef8584af.png)

**Comment by nadouani** [comment]
This section has been reworked in 4.0 release and supports the autocomplete.

Closing this issue.

Thanks @TheDr1ver
