### ISSUE TITLE
TemplateCtrl: Limit of nested fields [50] in index [the_hive_14] has been exceeded

### ISSUE THREAD

**Issue by MineshK** [TheHive-Project/TheHive#1189]
# TemplateCtrl: Limit of nested fields [50] in index [the_hive_14] has been exceeded.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 
| OS version (client)       | Windows
| TheHive version / git hash   | 3.3.1-1
| Package Type              | RPM, DEB, Docker, Binary, From source
| Browser type & version    | Chrome 

### Problem Description
When updating a case template, I add a Custom Field to the template, but when I try to save the template I get the error below. This is the 10th custom field added to this template (unsure if that is relevant, but unsure why the error says they are "Nested".

TemplateCtrl: Limit of nested fields [50] in index [the_hive_14] has been exceeded. 

### Steps to Reproduce
1. Create 10 x Custom Fields
2. Add 5 x Custom fields to Case Template
3. Save Template
4. Add another 5 x Custom fields to the Case Template
5. Error produced.

**Comment by nadouani** [comment]
Please see https://github.com/TheHive-Project/TheHive/issues/651
