### ISSUE TITLE
[FR] Clickable References

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1192]
In my particular Hive workflow, we have Alerts come in from our sources, serialized(Reference key) by the URL of the alert.

It would be good to have these References clickable, by either detecting that it's a valid (and implicity safe/defanged) URL, or defining ways for the Reference to have text + href(optional), as one defines in markdown.

**Comment by milesflo** [comment]
![image](https://user-images.githubusercontent.com/14067660/72190524-94b15180-33b4-11ea-98ee-7eb7798bac77.png)

Something like how it appears on the left-hand side

**Comment by nadouani** [comment]
The ID here is to add a `link` or `url` attribute to `Alert` objects.

**Comment by nadouani** [comment]
This is solved through the `alert.externalLink` attribute
