### ISSUE TITLE
[Q] Configure TheHive's first run using Docker Compose

### ISSUE THREAD

**Issue by 0xThiebaut** [TheHive-Project/TheHive#1199]
# [Q] Configure TheHive's first run using Docker Compose

### Request Type
Question

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 3.4.0
| Package Type              | Docker
| Browser type & version    | N/A

### Problem Description
I would like to deploy TheHive as part of a demo environment build using a `docker-compose` file. TheHive would be populated by alerts through [Elastalert](https://github.com/Yelp/elastalert) which, through TheHive4py, supports the legacy basic authentication (given `auth.method.basic` is configured).

The documentation defines [multiple steps](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#5-first-start) required to get the instance ready. Is it possible to automate these two steps (migration and user creation) using Docker environment variables?

I am aware this is not a secure setup given the hard-coded credentials but this is needed given the high number of demo environments to spin up.

**Comment by To-om** [comment]
This is implemented with issue #1204  (cf. [documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#customize-the-docker-image))
