### ISSUE TITLE
Imported Alerts Cannot be Deleted

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1201]
# Imported Alerts Cannot be Deleted

### Request Type
Bug / Feature Request

### Problem Description
Alerts that have either been Imported to a new Case or Merged into an existing Case cannot be deleted.

### Steps to Reproduce
1. Ingest/Create 2 Alerts, `A` and `B`
2. Import Alert `A` to a Case
3. Merge Alert `B` to Case `A`
4. Delete Case `A`
5. View Alerts tab
6. Alerts `A` and `B` will be there, marked as Imported and impossible to delete

### Possible Solutions
Deleted Cases should do a (optional?) cascading delete on relevant Alerts, assuming 1 Alert can only be imported to 1 Case.

### Complementary information
![image](https://user-images.githubusercontent.com/14067660/72295226-f61f2d80-360b-11ea-968c-35bcf12f5e1b.png)
^ Note that the selected alert cannot be Deleted, and that the Alerts count at the top has been marked as 0

Clicking on the link to the Alert produces the following error message:

![image](https://user-images.githubusercontent.com/14067660/72297997-fae6e000-3611-11ea-8055-85f96ab53de0.png)

**Marking the alert as Unread yields the following:**
![image](https://user-images.githubusercontent.com/14067660/72295445-72b20c00-360c-11ea-831c-e51d9e7681bc.png)

### Changes:
- Alert count reflects this alert being Unread
- Status is changed to "Updated" instead of imported
- Alert still **cannot** be Deleted now that it is Unread

###### Disclaimer, these screenshots were staged to redact PII

**Comment by ArnaudLhutereau** [comment]
Same problem when I transform an alert to a case :

1. Transform alert to case
2. Delete case
3. Go to the alert's list

Alert stays in but I can't delete it.

**Comment by V1D1AN** [comment]
Hello , I have the same problem ..
