### ISSUE TITLE
TheHive's docker containers should be orchestration-ready

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/TheHive#1204]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Package Type              | Docker

### Problem Description
The currently existing docker containers of thehive do not support orchestration. As previously mentioned in #1028, there is no nice way to start fresh but usable instances in the cloud and give admin creds to groups of students automatically.

To do that, the hive container would at least need to
- migrate the db automatically (shouldn't this should be done anyway?)
- create an admin account automatically (from env or secrets)
- take and register an API key for that account (from env or secrets)
- take and register a cortex key (from env or secrets)

Was there a specific reason that made you use docker's `command` to pass keys instead of env vars or secrets?

**Comment by To-om** [comment]
I hope this answers to you expectation (cf. [documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#customize-the-docker-image))
