### ISSUE TITLE
Issues with elastalert - winlogbeats

### ISSUE THREAD

**Issue by Dair8** [TheHive-Project/TheHive#1209]
Hello,

I have a couple of issues with alerts with logs from winlogbeats.

I have alerts created that trigger correctly and send that alert to TheHive, but then I found two issues:

    The first is that I can't extract observables such as:
    operative_system: "{match[host.os.name]}" or event_id: "{match[winlog.event_id]}"

The only observables that I receive on theHive are those without . ,i.e:
msg: "{match[message]}"

    The other issue is that I receive the following exception when the alert triggers:
    elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.host] of type [text] in document...

Nevertheless, the fields host.XXX appear in ELK.

I don't know if both issues are related.

Can you help?

**Comment by markus-nclose** [comment]
Hi Dair8,

The reason you can't access those fields is that they are actually nested. If expand an event on Kibana and view the JSON, you will see the fields like the below example:

`"beat": {
      "hostname": "server1",
      "version": "6.5.4",
      "name": "server1"
    }`

To access the nested fields, you would need to reference it like the following:
`operative_system: "{match[host][os][name]}" or event_id: "{match[winlog][event_id]}"`

Bonus tip. The same is true for accessing fields in Logstash.

`if [winlog][event_id] == "" {`

Hope it helps.

**Comment by Dair8** [comment]
That was it, thank you very much for your help
