### ISSUE TITLE
API search by title doesn't return correct results

### ISSUE THREAD

**Issue by jocelynjyl** [TheHive-Project/TheHive#1212]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu
| OS version (client)       | 10/Ubuntu
| TheHive version / git hash   | 3.x
| Package Type              | From source
| Browser type & version    | N/A

### Problem Description
Using the API to search for case by title when title has the format "Source - Type: abcd" doesn't return the correct results. It either returns no results, or it returns things that match the prefix. 

e.g. Searching "Source - Type: abcd" will return "Source - Type: abcd" and "Source - Type: something else". 

I've tried escaping both the colon (:) and spaces with \. 

Tested with hive4py, using the Insomnia app, and direct curl queries. 

### Steps to Reproduce
Example curl query: 
1. curl -XPOST -H 'Authorization: Bearer ***API_KEY***' http://localhost:9000/api/_search -H 'Content-Type:application/json' -d '{"query": {"_and": [{"_string": "title:Source - Type: abcd"}]}}'

**Comment by To-om** [comment]
The operator `_string` uses the [lucene query syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html).
If you want to check an exact value, use the query: `{"title": "Source - Type: abcd"}`
