### ISSUE TITLE
Not possible to import new alerts to cases when drilling down from dashboard

### ISSUE THREAD

**Issue by jurg** [TheHive-Project/TheHive#1218]
# Not possible to import new alerts to cases when drilling down from dashboard

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7.7
| OS version (client)       | CentOS 7.7
| TheHive version / git hash   | 3.4.0, c44df9d83e734377ab526f75014046f79a9f2a0f
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
When previewing an alert from the search page when drilling down on a dashboard, only the "Cancel" button is visible on the bottom of the modal. I'd expect "Mark as read", "Import alert as" etc to be visible and clickable.

This appears to be due to commit 7ab234e90b2f020ed8981ab988e4f5c39944c040 in an attempt to solve issue #1065, where the readonly-flag is hardcoded to "true" (presumably in ui/app/scripts/controllers/SearchCtrl.js, though I don't know exactly how all this stuff ties together). This hides the necessary buttons ("Mark as read" etc) from the bottom of the Alert Preview page.

### Steps to Reproduce
1. Create dashboard.
2. Enter the Search page from drilling down in a dashboard.
3. Click on an alert.

**Comment by nadouani** [comment]
Hello @jurg, sorry for taking a look on this old issue very late. That behavior is expected since we wanted just to preview the alert from the search page. 

Providing all the actions there might be a good option too. I will take on it.
