### ISSUE TITLE
Enrich Incident/Alert Data for internal host/user data (LDAP?)

### ISSUE THREAD

**Issue by rgine** [TheHive-Project/TheHive#1220]
I'm curious if it's possible to query AD via LDAP or some other mechanism to enrich alert or incident "indicators" with AD user or host data? 

For example, we may have an alerting system that only sends an internal IP and AD user account value. My analysts will need to manually resolve a hostname for the IP and search for user data for the AD username. 

We would like to (maybe through Cotex) perform the hostname resolution as well as extract the user's name, department, and other AD attributes.

**Comment by nadouani** [comment]
Hello, this is a typical use case of why you need an analyzer, 

AFAIK there is a PR for a LDAP analyzer that we will merge in one of the upcoming releases.
