### ISSUE TITLE
OAuth2 Bearer header should be of the format "Authorization Bearer" ?

### ISSUE THREAD

**Issue by linuxthor** [TheHive-Project/TheHive#1228]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS, RedHat
| OS version (client)       | Seven
| TheHive version / git hash   | 3.4.0
| Package Type              | RPM
| Browser type & version    | N/A

### Problem Description
While using the SSO feature to configure sign in via Microsoft Azure as the Identity Provider I was getting a 400 error back from Microsoft where the user details are checked at the userinfo endpoint with the returned token. Looking at the failed request it had a header of the form "Authorization bearer <token>" - when trying this request with cURL as "Authorization Bearer <token>" (i.e upper case B) it succeeds. 

### Possible Solutions
I think the faulty line of code may be:
https://github.com/TheHive-Project/TheHive/blob/master/thehive-backend/app/services/OAuth2Srv.scala#L101

**Comment by To-om** [comment]
You're right. According to OAuth2 RFC, Bearer must have a upper case "B". This will be fixed in next release.
