### ISSUE TITLE
AD Authentication with SSL not working

### ISSUE THREAD

**Issue by mspoerr** [TheHive-Project/TheHive#1232]
# AD Authentication with SSL not working

### Request Type
Question

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 3.4.0-1
| Package Type              | DEB

### Problem Description
The AD Authentication with SSL is not working. We started thehive with the "-Djavax.net.ssl.trustStore=/etc/thehive/truststore.jks -Djavax.net.ssl.trustStorePassword=xxx" settings, but when capturing the LDAPS communication, thehive always closes the connection because of untrusted certificates. 
The Root and Issuing certificates are in the keystore as "Entry type: trustedCertEntry"
AD Authentication without SSL is working fine.
How can I check if the keystore is loaded properly? Is there any other setting needed?

**Comment by mspoerr** [comment]
Any hint how to enable AD authentication debugging?

**Comment by To-om** [comment]
The truststore file must be a JKS file, using java Keytool.
`keytool -import -file YourCA-file.crt -alias YourCA -keystore myTrustStore`
If you use intermediate CA, you should add all CAs in path.
In order to enable debug you can add `-Djavax.net.debug=all` parameter in command line.

**Comment by mspoerr** [comment]
We found the issue: We imported two sets of certificates to the keystore - the old root and intermediate certs and the new ones and both sets come with the same CNs. We then deleted the currently unused set so that there is just one certificate per CN present in the keystore and now it is working fine.
