### ISSUE TITLE
Failed to Migrate from TheHive 3.3 to 3.4.0 - ElasticSearch request failure

### ISSUE THREAD

**Issue by romans8** [TheHive-Project/TheHive#1234]
### Request Type
Bug

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | K8's/NIX
| OS version (client)       | 10
| TheHive version / git hash   | thehiveproject/thehive:3.4.0
| Package Type              | Docker / K8's

### Problem Description
Migrated from Elastic 5.x to 6.8 -  Ok
Migrated from Cortex 2.1 to 3.0.1 - Ok
Migrated from TheHive 3.3 to 3.4.0 - Errors

I see http://elastic..url.here:9200/the_hive_14/_search?scroll=60000ms
I don't see http://elastic..url.here:9200/the_hive_15/_search?scroll=60000ms

### Possible Solutions
I suspect I will need to perform some curl commands per the migration documentation to backup 14 and restore to 15, or migrate somehow.

### Steps to Reproduce
Step 1 - Migrate ES to from 5.x to 6.8
Step 2 - Migrate Cortex Docker Code, Update the App Config, Rebuild, Log in and push the migrate button
Step 3 - Migrate TheHive Docker Code, Update the App Config, Rebuild, Error

### Complementary information
Logs

Using secret: ***********************************************************************
Warning automatic elasticsearch host config fails
elasticsearch host not configured
[info] o.r.Reflections - Reflections took 170 ms to scan 4 urls, producing 118 keys and 1308 values
[info] module - Loading model class models.LogModel
[info] module - Loading model class models.ArtifactModel
[info] module - Loading model class models.TaskModel
[info] module - Loading model class org.elastic4play.services.DBListModel
[info] module - Loading model class connectors.cortex.models.ActionModel
[info] module - Loading model class models.AlertModel
[info] module - Loading model class models.AuditModel
[info] module - Loading model class models.CaseTemplateModel
[info] module - Loading model class models.UserModel
[info] module - Loading model class org.elastic4play.services.AttachmentModel
[info] module - Loading model class models.DashboardModel
[info] module - Loading model class connectors.cortex.models.JobModel
[info] module - Loading model class models.CaseModel
[info] module - Loading model class connectors.cortex.models.ReportTemplateModel
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] a.r.Remoting - Starting remoting
[info] a.r.Remoting - Remoting started; listening on addresses :[akka.tcp://application@IP.IP.IP.IP:2552]
[info] a.r.Remoting - Remoting now listens on addresses: [akka.tcp://application@IP.IP.IP.IP:2552]
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@IP.IP.IP.IP:2552] - Starting up, Akka version [2.5.21] ...
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@IP.IP.IP.IP:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@IP.IP.IP.IP:2552] - Started up successfully
[info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@IP.IP.IP.IP:2552] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/cluster-usage.html#joining-to-seed-nodes
[info] c.s.e.h.ElasticClient$ - Creating HTTP client on http://elastic.url.here:9200
[info] c.c.s.CortexClient - new Cortex(cortex1, http://cortex.url.here:9001) authentication: connectors.cortex.services.CortexAuthentication$Key
[info] c.c.s.CortexAnalyzerSrv - Search for unfinished job ...
[error] o.e.d.DBConfiguration - ElasticSearch request failure: POST:/the_hive_15/_search?scroll=60000ms
StringEntity({"version":"true","query":{"bool":{"must":[{"term":{"relations":{"value":"case_artifact_job"}}},{"term":{"status":{"value":"InProgress"}}}]}},"from":0,"sort":[{"_id":{"order":"desc"}}]},Some(application/json))
=> ElasticError(index_not_found_exception,no such index,Some(_na_),Some(the_hive_15),None,List(ElasticError(index_not_found_exception,no such index,Some(_na_),Some(the_hive_15),None,null,None)),None)
[warn] o.e.d.SearchWithScroll - Search error
org.elastic4play.IndexNotFoundException$: null
at org.elastic4play.IndexNotFoundException$.<clinit>(Errors.scala)
at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:145)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)

Changed Config from/to:

FROM:
Elasticsearch
search {
Basic configuration
Index name.
index = the_hive
ElasticSearch cluster name.
cluster = es-cluster
ElasticSearch instance address.
host = ["elastic.url.here:9300"]
}

TO:
Elasticsearch
search {
Basic configuration
Index name.
index = the_hive
ElasticSearch instance address.
uri = "http://elastic.url.here:9200"
}
cluster {
  name = es-cluster
}

Ran:
curl -X POST "localhost:9200/_reindex?pretty" -H 'Content-Type: application/json' -d'
{
  "source": {
    "index": "the_hive_14"
  },
  "dest": {
    "index": "the_hive_15"
  }
}
'

Errors:
        {
      "index" : "the_hive_15",
      "type" : "case_artifact_job",
      "id" : "AWnabTlji7inWi6en7Qd",
      "cause" : {
        "type" : "illegal_argument_exception",
        "reason" : "can't specify parent if no parent field has been configured"
      },
      "status" : 400
    },

**Comment by To-om** [comment]
When you go to TheHive, you should see the [update page](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/updating.md).

**Comment by romans8** [comment]
For Cortex this happened. 

This unfortunately doesn't happen for The Hive.

The pods just keep restarting then I get a crash loop backoff for 5 min.

**Comment by romans8** [comment]
Changed Config from/to:

FROM:
Elasticsearch
search {
Basic configuration
Index name.
index = the_hive
ElasticSearch cluster name.
cluster = es-cluster
ElasticSearch instance address.
host = ["elastic.url.here:9300"]
}

TO:
Elasticsearch
search {
Basic configuration
Index name.
index = the_hive
ElasticSearch instance address.
uri = "http://elastic.url.here:9200"
}
cluster {
name = es-cluster
}

FIX:
# Elasticsearch
search {
  ## Basic configuration
  # Index name.
  index = the_hive
  # ElasticSearch cluster name.
  #cluster = es-cluster
  # ElasticSearch instance address.
  uri = "http://elastic.url.here:9200"

**Comment by battlesysadmin** [comment]
@romans8 , can we compare notes on our kubernetes manifests? After many hours of effort, I have been unable to deploy TheHive/Cortex successfully in k8s, getting stuck on finding the ElasticSearch cluster. Ready to give up, as the project has taken over a month. I have this in the logs:

`[info] o.e.ErrorHandler - GET /api/user/current returned 500`

Port-forwarding to the TheHive URL, I get a flashing red error dialog "**App: The ElasticSearch cluster is unreachable**"

**Comment by mdtro** [comment]
For those that stumble upon this as I did, make sure you've re-_opened_ the index if you restored it from a snapshot prior to attempting the upgrade.

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-open-close.html

```
curl -X DELETE "localhost:9200/the_hive_14/_open?pretty"
```
