### ISSUE TITLE
No longer possible to force usage of a case template (ui setting is missing)

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1239]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB

### Problem Description
It is no longer possible to force the usage of a case template as it was possible with thehive 3.4.
The full menu entry "ui settings" is not available

### Possible Solutions
This could be a possibility to define as org-admin or as global admin.

**Comment by nadouani** [comment]
This feature was not supposed to be ported in 4.0 but in later releases, but we finally included it in 4.0

**Comment by crackytsi** [comment]
@nadouani Thank you, I deeply appreciate that :) :) :)
