### ISSUE TITLE
Default Dashboards are missing

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1240]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB

### Problem Description
There are no longer any default dashboards

### Possible Solutions
Add the default dashboards during creation of the organization again.
Dashboards for Admin overall customers could also make sense.

**Comment by To-om** [comment]
Default dashboards cannot be created when the database is initialized (like with TH3) because they are linked to an owner and to organisation (and both doesn't exist yet).
Until I found a better solution, dashboards must be manually imported for each organisation.

**Comment by crackytsi** [comment]
Thanks @To-om 
I fully understand that.
Is there a file included that contains the dashboards and can be manually imported?
I think it would be great to mention the manual import process in the documentation. The included dashboards are great work (as the rest of TheHive and the core) and I think it would be a pity to leave that option after a version upgrade.

**Comment by To-om** [comment]
You are right, the documentation must be updated.

**Comment by To-om** [comment]
I've added some documentation

**Comment by gimmic** [comment]
I haven't found the solution to this for a fresh install? Where are the default dashboards now?

**Comment by gimmic** [comment]
Just as a small updated, I was pointed in the direction of this: https://github.com/TheHive-Project/TheHive/tree/3.4.2/migration/12/dashboards

Which allowed me to import the missing dashboards. I never had any from a fresh RC install and upgrade to final v4 release.
