### ISSUE TITLE
[Bug] Case Template default values can't be set during template creation

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1241]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB

### Problem Description
If you create a template in Thehive and want to set default values, it failes to save the template.
If you remove the default values and save and later add the values, it works again.

### Steps to Reproduce
1. Create template and try to save default values e.g. for integer values. Try to save.
1. Save without default values and later change the values, the template can be saved.

**Comment by crackytsi** [comment]
Error message:
TemplateCtrl: Invalid value type for custom field. Expected: integer Found : Some(1) (class scala.Some)

**Comment by To-om** [comment]
This issue is solved by commit ee3c19de
