### ISSUE TITLE
SearchSrv.NotFoundError 

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1242]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB

### Problem Description
If there is no cortex integrated, and you open a case a error message is popping up:
SearchSrv.NotFoundError 
As you can see in the developer console this is linked to a call, that results in a 404:
http://<ip>:9000/api/connector/cortex/action/_search?range=0-100&sort=-startDate

### Possible Solutions
Prevent that call if cortex is not configured.

**Comment by crackytsi** [comment]
If no cortex is configured and you see in the alerts view still the wheelchair. If you click on it, an error occures: AlertList: /api/connector/cortex/responder/alert/45152

**Comment by nadouani** [comment]
The fix needs to be by the following tasks, if cortex is not enabled

- [ ] Hide the responder button on alerts list
- [ ] Don't call Cortex to fetch responder actions in case details
- [ ] Don't call Cortex to fetch responder actions in task details
- [ ] Don't call Cortex to fetch responder actions in observable details
