### ISSUE TITLE
A (received) Shared Case is displayed as sender/owner

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1245]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB

### Problem Description
A (received) Shared Case is displayed as sender/owner.
This is irritating. Actually its only a received share.
Therefore the option is to delete it, but this fails ("Case sharing update failed")

### Steps to Reproduce
1. Share a case
2. Check view on the share receiver side.

### Possible Solutions
Make a section like "Shared by other organisations"

**Comment by jeromeleonard** [comment]
@crackytsi we need more details please. Does the problem stand in the UI ? Would you prefer to have another indicator to say that the case is "received" ?

**Comment by crackytsi** [comment]
My understanding is that if I have OrgA and OrgB the case stays in the Org. 
That means CaseA creates a Case, shares it with OrgB.
In this case we see that in OrgA we share Case with OrgB. 
("The current case is shared with the following organisation(s): OrgB"

But on OrgB we can also see:
("The current case is shared with the following organisation(s): OrgA"

I would expect a little difference:
("The current case is shared from organisation: OrgA"
instead of
("The current case is shared with the following organisation(s): OrgA"

That was confusing for me.

**Comment by jeromeleonard** [comment]
Ok I understand. In orgB you can see "Shared from another organisation" in the information label when putting the mouse over the little icon next to the title of the case. 
![image](https://user-images.githubusercontent.com/10532879/76400416-8c5b9f80-6380-11ea-9bda-aec87a7b0acc.png)

Maybe it is not enough.

**Comment by crackytsi** [comment]
This is a screenshot of the (receiving organisation) "shared from" 
![image](https://user-images.githubusercontent.com/11610825/76400671-f8d69e80-6380-11ea-95f5-5d22b61c4cab.png)

**Comment by jeromeleonard** [comment]
yes, maybe this part needs for improvement.

**Comment by nadouani** [comment]
> This is a screenshot of the (receiving organisation) "shared from"
> ![image](https://user-images.githubusercontent.com/11610825/76400671-f8d69e80-6380-11ea-95f5-5d22b61c4cab.png)

This section can contain multiple shares on that table, if OrgA shares the case with 10 other organisations. So telling you that `The current case is shared with the following organisation(s)` is meaningful.

We could probably add a visual indicator to highlight the share representing the owner of the case.

**Comment by nadouani** [comment]
We will try to make it clearer, thanks @crackytsi

**Comment by nadouani** [comment]
We now highlight the owner of the share when displaying the shares list

<img width="1012" alt="Screenshot 2020-05-04 at 17 07 23" src="https://user-images.githubusercontent.com/21827/80981101-c6e63380-8e29-11ea-8568-b2d546f0b725.png">
