### ISSUE TITLE
FR: Alignment of case custom-fields (metrics)

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1246]
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB

### Problem Description
Currently case custom fields are aligned on the left. In the past on the right side, there were the metrics.
The right oriented metrics were good to structure the gui and keep the page small.
I'm not so happy that the metrics are removed, because they were clear and easy to find on the right.
If Metrics still aren't continued, it would make sense to have 2 custom-fields per line (one left, one right)

### Possible Solutions
-align 2 custom-fields per line
-make custom-fields parametrizeable (left/right oriented)
-continue support for case metrics ;)

**Comment by nadouani** [comment]
Hello @crackytsi metrics have been removed because they are just a specific case of custom fields. 

We will display the custom fields using 3 columns for a better use of the space in the case details page.

**Comment by nadouani** [comment]
In alert preview panel, custom fields will be displayed using 2 columns, because the dialog has less space.

**Comment by crackytsi** [comment]
@nadouani Thank you :)
