### ISSUE TITLE
[Bug] Unable to save new or imported dashboards in 4.0-RC1

### ISSUE THREAD

**Issue by jamesbrock72** [TheHive-Project/TheHive#1250]
# Unable to save new or imported dashboards in 4.0-RC1

(Request Type)

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | Seven
| TheHive version / git hash   | 4.0-RC1
| Package Type              | RPM
| Browser type & version    | chrome  80.0.3987.122

### Problem Description
Not able to save dashboards. I can create and or import, and do get the notification that the dashboard was imported or saved, but they do not get listed under dashbaords.

### Steps to Reproduce
1. import dashboard or create a new one and save it
1. click away to another page
1. go back to dashbaords link and the new dashboard is not listed as available dashbaord

**Comment by cyberpescadito** [comment]
Facing the same issue here
