### ISSUE TITLE
Filtering by custom fields returns no results

### ISSUE THREAD

**Issue by martinr103** [TheHive-Project/TheHive#1252]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10.3
| TheHive version / git hash   | 4.0RC1
| Package Type              | Binary
| Browser type & version    | Firefox 73

### Problem Description

The fact that searching (filtering) for cases with specific custom fields is now possible (at least it seems so, as the GUI offers the custom fields in the filter dropdown) is GREATLY appreciated!

However, the search always returns "No records", regardless which of the custom fields available in our instance, and which field value I select for the filter.

**Comment by To-om** [comment]
@nadouani Custom fields  type "Integer" is not recognized in search module
