### ISSUE TITLE
[Bug] Attachments being truncated

### ISSUE THREAD

**Issue by christophercutajar** [TheHive-Project/TheHive#1260]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.4.0-RC2
| Package Type              | Docker

### Problem Description
Attachments that are uploaded to a case in TheHive are being truncated. Images only show the top half and documents are getting corrupted.

To try to resolve this issue, we added the following to the `application.conf` 

    # Max textual content length - defaults to 100kb
    play.http.parser.maxMemoryBuffer = 1M
    # Max file size - defaults to 10MB
    play.http.parser.maxDiskBuffer = 1G

However, we're still getting truncated imaged and corrupted files.  During investigation it was noticed that files over 200kb are being truncated. TheHive is not deployed behind an NGINX proxy.

### Steps to Reproduce

1. Create a case
2. Create a task
3. Add new task log
4. Upload an image or file 
5. Attempt to view the attachment

### Screenshot of an image

![image](https://user-images.githubusercontent.com/60098546/76523757-3b73a600-6469-11ea-8976-4186befb2746.png)

### Screenshot of a file after uploading it to TheHive and downloading it again.

![image](https://user-images.githubusercontent.com/60098546/76523921-868db900-6469-11ea-8979-3de9bd6368cf.png)

### Screenshot of the attachments 

![image](https://user-images.githubusercontent.com/60098546/76524047-bb9a0b80-6469-11ea-9d21-8ee79db44e9d.png)

**Comment by To-om** [comment]
`play.http.parser.maxMemoryBuffer` and `play.http.parser.maxDiskBuffer` are not related to this problem. If you try to upload a file larger than `maxDiskBuffer`, you'll get a "413 Entity too large" error.

If you try to upload the same file, TheHive doesn't store it again and use the old one. If the upload has truncated the file, uploading the file again won't solve the problem.

Can you compare the size of the original file, that displayed by TheHive and that of the truncated file ?
Can you confirm that you don't have a full disk ?

**Comment by christophercutajar** [comment]
@To-om taking `Getting started.pdf` as an example, TheHive illustrates that it's `696kb` in size while when I download the file it's only `272kb`. I've also checked the disk space and only `12%` used and so there is ample space for new files.

**Comment by To-om** [comment]
I can't reproduce this behaviour. Can you tell me more on your environment ?
Which version of elasticsearch do you use ? How do you run TheHive ? Do you use docker-compose ? If yes, can you paste the yaml file ? Which browser do you use ? Do you wait the end of the upload before going to another TheHive page ? Have you customize datastore related settings in your application.conf file ?

When you download the file you should see the sha256 of the file in the url. Does that hash is correct, for original file or truncated file ?

**Comment by christophercutajar** [comment]
Which version of elasticsearch do you use ? - ES version: 6.8.2
How do you run TheHive ? - We're running TheHive in K8s
Which browser do you use ? - Used both Google Chrome and Firefox
Do you wait the end of the upload before going to another TheHive page ? - Yes
Have you customize datastore related settings in your application.conf file ? - No customisations related to datastore

So this is interesting:

SHA256 before upload: `5a8a070660e92aba89b034ef6af645f90ce8fe6d9a3d376315e884dda2436f73 `
SHA256 in URL : `5a8a070660e92aba89b034ef6af645f90ce8fe6d9a3d376315e884dda2436f73 `
SHA256 of downloaded file: `38dd504850adec61ebef424e2ad642e5ac856b72db9956b13e017e4c0be9838c `

**Comment by crackytsi** [comment]
Do you access thehive via http or https?
I already created an issue for https, http works with https reverse proxy for me.

**Comment by christophercutajar** [comment]
Access is via HTTPS.

**Comment by To-om** [comment]
There are several known issues if you configure https directly on TheHive. They are related to PlayFramework and AkkaHttp. You must add a reverse proxy in front of TheHive to add a SSL layer (cf. [documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#101-https-using-a-reverse-proxy)).

**Comment by christophercutajar** [comment]
Thanks @To-om & @crackytsi for your feedback. Deployed NGINX as files are not being truncated anymore.
