### ISSUE TITLE
[Feature Request] Data analytics - ThirdParty.

### ISSUE THREAD

**Issue by dtokkk** [TheHive-Project/TheHive#1268]
### Request Type
Feature Request

### Problem Description
In previous version of the Hive (3.x) the DB ElasticSearch could be used on Kibana -> Canvas.
Can the data of TheHive stored in ElasticSearch and Cassandra simultaneously? Or there is another solution to integrate with third party Analytics tools? Example Apache Cassandra -> Apache Zeppelin. 

Regarding with that one the keyspace "thehive"DB in Cassandra is stored in hex. Can you document the schema of the actual keyspace thehive.

Errors on Zeppelin ->
java.nio.HeapByteBuffer[pos=0 lim=8 cap=8]

**Comment by To-om** [comment]
A direct access to database is not recommended as the format can change after an update.
Moreover you have to implement visibility rules in your analytics tools if you use several organisations.

If you still want to explore the database, I can suggest you to use [tools compatible with JanusGraph](https://github.com/janusgraph/janusgraph#visualization)
