### ISSUE TITLE
[Bug] Dashboards empty

### ISSUE THREAD

**Issue by dtokkk** [TheHive-Project/TheHive#1269]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 4RC1
| Package Type              | DEB

### Problem Description
After you created a dashboard there is not in the list. The dashboard list is empty. This issue happens with and user with rol analyst and org-admin.

### Steps to Reproduce
1. Dashboard -> Create a New Dashboard -> Save -> Dashboard.

**Comment by To-om** [comment]
This issue duplicates #1250
