### ISSUE TITLE
[Bug] Unable to rename/update case template Name field

### ISSUE THREAD

**Issue by gimmic** [TheHive-Project/TheHive#1275]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04 LTS
| OS version (client)       | Ubuntu 19.04
| TheHive version / git hash   | 4 RC1
| Package Type              | DEB
| Browser type & version    |If applicable

### Problem Description
After creating a case template, you cannot change the name of the template

### Steps to Reproduce
1. create case template
2. Attempt to update template name
3. No error, 200 POST OK, but case template name is not updated

**Comment by nadouani** [comment]
In TheHive 4 we will add a field called `displayName` to case templates and `name` has been made read-only, which is not backward compatible.

Asking @To-om for a step back about the `name` attribute.
