### ISSUE TITLE
[Feature Request] Show case sharing information on main case overview page

### ISSUE THREAD

**Issue by gimmic** [TheHive-Project/TheHive#1277]
### Work Environment
| TheHive version / git hash   | 4 RC1

### Problem Description
On the main case list, it would be helpful to show a sharing icon per-case if the case is shared with other orgs. The mouse-over text could be the name(s) of the organizations the case is shared to. 

This would provide at-a-glance overview of which cases are currently shared with another organization inside the hive. It could also alternatively provide a mechanism to add/modify current sharing settings for that case. 

Dirty Mockup, note the sharing icon next to the severity:
![image](https://user-images.githubusercontent.com/568957/78034002-c4755300-732c-11ea-8d10-32f432503aa4.png)

**Comment by nadouani** [comment]
Thanks @gimmic we will display the number of shares in the case list, and a link that open the sharing details of the case

**Comment by nadouani** [comment]
This is it.

<img width="1114" alt="case-list-sharing" src="https://user-images.githubusercontent.com/21827/82673227-cd561700-9c41-11ea-8cd2-6bd2bfe954b1.png">

**Comment by gimmic** [comment]
@nadouani Great to see this implemented! I do feel it would be more useful to list the organizations in the tooltip on mouse over than the count(which is already in the visual).

Should I open a new request?
