### ISSUE TITLE
[Bug] Changing task name removes other tasks

### ISSUE THREAD

**Issue by pdux** [TheHive-Project/TheHive#1281]
### Request Type
Bug

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |CentOS 7.6
| OS version (client)       | W10, Chrome
| TheHive version / git hash   | 4
| Package Type              | RPM
| Browser type & version    | Chrome

### Problem Description
This is about tasks added to the Case Temaplates!!!
I have had 6 tasks on list (Phishing workflow) and in the last one I misspelled the task title, when changed the title of the task and saved, next task on the list got the same new title. 
Example: 
1. task_11
2. task_2
3. task_3
Misspelled task_11, should be task_1. After editing task title:
1. task_1
2. task_1
3. task_3

### Steps to Reproduce
1. Create 5 tasks 
2. Change title of any of the tasks -> save task -> save template
3. Check list of tasks

Edit: 
The whole task changed data, not only title, but description also. 
This is about tasks added to the Case Temaplates!!!

**Comment by kwouffe** [comment]
I confirm:
- Changing a task name and saving the task (Update task button) is not visible on the UI
- After saving the template (Save Task Template button) and reloading the template, another task is modified instead
