### ISSUE TITLE
[Bug] Unable to add new datatypes

### ISSUE THREAD

**Issue by jsomwaru** [TheHive-Project/TheHive#1288]
### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | AL2
| TheHive version / git hash   | 4.0
| Package Type              | RPM

### Problem Description

I think I found a bug in the Hive4. When I sign in as an admin and navigate to:

Admin > Observable types

Then try to add an observable. The observable appears in in the UI on the observable types page. However, when i sign out and sign into my personal account on the hive. When trying to add observables to the case the new data types are not there.

Also in the Admin > Observable types page I am not able to delete added datatypes.

### Steps to Reproduce
1. Authenticate admin account
2. Admin > Observable types 
3. add type
4. Create a case and new type is not there

### Complementary information
<img width="1901" alt="Screen Shot 2020-04-21 at 2 37 33 PM" src="https://user-images.githubusercontent.com/32558301/79986218-b58c4700-8479-11ea-9083-7c7ad160e4ba.png">

<img width="905" alt="Screen Shot 2020-04-21 at 2 38 20 PM" src="https://user-images.githubusercontent.com/32558301/79986232-ba50fb00-8479-11ea-9023-1e87fd0de18a.png">

**Comment by jsomwaru** [comment]
This issue probably won't be looked at because you guy are completely redoing observables. But this is a bug and currently not possible in the latest release of the hive4.

**Comment by jsomwaru** [comment]
The bug can be seen in the logs.

On the admin add Observable types page:
The logs show the service making a request to 
<img width="231" alt="Screen Shot 2020-04-27 at 4 22 25 PM" src="https://user-images.githubusercontent.com/32558301/80417158-4b253d80-88a3-11ea-9b01-9c2cac89ccc0.png">

On the Case page:
The logs show the service going to
<img width="505" alt="Screen Shot 2020-04-27 at 4 23 45 PM" src="https://user-images.githubusercontent.com/32558301/80417262-790a8200-88a3-11ea-8751-340019bf623d.png">


These api requests return different data. The list_artifactDataTypes api call only return data types created by the system and this is why adding observable types does not and will not work on the most recent version of the hive4.

**Comment by nadouani** [comment]
In fact, the observable dialog relies on the old api for observable datatypes. We will use the new API. Thanks for finding this bug.
