### ISSUE TITLE
[FR#community] Create a Discord for community discussion

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1289]
[Discord](https://discordapp.com/) is a chat platform with integrated RBAC and channels, kind of like IRC. It's commonly used for community organization in FOSS and fan groups.

We have the Gitter, but it doesn't see much continued discussion... likely due to how niche the platform is.

Having an Official Discord for all things Hive(specific channels for TheHive, Cortex, TH4Py, announcements, and more) could lead to faster response times with questions, and reduce the amount of Issues opened related to questions and troubleshooting.

**Comment by milesflo** [comment]
(remove bug tag, add needs-discussion)

**Comment by jeffrey-e** [comment]
Hi @milesflo there is a community around developer topics I started a while back on slack. Maybe something to your likings?

https://join.slack.com/t/the-hive-community/shared_invite/zt-ec0qdfhi-wK5dgJSFcVAmhLgh9vzptg

**Comment by garanews** [comment]
@nadouani is the time ripe?

**Comment by nadouani** [comment]
Hello guys, now that I can take some time for this topic, I'm open to discuss it. Having a public community in discord is a fair point. Gitter is in fact limited.

**Comment by nadouani** [comment]
Once the discussion is closed, I'll create a dedicated github issue to plan and track actions

**Comment by milesflo** [comment]
Looking great!
