### ISSUE TITLE
[Bug] Mobile-responsive Hamburger not visible

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1290]
# Mobile-responsive Hamburger not visible

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.4.0
| Package Type              | Docker
| Browser type & version    | Firefox

### Problem Description
TheHive's responsive hamburger menu is not correctly stylized to appear.

(Note that when I say 'mobile', I'm referring to the small side of responsive design, not that this service should be accessible from a phone)

At first, I thought there _wasn't_ a hamburger menu to begin with, but mousing over the expected position revealed that there is a button there.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/14067660/80156254-52350e80-8578-11ea-995f-407a87a356d0.png">
<img width="866" alt="image" src="https://user-images.githubusercontent.com/14067660/80156298-6a0c9280-8578-11ea-9f5c-a9f5c9a65764.png">

The button contains 3 spans with the class `icon-bar`:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/14067660/80156349-89a3bb00-8578-11ea-98a0-c9e3375a34d0.png">

### Steps to Reproduce
1. Open TheHive site
1. Make browser narrow
1. Observe lack of hamburger menu

### Possible Solutions

This CSS class should be altered to have the property `background-color: white;`

Result:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/14067660/80156416-b48e0f00-8578-11ea-93c2-059789380555.png">

Alternatively, you can use the unicode char U+2630 ☰. This is pretty common and means less fighting with CSS, IMO:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/14067660/80156621-40a03680-8579-11ea-951f-b9489a7fd477.png">

**Comment by LaZyDK** [comment]
Wow. I didn’t even know that we had that button on mobile devices. This has been a nuance for quite some time for me :)

**Comment by milesflo** [comment]
This is still present in TH4

**Comment by milesflo** [comment]
@nadouani 🙌 🚀
