### ISSUE TITLE
[Feature Request] OAuth support for Basic authentication to authorization server's tokenUrl

### ISSUE THREAD

**Issue by hkelley** [TheHive-Project/TheHive#1294]
Current version of OAuth2Srv.scala assumes the authorization servers support the the RFC 6750 Bearer token.

Some authorization servers (Okta) only support  Basic auth. 
 https://developer.okta.com/docs/reference/api/oidc/#token

### Possible Solution
Add a configuration option to allow the selection of an authentication scheme,  Bearer or Basic.
Modify OAuth2Srv.scala at around line 96 to build an appropriate Authorization header based on the configuration option.

**Comment by To-om** [comment]
The basic authentication header format is `Authorization: Basic base64(user:password)`. I don't have user and password, so what should I put in that header ? The token ?

**Comment by hkelley** [comment]
I think I was mistaken when I opened this.   The bearer token mechanism in TheHive is working with Okta  (bearer/access token from Authentication servers is delivered in an HTTP Authorizaion header to /token endpoint).

**Comment by To-om** [comment]
Ok.
TheHive4 works with Okta and I'll use OAuth2 module from TheHive4 in TheHive3.
