### ISSUE TITLE
[Question] What are the criteria, that make an observable appear in the "Observable seen in X other case(s)" list?

### ISSUE THREAD

**Issue by Passimist** [TheHive-Project/TheHive#1297]
When I open two cases, both containing an identical PDF file and URL,
then open the file/url in one case it lists the observable of the other case under: "Observable seen in 1 other case(s)".

My Question is: What are the criteria that make the observable appear there?
Obviously it appears when using identical files and URLs. But will it for example work with files with identical hash but different filenames?

I tryed to find the answer to my question in the sourcecode but my understanding of the .scala files that probably contain it is not enough.

I hope this is the right way to ask this question and I am looking forward to any answers! :)

**Comment by Passimist** [comment]
Im sorry about the "bug" label... I cant find an option to change it to "Question".

**Comment by nadouani** [comment]
Hello @Passimist If an observable is similar to another if they have the same `dataType` and same `data`

**Comment by Passimist** [comment]
Hello @nadouani 
thank you for your reply. In case of dataType: file there is not data but instead attachment, right?
Does this mean all fields of the attachment dictionary have to match for it to be similar? Or maybe all hashes?
