### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by msszafar** [TheHive-Project/TheHive#1299]
# thehive throws exception on **centos** `org.apache.http.ConnectionClosedException: Connection closed`

Following steps were performed on CentOS up till now 

1. **Installed** using `yum install thehive`

1. Got the **key** using command `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1` and **added** in /etc/application.conf as **`play.http.secret.key="key_here"`**

1. **enabled the service** `sudo systemctl enable thehive` and started it `sudo systemctl start thehive` (didn't use root user because thehive doesn't start service while using root user) 

1. **Connected with localhost on port 9000** using **curl** `sudo curl -v http://127.0.0.1:9000` and its out is 
`About to connect() to 127.0.0.1 port 9000 (#0)
   Trying 127.0.0.1...
 Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
 GET / HTTP/1.1
 User-Agent: curl/7.29.0
 Host: 127.0.0.1:9000
 Accept: */*
 HTTP/1.1 303 See Other
 Location: /index.html
 Set-Cookie: THE-HIVE-XSRF-TOKEN=fd82c415e6565c43d1dfe6c35226973f15119d55-1588148136190-9b7341e580846b0a581156fd; Path=/
 Date: Wed, 29 Apr 2020 08:15:36 GMT
 Content-Length: 0
 Connection #0 to host 127.0.0.1 left intact` 

1. while accessing it from web-like **`HTTP://x.x.x.x:9000`** it throws exception 

`App: 
org.apache.http.ConnectionClosedException: Connection closed`

**Comment by nadouani** [comment]
Hello please use a valid issue template and provide logs and configs to be able to give you hints about your issue. This looks like a wrong installation
