### ISSUE TITLE
[Bug] ws.ssl.trustManager won't work for CORTEX config stanza

### ISSUE THREAD

**Issue by pettai** [TheHive-Project/TheHive#1305]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| TheHive version / git hash   | 4.0.0-RC1
| Package Type              | DEB

### Problem Description

Then adding ws.ssl.trustManager PEM store configuration doesn't work.
TheHive4 doesn't start or log anything upon adding that additional config to application.conf 

```
play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
cortex {
 servers: [
   {
     name: "external-CORTEX"                # Cortex name
     url: "https://cortex.on.some.other.machine" # URL of Cortex instance
     auth {
       type: "bearer"
       key: "<API_KEY>"                 # Cortex API key
     }
     ws.ssl {
       trustManager {
         stores [
           { type: "PEM", path: "/etc/thehive/CA.crt" }
         ]
       }
     }                        # HTTP client configuration (SSL and proxy)
   }
 ]
}
```

### Steps to Reproduce
1. Install TheHive4 deb package
1. update conf
1. restart TheHive4

### Complementary information

If I remove/comment out the `ws.ssl.trustManager...` stanza, TheHive4 will start up, but the Cortex integration will be "red" as non-working. If I re-add it, thehive4 service won't start and there will be nothing logged in `/var/log/thehive/application.log` at all, so I have nothing to share.

The only message(s) ends up in syslog, saying:
`May  4 13:29:01 hive4 systemd[1]: Started Scalable, Open Source and Free Security Incident Response Solutions.
May  4 13:29:02 hive4 systemd[1]: thehive.service: Main process exited, code=exited, status=255/n/a
May  4 13:29:02 hive4 systemd[1]: thehive.service: Failed with result 'exit-code'`

The same ws.ssl.trustManager configuration works fine on TheHive 3.4.x against the same Cortex instance. 

It would at least be more helpful to get some sort of output that could explain why the current configuration doesn't wanna work...

**Comment by To-om** [comment]
You must insert a `:` or a `=` between `stores` and `[`:
```
play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
cortex {
 servers: [
   {
     name: "external-CORTEX"                # Cortex name
     url: "https://cortex.on.some.other.machine" # URL of Cortex instance
     auth {
       type: "bearer"
       key: "<API_KEY>"                 # Cortex API key
     }
     ws.ssl {
       trustManager {
         stores: [
           { type: "PEM", path: "/etc/thehive/CA.crt" }
         ]
       }
     }                        # HTTP client configuration (SSL and proxy)
   }
 ]
}
```
