### ISSUE TITLE
[Bug] Hide multifactor option in user-dialog if Enable Multi-Factor Authentication is disabled.

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1317]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC2
| Package Type              | DEB

### Problem Description
So, the first TheHive 4rc2 issue ;)

If certificate based authentication via reverse-proxy with header variable is used (or maybe in other situtations as well), enabling of "Multi-Factor Authentication" failes.
The behaviour is, after clicking on this button, a page reload happens that leasds to to login page to type in User/password (even if certificate authentication was already performed).

This authentication is already some kind of strong 2FA. So I would really appreciate it, if there is no force to use that kind of authentication as written in the latest blog "We will consider making 2FA mandatory in TheHive 4.1."

### Possible Solutions
Optimize Authentication.

**Comment by aacgood** [comment]
Also as per <https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Administration/Authentication.md> I had forgotten to set multifactor to be enabled.
auth.multifactor.enabled = true

**Comment by crackytsi** [comment]
@aacgood : Thank you, I really should read the docs ;)
Ok, never the less, I think in this case the user-dialog option should consequently not be offered, so I renamed that ticket to 

"Hide multifactor option in user-dialog if Enable Multi-Factor Authentication is disabled."

**Comment by nadouani** [comment]
@To-om 

- can the `auth.multifactor.enabled` be enabled by default?
- does the `/api/status` contain an indicator regarding the 2fa option, if it's enabled or not?

**Comment by To-om** [comment]
The information is already in the result of `/api/status` (`mfa` in `config.capabilities`):
```
{
  [...]
  "config": {
    "capabilities": [
      "changePassword",
      "setPassword",
      "authByKey",
      "mfa"
    ]
  }
}
```

**Comment by nadouani** [comment]
@To-om `config.capabilities` seems to always contain `mfa` independently from `auth.multifactor.enabled`.

**Comment by To-om** [comment]
It should be ok now.
