### ISSUE TITLE
[Bug] WebHook creation does not work

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1318]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC2
| Package Type              | DEB

### Problem Description
I tried to create a webhook.
Basically there is a little mistake in the documentation about the curl command, see my PR here:
https://github.com/TheHive-Project/TheHiveDocs/pull/167

But never the less, after creation it just returns:
{"path":"notification","defaultValue":[],"value":null}

Which sounds wrong to my eyes.
After trying to perform a get command to /api/config/organisation/notification it is also returning this result.
The WebHook does not work.
Can you take a look into that and give me a little hint?

**Comment by To-om** [comment]
The documentation was wrong. The correct body is:
```
{
  "value": [
    {
      "delegate": false,
      "trigger": { "name": "AnyEvent"},
      "notifier": { "name": "webhook", "endpoint": "local" }
    }
  ]
}
```
@crackytsi I let you tell me if webhooks work for you before I close this issue.

**Comment by aacgood** [comment]
Not @crackytsi here but can confirm the updated POST body works now.

Also, looks like the setting is set per organisiation and not globally.

**Comment by crackytsi** [comment]
@To-om : Thank you very much, it works.
Can you please also share a curl that removes this configuration?

I also noted that compared to the old-webhook all nested objects are added (e.g. update of log --> contains data of case-task and case). Meanwhile in some situtations that might be helpfull in others this generates bigger responses and slows down the speed. Is this configurable to have the output same as in the 2.x and 3.x releases?

**Comment by To-om** [comment]
Now version 0 doesn't include parent object and version 1 does. This let you choose.

**Comment by To-om** [comment]
@crackytsi if you want to remove webhook, set an empty list:
```
curl -XPUT \
  -u$thehive_user:$thehive_password \
  -H 'Content-type: application/json' \
  $thehive_url/api/config/organisation/notification -d '
    {
      "value": []
    }
  '
```

**Comment by crackytsi** [comment]
Thank you very much :)
