### ISSUE TITLE
[Bug] Importing of some user failes

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1323]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC2
| Package Type              | DEB

### Problem Description
When I start the migration  tool to import everything, I can see the following error message:
```
[error] o.t.t.m.t.Input - org.thp.thehive.migration.dto.InputUser read failure:List(
 - : JsonValidationError(List('roles' is undefined on object: {"name":"error2","updatedAt":1518167098512,"status":"Locked","preferences":"{}","createdAt":1497380352646,"createdBy":"user1","updatedBy":" user1","password":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","_type":"user","_routing":"user7","_parent":null,"_id":" user7","_version":1}),WrappedArray()))
```

It seems that the attribute roles (I guess it was never used) makes some trouble.
Can you handle that in an upcoming release to allow also this user migration?

**Comment by To-om** [comment]
This error means that your data in ElasticSearch has invalid format. TheHive 3 doesn't permit to create an user without roles.
Anyway, I add a fallback for this case and consider the user as "read-only" profile.
