### ISSUE TITLE
[Bug] documentation error

### ISSUE THREAD

**Issue by pdux** [TheHive-Project/TheHive#1325]
I think there is small misspeling in the TH4 installation manual
https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_rpm.md#cassandra-database

Under "Configuration" there is: Run the command **sqlsh**:
Should be: Run the command **cqlsh**:

**Comment by nadouani** [comment]
Thanks @pdux fixed.
