### ISSUE TITLE
[Bug] Assignee List in Case and Tasks is no longer sorted Alphabetical

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1327]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC2
| Package Type              | DEB

### Problem Description
In TheHive 4 the Assignee List for Users in Tasks and Cases are no longer sorted. So usernames are mixed. That makes it more hard to find the correct person to assign a case or task.

### Possible Solutions
Plesae sort this userlist again alphabetical

**Comment by nadouani** [comment]
We added the alpha sort, note just that it's case sensitive.

In the future user selection component has to be improved to add scrolling, pagination and filtering
