### ISSUE TITLE
[Bug] Optimize Authorization Error message

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1331]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC2
| Package Type              | DEB

### Problem Description
I user header based authentication using a variable. To change the user I logoff and login with a different user. After the session expires (silently) the page still stays open, when I re-request the page (using F5) the header based user is again authenticated and userd. If this user is in a different organisation, access failes with a strange error message: "Invalid tuple". The idear is to optimize this error message or behaviour

### Possible Solutions
Bring an error message something like "You are not authorized to view this object".

**Comment by nadouani** [comment]
This was solved in TheHive 3 using the modal that is displayed when the expiration is reached. We will consider reenabling this feature.

**Comment by To-om** [comment]
I think that this is fixed in RC3. If you encounter this strange error message again, can you provide the full logs with stacktrace (from /var/log/thehive/application.log) ?
