### ISSUE TITLE
Make user management list paginable and sortable with default sort of username

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1332]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC2
| Package Type              | DEB

### Problem Description
Currently the userlist in user-managagement of organization is no longer sortable and paginable.
There is also no default sorting, so usernames are mixed and you have to search for a name using browser features.

### Possible Solutions
Make them sortable like in the old version, I'm aware that requires a lot of developement.  But I wanted to mention that for completness.

**Comment by nadouani** [comment]
User list improvements

![user-list](https://user-images.githubusercontent.com/21827/88174076-e9ffd280-cc23-11ea-97ac-5a1b06cd59ff.png)
