### ISSUE TITLE
[Bug] Read-only has options to edit task-logs

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1334]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive version / git hash   | 3.x, hash of the commit
| Package Type              | RPM, DEB, Docker, Binary, From source
| Browser type & version    | If applicable

### Problem Description
A read-only user can edit the task-logs.
Only if the user wants to store the logs, it failes, using a red error message on the left with the content:
"CaseTaskLog: org.thp.thehive.models.Log not found"

### Steps to Reproduce
1. Create RO user,
1. Login as RO user
1. Edit a log entry and save it using ok button.

### Possible Solutions
If user has only read-only permission don't give the offer in the GUI to edit a field.
The backend seems to successfully prevent the update because of missing permissions (log message is a little confusing).

**Comment by nadouani** [comment]
Thanks @crackytsi for this one, is was tricky to "see" :)
