### ISSUE TITLE
[Bug] Can't tag observable as IOC in Alert

### ISSUE THREAD

**Issue by CTIMarc** [TheHive-Project/TheHive#1335]
### Bug
When using API, we can't tag observable (artifact) as IOC. (ioc=True is not working)

### Problem Description
Create an alert with artifact and try to tag it as IOC.

**Comment by nadouani** [comment]
Hello @CTIMarc do you use TheHive4py or a raw call to the APIs?

**Comment by nadouani** [comment]
I guess it's TheHive4py since you are referring to `ioc=True`

**Comment by nadouani** [comment]
This is already fixed in TheHive4py
