### ISSUE TITLE
[Bug] severity change when create new case don't work

### ISSUE THREAD

**Issue by pdux** [TheHive-Project/TheHive#1338]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Oracle Linux Server 7.7
| OS version (client)       | W10
| TheHive version / git hash   | 4 RC2
| Package Type              | RPM
| Browser type & version    | Chrome

### Problem Description
When creating new case, I'm changing the severity from M to H, then save the case, the saved case has severity M

### Steps to Reproduce
1. create new case 
2. change severity to H
3. save case 
4. check severity - M

If you change the severity when the case is already created all is ok.

**Comment by To-om** [comment]
This bug appears only if you apply a case template.
