### ISSUE TITLE
API modifying alert (patch) custom fields delete previous ones

### ISSUE THREAD

**Issue by vazromju** [TheHive-Project/TheHive#1339]
Hello.
When update an Alert via API with PATCH and update empty custom fields, fields already filled are deleted and only get the new ones.
**Example**:
I have this Custom Fields
Action:  drop
AppID:  telnet
RemedyCase ---> empty

**Create a json.file**
	
```
{
    "customFields": { 
            "RemedyCase" : {
			"string": "Remedy0001"
        }
}

```
**and curl it:**

`curl -XPATCH -d @json.file -H 'Authorization: Bearer <api_key>' -H 'Content-Type: application/json' http://thehive.soc:9000/api/alert/518f0f4b5a096963a3c1be725363ea99  | json_pp
`

**now I get**
Action:  ---> empty
AppID:  ---> empty
RemedyCase:  Remedy0001

Do I need to fill again all the fields when updating an empty one?

Thank you.

**Comment by nadouani** [comment]
Hello @vazromju the request body here means: replace my custom fields with 

```
{ 
"RemedyCase" : { "string": "Remedy0001" }
}
```

Which in fact replaces value of `customFields`.

If you need to set just the dedicated custom fields than use this patch body

```
{"customFields.RemedyCase.string": "Remedy0001"}
```

Let me know if it works

**Comment by vazromju** [comment]
ok, ok.
seen
Thank you
