### ISSUE TITLE
[Bug] Webhook compatibility issues on custom-fields

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1345]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.0 RC2
| Package Type              | DEB
| Elasticsearch | 5.6.10

### Problem Description
The WebHook of TheHive4 behaves different regarding custom-fields compared to version 3.4:

TheHive 3.x:
```
	'details': {
		'customFields': {
			'fieldname': {
				'string': 'selected value'
			}
		}
	},

```
TheHive 4:
```
	'details': {
		'customField.fieldname': 'selected value'
	},
```

Also in the "object" the names are different:
TheHive 3.x
```
		'customFields': {
			'fieldname': {
				'order': 3,
				'string': 'selected value'
			},
		},
```

TheHive 4:
```
		'customFields': {
			'fieldname': {
				'string': 'selected value'
			}
		},
```

The "order" attribute seems also to be missing,
If it is not too much work, it would be great if this could be make compatible :)

**Comment by crackytsi** [comment]
@To-om can you fix this also with the upcoming release?

**Comment by crackytsi** [comment]
Thanks so much :) :) :)

**Comment by crackytsi** [comment]
@To-om I think there is still something wrong. In TH3 it is customFields with s and not customField (without s)

**Comment by To-om** [comment]
You're right ! Nice catch.

**Comment by crackytsi** [comment]
@To-om Just to mention it: there is another small difference. That does not play any rule for me (e.g. also works with your python-webhook stubb), so not sure if I should open an issue.

Meanwhile TH3 shows:
`'operation': 'Update',`
TH4 shows, note the small "U" letter:
`'operation': 'update',`
