### ISSUE TITLE
[Feature Request] Connect Cortex user per organisation

### ISSUE THREAD

**Issue by JulianBaSi** [TheHive-Project/TheHive#1363]
# Connect Cortex user per organisation

### Request Type
Currently you only can connect one Cortex user per TheHive-instance. 
You may do not want to have the same Analyzer/Responder configuration for all of your TheHive-organisations. 

Therefore it would be nice if you can connect multiple Cortex user (may from different Cortex organisaitons) and select a Cortex connection per TheHive-organisation. I suggest that you have a list of all connected Cortex-User in the org-administration and you can select the right one for your org.

**Comment by To-om** [comment]
In the Cortex connector configuration, you can list which organisations can use this Cortex with setting `includedTheHiveOrganisations` or list which organisations must not use this Cortex with setting `excludedTheHiveOrganisations`:
```
cortex {
  servers = [
    {
      name=Cortex1,
      url="http://localhost:9001"
      auth { type = "bearer", key = "key1" }
      includedTheHiveOrganisations = ["org1", "org2"]
    }
    {
      name=Cortex2,
      url="http://localhost:9001"
      auth { type = "bearer", key = "key2" }
      excludedTheHiveOrganisations = ["org2", "org3"]
    }
  ]
```
In that example, Cortex1 is available for organisations org1 and org2 and Cortex2 is available for all organisations except org2 and org3.
