### ISSUE TITLE
[Bug] Free text search does not work

### ISSUE THREAD

**Issue by JulianBaSi** [TheHive-Project/TheHive#1364]
# Free text search does not work

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 10
| TheHive version / git hash   | 4.0.0-RC2
| Package Type              | DEB
| Browser type & version    | Chrome 81

### Problem Description
If you search anything with the free text search you always get all entries of the selected type as result.

### Steps to Reproduce
1. create 2 cases
1. add min. 2 observables to one case, with different name
1. go to "Search"
1. select "Cases" or "Observables"
1. Enter some free text. Just like e.g. "setes"
1. Get all created entries of the selected type.

**Comment by nadouani** [comment]
Hello @JulianBaSi Thanks for the raising the issue.

The full text search will be disabled in TheHive 4 before adding an indexation layer.
With that being said, we have added the wildcard support when searching for text fields.

Thanks
