### ISSUE TITLE
[Bug] Limiting admin rights breaks front end

### ISSUE THREAD

**Issue by derDuffy** [TheHive-Project/TheHive#1368]
### Request Type 
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.0-RC2-1
| Package Type              | DEB
| Browser type & version    | FireFox

### Problem Description
Creating a new administration profile which can only add custom fields prevents the front-end from finishing to load. Once logged in you will get an empty page and the little activite indicator on the top keeps spinning and resetting. In my case it started with 5 went to 1 and started over.

Menu becomes unusable due to refresh.

### Steps to Reproduce
1. Create new admin profile
2. Limit the permissions to manageCustomField
3. Assign the profile to a user
4. Login using that user

### Possible Solutions
n/a

### Complementary information
I could verify that adding priviledges fixes the issue. Mainly addint the manageOrganizations permission lead to the issue getting better. The wheel kept spinning though.

**Comment by nadouani** [comment]
Hello @derDeffy, thanks for the issue. We will fix that one.
