### ISSUE TITLE
[Bug] Top 5 tags in Case -> Stats aren't correctly ordered

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1372]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4 RC3
| Package Type              | DEB

### Problem Description
The Top 5 Tags in Case list -> Stats aren't ordered.
See screenshot here:
![image](https://user-images.githubusercontent.com/11610825/83111618-2f40d180-a0c5-11ea-91cd-85e25b148d6a.png)

As I just noticed that also applies to TH3, but it would be nice to have them in any order. e.g. highest number first.

### Possible Solutions
Apply an order-by if possible.

**Comment by To-om** [comment]
@nadouani the result of the field aggregation API returns an JSON object and its fields can't be ordered. Frontend must do a sort.

**Comment by crackytsi** [comment]
There are much more responses than just 5 delivered, see screenshot here (on latest snapshot of developTH4 source):
![image](https://user-images.githubusercontent.com/11610825/83621246-b7741a80-a58e-11ea-8245-ca65da0b33fd.png)

**Comment by To-om** [comment]
@crackytsi which version of TheHive do you use ?

**Comment by crackytsi** [comment]
I use latest dev branch: https://github.com/TheHive-Project/TheHive/commit/107e558f35c90b4f6ffdc6db23b1ac9c4fb9d0f4

**Comment by To-om** [comment]
Have you updated scalligraph repo (`git submodule update`) ?

**Comment by crackytsi** [comment]
I used a complete new directory to build everything, so it should be the latest version.

**Comment by crackytsi** [comment]
@To-om Sorry, you are right. It was my fault in using the right compile-folder. I see now only the top 5 (unordered) :)
Thanks for your patience with me... :)

**Comment by nadouani** [comment]
This should be fixed. If anyone can tested and confirm the fix.
