### ISSUE TITLE
[Bug] CustomFields does not appear sorted in the case template

### ISSUE THREAD

**Issue by susangz** [TheHive-Project/TheHive#1383]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 18.04.4 LTS
| TheHive version / git hash   | thehive4 (4.0.0-0.1RC1)
| Package Type              | deb

### Problem Description
Custom fields added to a template does not appear in that order when a case is created. 
When the template is exported, the order fields is correct but that order is not followed when the case is shown in TheHive GUI.

### Steps to Reproduce
1. Create custom fields
2. Add them to a template in a predefined order
3. Create a new Case with that template
4. Check the Additional information in the new case with the custom fields does not appear in the order they were included in the template.

**Comment by nadouani** [comment]
Hello, is this issue true in RC3?

**Comment by nadouani** [comment]
Please reopen if this is still valid

**Comment by nadouani** [comment]
Reopening the issue as I can confirm it exists

**Comment by nadouani** [comment]
@To-om the orders of custom fields in case template are not taken into account when creating a case from a template

**Comment by s-knauer** [comment]
The order of custom fields is still not preserved in alert and case creation for TH4.

I set the order in the case template and checked the (equivalent) order being in the CustomFieldhelper.fields dictionary when using thehive4py for uploading a new alert (which should be imported as a case via the case template.)

The dictionary shows: {'fieldname' : {'order': 0, 'string': 'ABCD'}, 'fieldname2': {'order': 1, 'string': 'EFGH'} .... }. 
The template also states for Custom Fields the order: Fieldname, then fieldname2 and so on.
But the ordering in the webinterface is randomised. In the alert as well as in the case.

When i create an empty case via the webinterface, the fields have the right order. But when using real data for creating an alert, the ordering is ignored.
