### ISSUE TITLE
[HELP WANTED] Unable to connect Webhook

### ISSUE THREAD

**Issue by JulianBaSi** [TheHive-Project/TheHive#1386]
# Unable to connect Webhook

### Request Type
Bug / Help Wanted

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 10
| TheHive version           | 4.0.0-RC3-3
| Package Type              | DEB

### Problem Description
I need to connect a Webhook for TheHive. I followed your instructions, ending in the configuration as shown below.
If I capture the localhost interface, I cannot see that TheHive trys to send a Request. So I assume that the bug is on TheHive´s site.

### Steps to Reproduce
1. Run the [script](flask-script-to-test-webhook)
1. Configure TheHive as shown below
1. Create something new (case, user, ..)

#### Configuration in application.conf
```
notification.webhook.endpoints = [
  {
    name: "local"
    url: "http://127.0.0.1:5000/"
    version: 0
    wsConfig = {}
    includedTheHiveOrganisations = []
    excludedTheHiveOrganisations = []
  }
]
```

#### Activated webhook for organisation
``` 
curl -u orgadmin@thehive.local:secret http://127.0.0.1:9000/api/config/organisation/notification
{"path":"notification","defaultValue":[],"value":[{"delegate":false,"trigger":{"name":"AnyEvent"},"notifier":{"name":"Webhook","endpoint":"local"}}]} 
```
#### Flask Script to test Webhook
```
from flask import Flask, request
import json

app = Flask(__name__)

@app.route('/',methods=['GET'])
def foo():
   return "Server for TheHive Webhooks"

@app.route('/webhook',methods=['POST'])
def foo():
   data = json.loads(request.data)
   print(json.dumps(data, indent=4))
   return "OK"

if __name__ == '__main__':
   app.run()
```

**Comment by crackytsi** [comment]
My WebHook looks like this and works fine:
```
curl -v -XPUT -u$user:$password -H 'Content-type: application/json' http://127.0.0.1:9000/api/config/organisation/notification -d '
{
  "value": [
    {
    "delegate": false,
    "trigger": { "name": "AnyEvent"},
    "notifier": { "name": "webhook", "endpoint": "myLocalWebHook" }
    }
  ]
}'
```
I wonder about your configuration

Configuration stanze is:

```
notification.webhook.endpoints = [
  {
    name: myLocalWebHook
    url: "http://127.0.0.1:5000/webhook"
    version: 0
    wsConfig: {}
    includedTheHiveOrganisations: []
    excludedTheHiveOrganisations: []
  }
]

```

The Flask Script should work.

**Comment by JulianBaSi** [comment]
Thanks! Works fine now. 
The problem was the "=" instead of ":". Just didn´t read carefully
