### ISSUE TITLE
[Enhancement] Prevent link with "admin" organisation

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#1395]
### Request Type
Enhancement

### Problem Description
The organisation "admin" has special meaning and should not be link with any other organisation.

**Comment by crackytsi** [comment]
@To-om 
Just an additional thought from me about that:
Migration tool currently imports Admin-User of an organisation into the Admin-Org.
If they are not linked, this behaviour should be changed, otherwise you have 2 times the same (independent) account.

**Comment by To-om** [comment]
An user can be on 2 unlinked organisations. Links between organisations define visibility rules: objects (case, task, user, ...) belonging to one are visible to the other.
