### ISSUE TITLE
[Bug] TheHive is stalled while importing Alerts with a large number of observables

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/TheHive#1416]
## Issue 

In somes cases, when alerts with a high number of observables is imported, TheHive become unreachable, despite CPUs with 8 cores. TheHive distributes importing tasks on several threads in order to use full capabilities of multi-core CPU : it directly depends from the number of cores. Importing an event create a task for each observable and then monopolize almost all threads. Other tasks have to wait for threads to become free.

## Solution 
The solution is use dedicated thread pool for all tasks that requires high number of threads. This allocates new threads for dedicated tasks.

**Comment by To-om** [comment]
fixed by a320572

**Comment by To-om** [comment]
The fix does not work completely
