### ISSUE TITLE
[Feature Request] Automatically Randomly Assign Task to User

### ISSUE THREAD

**Issue by jonathanbrooke** [TheHive-Project/TheHive#1419]
### Request Type
Feature Request

### Problem Description
I have a group of IR Analysts that I would like to randomly assign tasks to (fairly, potentially rotational assign/based on cases completed per day etc.)

How could I set it so that for every new case created, the case and all of its tasks are assigned to one of the specified IR Analysts?

**Comment by nadouani** [comment]
Hello, this sounds like a very custom use case. I would handle it using an automation script that listen to case creation events, or to task creation events and assign the tasks to the user you decide programatically.

Or you can define a default assigner for each case when you define your case templates

**Comment by jonathanbrooke** [comment]
> Hello, this sounds like a very custom use case. I would handle it using an automation script that listen to case creation events, or to task creation events and assign the tasks to the user you decide programatically.
> 
> Or you can define a default assigner for each case when you define your case templates

Can we access TheHive events using an Event Listener? How might I access this data?
