### ISSUE TITLE
[Bug] Cannot query for null value

### ISSUE THREAD

**Issue by dainok** [TheHive-Project/TheHive#1421]
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | MacOs
| TheHive version / git hash   | 3.4.2-1
| Package Type              | From source
| Browser type & version    | Python Requests

### Problem Description

Failed to query with null values.

### Steps to Reproduce

Working request:

~~~
POST /api/alert/_search
{"query": {"_field": "_parent", "_value": "test"}}
~~~

Failing request:

~~~
POST /api/alert/_search
{"query": {"_field": "_parent", "_value": null}}
~~~

Result of failiing request:

~~~
{
  "type": "play.api.libs.json.JsResultException",
  "message": "JsResultException(errors:List((,List(JsonValidationError(List(Invalid query: unexpected {\"_field\":\"_parent\",\"_value\":null}),WrappedArray())))))"
}
~~~

**Comment by nadouani** [comment]
This query in invalid. What's the use case?

**Comment by dainok** [comment]
Get alerts without an associated case for a review.

**Comment by nadouani** [comment]
Try to check the « case » field instead of « _parent »

**Comment by dainok** [comment]
Seems that "case" is only populated when alert is part of a case. I'm not sure how I supposed to query for the absence of a field.

**Comment by nadouani** [comment]
Hello, please try this query:

```
{
    "query": {
        "_not": {"_contains": "case"}
    }
}
```

**Comment by dainok** [comment]
It works! Thank you for your time and sorry if I made you waste time.
I was too focused on my approach.
