### ISSUE TITLE
[Bug] Issue with dashboard creation

### ISSUE THREAD

**Issue by SOCOST** [TheHive-Project/TheHive#1430]
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04 LTS
| OS version (client)       | Ubuntu 20.04 LTS
| TheHive version / git hash   |  3.4
| Package Type              | DEB

### Problem Description
When a dashboard is created, there isn't a button to "add" a new graphic. The form only shows the "remove" button (see screenshot)

### Steps to Reproduce
1. Go to Dashboards
2. Select "Create new Dashboard"
3. Fill the form

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

![image](https://user-images.githubusercontent.com/68221026/87297108-2a669e80-c508-11ea-90e0-30cbac2cd413.png)

**Comment by nadouani** [comment]
There is not buttons under the `cancel` button on the right side?

**Comment by SOCOST** [comment]
Hi Nadouani. Thank you for your response.
Yes, there are buttons on the right side (see screenshot), but nothing happens when I click on them. I have tested this issue with three different browsers:

![image](https://user-images.githubusercontent.com/68221026/87396935-df09ca00-c5b3-11ea-940f-a93bdd3ab3c7.png)

**Comment by SOCOST** [comment]
Hi Nadouani. Can you please give us an update on this case? We really think TheHive is a great tool that will offer many improvements in our bussiness once we get the dashboards working. Thank you again.

**Comment by auslaender6** [comment]
@SOCOST : This is drag and drop ;) not "click". You have to left click, hold it and drop it into the empty field.

**Comment by SOCOST** [comment]
Thank you @auslaender6
