### ISSUE TITLE
[Bug]Observable Type not found

### ISSUE THREAD

**Issue by RaginiGopi** [TheHive-Project/TheHive#1440]
We are getting the error in the application log while trying to send alerts from Splunk to Thehive.
**682 [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-18 - POST /api/alert returned 404
org.thp.scalligraph.NotFoundError: ObservableType source_IP not found**

App used is Create theHive Alert

Sample payload is 
_{"caseTemplate": "xxx", "title": "xxx", "severity": 3, "artifacts": [{"message": "_time observed in this alert", "dataType": "_time", "data": "1594882800"}, {"message": "count observed in this alert", "dataType": "count", "data": "xxx"}, {"message": "index observed in this alert", "dataType": "index", "data": "xxx"}, {"message": "sourcetype observed in this alert", "dataType": "sourcetype", "data": "xxx"}, {"message": "source_IP observed in this alert", "dataType": "source_IP", "data": "xxx"}], "tags": ["xxx"], "tlp": 2, "sourceRef": "xxx", "type": "Splunk", "description": "xxx", "source": "xxx"}'_

**Comment by nadouani** [comment]
Hello,

could you please provide the context as described on the github issue template? 
We need to know which version of thehive you are using.

And btw, did you add the `source_IP` type in the admin section?

**Comment by RaginiGopi** [comment]
### Work Environment

Question | Answer
-- | --
OS version (server) | Ubuntu 16.04
OS version (client) | Windows 10 - Chrome
TheHive version  | 3.4
Package Type | From Source

### Problem Description
Not possible to send alerts from Splunk to the hive using _Create theHive Alert_ application installed at the splunk end.

Got the following error in hive application logs

** [WARN] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-18 - POST /api/alert returned 404
org.thp.scalligraph.NotFoundError: ObservableType source_IP not found**

Sample payload sent from Splunk is 
_{"caseTemplate": "xxx", "title": "xxx", "severity": 3, "artifacts": [{"message": "_time observed in this alert", "dataType": "_time", "data": "1594882800"}, {"message": "count observed in this alert", "dataType": "count", "data": "xxx"}, {"message": "index observed in this alert", "dataType": "index", "data": "xxx"}, {"message": "sourcetype observed in this alert", "dataType": "sourcetype", "data": "xxx"}, {"message": "source_IP observed in this alert", "dataType": "source_IP", "data": "xxx"}], "tags": ["xxx"], "tlp": 2, "sourceRef": "xxx", "type": "Splunk", "description": "xxx", "source": "xxx"}'

Getting the same error for every dataType (_time, count,index, sourcetype, ...) in the payload. 

When the same payload is used for previous version of the Hive, alerts were creating on hive.

@nadouani Where should I add the source_IP in admin section ?

**Comment by nadouani** [comment]
You need to be an admin user et add the datatype from the Datatype administration page
