### ISSUE TITLE
[Bug] Submitting a "\_" in a Task Log removes the  "\" resulting as "_" in the log

### ISSUE THREAD

**Issue by auslaender6** [TheHive-Project/TheHive#1443]
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian (TurnKey Core)
| OS version (client)       | Win10
| TheHive version / git hash   | 3.4.2-1
| Package Type              | RPM
| Browser type & version    | Chrome 83.0.4103.116 (64Bit)

### Problem Description
If we post a new Task Log entry, and the is an "\_" in the text the "\" will be removed and anoly the "_" is saved. ("" are just for better reading)

### Steps to Reproduce
1. Post text into the Task Log: Path example: C:\__test_group\__\example
2. After Saving, it shows: Path example: C:__test_group__\example

**Comment by auslaender6** [comment]
Looks like a view issue. See Screenshots.
![Bug 1](https://user-images.githubusercontent.com/36446823/88166809-2af1ea00-cc18-11ea-8443-dae2af9aa0f2.PNG)
![bug 2](https://user-images.githubusercontent.com/36446823/88166812-2b8a8080-cc18-11ea-9a09-9d9395a2e4b3.PNG)

**Comment by nadouani** [comment]
Task logs are using markdown syntax, if you want to skip formatting use double backquotes like  `C:\__test_group\__\example`
