### ISSUE TITLE
[Feature Request] Minor patch bump on Akka to better support Kubernetes Discovery

### ISSUE THREAD

**Issue by drewstinnett** [TheHive-Project/TheHive#1459]
# [Feature Request] Minor version bump on Akka to better support Kubernetes Discovery

### Feature Request

I'm working on a helm chart to deploy  TheHive to our Kubernetes cluster.  Looking at the [Akka Kubernetes Documentation](https://doc.akka.io/docs/akka-management/current/bootstrap/kubernetes-api.html), using their native Kubernetes discovery this would greatly simplify the clustering configuration, however the version of Akka that ships with TheHive4 is a little too old.  Could we bump this from `2.5.21` up to a version which supports the Kubernetes API?  The minimal version would be according to [this](https://doc.akka.io/docs/akka-management/current/discovery/kubernetes.html) would be `2.5.27`.   Thanks for all the awesome work!

**Comment by drewstinnett** [comment]
Also this should be a Feature Request, not bug, but can't seem to change the tags around 😁

**Comment by To-om** [comment]
TheHive4 comes with [play 2.8.2](https://github.com/TheHive-Project/TheHive/blob/4.0.0/project/plugins.sbt#L1) which depends on [akka 2.6.5](https://github.com/playframework/playframework/blob/2.8.2/project/Dependencies.scala#L10)

**Comment by drewstinnett** [comment]
Ahhh, apologies I was looking at the master branch, thanks for the info!
