### ISSUE TITLE
TheHive 4 - Application.conf file 

### ISSUE THREAD

**Issue by jjoseph8008** [TheHive-Project/TheHive#1461]
# Application.conf file for TheHive 4

Bug / Feature Request

### Work Environment

|---------------------------|--------------------
| OS version (server)       | Red Hat
| OS version (client)       | Windows 10
| TheHive version / git hash   | 4.0
| Package Type              | RPM
| Browser type & version    | If applicable

### Problem Description

I installed Cassandra and TheHive on RedHat using the steps in 
https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_rpm.md#installation-1

Used a local file system to store files /opt/thp_data/files/thehive as per documentation. However, I noticed that the documentation when it came to application.conf was slightly different. 
Documentation had the following:
storage {
provider = localfs
localfs.location = /opt/files/thehive
}

1. But application.conf file had localfs.directory instead of localfs.location.  I was wondering if someone can confirm whether localfs.directory is the right one or if it is supposed to be localfs.location.
2.  The file path /opt/files/thehive does not exist. I think this should be /opt/thp_data/files/thehive. Please let me know which one is the correct one.

**Comment by To-om** [comment]
The correct setting is `localfs.location`. The value depends on your system. There is no correct default value. Put an existing directory, writable by thehive user.
