### ISSUE TITLE
[Bug]Migration tool date/number/duration params don't work

### ISSUE THREAD

**Issue by empiresailor** [TheHive-Project/TheHive#1478]
# [Bug]Migration tool date/number/duration params don't work

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.0-1
| Package Type              | DEB
| Browser type & version    |Chrome 84.0.4147.125

### Problem Description
It's impossible to start the migration when you add date/number/duration params
`Error: Option --case-from-date expects a number but was given '20200727'
Try --help for more information.`

### Steps to Reproduce
Start the migration with xxxx-age or xxxx-from-date params

**Comment by mamoedo** [comment]
Same problem here

**Comment by To-om** [comment]
The accepted formats are:
 - `yyyyMMddHHmmss`
 - `yyyyMMddHHmm`
 - `yyyyMMddHH`
 - `yyyyMMdd`
 - `MMdd`
