### ISSUE TITLE
Ability to have nested tasks

### ISSUE THREAD

**Issue by hiddenillusion** [TheHive-Project/TheHive#148]
It would be useful to be able to create nested tasks. e.g. - I may have multiple things that part of a single task (sort of like a check list of items that need to be completed for that single task to be complete).

As it currently stands, the only way around this is to create separate tasks for each line item, which can be extremely cluttering.

Another use case would be:

- Case =  an entire engagement.
- Each task created within _Case_ (Case > task) is an analysis performed on an endpoint/source of evidence
- Each sub-task created within it's parent task (Case > task > sub-task) could be actions actions to take for the individual analysis.

Otherwise, I'd have to (1) create a new case for each individual investigation even though they're part of a larger case (2) merge all the cases together at the end but that isn't ideal

### Implementation details

- [x] Add `group` field to `case_task` model
- [x] Add a `default` group to existing tasks during migration
- [x] Update case template model and administration UI
- [x] Update the task details page to display the group
- [x] Update the task list page to display the tasks groups
- [x] Update the task list page to allow grouping

**Comment by neorage2k3** [comment]
I would find this feature request very helpful as well

**Comment by cvdsouza** [comment]
this would be a great feature to have. Would be very helpful.

**Comment by jasonblanks** [comment]
+1 This would help us to logically set phases of an incident.  If this was included with 
[issue #341](https://github.com/TheHive-Project/TheHive/issues/341)

**Comment by nadouani** [comment]
The required implementation steps:

- [ ] Add `group` field to `case_task` model
- [ ] Add a `default` group to existing tasks during migration
- [ ] Update case template model and administration UI
- [ ] Update the task details page to display the group
- [ ] Update the task list page to display the tasks groups
- [ ] Update the task list page to allow grouping
