### ISSUE TITLE
[Bug] Can't run analyzers with the last version

### ISSUE THREAD

**Issue by seifreed** [TheHive-Project/TheHive#1481]
### Request Type
Bug 

### Work Environment

Debian 10

### Problem Description

Since the last update I can't run the analyzers for any data type I have in my cases:

![image](https://user-images.githubusercontent.com/1843119/90378696-f720ad80-e079-11ea-9d44-c73ae81b6944.png)

### Steps to Reproduce
1. Update the last Hive4 version
2. Try to enrich an existing observable in the system

**Comment by rriclet** [comment]
@seifreed Could you provide more information about your configuration, TheHive and Cortex version used ?

**Comment by nadouani** [comment]
Closing the issue as outdated.
