### ISSUE TITLE
[Bug] Case close notification displays "#undefined" instead of case number

### ISSUE THREAD

**Issue by DrJohn1** [TheHive-Project/TheHive#1488]
# When closing a case, the notification will show "The case #undefined has been closed" on the notification (bug)

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| TheHive version / git hash   | 4.0.0-1
| Package Type              | DEB

### Problem Description
Closing case notification shows `undefined` instead of case number:
![Issue_CloseCaseUndefined](https://user-images.githubusercontent.com/25451370/90975475-d0a8b980-e534-11ea-8419-4e7487650a5e.png)

### Steps to Reproduce
1. Close a case.
1. The notification will show `#undefined`.

### Possible Solutions
Changing the variable `caze.caseId` to `caze.number` in line 95 of `frontend/app/scripts/controllers/case/CaseCloseModalCtrl.js` seems to fix the issue.

**Comment by To-om** [comment]
Fixed by #1515
