### ISSUE TITLE
[Feature Request / Issue] Change of Base URL / Proxy Requests to the Hive

### ISSUE THREAD

**Issue by JustCodeIt4Head** [TheHive-Project/TheHive#1504]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 9.x LTS
| OS version (client)       |  Windows 7 / 10
| TheHive version / git hash   | 3.4.2 latest from Docker Hub (2e817ee9638c)
| Package Type              | Docker
| Browser type & version    | Google Chrome Version 85.0.4183.83

### Problem Description
When using an Nginx reverse proxy with Plesk Domain Management the proxy_pass requests are always redirected to / and not to the actual location. E.g the proxy_pass is with location /hive/ and the directive is proxy_pass http://127.0.0.1:9000/; the followup requests always get send to / instead of http://somedomain.com:9000/hive/.

### Steps to Reproduce
1.  Install Hive on Docker on a System with Plesk
2.  Set directive as documented in the Documentation (note that / is not available as a location):
location /hive/ {
 add_header	Strict-Transport-Security "max-age=31536000; includeSubDomains";
 proxy_pass              http://127.0.0.1:9000/;
 proxy_http_version      1.1;
 proxy_set_header Connection "";
}
3.  use location e.g somedomain.com/hive/
4. Proxy redirects to somedomain.com/index.html on Port 80 instead of given port 9000

### Possible Solutions
Possibility to change the root URL and domain that Hive is listening too or add the Possibility to listen for SSL traffic on Port 9000 instead of using a reverse proxy for it

### Complementary information
Grafana calls the Variables that need to be changed root URL aka " The full public facing url you use in browser, used for redirects and emails. If you use reverse proxy and sub path specify full url (with sub path)" and domain as the public facing domain name used to access the Application.
Dont know how they are called in TheHive

Edit: Accidentally got labeled as a bug, can someone relable it as Issue or Feature Request?

**Comment by To-om** [comment]
You can change the base URL of TheHive with the setting `play.http.context="/hive"` in application.conf

**Comment by JustCodeIt4Head** [comment]
> You can change the base URL of TheHive with the setting `play.http.context="/hive"` in application.conf

Hi ,
thank you for the hint. Is there any Documentation of the Parameters / Calls that can be made in the application.conf?

**Comment by V1D1AN** [comment]
Thanks for this information !!!!!!
Can you put it in the doc please..
I've been looking for hours how to do it

**Comment by JustCodeIt4Head** [comment]
Change of Base URL via play.http.context="/hive"
Mentioned here: https://github.com/TheHive-Project/TheHive/issues/1504#issuecomment-689358596
