### ISSUE TITLE
[Bug] Slow UI performance in observable analyzer jobs page

### ISSUE THREAD

**Issue by DrJohn1** [TheHive-Project/TheHive#1505]
# The list of available analyzers in the observable page is very slow on instances where a high number of analyzer jobs have been run in total (bug)

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| TheHive version / git hash   | 4.0.0-1
| Package Type              | DEB

### Problem Description
On a TheHive instance, as the number of analyzer jobs increases, the list of available analyzers / analyzer job results takes longer on any new observable. 
![Analyzers_not_loading_001](https://user-images.githubusercontent.com/25451370/91892381-d881ff80-ec92-11ea-8070-92f2b2dc1e03.png)

Time taken for the list of available analyzers to appear on the observable page of a new ovservable (no analyzer jobs run on it):
| Total cases | Total observables | Total analyzer jobs run | Time to load analyzer list page (new observable)
|-------|-------------------|----------------------|--------------------
| 20     | 100  | 200 | <1 second
| 400   | 2000 | 4000 | > 8 seconds
| 800  | 4000  |8000 | > 15 seconds

![Analyzers_not_loading_002](https://user-images.githubusercontent.com/25451370/91892440-f64f6480-ec92-11ea-99ac-eb005de1327f.png)

### Steps to Reproduce
1. Create a TheHive instance and add multiple cases and observables.
1. Run multiple analyzers on different observables per case (500 observables, 20 analyzer jobs per observable).
1. Create a new case and add an observable.
1. When entering the observable details page, analyzers / analyzer jobs will take a long incremental time to appear.

### Complementary information
Testing the query `/api/connector/cortex/job/_search` with TheHive4py, the same incremental times are obtained, it seems it may be related to cortex queries still using V0 API.

**Comment by rriclet** [comment]
This issue has been fixed with #1731, included in release 4.1.0.
Feel free to re-open this issue if you still notice slow performance.
