### ISSUE TITLE
[Bug] Slow UI performance when closing a case

### ISSUE THREAD

**Issue by DrJohn1** [TheHive-Project/TheHive#1506]
# When closing a case, the list of open/in progress tasks takes too long to load, causing issues if pressing "Close tasks and case" before it completely loads (bug)

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| TheHive version / git hash   | 4.0.0-1
| Package Type              | DEB

### Problem Description
When selecting "Close" case button, the first dialog listing open/in progress tasks will appear empty and take a long time (>10 seconds) to appear. If you select "Close tasks and case" before the list appears, the close dialog will appear twice, losing any changes you enter and not closing the case when pressing "Close case":
![Close_case_001](https://user-images.githubusercontent.com/25451370/91895950-5f85a680-ec98-11ea-9d25-86481b50728e.png)
Example shows no tasks, however this case still has three tasks open.

The logs show it takes, in this test case, 7 seconds to populate the list (but it increases exponentially as more cases and tasks are created on the TheHive instance):
![Close_case_003](https://user-images.githubusercontent.com/25451370/91896029-8348ec80-ec98-11ea-8338-b4b913ac3223.png)

### Steps to Reproduce
1. Create a new instance and add multiple cases and tasks to the cases.
1. Load a high number of cases and tasks (100 cases, 2000 tasks).
1. Press Close in a case and on the next dialog press "Close tasks and case" before the list appears.
1. Changes made to the close dialog will not be saved as the dialog resets.

**Comment by rriclet** [comment]
This issue has been fixed with #1731, included in release 4.1.0.
Feel free to re-open this issue if you still notice slow performance.

**Comment by scottbrazil** [comment]
I'm using release 4.1.24 and it takes 60s just to open the popup for closing the case
