### ISSUE TITLE
[Bug] Tags of observables in Alerts are not created when promoted

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/TheHive#1510]
### Problem Description
When an alerts contains observables with tags and is promoted as Case, tags are not seen in observables details nor in observables list.

**Comment by alanjones** [comment]
I believe this has already been fixed in 4.0.1.

https://github.com/TheHive-Project/TheHive/issues/1499

**Comment by To-om** [comment]
@alanjones #1499 merge tags only  if observable already exists. Here it is another problem.
