### ISSUE TITLE
[Error]Elasticsearch service failed

### ISSUE THREAD

**Issue by viszsec** [TheHive-Project/TheHive#1513]
Hi Team,

I had issues troubleshooting this elasticsearch service which includes reinstalling it.

The hive service worked fine. it just this elasticsearch keeps on failing after enabling and starting it.

can someone help me on this? really appreciate it!

===========================
elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-09-08 05:33:21 UTC; 2min 59s ago
       Docs: http://www.elastic.co
    Process: 139774 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
    Process: 139775 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} >
   Main PID: 139775 (code=exited, status=1/FAILURE)

Sep 08 05:33:16 iraas systemd[1]: Starting Elasticsearch...
Sep 08 05:33:16 iraas systemd[1]: Started Elasticsearch.
Sep 08 05:33:16 iraas elasticsearch[139775]: OpenJDK 64-Bit Server VM warning: Ignoring option UseConcMarkSweepGC; support was removed in 14.0
Sep 08 05:33:16 iraas elasticsearch[139775]: OpenJDK 64-Bit Server VM warning: Ignoring option CMSInitiatingOccupancyFraction; support was removed in 14.0
Sep 08 05:33:16 iraas elasticsearch[139775]: OpenJDK 64-Bit Server VM warning: Ignoring option UseCMSInitiatingOccupancyOnly; support was removed in 14.0
Sep 08 05:33:21 iraas systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 05:33:21 iraas systemd[1]: elasticsearch.service: Failed with result 'exit-code'.

**Comment by To-om** [comment]
I suggest you to see the Elasticsearch logs (probably located in /var/log/elasticsearch)

**Comment by viszsec** [comment]
Hi @To-om ,

the problem solved now after choosing with the docker installation options. However, the cortex was not functioning well. Elasticsearch cluster is unreachable. Is there a way to solve the issue? is it config issue?

**Comment by viszsec** [comment]
issue solved.
