### ISSUE TITLE
Spelling mistake: "getReportTemplace" -> "getReportTemplate"

### ISSUE THREAD

**Issue by miyoyo** [TheHive-Project/TheHive#1518]
Issue in this file, line 39:

https://github.com/TheHive-Project/TheHive/blob/48a306669c0bf3c79340f7eab3b6e1310ecc661b/cortex/connector/src/main/scala/org/thp/thehive/connector/cortex/controllers/v0/AnalyzerTemplateCtrl.scala#L39

**Comment by To-om** [comment]
This typo has already been fixed by ee07bc9e (cf. [AnatyzerTemplateCtrl.scala](https://github.com/TheHive-Project/TheHive/blob/develop-th4/cortex/connector/src/main/scala/org/thp/thehive/connector/cortex/controllers/v0/AnalyzerTemplateCtrl.scala#L96))
