### ISSUE TITLE
[Bug] Entrypoint: Waiting for cassandra with --no-config

### ISSUE THREAD

**Issue by Cynn8888** [TheHive-Project/TheHive#1519]
#Request Type
Bug

Work Environment
TheHive 4.0.0

Problem Description
The docker entrypoint doesn't sleep for 30 seconds until the cassandra Db is up when --no-config is used. Thehive cannot connect an exits the container.

**Comment by kahla-sec** [comment]
Hello , are you using the custom application.conf file when you run the container?
 The --no-config command is intended for testing purposes and doesn't use cassandra as a Db. You can refer to this short tutorial if you want to use --no-config command https://bit.ly/2RdT4jW.
Thank you.
