### ISSUE TITLE
Cannot import report templates - Attribute name is missing [Bug]

### ISSUE THREAD

**Issue by daskydasky** [TheHive-Project/TheHive#1520]
Cannot import report templates

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 10.5
| OS version (client)       | Windows 10
| TheHive version / git hash   | 4.0.0-1
| Package Type              | DEB
| Browser type & version    | Firefox

### Problem Description
I have a newly built server with TheHive v4 on it. When trying to import the official case templates getting the below error:
TemplateCtrl: [Attribute name is missing] 
and the import fails.

Log attached; 
[log.txt](https://github.com/TheHive-Project/TheHive/files/5195425/log.txt)

**Comment by To-om** [comment]
This error means that your case template doesn't have name (and case template must have one). Where does it come from? Can you attach it to that case?

**Comment by daskydasky** [comment]
Downloaded from https://dl.bintray.com/thehive-project/binary/report-templates.zip
Is this not the one I should be using with v4?

**Comment by To-om** [comment]
You confuse the report templates and case templates. The report templates are used to display analyzer result (from Cortex). The case template describe a case.
