### ISSUE TITLE
[Feature Request] Prompt to save changes to Case Templates before navigating away

### ISSUE THREAD

**Issue by caltom26** [TheHive-Project/TheHive#1524]
### Request Type
Feature Request

When creating a case template, if we navigate away from the case template before clicking "Save case template" all changes are lost. We have lost a bit of work as the save button isn't in a prominent location, and there are no prompts before navigating away from a page with unsaved changes. 

When we navigate away from the page there should be one of two prompts: 

1. You have unsaved changes on this case template. Would you like to save your changes? [Yes/No]
2. You have unsaved changes on this case template. Are you sure you want to navigate away from this template? All unsaved changes will be lost. [Yes/No]

**Comment by nadouani** [comment]
This will be fixed by #1804. We will use a modal that you need to either cancel or validate by hitting a button (no ESC, or backdrop click enabled)
