### ISSUE TITLE
[Bug] New TheHive 4 Roles not displayed under /api/current endpoint

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1535]
# [Bug] New TheHive 4 Roles not displayed under `/api/current` endpoint

### Request Type
Bug

### Problem Description
This is an x-post from the TheHive4Py repo. Work may be required on either/both projects.

https://github.com/TheHive-Project/TheHive4py/issues/178

**Comment by To-om** [comment]
The [output](https://github.com/TheHive-Project/TheHive/blob/develop-th4/dto/src/main/scala/org/thp/thehive/dto/v0/User.scala#L21) of the API `/api/user/current` must be compatible with TheHive3 and doesn't contain user permissions.
On the other hand the new API (`/api/v1/user/current`)  provides [informations](https://github.com/TheHive-Project/TheHive/blob/develop-th4/dto/src/main/scala/org/thp/thehive/dto/v1/User.scala#L19) on user permissions. It also contains the list of user organisations, including the profile.

The new version of TheHive4py should use v1 APIs which provide enough information. I close this issue.
