### ISSUE TITLE
[Feature Request] Add the ability to disable SSL certificate check

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#1538]
### Request Type
Feature Request

### Work Environment
TheHive 4.0.0

### Problem Description
In test environment, it is often difficult to have valid certificates (with correct DNS name in subject alternative name, and present in the truststore) for external services (MISP and Cortex).
It would be helpful to add the ability to disable SSL certificate check in configuration file.

**Comment by To-om** [comment]
It is already possible with the configuration:
```
wsConfig.ssl.loose.acceptAnyCertificate: true
```

**Comment by saurabhPV** [comment]
does it work for elasticsearch too ? I want to use HTTPS but without certificate validation

**Comment by yawergam** [comment]
Hello To-om.
Can you please help- where I need to put this string "wsConfig.ssl.loose.acceptAnyCertificate: true" in thehive config file?

**Comment by AbanobMedhatK** [comment]
Can u provide screenshot of where to put the configuration for disable SSL Validation check for MISP ?

**Comment by Luanpablo100** [comment]
Hi, is there any way to do this with Cortex too? I need to put it in the same environment as there is an elasticsearch with wazuh that has self-signed certificates.
