### ISSUE TITLE
[Bug] Alphabetize Case Template view

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1551]
# Alphabetize Case Template view
### Request Type
Feature Request

### Problem Description
The Case Template view (found in hxxp://`url`/index.html#!/administration/organisations/`organization`/details) should be alphabetized by title for easier lookup & access. Right now my team is Ctrl+F-ing the page to find the template they need. I believe it is currently ordered chronologically by add-date.

**Comment by arkhelieldan** [comment]
I agree, its problem for my team too. Its possible organize by title or prefix for example?

**Comment by ch0wm3in** [comment]
We would also like to see this feature, pretty please with a cherry on top.

**Comment by nadouani** [comment]
This will be fixed by #1804
