### ISSUE TITLE
ObservableCreaionCrrl: Observable already exist notification 

### ISSUE THREAD

**Issue by KDx48** [TheHive-Project/TheHive#1555]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  RedHat,
| OS version (client)       | 10
| TheHive version / git hash   | 4.0
| Browser type & version    | Chrome Version 85.0.4183.121

### Problem Description
when tryin to add observables to a case this notification comes up and preventing me to do so.

**Comment by To-om** [comment]
which notification ?

**Comment by KDx48** [comment]
it seems not a technical issue .. but the observable was typed twice. Thanks To-om
