### ISSUE TITLE
[Bug] Case Tasks get deleted if not started

### ISSUE THREAD

**Issue by vi-or-die** [TheHive-Project/TheHive#1565]
# Case tasks get deleted if the task wasn't started before closure of the case

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | 10, MAC
| TheHive version / git hash   | 4.0.0
| Package Type              | RPM
| Browser type & version    | Chrome & Firefox

### Problem Description
If a case task has comments added to it, but the start task button was never clicked, the task and the associated logs are deleted when the case is resolved. Previously in v3 when a comment was added to a task it was automatically started. 

### Steps to Reproduce
1. Create Case
1. Create a task 
1. Add comment to the task but do not click start task
1. Close the case
1. Check case for task

### Possible Solutions
None

### Temporary work arounds
* Require users to start tasks they are adding comments in. 
* Maybe use webhook/api when version 1 is released

**Comment by To-om** [comment]
Now, the task is automatically started when the first log is created, thus if the task has a log its status can't be waiting and then won't be deleted when the case will be closed.

**Comment by vi-or-die** [comment]
@To-om  Thank you!
