### ISSUE TITLE
[Feature Request] Set default import template on new alerts via hive4py

### ISSUE THREAD

**Issue by gimmic** [TheHive-Project/TheHive#1568]
### Problem Description 
Add a method or option to define the default case import template on hive4py alert creation.

### Steps to Reproduce
1. Use hive4py / API to create an alert from a known-source.
2. Know that you will always template that source to a specific case template.
1. Save one additional "click" on analyst review to promote alert to case. 

### Possible Solutions
Allow for an option to specify default/preferred case template in the alert submission.

### Complementary information
This is because many alerts from specific systems or in a multitenancy environment you will have some context in the alert to decide what type of case template should be applied if it is promoted to a full case. Right now, this is a human choice in a drop down menu to apply the template, and can remain such- but it could default select the 'correct' option.

**Comment by To-om** [comment]
TheHive accepts the parameter "caseTemplate" in alert creation. The value must match to an existing case template, otherwise, it will be ignore.
If TheHive4py doesn't permit to set the case template during alert creation (I didn't check), please create an issue on TheHive4py repository.
