### ISSUE TITLE
[Bug] API to POST custom fields (/api/list/custom_fields) does not work

### ISSUE THREAD

**Issue by susangz** [TheHive-Project/TheHive#1580]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18
| TheHive version / git hash   | 4
| Package Type              | DEB

### Problem Description
I'm trying to create custom fields in TheHive4 using the  /api/list/custom_fields. It doesn't return an error, but the custom field is not registered.

### Steps to Reproduce
1. Execute POST with the new custom field. For example:

$ curl -XPOST -H 'Authorization: Bearer nkPoX3IyOWwshnrLsWT9CI0CO0ekZZLW' -H 'Content-Type: application/json' 'http://localhost:9000/api/list/custom_fields' -d '{"value":{"name":"Additional Classification: classified as APT?","reference":"additionalClassificationClassifiedAsAPT","description":"Indicate if the Cyber Security Incident can be classified as APT (only cyber security incidents)","type":"string","options":["Yes","No"]}}'

2. Retrieve all the custom fields registered and the list is empty:

$ curl -H 'Authorization: Bearer nkPoX3IyOWwshnrLsWT9CI0CO0ekZZLW' 'http://localhost:9000/api/list/custom_fields'
{}

**Comment by nadouani** [comment]
In TheHive4, the `/list` has been removed.

There is now and API dedicated to custom fields, but for creation you need to use a super admin user or a user with the custom field related permission.

### Create CF:
```
POST /api/customField

{
    "name": "Additional Classification: classified as APT?",
    "reference": "additionalClassificationClassifiedAsAPT",
    "description": "XXXX",
    "type": "string",
    "options": ["Yes", "No"]
}
```

BTW, I would use a `boolean` custom field in your case.
