### ISSUE TITLE
[Feature Request] allow user to choose the format of the date displayed

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/TheHive#1583]
### Request Type
Feature Request

### Description

in the current version of TH, date is displayed with MM/DD/YYYY. It would be very cool for analysts/Orgs to choose the usual  forma they want to display. Some might prefer DD/MM/YYYY

**Comment by crackytsi** [comment]
Or even dd.mm.yy ;)

**Comment by jh1995** [comment]
Me too, please! 
_For a quick temporary fix one could try to edit ui/app/scripts/filters/shortDate.js_

**Comment by nadouani** [comment]
This looks like below

![Screenshot 2021-02-24 at 23 18 49](https://user-images.githubusercontent.com/21827/109073441-aa87f000-76f6-11eb-8039-96a18a8ab2d3.png)
