### ISSUE TITLE
[Bug] Alert artifact tags not imported to case

### ISSUE THREAD

**Issue by r0sier** [TheHive-Project/TheHive#1585]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04.5
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.0-1
| Package Type              | From source
| Browser type & version    | Firefox

### Problem Description
When exporting an alert into a case, the tags included within the observables are not imported into the case. For example, an alert could be generated with the observable 8[.]8[.]8[.]8 and tag 'IP'. When the alert is imported into a Hive case, the tags from the observables are removed. See images below. 

### Steps to Reproduce
1. Create an alert with an alert artifact that uses tags
2. View the alert and import into a Hive case

### Complementary information
Screenshot one shows the artifacts with tags inside of an alert: 
![image](https://user-images.githubusercontent.com/60659760/96594214-47b6c000-12e2-11eb-90ee-daa28e56208e.png)
 Screenshot two shows that once imported, the artifact tags are removed: 
![image](https://user-images.githubusercontent.com/60659760/96594326-64eb8e80-12e2-11eb-940f-a909874f2caf.png)

**Comment by nadouani** [comment]
Hello @r0sier this has been fixed in #1510. Closing as duplicate
