### ISSUE TITLE
[Bug] Dashboards - Impossible to plot more than one series in Multi Line plot - only the last series is plotted

### ISSUE THREAD

**Issue by kwouffe** [TheHive-Project/TheHive#1587]
While migrating dashboards from TH3 to TH4 we identified an issue on the Multi Line plot:
 - Only the last series is plotted

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Debian GNU/Linux 10 (buster)
| OS version (client)       |  MacOS / ArchLinux / Ubuntu
| TheHive version / git hash   | 4.0.0-1 
| Package Type              | DEB
| Browser type & version    | NA

### Problem Description
On dashboards in TheHive4, when creating a multi Line plot. Only the last serie is plotted. The other series are not displayed.

### Steps to Reproduce

 - Create a dashboard
 - add a multi-line plot to the dashboard
 - select any time interval
 - add several series (at least 2)

example:

![image](https://user-images.githubusercontent.com/11735215/96848198-6b017c80-1454-11eb-87bf-fdfdbfc6a48f.png)

**Comment by nadouani** [comment]
Hello @kwouffe thanks for raising this issue but it has already been fixed in #1503
