### ISSUE TITLE
[Bug] default MISP connector import line has a typo

### ISSUE THREAD

**Issue by iwitz** [TheHive-Project/TheHive#1595]
# MispModule import line in application.sample.conf has a typo

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RHEL 7
| OS version (client)       | N/A
| TheHive version / git hash   | 4.0 RPM release
| Package Type              | RPM
| Browser type & version    | N/A

### Problem Description
In the template configuration file, the MispModule import line import ends with "mi**ps**.MispModule" ; when used as is, TheHive won't start.
It works with "mi**sp**.MispModule"

### Steps to Reproduce
1. Install the TheHive 4.0 RPM
2. Rename application.sample.conf to application.conf to use it as a configuration template
3. Configure TheHive with the MISP connector
4. Try to start TheHive with `systemctl start thehive` ; it won't start

### Possible Solutions
Line that contains the typo / fix :
```
// play.modules.enabled += org.thp.thehive.connector.mips.MispModule
// play.modules.enabled += org.thp.thehive.connector.misp.MispModule
```

**Comment by nadouani** [comment]
Thanks @iwitz this is already fixed.
