### ISSUE TITLE
[Bug] StreamSrv 504 Gateway Time-out (http vs https) nginx

### ISSUE THREAD

**Issue by torrycrass** [TheHive-Project/TheHive#1602]
# Redirect using http vs https after adding nginx

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04 TLS
| TheHive version / git hash   | 4.x, apt install (default)
| Package Type              | DEB
| Browser type & version    | Mozilla (latest October 28th)

### Problem Description
TheHive4 was successfully installed and running. After this nginx was added as a reverse proxy to allow TLS use.

All functions seem to work.

On use of some screens an error pop-up appears in the lower left saying the following:

```
StreamSrv: <html> <head><title>504 Gateway Time-out</title></head> <body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.14.0 (Ubuntu)</center> </body> </html> 
```

The system logs indicate a likely problem with a code reference that points to `http://` vs. `https://`

nginx error log shows the following:
```
2020/10/29 02:34:29 [error] 19760#19760: *12432 upstream timed out (110: Connection timed out) while reading response header from upstream, client: X.X.X.X, server: , request: "GET /api/str
eam/HdfdDFJD1Djewdjs4 HTTP/1.1", upstream: "http://X.X.X.X:9000/api/stream/HdflkjdfsljkZkhdf", host: "X.X.X.X:8888", referrer: "https://X.X.X.X:8888/index.html"
```

### Steps to Reproduce
1. Unknown exactly, it pops up seemingly at random when clicking around in the platform.

### Possible Solutions
1. Error seems to indicate there might be a static http:// reference in the code somewhere vs. allowing for https (see nginx error log).

### Complementary information
Nothing more at this time.

**Comment by miyoyo** [comment]
This might just be a configuraion issue on nginx's side where it considers long polling as timing out.

TheHive uses long polling for the stream, which is effectively connecting to a socket, and either receiving a response by the server sending the answer whenever, or timing out and trying again.

When TheHive times out it's long polls, it returns [], but nginx will return you the 504 page.

See this link for more info:
https://stackoverflow.com/questions/17713305/long-polling-with-nginx-advice-and-clarification

**Comment by nadouani** [comment]
Please refer to this doc to configure the timeout:

https://github.com/TheHive-Project/TheHiveDocs/blob/9f6ad2402db6457b37a6406849c42f69d071053c/admin/configuration.md#101-https-using-a-reverse-proxy
