### ISSUE TITLE
[Bug] Check tag autocompletion

### ISSUE THREAD

**Issue by jeromeleonard** [TheHive-Project/TheHive#1611]
### Request Type

Bug

### Problem Description

Verify tag queries and autocomplete:

- [x] In search forms
- [x] In Case forms
- [x] Observable forms
- [x] Case template forms

**Comment by nadouani** [comment]
After a verification, the findings are the following:

- Tags in search form doesn't implement the autocomplete capabilities
- Editable tag fields (case details form, observable details form) use an `/api/v0/query` API call => Not working
- Tags input fields (case creation form, observable creation form) use an `/api/v0/query` API call => Not working

The  `/api/v0/query` has the following body:

```
{
    "query": [{
        "_name": "listTag"
    }, {
        "_name": "fromCase / fromObservable"
    }, {
        "_name": "filter",
        "_like": {
            "_field": "text",
            "_value": "*XXXXX*"
        }
    }, {
        "_name": "text"
    }]
}
```

@To-om can you please check the API calls for the `listTags` named query?
