### ISSUE TITLE
Authentification failure after the update of DB [Bug]

### ISSUE THREAD

**Issue by sqrtZeroKnowledge** [TheHive-Project/TheHive#1613]
### Request Type

Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 
| OS version (client)       | 20.14 LTS 
| TheHive version / git hash   | 4 of the commit
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
Hello Team,

I would like to inform you about an issue i'm facing at this time with the current version and is about after updating the database of ThHive and Cortex with same logins I've been tried not login and pop up  a message as Authentification failure

### Steps to Reproduce
1. Install docker-compose up the docker.yaml of in the repository
1. access to the Web UI interface of TheHive
1. Update the DB

### Possible Solutions

I've been tried to delete the db many times in ES and try to retype it again, with using commands in the docker-compose --create-admin test test, or user nothing beneficial in that's case, also i checked the communication between cortex and thehive is work is established.

### Complementary information
thehive_1        |      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
thehive_1        |      at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
thehive_1        |      at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
thehive_1        | [error] o.e.s.a.MultiAuthSrv - Authentication failure
thehive_1        | org.elastic4play.AuthenticationError: Authentication failure
thehive_1        |      at services.LocalAuthSrv.$anonfun$authenticate$1(LocalAuthSrv.scala:35)
thehive_1        |      at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
thehive_1        |      at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
thehive_1        |      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
thehive_1        |      at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
thehive_1        |      at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
thehive_1        |      at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
thehive_1        | [info] o.e.ErrorHandler - POST /api/login returned 401
thehive_1        | org.elastic4play.AuthenticationError: Authentication failure
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$2.applyOrElse(MultiAuthSrv.scala:54)
thehive_1        |      at org.elastic4play.services.auth.MultiAuthSrv$$anonfun$authenticate$2.applyOrElse(MultiAuthSrv.scala:51)
thehive_1        |      at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
thehive_1        |      at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
thehive_1        |      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
thehive_1        |      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
thehive_1        |      at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
thehive_1        |      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
thehive_1        |      at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
thehive_1        |      at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)

`version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"`

**Comment by nadouani** [comment]
Hello, please fill in the issue correctly, by following the issue template, and give it a title

**Comment by jbfeldman** [comment]
I'm also getting this behavior. Because I get an auth failure after trying to login with my freshly created admin credentials, the docker version of TheHive is completely unusable. Using the TH_CREATE_ADMIN_LOGIN TH_CREATE_ADMIN_PASSWORD env variables also failed. Looking at the logs, it looks like improper out of the box ES configuration might be the culprit, although I'm not certain

**Comment by nadouani** [comment]
Closing this issue as the docker-compose file is not longer part of this repo. For any docker-compose related issue please use this repo: https://github.com/TheHive-Project/Docker-Templates
