### ISSUE TITLE
[Bug] deleted tasks still listed

### ISSUE THREAD

**Issue by pdux** [TheHive-Project/TheHive#1624]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | W10
| TheHive version / git hash   | TH4 RC1
| Package Type              | RPM
| Browser type & version    | any

### Problem Description
When creating case template I added many tasks (t1 / t2 / t3 / t4). Then when openinig new case and using this template, I don't need t2 so I remove it. Then I proceed with the case and close all not-removed tasks and close the case. 
In the bar on top I still see "My tasks 1", when I click there I see removed task "t2" with status "Cancel" and duration "not started yet". There is no possible to open or close the task. And it will be listed there forever. 
The task was removed and should not be there. 

### Steps to Reproduce
1. create case template with tasks 1 / 2 / 3 /  4 
2. open new case using this new template
3. remove/delete task 2 
4. close all other tasks not removed (1 / 3 /4) 
5. close the case 
6. you will see at the top "My tasks 1" - click it
7. you have task 2 

### Possible Solutions
N/A

### Complementary information
N/A

**Comment by nadouani** [comment]
This is duplicate with #1612, Thanks @pdux
