### ISSUE TITLE
[Question] Specify organization when creating alert via API

### ISSUE THREAD

**Issue by smogm** [TheHive-Project/TheHive#1639]
### Request Type
Feature Request

### Problem Description
At the moment the TheHive 4.0 API is only able to create alerts in the organization the API user is assigned to.
For MSSP use cases it would be great to have a "organization independent" user role, which is able to specify the organization while creating the alert via the API.
Thus one API user can create alerts for various organizations.

**Comment by nadouani** [comment]
Hello, you need to add a `X-Organisation: <ORGANISATION-NAME>` header to your API call.

**Comment by smogm** [comment]
Hello @nadouani, does the API user need some special permissions to be able to create alerts in all organisations?
It looks like I still need one dedicated user for each organisation, else I see an authentication error.

At the moment I have an user "hive-bridge" which should poll a SIEM system and create alerts from the SIEM in thehive.
This user is member of the "main organisation" to which all other organisations are "linked".
But I would like to create or assign alerts to specific organisations so our customers can see the alerts of their organisation only.

Is this possible?
