### ISSUE TITLE
[Bug] Display issue of custom fields

### ISSUE THREAD

**Issue by meelich** [TheHive-Project/TheHive#1653]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.1
| Package Type              | DEB

### Problem Description
We are using two custom fields. The first one if the email message-ID, the second one is a drop down that the analyst can chose from. Since the message-ID is very long, it is displayed on top of the second custom field, which makes the second custom field illegible. Unless you know that there is a drop down field, you would not be able to see if from looking at the view. 
Please find screenshot in the attached file.

### Steps to Reproduce
1. Create first custom field, populate it with the message-ID
2. Create second custom field as a drop-down of string.

### Possible Solutions
- Cut off text string in display and only show whole string in edit mode.
- Allow for line wrapping before it runs over second custom field

![Capture](https://user-images.githubusercontent.com/38258905/99219391-86894a00-27aa-11eb-87bc-ce1c5a67240a.JPG)

**Comment by nadouani** [comment]
This is the first fix.

![Uploading Screenshot 2020-11-18 at 07.33.20.png…]()

**Comment by nadouani** [comment]
This fixes the filter preview display

<img width="798" alt="Screenshot 2020-11-18 at 12 09 25" src="https://user-images.githubusercontent.com/21827/99523728-bcd7ec80-2997-11eb-8194-6d851548c50f.png">

**Comment by meelich** [comment]
Perfect, thanks for the update!
