### ISSUE TITLE
[Bug] API method broken: /api/case/artifact/_search in 4.0.1

### ISSUE THREAD

**Issue by DrJohn1** [TheHive-Project/TheHive#1659]
# API method broken: /api/case/artifact/_search (Bug)

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 4.0.1
| Package Type              | DEB

### Problem Description
Any calls to the API method /api/case/artifact/_search return "failed with ''org.thp.thehive.models.Case$$anon$28$$anon$29 cannot be cast to org.thp.thehive.models.Observable'. This happens also from TheHive4py.

### Steps to Reproduce
1. Make a POST call to /api/case/artifact/_search
1. An error is returned

### Complementary information
The error shown:
![error_model_observable](https://user-images.githubusercontent.com/25451370/99365192-3cda5580-28b7-11eb-9b5a-042ced8da7b5.jpg)

**Comment by nadouani** [comment]
Same thing, I cannot reproduce, calling 

```
curl -XPOST -H "Authorization: Bearer XXXXX" "https://THEHIVE/api/case/artifact/_search"
```

is working fine

**Comment by DrJohn1** [comment]
The issue appears in 4.0.1 when requesting an attribute using "get_case_observables(...)" thehive4py method.

As with issue #1660, when adding json.dumps() to the method works again:

In 4.0.0:
```
return requests.post(req, params=params, json=data, proxies=self.proxies, auth=self.auth, verify=self.cert)
```

An to work in 4.0.1, I added json.dumps() to the data parameter:
```
return requests.post(req, params=params, json=json.dumps(data), proxies=self.proxies, auth=self.auth, verify=self.cert)
```

**Comment by nadouani** [comment]
Thanks @DrJohn1 this sounds like a helpful input.
