### ISSUE TITLE
[Bug] Unable to define ES index on migration

### ISSUE THREAD

**Issue by mamoedo** [TheHive-Project/TheHive#1661]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 4.0.1
| Package Type              | Binary

### Problem Description
On the migration tool it's not possible to set `es-index` param. Whatever you put there, is omited.

### Steps to Reproduce
1. Use the migration tool with the following param `--es-index the_hive_test_15`
2. Observe that the tool starts migrating another index

### Possible Solutions
It seems to be a typo in the migration tool https://github.com/TheHive-Project/TheHive/blob/master-th4/migration/src/main/scala/org/thp/thehive/migration/Migrate.scala

Line 59 says `intput` instead of `input`

**Comment by To-om** [comment]
Thanks @mamoedo, you're right, it's a typo.
