### ISSUE TITLE
[Bug] Dashboard max aggregation on custom-integer field does not work

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1662]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.1
| Package Type              | DEB

### Problem Description
Aggregation of max based on an integer field in multi-lines dashboard  does not work.

### Steps to Reproduce
1. Create an integer custom-field
2. set this integer custom field on a case to a value
3. define a dashboard using multi-lines
4 define a series:
![image](https://user-images.githubusercontent.com/11610825/99494855-057caf00-2972-11eb-8439-7a4a4b656416.png)
5. Result: Failed to fetch data.

**Comment by nadouani** [comment]
Thanks @crackytsi  we will try to fix it in 4.0.2.

**Comment by nadouani** [comment]
@To-om here is dashboard that allows to reproduce the issue

[Issue_#1662.json.txt](https://github.com/TheHive-Project/TheHive/files/5559254/Issue_.1662.json.txt)

**Comment by nadouani** [comment]
Here are the details of the issue:

```
POST /api/alert/_stats

{
    "query": {},
    "stats": [{
        "_agg": "time",
        "_fields": ["createdAt"],
        "_interval": "1d",
        "_select": [{
            "_agg": "max",
            "_name": "agg_1",
            "_query": {},
            "_field": "customFields.csirts"
        }]
    }]
}
```

returns

```
{
    "type": "java.lang.ClassCastException",
    "message": "java.util.LinkedHashMap cannot be cast to java.lang.Comparable"
}
```
