### ISSUE TITLE
TheHive 4.0.1 Update

### ISSUE THREAD

**Issue by Tyrell20** [TheHive-Project/TheHive#1664]
Hello,
could you please indicate me when the rpm about the latest version of TheHive will be available?

Many thanks

**Comment by nadouani** [comment]
What about https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_rpm.md#installation-1

**Comment by Tyrell20** [comment]
Hi @nadouani  we have TheHive 4.0.0 but in the repository seems not available the latest update 4.0.1

`[root@xxx opt]# yum update
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
cassandra/signature                                                                                                                   |  833 B  00:00:00
cassandra/signature                                                                                                                   | 2.9 kB  00:00:00 !!!
docker-ce-stable                                                                                                                      | 3.5 kB  00:00:00
elasticsearch-5.x                                                                                                                     | 1.3 kB  00:00:00
epel/x86_64/metalink                                                                                                                  |  25 kB  00:00:00
epel                                                                                                                                  | 4.7 kB  00:00:00
thehive-project                                                                                                                       | 2.9 kB  00:00:00
(1/8): docker-ce-stable/x86_64/updateinfo                                                                                             |   55 B  00:00:00
(2/8): docker-ce-stable/x86_64/primary_db                                                                                             |  46 kB  00:00:00
(3/8): cassandra/primary_db                                                                                                           | 4.3 kB  00:00:00
(4/8): elasticsearch-5.x/primary                                                                                                      | 165 kB  00:00:00
(5/8): epel/x86_64/group_gz                                                                                                           |  95 kB  00:00:00
(6/8): epel/x86_64/updateinfo                                                                                                         | 1.0 MB  00:00:00
(7/8): epel/x86_64/primary_db                                                                                                         | 6.9 MB  00:00:00
(8/8): thehive-project/primary_db                                                                                                     | 4.5 kB  00:00:00
elasticsearch-5.x                                                                                                                                    434/434
No packages marked for update


[root@xxx opt]# yum -v list thehive4 --show-duplicates
Installed Packages
thehive4.noarch                                                           4.0.0-1                                                            @thehive-project
Available Packages
thehive4.noarch                                                           4.0.0-1                                                            thehive-project

`
