### ISSUE TITLE
[Question] Is it possible to use custom fields in Kibana Dashboards?

### ISSUE THREAD

**Issue by SOCOST** [TheHive-Project/TheHive#1671]
TheHive version: 3.4.2
Client OS: Windows 10 v1909
Server OS: Ubuntu 20.04 LTS
Browse type and version: Chrome Versión 84.0.4147.105 (Build oficial) (64 bits)
Cortex version: 3.0.1-1

When a custom field is added to a dashboard in Kibana, the following message is shown:

_No results displayed because all values equal 0._

Is there any way to add this fields to Kibana dashboards?

Thank you.

**Comment by nadouani** [comment]
Hello, no idea about the usage of TheHive in Kibana. This seems like a Kiban question :)
