### ISSUE TITLE
Computing alert_id in feeder script.

### ISSUE THREAD

**Issue by ch0wm3in** [TheHive-Project/TheHive#1674]
Hi,

In this backend code [link](https://github.com/TheHive-Project/TheHive/blob/9f63ba6e5d27be79d3c57aee6a86157f7dabd9c3/thehive-backend/app/models/Alert.scala#L104)
You are defining the alert_id to be a md5 hash, but when i look in the thehive gui for ingested alert, i see some sort of integer eg. "~12345679" 

How would i go about computing this in my feeder script?

I'm asking because our use case right now is to update the alert if it sees the same sourceref again with some customfield about it being seen again, and currently i'm using thehiveapi.find_alert(query=Eg('sourceRef':'md5')). This takes about 1-2 seconds to execute(according to timeit) and is not optimal for ingesting a large sum of events, whereas the get_event(alertid) is only 0.2 seconds to complete, but i cannot know the alert_id on beforehand if i cant compute it the same way thehive backend does it.

Is this possible or is the alert_id some incremental database id of the alert_id md5?  

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu, 
| OS version (client)       | Ubuntu,
| TheHive version / git hash   | 4.0.1
| Package Type              | DEB

**Comment by nadouani** [comment]
You don't have to compute the ID, it's an internal id generated by TheHive. 

The `sourceRef` is another string field where you can put the reference of your items coming from the feeder.

**Comment by ch0wm3in** [comment]
I'm completely aware of sourceRefs function. That's not the question. 

I'll try to describe my problem better

My flow right now is

1.Get daily events from feeder source, feeder source is api which is locked to time range of 00:00-today - now
2. Feeder script runs every 5 minutes
3. Script generates md5 of sourceref on every alert
4. Currently we use find_alert in hive4py to search on sourceRef to see if the script is reingesting known alert and based on timestamp logic from feeder determining if information about repeat event should be updated in thehive alert.
5. Find_alert takes 1-2 seconds to execute whereas get_event takes less than 0.2 seconds.


Would it be possible to generate this internal ID in script if based on the hash of $tpe|$source|$sourceRef to avoid using expensive find_alert api function?


Thanks for an awesome project by the way, and the help.
