### ISSUE TITLE
Alert_id how is it generated?

### ISSUE THREAD

**Issue by ch0wm3in** [TheHive-Project/TheHive#1677]
https://github.com/TheHive-Project/TheHive/issues/1674 i think my question was not understood but to clarify from previous issue:

I'm completely aware of sourceRefs function. That's not the question.

I'll try to describe my problem better

My flow right now is

1.Get daily events from feeder source, feeder source is api which is locked to time range of 00:00-today - now
2. Feeder script runs every 5 minutes
3. Script generates md5 of sourceref on every alert
4. Currently we use find_alert in hive4py to search on sourceRef to see if the script is reingesting known alert and based on timestamp logic from feeder determining if information about repeat event should be updated in thehive alert.
5. Find_alert takes 1-2 seconds to execute whereas get_event takes less than 0.2 seconds.

Would it be possible to generate this internal ID in script if based on the hash of $tpe|$source|$sourceRef to avoid using expensive find_alert api function?

Thanks for an awesome project by the way, and the help.

You say specifically in https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/alert.md that an alert id is generated from an md5 of type|source|sourceRef but the id is not an md5, but since i know in my script what to fill those variables i could pre-generate it and get faster searching than find_alert(query) would provide me with and use get_alert(alertid).

**Comment by nadouani** [comment]
Hello, I get your point. You would like to speed up the check if the alert exists in the db. The answer is sadly no.

**Comment by nadouani** [comment]
Hello @ch0wm3in I have your answer!! 

TheHive 4 is able to get an alert by its `type;source;sourceRef` combination:

```
GET /api/alert/TYPE;SOURCE;SOURCEREF
```
