### ISSUE TITLE
[Bug] Can not aggregate Alerts based on title attribute

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1689]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 3.5.0
| Package Type              | DEB

### Problem Description
With TheHive 3.5 is is not possible to aggregate by Alert Title, see screenshot below:
![image](https://user-images.githubusercontent.com/11610825/100323745-7d785400-2fc6-11eb-8546-78832ee50ba6.png)

### Steps to Reproduce
1. Create a Donut Dashboard
1. Try to aggregate by Alert title

### Possible Solutions
Add "title" Attribute also for aggregation.

**Comment by nadouani** [comment]
Unfortunately, `title` is an indexed field (to allow full text search) and stored in ES in a way it cannot be aggregated.
