### ISSUE TITLE
[Question] Best practices when using API with multiple oranisations?

### ISSUE THREAD

**Issue by smogm** [TheHive-Project/TheHive#1692]
I'm using TheHive4 with multiple organisations.
Now I want to utilize the API to create Alerts from an external source and assign them to a specific organisation.

As far as I can see there is the new HTTP header `X-Organisation` also used in TheHive4py [here](https://github.com/TheHive-Project/TheHive4py/blob/1.x/thehive4py/auth.py#L29).

My understanding is that the API user has to be part of the organisation set via `X-Organisation`, else I only see 
```
{"type":"AuthorizationError","message":"Operation not permitted"}
```
error messages.
Or am I doing something wrong here?

When I don't set the organisation, the alerts will be assigned to the defaultOrg set in the application.conf.

How is it possible to use **one** API user to create alerts on different organisations?
Maybe an example could help me to understand how it has to be done.

Thank you!

**Comment by nadouani** [comment]
Hello,

if you want a single user to create alerts in different organisations, you need to add that user in all the organisations, and use `X-Organisation` header for each API call to specify the org.

Also, make sure the user has the right permissions like `manageAlert` for alert creation.
