### ISSUE TITLE
[Bug] Analyzers can't run

### ISSUE THREAD

**Issue by hoboristi** [TheHive-Project/TheHive#1693]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | -
| TheHive version / git hash   | 3.4.2-1
| Package Type              | DEB
| Browser type & version    | -

### Problem Description
play.modules.enabled += connectors.cortex.CortexConnector
is provided at application.conf, connection details too, but Hive does not run any analyzer with this error message:
"Sorry, there are currently no analyzers for the selected observable type(s)"

### Steps to Reproduce
1. cortex analyzers configured
1. thehive config:
play.modules.enabled += connectors.cortex.CortexConnector

cortex {
  "cortex-connection" {
   url = "http://127.0.0.1:9001/"
   key = "PASSWORD_FOR_CORTEX"
   }
}

1. Try to run analyzer

### Complementary information
Logging the following line repeatedly:
020-11-26 14:27:20,878 [DEBUG] from play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool in pool-7-thread-1 - Entry count for : http://127.0.0.1:9001 : 1

**Comment by nadouani** [comment]
Hello @hoboristi the information above are not enough to understand the issue. Is your cortex working? are you able to run the analyzers from Cortex?

**Comment by hoboristi** [comment]
Hi,

It was systemd-resolved issue, somehow hive didnt find cortex address, so we can close the issue I suppose.
