### ISSUE TITLE
[Bug] Analysers and Responders does not show in the hive

### ISSUE THREAD

**Issue by imad-testing** [TheHive-Project/TheHive#1696]
Hello, i'm new to the hive. I build some analysers and responders on cortex and I tested them. I want now to integrate these analysers with the hive. I created a case, then I imported this case inside an alert. then, I added an observable but the analysers did not showed up. Can anyone help me please?

 
![image](https://user-images.githubusercontent.com/71173607/100938122-d2532780-34fc-11eb-851c-468c89f1c84e.png)

Also, I enabled on cortex:

![image](https://user-images.githubusercontent.com/71173607/100938267-11817880-34fd-11eb-82ad-2b4f1e52ef03.png)

**Comment by nadouani** [comment]
Hello, are you sure your Cortex configuration in TheHive is correct? Are you using the right API key from the right organisation in Cortex?
Can you share your TheHive About dialog?

**Comment by rriclet** [comment]
Please feel free to reopen the bug if needed.
