### ISSUE TITLE
[Question]API modifying case (patch) adding a customfield remove all the others

### ISSUE THREAD

**Issue by sergiopagnozzi** [TheHive-Project/TheHive#1698]
### Request Type
Bug 

Hello,
I have an issue.
We noted on our cases a customfield was removed.
We addedd it back to our templates however it is not restored in each cases.
The elasticsearch db contains this info and I tried to add the customfield to each cases running several CURL like the one below:

```
 curl -XPATCH -d @custom_json -H 'Authorization: Bearer token' -H 'Content-Type: application/json' "http://thehiveurl:9000/api/case/AXX1F1Ffo5AT7-Hl6QKx"
```

the json file contains:
`{"customFields.Site.string": "SITO"}`

If the case contains the customfield Site it works as expected populating it.

If it is not present (as for our case) the command reports:
```
{"type":"InternalError","message":"Unknown error: ElasticError(illegal_argument_exception,failed to execute script,None,None,None,List(ElasticError(remote_transport_exception,[3txbsvD][10.17.20.26:9300][indices:data/write/update[s]],None,> ctx._source[\"updatedBy\"]=params.param0;ctx._source[\"customFields\"][\"Site\"][\"string\"]=params.param1;ctx._source[\"updatedAt\"]=params.param2, lang -> painless))))"}
```
If I try to add new custom field using the below json:
```
{
    "customFields": { 
            "Site" : {
			"string": "SITO"
        }
}
```

The custom fiel Site is added but all the others removed.

Could you pelase let me know how to append a custom field without removing all the others?

Thanks

**Comment by nadouani** [comment]
Hello, `case.customFields` is a json object in the case. If you want to append, then get that json, add you new field and save it again.
