### ISSUE TITLE
Error while Migrating Hive 3 to Hive 4[Bug]

### ISSUE THREAD

**Issue by perdigana** [TheHive-Project/TheHive#1700]
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 20.04
| OS version (client)       | Ubuntu 20.04
| TheHive version / git hash   | 4.0
| Package Type              | Followed the Installation instruction for Debian on the Doc section
| Browser type & version    | If applicable

### Problem Description
MIgration Failed:
<See attachment>[MigrationError.txt](https://github.com/TheHive-Project/TheHive/files/5651912/MigrationError.txt)

Command used was:
sudo /opt/thehive/bin/migrate -o /etc/thehive/application.conf -m <CompanyName> -u <Internal-IP> -i the_hive --min-case-age 1400d --min-alert-age 1400d --min-audit-age 1400d

### Steps to Reproduce
1. Install TheHive 4.0 on Ubuntu 20.04 based on the description for Debian within TheHive Docs.
2. ShutDown the Hive service and start Migration

**Comment by nadouani** [comment]
Answered in discord
