### ISSUE TITLE
Alert creation is very slow (20-25 seconds)

### ISSUE THREAD

**Issue by trocade** [TheHive-Project/TheHive#1703]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04 LTS
| OS version (client)       | Ubuntu 16.04 LTS (Via python API)
| TheHive version    | 4.0.2
| Package Type              | DEB
| Browser type & version    | N/A

### Problem Description
We are in the progress of migrating from thehive3 to thehive4 and are currently working on the alerting part.
When creating a alert in thehive3.5 it takes a few seconds but in thehive4 the same operation takes 20-25seconds.

### Steps to Reproduce
1. Send alert using API

### Complementary information
Singe system setup using local filesystem as provider and one cassandra instance.
Aprox. 60.000 alerts (imported from thehive3)
nginx proxy for certificates

I can not find information on how to debug the API calls so the only log entries we have are these:
#### Application
`2020-12-08 12:09:04,690 [INFO] from org.thp.scalligraph.AccessLogFilter in application-akka.actor.default-dispatcher-4915 [00000fd9|] 127.0.0.1 POST /api/alert took 23336ms and returned 201 1794 bytes`
#### NGINX
` "POST /api/alert HTTP/1.1" 201 1794 "-" "python-requests/2.22.0"`

**Comment by rriclet** [comment]
This issue has been fixed with #1731, included in release 4.1.0.
Feel free to re-open this issue if you still notice slow performance.
