### ISSUE TITLE
[Bug] The Hive 4.0.2 missing directories

### ISSUE THREAD

**Issue by victorhugo-sg** [TheHive-Project/TheHive#1714]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)    Ubuntu 20.04
| OS version (client)     N/A
| TheHive version / git hash   | 4.0.2-1
| Package Type              | Binary

### Problem Description
After running "sudo wget https://download.thehive-project.org/thehive4-latest.zip"
The following version get's downloaded 4.0.2-1
After an unzip only the following directories appear

- Readme.md
- bin
- conf lib

I am not seeing packages which from my understanding is where thehive.service exists.

### Steps to Reproduce
run wget wget https://download.thehive-project.org/thehive4-latest.zip
unzip

**Comment by victorhugo-sg** [comment]
The reason I bring this up is because you're [installation documents](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#elasticsearch-installation)

Still reference this directory: 

sudo addgroup thehive
sudo adduser --system thehive
**sudo cp /opt/thehive/package/thehive.service** /usr/lib/systemd/system
sudo chown -R thehive:thehive /opt/thehive
sudo chgrp thehive /etc/thehive/application.conf
sudo chmod 640 /etc/thehive/application.conf
sudo systemctl enable thehive
sudo service thehive start

**Comment by victorhugo-sg** [comment]
Also, if you follow this same guide referenced above step by step it appears to be out of order. 

Step 5. 

sudo addgroup thehive
sudo adduser --system thehive
sudo cp /opt/thehive/package/thehive.service /usr/lib/systemd/system
sudo chown -R thehive:thehive /opt/thehive
sudo chgrp thehive /etc/thehive/application.conf  **-this will fail, because the directory does not exist. I typically have to change this to /opt/thehive/conf/application.conf, in order to get this to work.**
sudo chmod 640 /etc/thehive/application.conf **- same here**
sudo systemctl enable thehive
sudo service thehive start

I also have to make these changes: 

ExecStart=/opt/thehive/bin/thehive \
        -Dconfig.file=/opt/thehive/conf/application.conf \
        -Dlogger.file=/opt/thehive/conf/logback.xml \
        -Dpidfile.path=/dev/null

and this should come before step 5. 

(cat << _EOF_
# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
play.http.secret.key="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
_EOF_
) | sudo tee -a /opt/thehive/conf/application.conf

**Comment by victorhugo-sg** [comment]
Another issue w/ the document. You're walking the user through installing Java 11 and Elasticsearch 7.x, but then have them run this: 

4. Install TheHive
Binary packages can be downloaded from Bintray. The latest version is called thehive-latest.zip.

Download and unzip the chosen binary package. TheHive files can be installed wherever you want on the filesystem. In this guide, we assume you have chosen to install them under /opt.

cd /opt
wget https://download.thehive-project.org/thehive-latest.zip
unzip thehive-latest.zip
ln -s thehive-x.x.x thehive

This will download thehive 3.4.x which isn't supported causing issues.

**Comment by nadouani** [comment]
Hello, just to make sure, are you trying to install TheHive 4 or TheHive 3? Because you talk about TheHive 4.0.2 and you follow the docs of TheHive 3.

Can you please double check with the correct install guide: https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_binaries.md

Thanks

**Comment by nadouani** [comment]
Please reopen if needed
