### ISSUE TITLE
[Bug] API returns "admin" organisation for org-admin users

### ISSUE THREAD

**Issue by marioncandau** [TheHive-Project/TheHive#1722]
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 4.0.0-1
| Package Type              | From source

### Problem Description
I have created an org-admin test with the REST API and its organisation is A. I can see this user into organisation A page of The Hive. 
When I request /api/users/test the organisation is "admin" instead of "A".

### Steps to Reproduce
1. Create an org-admin test belongs to A organisation.
2. request /api/users/test and check the organisation value.

**Comment by nadouani** [comment]
Is this user also part of the admin organisation?

**Comment by marioncandau** [comment]
No, it is only in A organisation.

Le mer. 23 déc. 2020 à 20:02, Nabil Adouani <notifications@github.com> a
écrit :

**Comment by rriclet** [comment]
This issue was fixed in later versions of TheHive 4.
