### ISSUE TITLE
[Bug] Multiline dashboard doesn't work in 4.0.2

### ISSUE THREAD

**Issue by lybinhlap** [TheHive-Project/TheHive#1724]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu 20.04
| TheHive version / git hash   | 4.0.2
| Package Type              | DEB
| Browser type & version    | Edge

### Problem Description
I still have encountered with issue about Multiline dashboard doesn't work in thehive 4.0.2. I saw this issue was fixed in thehive 4.0.1 with #1503 

### Steps to Reproduce
1. Go to Dashboard -> Edit a dashboard -> Add Multiline widget.
2. 
![image](https://user-images.githubusercontent.com/8321774/103145593-ca8b4980-476f-11eb-8f3d-323842659389.png)
3. Only the last series is piloted
![image](https://user-images.githubusercontent.com/8321774/103145608-01f9f600-4770-11eb-85a2-7b73a678befd.png)

**Comment by nadouani** [comment]
It looks like both of them are plotted but the data is the same. Look at the selected plot, it shows high=71 and medium=71.

Please feel free to reopen if you have more input.

**Comment by lybinhlap** [comment]
In fact, the number of high alerts and medium alerts are not equal. I ran searches in Alerts tab:

![image](https://user-images.githubusercontent.com/8321774/103253800-36aabf00-49b5-11eb-84eb-2a41b8f8648e.png)
![image](https://user-images.githubusercontent.com/8321774/103253815-42968100-49b5-11eb-9c8b-091f60b61c77.png)

So I think I am encountering the same problem like #1503
