### ISSUE TITLE
Unknown version misp 

### ISSUE THREAD

**Issue by IrArTr** [TheHive-Project/TheHive#1728]
Hello, I am trying to figure out how to integrate MISP into thehive. I've configured everything according to documentation, I can see MISP integration enabled in thehive gui right bottom, but when i check About section of thehive. I get version unknown error. I have misp running in docker and try to put the ip of the container, localhost, ip that comes out to the web, but nothing works, it's a problem of the ssl?? and how can I fix it ?

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu
| OS version (client)       |  Ubuntu, ...
| TheHive version / git hash   | 4.02
| Package Type              |  Docker

When I used MISP without ssl it worked fine, but that misp image is not working well  

this is my application.conf

play.modules.enabled += org.thp.thehive.connector.misp.MispModule
misp {
 interval: 1 hour
 servers: [
   {
     name = "local"                  
     url = "https://ip"   
     auth {
       type = "key"
       key = "apikey"                 
     }
     ws {}                        # HTTP client configuration (SSL and proxy)
   }
 ]
}

**Comment by nadouani** [comment]
Hello, how would you like us to investigate the issue here, without errors, logs etc... What does the "About" dialog in TheHive tell you about the MISP connector?
