### ISSUE TITLE
[Bug] TheHive4 sharing add share not working

### ISSUE THREAD

**Issue by Canon88** [TheHive-Project/TheHive#1729]
TheHive: Version: 4.0.3-1

When I create a case using a user in the SOC, I cannot share it with the DevOps organization. The share button is grayed out. Why is this? Please let me know if this is a problem with my operation. Thank you.

![image](https://user-images.githubusercontent.com/19372121/103421144-db0b4c00-4bd5-11eb-9870-e758867340df.png)

**Comment by Canon88** [comment]
anyone help me?

**Comment by nadouani** [comment]
Is the organisation linked with any other org? Does your user have the `manageShares` permission?

**Comment by Canon88** [comment]
> Is the organisation linked with any other org? Does your user have the `manageShares` permission?
Yes, I'm sure the administrator has that right.

![image](https://user-images.githubusercontent.com/19372121/103622085-27a5ad00-4f71-11eb-801a-c1c2dca2a1fe.png)

**Comment by nadouani** [comment]
And what about the first question? `Is the organisation linked with any other org?`

**Comment by Canon88** [comment]
> And what about the first question? `Is the organisation linked with any other org?`

I am a newbie, how do I set up a link between 2 organizations? Can you tell me? Thanks!

**Comment by Canon88** [comment]
I have a question. I am using TheHive (v4.0.0-1) image of a VMware VM. It's sharing feature is working. Why is this happening?

![image](https://user-images.githubusercontent.com/19372121/103654019-4ec7a300-4fa0-11eb-9afc-dcae20d70d07.png)
