### ISSUE TITLE
Closing case error

### ISSUE THREAD

**Issue by y0d4a** [TheHive-Project/TheHive#1730]
hello,
i try to close the case, but getting error:
`
caseDetails: Unknown error: ElasticError(cluster_block_exception,blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];,None,None,None,List(ElasticError(cluster_block_exception,blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];,None,None,None,null,None)),None)
`

is it elastic issue?

tnx

**Comment by nadouani** [comment]
Hello, please provide more details about your stack, version etc...

**Comment by y0d4a** [comment]
sorry, it is docker images..

thehiveproject/thehive:latest   
thehiveproject/cortex:latest    
elasticsearch:6.8.8

on CentOS Linux release 7.8.2003 (Core)

**Comment by nadouani** [comment]
thehive:latest and cortex:latest use Elasticsearch 7 and doesn't work with ES < 7.

Please try with ES7 and reopen the issue with more details if needed.
