### ISSUE TITLE
[Bug] StreamSrv - 504 Gateway Timeout

### ISSUE THREAD

**Issue by shortstack** [TheHive-Project/TheHive#1748]
# [Bug] StreamSrv - 504 Gateway Timeout

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Mac
| TheHive version / git hash   | 4.0.2-1
| Package Type              | deb
| Browser type & version    | Chrome

### Problem Description
Getting 504 gateway timeout / StreamSrv popup periodically.

Happens when TheHive is behind nginx reverse proxy *or* an AWS ALB.

stream.longpolling.refresh is 15s in application.conf.

Proxy timeouts on nginx and/or the ALB health check are set to above that, still getting the error.

### Steps to Reproduce
1. Browse to TheHive
2. Wait 
3. Red StreamSrv 504 gateway timeout popup appears

**Comment by shortstack** [comment]
Reproduced on v4.0.4-1 also

**Comment by nadouani** [comment]
Hey @shortstack this sounds like you need to replace that using `stream.longPolling.refresh` with upper cased `P`. We will fix the docs and the sample conf file

**Comment by shortstack** [comment]
no! more! popups! thank you thank you thank you :)
