### ISSUE TITLE
[Issue] MISP Connector [Unknown version (ERROR)]

### ISSUE THREAD

**Issue by khalidrehan** [TheHive-Project/TheHive#1751]
### Issue
I have configured the MISP connector, and it is giving [Unknown version (ERROR)]
![image](https://user-images.githubusercontent.com/37035465/104849072-e8744600-58f8-11eb-9c4f-4eac243f5c9f.png)

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 4.0.0
| Package Type              | From source: https://download.thehive-project.org/thehive-training-4.0.ova

### Problem Description
TheHive application.conf has been edited as following:
```
# More information at https://github.com/TheHive-Project/TheHiveDocs/TheHive4/Administration/Connectors.md
# Enable MISP connector
play.modules.enabled += org.thp.thehive.connector.misp.MispModule
 misp {
   interval: 1h
   servers: [
    {
      name = "MISP-5"            # MISP name
      url = "https://misp5.mdomain.local" # URL or MISP
      auth {
        type = key
        key = "LFKL3J3ITHXPGtKzoeMW3P8GCcZ0GnXt8iBq7TiP"             # MISP API key
        max-attributes = 1000
        tags = ["misp"]
        max-size = 1 MiB
        max-age = 7 days
      }
# Truststore to use to validate the X.509 certificate  of  the  MISP
# # instance if the default truststore is not sufficient.
#     ws.ssl.trustManager.stores = [
#      {
#        type: "JKS"
#        path: "/path/to/truststore.jks"
#      }
#     ]
#      ws {                        # HTTP client configuration (SSL and proxy)
       # proxy {}
       # ssl {}
#      }
    }
  ]
}
```
And the attached information [URL](https://github.com/TheHive-Project/TheHiveDocs/TheHive4/Administration/Connectors.md) is not correct or outdated, even I noticed that the play module had wrong spellings.

### Possible Solutions
I have followed this [tutorial ](https://blog.agood.cloud/posts/2019/09/29/integrate-misp-to-thehive/)as a possible solution, but I don't have a root CA, and I don't have a chain.pam file.

Even though, I don't get a certificate error:
```
thehive@ubuntu:~$ curl --insecure -v https://misp5.mdomain.local 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'
* Server certificate:
*  subject: C=LU; ST=State; L=Location; O=Organization; OU=Organizational Unit; CN=misp.local; emailAddress=info@misp.local
*  start date: Dec 22 20:05:52 2020 GMT
*  expire date: Dec 22 20:05:52 2021 GMT
*  issuer: C=LU; ST=State; L=Location; O=Organization; OU=Organizational Unit; CN=misp.local; emailAddress=info@misp.local
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
* Connection #0 to host misp5.mvs.local left intact
thehive@ubuntu:~$
```
I hope to get an updated URL to the connectors configuration.

Regards,
Khalid.

**Comment by khalidrehan** [comment]
### Issue
I have deployed TheHive ver. 3.4, and the I got the same issue.

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 3.4
| Package Type              | From source: Training VM


### Problem Description
TheHive application.conf has been edited as following:
```
play.modules.enabled += connectors.misp.MispConnector
misp {
  # Interval between consecutive MISP event  imports  in  hours  (h)  or
  # minutes (m).
  interval = 1h

  "MISP-SERVER-ID" {
  #  # MISP connection configuration requires at least an url and a key. The key must
  #  # be linked with a sync account on MISP.
    url = "https://192.168.8.128/"
    key = "aSOvByKEy1rVIOYQIYBOs8D2BNXxoZFDUMD6whBn"
  #  ## MISP event filters
  #  # MISP filters is used to exclude events from the import.
  #  # Filter criteria are:
  #  # The number of attribute
    max-attributes = 1000
  #  # The size of its JSON representation
    max-size = 1 MiB
  #  # The age of the last publish date
    max-age = 7 days

  } ## <-- Uncomment to complete the configuration
}
```

Where to look?

Regards,
Khalid.

**Comment by khalidrehan** [comment]
Do I need the MISP with a trusted certificate to make it work?

**Comment by khalidrehan** [comment]
@nadouani 
Kindly, advise!
Regards,
Khalid.

**Comment by alanjones** [comment]
> @nadouani
> Kindly, advise!
> Regards,
> Khalid.

It's been my experience that thehive needs to trust the certificate presented by MISP for the integration to work.

**Comment by khalidrehan** [comment]
> > @nadouani
> > Kindly, advise!
> > Regards,
> > Khalid.
> 
> It's been my experience that thehive needs to trust the certificate presented by MISP for the integration to work.

By MISP? are you sure?
It is not mentioned by TheHive instructions!

I have tried to create a local CA:
![image](https://user-images.githubusercontent.com/37035465/104969607-037aaf00-59fa-11eb-871c-0ffe4794086b.png)

And add to TheHive server's root trust, and still nothing.

**Comment by khalidrehan** [comment]
```
thehive@thehive-training:~$ curl --insecure -v https://192.168.8.128 2>&1 | awk 'BEGIN { cert=0 } /^\* Server certificate:/ { cert=1 } /^\*/ { if (cert) print }'
* Server certificate:
*  subject: L=..; O=...; OU=.....; CN=...; emailAddress=...
*  start date: Jan 18 22:05:29 2021 GMT
*  expire date: Jan  3 22:05:29 2024 GMT
*  issuer: CN=krehan
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection #0 to host 192.168.8.128 left intact
```

**Comment by khalidrehan** [comment]
> SSL certificate verify ok.

**SSL certificate verify ok.**

**Comment by khalidrehan** [comment]
OK, I solved it.

1. I created a [CA (Certificate Authority) locally](https://www.digitalocean.com/community/tutorials/how-to-set-up-and-configure-a-certificate-authority-ca-on-ubuntu-20-04) using Ubuntu Server.
2. I added its chain to both servers (MISP and TheHive).
3. I create a request from the MISP server to issue a signed certificate from the Root CA, and I made sure that URL is mentioned inside the certificate, [I used OpenSSL CSR Creation](https://www.digicert.com/easy-csr/openssl.htm) to get the command, and I had to mention the url details in the Common-Name.
4. The I issued the certificate from then CA, and send it back to MISP.
5. Then I updated /etc/ssl/private/ misp.local.key and misp.local.crt files.
6. The root CA pem file copied to /etc/ssl/private/misp-chain.crt
7. Uncomment out the  #SSLCertificateChainFile line in /etc/apache2/sites-available/misp-ssl.conf ([Reference](https://blog.agood.cloud/posts/2019/09/29/integrate-misp-to-thehive/))..
8. Restart the Apache server.
9. Make sure to use the URL in TheHive connector settings, not the IP.
![image](https://user-images.githubusercontent.com/37035465/104973679-7db13080-5a06-11eb-9bcb-b4ca7707b9b5.png)
