### ISSUE TITLE
"Close tasks and case" deletes tasks instead of closing them

### ISSUE THREAD

**Issue by aim4r** [TheHive-Project/TheHive#1755]
# Clicking on "Close tasks and case" deletes tasks instead of closing them

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 4.0.4
| Package Type              | DEB

### Steps to Reproduce
1. Create a case with one or more tasks. Do not open or delete the tasks.
2. Close the case, and choose "Close tasks and case" 
![Close tasks and case](https://user-images.githubusercontent.com/764189/105231610-705f8780-5b67-11eb-96e0-65242c1532f5.png)
3. Notice how the tasks are deleted (instead of closed)
![Tasks are gone](https://user-images.githubusercontent.com/764189/105231635-79505900-5b67-11eb-9809-296d89afcc58.png)

**Comment by cshanahan** [comment]
My team and I stumbled upon this bug yesterday. We are running 4.0.2.

To add to the conversation, tasks that are open when the case is closed are being deleted, whether they have notes associated with them or not. So, we have lost tasks and the notes that were associated with those tasks when the case was closed.

The work-around is obvious, make sure all tasks have been opened and closed before you close the case.

**Comment by nadouani** [comment]
TheHive deletes tasks that have not been started at all, when closing a case. There is no valid reason to keep those tasks.

If you work on them, then their status should be set to `started`(automatically I guess).

**Comment by nadouani** [comment]
I confirm that TheHive remove tasks in "Waiting" status (not started), which is legit.

**Comment by aim4r** [comment]
Not sure what everyone thinks, but when I click on "**Close** tasks and case", I expect TheHive to **close** the tasks, not **delete** them :)

As noted by @cshanahan above, even the **open** tasks are being deleted when "**Close** tasks and case" is clicked.

**Comment by nadouani** [comment]
> As noted by @cshanahan above, even the open tasks are being deleted when "Close tasks and case" is clicked.

This is not true.

**Comment by aim4r** [comment]
> > As noted by @cshanahan above, even the open tasks are being deleted when "Close tasks and case" is clicked.
> 
> This is not true.

I just gave it a try, and confirm that only the unstarted tasks are being deleted.

May be it would be a good idea to modify the warning message `This case contains the following open or unassigned tasks` by adding a note like `All unopened tasks will be deleted when the case is closed`.

**Comment by nadouani** [comment]
I'll change the warning to:

`This case contains the following open or unassigned tasks. Closing the case will permanently remove the unassigned ones. This action cannot be undone`

**Comment by nadouani** [comment]
![Screenshot 2021-02-04 at 19 17 26](https://user-images.githubusercontent.com/21827/106937104-a7b06580-671d-11eb-88f6-f603fe550714.png)
