### ISSUE TITLE
Identical URL Observables can still be added multiple times to the same case

### ISSUE THREAD

**Issue by Passimist** [TheHive-Project/TheHive#1756]
Reopen of issue at the bottom of this post:

@To-om @nadouani Hi guys, I hope you had a nice start into the new year! Can you please reopen this issue?
I just upgraded to TheHive 4.0.3 and I can still upload identical url observables via TheHive4py (not the latest thehive4py version but the one before **EDIT tried it with the newest thehive4py version and issue occurrs there aswell**).
![image](https://user-images.githubusercontent.com/53262314/103538122-edb3a880-4e95-11eb-8638-9ae66781bf03.png)
![image](https://user-images.githubusercontent.com/53262314/103538143-f73d1080-4e95-11eb-9c8c-af0f31f10c6d.png)
If I can provide any additional information to help fix this please let me know.
Some information that may help:
Submitted via thehive4py
Submitted almost at the same time
Observables have different observable IDs
This does not always work (but quite often as far as I can tell)
EDIT: As a workaround I now use a filelock to prevent simulaneous creation of identical URL observables. So far this helped preventing the bug. If this is a fix then it might be some kind of race condition? I ll update if the problem occurrs with this workaround in the next few days.

_Originally posted by @Passimist in https://github.com/TheHive-Project/TheHive/issues/1718#issuecomment-753965335_

**Comment by nadouani** [comment]
Hello @Passimist we will take a look at this an give you an answer / a fix

**Comment by Passimist** [comment]
Great, let me know if you need any information! Since I prevented simultaneous URL observable creation in my code that uses thehive4py (with a file lock and 5sec sleep after claiming the lock) the issue did not occurr again.

**Comment by To-om** [comment]
This issue is already fixed in 4.1.0
