### ISSUE TITLE
[Feature Request] Ops Genie Integration or something similar

### ISSUE THREAD

**Issue by victorhugo-sg** [TheHive-Project/TheHive#1757]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| TheHive version / git hash   | 3.4.1
| Package Type              | Binary
| Browser type & version    | Chrome

### Problem Description

Has anyone integrated op's genie into TheHive and have some documentation I can reference. Ideally, what I would like to create is an "pager" alert and an "escalation" workflow builtin or integrated into TheHive. 

### Example
Alert Comes onto the Hive Sev. M
TheHive kicks off a workflow and sends a "pager alert" via Ops genie to an on call analyst. 
The analyst begins investigation and either gets stuck or feels they need to escalate. They change the severity to high and either automatically or via a custom button can kick off a "pager alert" that would kick off a Sev. H escalation process va Ops genie. 

### Complementary information
Other Tools which can be used: PagerDuty, VictorOps, etc.

**Comment by mnmnc** [comment]
How is this a bug?

Use the webhook functionality of TheHive to incercept events of incomming alerts. You can capture those events in shuffle, n8n etc. There are couple of example templates in DockerTemplates repository in this organization.
In n8n, Apache Nifi or shuffle you can react to this event by sending a request to opsgenie.

**Comment by nadouani** [comment]
@victorhugo-sg is this a 3.4 or 4.x related feature request?

**Comment by nadouani** [comment]
Anyways, this type of feature is not aimed to be included in TheHive itself, but as an integration with an external tool like stated by @mnmnc
