### ISSUE TITLE
[Feature Request] Add MITRE ATT&CK support

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#1766]
### Request Type
Feature Request

### Problem Description
The goal of this feature is to add MITRE ATT&CK support in TheHive. The main objective is to allow users to enrich their incidents by assigning discovered attack patterns.

### Features

**BE**

- [x] Add API to import attack-pattern [catalog](https://github.com/mitre/cti/blob/master/enterprise-attack/enterprise-attack.json?raw=true) 
   - [x] include `revoke=true`
   - [x] import x_mitre_detection
   - [x] import x_mitre_platforms
   - [x] import x_mitre_data_sources
   - [x] import x_mitre_system_requirements
   - [x] import x_mitre_permissions_required
   - [x] import x_mitre_defense_bypassed
   - [x] import x_mitre_remote_support
   - [x] Add capecId & capecUrl properties to Pattern model
- [x] Add API to fetch an attack pattern details
   - [x] add a `getPattern` query 
      - [x] including a `children` extra data (for techniques to load sub techniques)
      - [x] including a `parent` extra data (for sub-techniques to load parent technique)
- [x] Add API to list/filter attack-patterns
   - [x] add a `parent` property to allow filtering by parent technique
- [x] Add API to create a procedure within a case
- [x] Add API to list case procedures
   - [x] `procedures` query to be used on case objects and return lists of case procedures
   - [x] update `/api/v1/pattern/case/{case_id}` to return the list of patterns instead of list of pattern ids
- [x] Add API to update a case procedure (description & occurence)
- [x] Add API to delete a case procedure
- [x] Filter imported patterns (keep only attack-pattern)
- [x] Importing a new pattern file should also update existing patterns
- [x] Rename `procedure.occurence` to `procedure.occurDate`
- [x] Add `patternId` property to `procedure` in `/api/v1/describe` to allow filtering procedures by pattern
- [x] Add a `tactic` field to `procedure` model + its corresponding property for filtering
- [x] Make `procedure.description` optional
- [x] Add a `patternParent` extraData to the `listProcedure` query

**FE**

- [x] Add administration UI
   - [x] List + filters patterns
   - [x] Pattern details dialog
- [x] Add case procedures section
   - [x] Add a procedure to a case
   - [x] List + filter case procedures
   - [x] Allow update `procedure.occurDate`
   - [x] Display procedure dates
- [x] Add procedure display directive in the flow section

**QA**

- [x] check handling of revoked patterns

**Comment by rriclet** [comment]
https://github.com/TheHive-Project/TheHive/commit/2bb261877fae68bbeb223848c4748eef64e00822
