### ISSUE TITLE
[Bug] Deleting a shared case on org2 doesn't delete task from the Org1 resulting in log spam and undeletable task

### ISSUE THREAD

**Issue by azgaviperr** [TheHive-Project/TheHive#1767]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  CentOS
| OS version (client)       | 10
| TheHive version / git hash   | 4.0.4-1
| Package Type              | Docker
| Browser type & version    | Chrome

**Describe the bug**

Task persist on other organisation if a case is removed from an other org after case sharing.
Those task can be taken with an error message but can"t be deleted or interracted with

**To Reproduce**
1. Create a task from template with task list. 
2. Share it directly to an organization 1. 
3. Switch to the organization 2 (same user or not) and delete the case.
4. See that task and case are deleted on organisation 2. But only case deleted on Organization 1, as task persi

**Expected behavior**

Deleted cas while shared should also delete all other link to the case on other org. TASK/OBSERVABLE etc

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

**Possible solutions**
None yet

**Additional context**

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

When clicking on take on a task
![image](https://user-images.githubusercontent.com/7451354/106497296-25763600-64be-11eb-9117-b59fef012afa.png)

lot of  error in logs : certex doesn't comply 

[error] o.t.s.t.TraversalOps [|067a86ef] vertex 460968176 doesn't comply with its schema, field data is missing:
v[460968176]
[error] o.t.s.t.TraversalOps [|067a86ef] vertex 460968176 doesn't comply with its schema, field _createdAt is missing:
v[460968176]
[error] o.t.s.t.TraversalOps [|067a86ef] vertex 460968176 doesn't comply with its schema, field _createdBy is missing:

**Comment by To-om** [comment]
This has been bixed by #1606
