### ISSUE TITLE
[Bug] Audit log search crashes the application

### ISSUE THREAD

**Issue by KaanSK** [TheHive-Project/TheHive#1776]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Latest Ubuntu Docker image
| OS version (client)       | Latest 
| TheHive version / git hash   | 4.0.4
| Package Type              | DEB
| Browser type & version    | All

### Problem Description
Making a search on audit logs completely halts the system after a short period of time. The application is not available until a restart.

Additionally, audit log search is not working to begin with. No response can be retrieved for the queries.

### Steps to Reproduce
1. Go to Search/audit logs
1. Make any query using the filters (its also not working)
1. Make a filter with: "startDate" and enter [ today - (today - 7days)]
2. Error logs can be seen on TheHive instance and after a brief time delay, system completely halts.

### Possible Solutions
Audit search api endpoint should be investigated. It's already not working at all.

**Comment by rriclet** [comment]
https://github.com/TheHive-Project/TheHive/issues/1851
