### ISSUE TITLE
[Feature Request] Show case status in the default view (open / closed as FP / closed as TP, etc.) 

### ISSUE THREAD

**Issue by aim4r** [TheHive-Project/TheHive#1781]
# Show case status in the default view

### Request Type
Feature Request

### Request Description
When browsing the list of cases (default TheHive page), it would be useful to have a default column that indicates the case closure status : 
- Open
- Closed (FP)
- Closed (TP)
- Closed (Other)
- Closed (Indeterminate)

### Why ?
Security managers often have to periodically review cases (open and closed), and drill in a few of them to check if they were handled correctly and adequatly. Factors that would influence a manager's decision to drill in a particular case (or skip it) include a mix of :
- Case Title
- Case Severity  
- Case Assignee 
- Case Closure Status (Open, FP, TP, Indeterminate, etc.)

For example, a case with a severity of High and which has been closed as Indeterminate may require special attention. A case with a severity of Low and that was handled by a newbe, may require attention, etc.

All of the information above is exposed in the default view, except the Case Closure Status, which would be great to have readily available in the default view.

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 4.0.4

**Comment by nadouani** [comment]
Hello @aim4r the case list already show the close status for closed cases:

![Screenshot 2021-03-01 at 15 51 54](https://user-images.githubusercontent.com/21827/109514282-23e06380-7aa6-11eb-8e83-6dd48a6e354c.png)

We can make it clickable for filtering, and display a status column
