### ISSUE TITLE
[Bug] Observable comparison breaks when pasting "manually" defanged uri/url/path 

### ISSUE THREAD

**Issue by ch0wm3in** [TheHive-Project/TheHive#1783]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       |  20.04
| TheHive version / git hash   | 4.0.4-1
| Package Type              | DEB
| Browser type & version    | Chrome 88.0.4324.146

### Problem Description
When adding a "manually" defanged uri/url/path/domain to observable for a case it wont match for a similar observable in another case where this observable was added "fanged" and defanged by thehive.

### Steps to Reproduce
1. Make new case named "defanged beforehand"
2. add observable "test[.]lol" to "defanged beforehand" 
3. Make new case named "defanged afterwards"
4. add observable "test.lol" to "defanged afterwards"
5. Expected similarity match between cases, visually identical but apparently not in backend.

**Comment by nadouani** [comment]
`test[.]lol` and `test.lol` are different observables. TheHive doesn't do anything when you create an observable as `test[.]lol` except storing it as is.

TheHive doesn't change the data during the storage. Defanging is just a display feature.

**Comment by ch0wm3in** [comment]
Thanks for the answer @nadouani

This sounds like the correct handling of the data, but usability wise its not.
When you in example manualy extract observables from an analyser you get defanged uris or domains(where its just html report, but no possibilty to import the wanted observable to case). 

So this current handling of observables, would require the user to be aware of defanging being just a "display feature" and sit with an extra browser window and fang his/hers observables before putting them into thehive. 

My 2 cents, is that if you expect fanged/live observables, you should also enforce it that way. Either by automatically fanging an observable or at least some kind of warning for the user.
