### ISSUE TITLE
[Feature Request] Allow user to reorder case templates, or display them in alphabetic order

### ISSUE THREAD

**Issue by aim4r** [TheHive-Project/TheHive#1787]
# Allow user to reorder case templates, or display them in alphabetic order

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 4.0.5

### Problem Description
When an organisation has many case templates, it is not ideal to see them scrambled with no logical order.

For example, we have quite a few templates and they currently appear in the following (confusing) order :
- Authentication events: Password spraying
- Antivirus events: Ransomware
- Network events: Scans
- Authentication events: Bruteforce 
- Antivirus events: Adware
- Network events: SMB prpagation
- etc.

Ideally, they would appear like this :
- Authentication events: Bruteforce 
- Authentication events: Password spraying
- Antivirus events: Adware
- Antivirus events: Ransomware
- Network events: Scans
- Network events: SMB prpagation
- etc.

Therefore it woul be great to either :
- allow users to controll the order in which case templates are displayed, or 
- diplay the case templates in alphabetic order

**Comment by D4rkw0lv3s** [comment]
I agree this would help a lot when managing case templates!

**Comment by nadouani** [comment]
This will be fixed by #1804
