### ISSUE TITLE
[Feature Request] Better status information/debug info with Cortex and MISP integration icons

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/TheHive#1794]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubunty 18.04
| TheHive version / git hash   |  4.0.5
| Package Type              | DEB
| Browser type & version    | All

### Problem Description
I can see that Cortex and MISP integrations are enabled but they do not appear to be active (persistent red). There are no error messages indicating that connections are attempted nor is there the ability, AFAIK, to test the connections.

### Steps to Reproduce
1. Configure the connectors for MISP and Cortex
1. Login to TheHive
1. The integration icons stay red. It would be nice to be able to actually be able to test the connections by clicking on the icons.

**Comment by nadouani** [comment]
What does the about dialog say? What does `/api/status` return?

**Comment by smclinden** [comment]
Cortex:

{"versions":{"Cortex":"3.1.0-1","Elastic4Play":"1.12.3","Play":"2.8.3","Elastic4s":"7.9.1","ElasticSearch client":"7.9.1"},"config":{"protectDownloadsWith":"malware","authType":["key","local","ldap"],"capabilities":["authByKey","changePassword","setPassword"],"ssoAutoLogin":false}}

**Comment by nadouani** [comment]
This seems like the result coming from cortex application not from thehive.

Can you share what does thehive say on `/api/status`

**Comment by smclinden** [comment]
For some reason, it is not picking up the URL of the Cortex server from applicaton.conf:

{"versions":{"Scalligraph":"0.1.0-SNAPSHOT","TheHive":"4.0.5-1","Play":"2.8.5"},"connectors":{"cortex":{"enabled":true,"status":"ERROR","servers":[{"name":"local","version":"","status":"ERROR"}]},"misp":{"enabled":true,"servers":[{"name":"MISP","version":"","status":"ERROR","url":"https://misp.tools.dcsg.com","purpose":"ImportAndExport"}],"status":"ERROR"}},"config":{"protectDownloadsWith":"malware","authType":["session","basic","local","key","ldap"],"capabilities":["changePassword","setPassword","authByKey","mfa"],"ssoAutoLogin":false,"pollingDuration":1000},"schemaStatus":[{"name":"thehive-cortex","currentVersion":1,"expectedVersion":1,"error":null},{"name":"thehive","currentVersion":14,"expectedVersion":14,"error":null}]}

**Comment by nadouani** [comment]
So please check the URL or the SSL configuration is you Cortex is served over https. This seems to be a configuration issue. Thanks.

As you can see the about dialog displays `ERROR` if TheHive is not able to connect to Cortex, or `AUTH` if it is an authentication error. TheHive log file shows the reason on startup.

Please reopen this issue if you have another input.
