### ISSUE TITLE
[Feature Request] Alert id is now generated by the backend instead of being a hash of type, source and sourceRef

### ISSUE THREAD

**Issue by masual** [TheHive-Project/TheHive#1801]
### Request Type
Feature Request

### Problem Description
In The Hive 3 the **id** of the **alert** was the result of an MD5 hash of  **type**, **source** and **sourceRef** fields . Our organization rely on this behaviour for managing alerts. We have to manage a lot of alert sources and we implemented automations to create and update alerts in The Hive using the API. Our automations generate a hash with the relevant fields of the original alert, use it as the **sourceRef**, and then generate the **id** by calculating the MD5 hash of **type**, **source** and **sourceRef**. With that we are able to know the **id** of the alert in advance without any API calls.  That allowed us to create new alerts and update existing ones fast and withouth burdening The Hive. 

We migrated our preproduction environment from TH3 to TH4, and now our integrations are broken. With the new API the id is automatically generated by the backend, and we are not able to change it. We are working on a fix, but the only thing that seems feasible is to perform a **_api/alert/_search_** and use the **sourceRef** value as the query:

> {
> 	 "query": {
> 	 	"sourceRef": "c5c733c23fb0caae534612642543453aed77529b31bb05363fcb57867cfbcd7a"
> 	 }
> }

but this method is very slow and we are afraid that we can overload TheHive/Cassandra when a lot of new alerts arrive to our system.

Any thoughts on how to solve this issue?

**Comment by nadouani** [comment]
Hello, this makes sense, we will see how to handle this.

**Comment by nadouani** [comment]
Well, this already exists:

```
curl -XGET http://localhost:9000/api/alert/ALERT_TYPE;ALERT_SOURCE;ALERT_SOURCE_REF
```

**Comment by nadouani** [comment]
@masual please check it and let me know

**Comment by masual** [comment]
@nadouani 

This method could work, thank you! I have just performed a few fast tests and it seems every time it returns the result quite fast. Compared to the `/search` endpoint, ¿what is the difference? I assume there is some kind of indexing by `ALERT_TYPE;ALERT_SOURCE;ALERT_SOURCE_REF` going on in **Cassandra/JanusGraph**, is that correct?

Another question, is this method in te **documentation**? I coud not find any information regarding the TheHive 4.0 API modifications.

**Comment by nadouani** [comment]
The v1 APIs are optimized for the new backend. V0 (`_search`) are backward compatible but not optimized.

API docs is a topic that requires some time to be produced, and for now we focus our time on new features / bug fixes

**Comment by nadouani** [comment]
I'll close this issue then.
