### ISSUE TITLE
[Bug] Unable to use Cortex analyzers 

### ISSUE THREAD

**Issue by giovanniguadagnini** [TheHive-Project/TheHive#1810]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu.
| OS version (client)       | Ubuntu 20.04
| TheHive version   | 4.0.0-1
| Browser type & version    | Firefox

### Problem Description
Hi I've installed today you virtual machine in order to test the environment from this link (https://github.com/TheHive-Project/TheHiveDocs/blob/master/training-material.md), I've a problem when I try to execute an analyze a simple ip address the analyzers tab in the observable is empty. Cortex is configured and it's seems to be working fine. How can I solve the problem?
![image](https://user-images.githubusercontent.com/43404799/109688403-84de6900-7b84-11eb-84e7-0891fbf0899c.png)
![image](https://user-images.githubusercontent.com/43404799/109688449-8f006780-7b84-11eb-93c3-4e842d42eb51.png)

If I try to click on run all the page prompt me an alert in which I should choose the server but the list is empty....
![image](https://user-images.githubusercontent.com/43404799/109688481-99bafc80-7b84-11eb-8689-f28620fa1899.png)

### Steps to Reproduce
1. Log into the hive
2. Create a new event 
3. Insert an observable and try to execute analyzer
![image](https://user-images.githubusercontent.com/43404799/109688355-798b3d80-7b84-11eb-8121-1bb7ec25eb5c.png)

**Comment by giovanniguadagnini** [comment]
And I also have installed the last version of analyzers and responders by cloning the repo and running the pip3 installation command for the requirements.txt, I've also reuploaded the the template for the analyzer in the hive using the admin account

**Comment by nadouani** [comment]
Hello, please upgrade to TheHive 4.0.5 and let us know if the issue is still there. Thanks

**Comment by nadouani** [comment]
We know that the training material has not been updated, We will refresh it soon.

**Comment by giovanniguadagnini** [comment]
Ok thanks for the answer, but just to be sure to not break the vm how I have to update the project? 

I tried to do it by running sudo apt upgrade thehive4 but it tells me that it's already the lastest version..

![image](https://user-images.githubusercontent.com/43404799/109781037-db40bb80-7c07-11eb-8c0c-896a4ffc31d4.png)

**Comment by giovanniguadagnini** [comment]
Ah just to let you know there is a typo in the connector of misp, as it's possible to see in the image the connector is not correct...
![image](https://user-images.githubusercontent.com/43404799/109781884-95382780-7c08-11eb-8e1e-f2c6bb2c0d73.png)

**Comment by nadouani** [comment]
The package repo has been moved after 4.0.0. You can follow find more details at https://github.com/TheHive-Project/TheHiveDocs/blob/master/TheHive4/Installation/Install_deb.md#stable-versions

**Comment by giovanniguadagnini** [comment]
Ok thanks, updated without problems, some observables are still without the possibility to use the analyzers but I guess the problem is related to how the task is being created, for example now the analyzer window on hostname is still empty
![image](https://user-images.githubusercontent.com/43404799/109831383-ae0fff80-7c3f-11eb-94db-582b94f85590.png)

**Comment by nadouani** [comment]
Please check the analyzers you enabled in Cortex. Only those will be visible in TheHive based on the observable data type.
