### ISSUE TITLE
[Bug] Missing Case Templates in the admin dropdown

### ISSUE THREAD

**Issue by blueteamzone** [TheHive-Project/TheHive#1814]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Training VM
| OS version (client)       | Win10
| TheHive version / git hash   | 3.5.1
| Package Type              | DEB
| Browser type & version    | Firefox 86.0 

### Problem Description
Case templates are missing in the training VM TheHive. How can I get access to case templates?
![image](https://user-images.githubusercontent.com/60802334/109971229-48327f00-7cf6-11eb-9cd9-50e62faf46b5.png)

**Comment by nadouani** [comment]
This UI is not from TheHive 3.5.1 but from TheHive4, where case templates are manageable by org admin users
