### ISSUE TITLE
[Bug] TheHive4 binary download returns 404 response

### ISSUE THREAD

**Issue by Zarkrosh** [TheHive-Project/TheHive#1820]
### Request Type
Bug

### Work Environment

Not relevant.

### Problem Description
The binary download of TheHive4 is not available on the URL mentioned in the installation guide (https://download.thehive-project.org/thehive4-latest.zip).

### Steps to Reproduce
1. wget https://download.thehive-project.org/thehive4-latest.zip

### Complementary information
![issue_thehive4](https://user-images.githubusercontent.com/9593772/110330214-cf953080-801d-11eb-9efc-871ea1512a28.png)
The beta version download is up (https://download.thehive-project.org/thehive4-beta-latest.zip).

**Comment by nadouani** [comment]
Should be fixed now, thanks for the catch
