### ISSUE TITLE
[Bug] Observables tags stated as required but isnt

### ISSUE THREAD

**Issue by OlivierGTelia** [TheHive-Project/TheHive#1822]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | Windows 10
| TheHive version / git hash   | TheHive 4.0.0-1
| Package Type              | RPM
| Browser type & version    | Chrome

### Problem Description
Its possible to create an observable without tags, even if its supposed to be required:
![image](https://user-images.githubusercontent.com/78533798/110443758-91028300-80bc-11eb-9e57-83ca9c9f27fd.png)
![image](https://user-images.githubusercontent.com/78533798/110443815-9f509f00-80bc-11eb-9b8a-4ad8cddbfc44.png)

### Steps to Reproduce
1. Create new observable
2. Add a description (this is required to create it)
3. Create new observable.
### Possible Solutions
Either remove the two required stars from the creation form, or enforce a tag for observable creation.

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

**Comment by nadouani** [comment]
The `**` states: `At least, one required field`. So you need to either set tags or description
