### ISSUE TITLE
[Bug] Negation Filter

### ISSUE THREAD

**Issue by KRUXLEX** [TheHive-Project/TheHive#1825]
Is any option to set "non-filter" for example on observable list?
For any filter of course. For now you can filter for example by type (domain, fqdn, url etc.). But what if i want see all non domian observable? I was try !domain, ~domain, ^domain, ?!domain etc.

If isn't any option for it. PLease for future add for 3.5.0-2 and 4.x version

**Comment by nadouani** [comment]
This is already supported in TheHive 4. There is no plan to update this in TheHive 3.
