### ISSUE TITLE
[Bug] Inability to switch between organizations

### ISSUE THREAD

**Issue by staf711** [TheHive-Project/TheHive#1835]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7.3.1611
| OS version (client)       | 10
| TheHive version   | 4.0.3-1
| Package Type              | RPM
| Browser type & version    | gogle chrome 87.0.4280.66

### Problem Description
If you create two or more organizations with non-latin names for one user, you lose the ability to switch between organizations

### Steps to Reproduce
1. Create two non-latin-letter organizations in the Manage Organizations section of The Hive web page. For instance. "Пример-1" and "Пример-2"
2. Add the same user to each organization
3. Log into TheHive as the user from step 2 and try switching between organizations.

### Complementary information
![image](https://user-images.githubusercontent.com/40694301/111030113-b02d4780-8411-11eb-9227-d2ab500808f2.png)

**Comment by nadouani** [comment]
Thanks @staf711 this has been already fixed in 4.1
