### ISSUE TITLE
[Bug] File observables with special character in name can not be downloaded

### ISSUE THREAD

**Issue by KaanSK** [TheHive-Project/TheHive#1842]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu docker base image
| OS version (client)       | All ...
| TheHive version / git hash   | 4.0.5
| Package Type              | DEB
| Browser type & version    | All

### Problem Description
File observables with special characters in filenames can not be downloaded. "Invalid filename" error is shown. File can be found in server filesystem.

### Steps to Reproduce
1. Create a file observable with example name: "Re: Re: malicious mail.eml"
1. Try to download zipped file from TheHive UI
1. Observe the error

### Possible Solutions
1. Filenaming logic (mapping filename to file) may be investigated
2. Validations could be added on frontend and backend
3. Special chars and whitespace could be stripped

**Comment by To-om** [comment]
Some characters are prohibited
