### ISSUE TITLE
[Bug] AttackPatternImportCtrl: Request Entity Too Large during Import MITRE ATT&CK 

### ISSUE THREAD

**Issue by uksza** [TheHive-Project/TheHive#1854]
### Request Type
Bug. 
`AttackPatternImportCtrl: Request Entity Too Large` during Import MITRE ATT&CK pattern

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |CentOS
| OS version (client)       | 8
| TheHive version / git hash   | 4.1.0-1
| Package Type              | RPM

### Problem Description
It looks file from https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json?version=TheHive-4.1.0-1 is too large (about 16mb). 

If you reduce file size (by cut some branches from json) - import works fine.

### Steps to Reproduce
1. click admin
1. click ATT&CK patterns
1. click Import MITRE ATT&CK patterns
1. download json from [url](https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json?version=TheHive-4.1.0-1), attach
1. import

### Possible Solutions
manualy split file to 2 or 3 pieces and import it separately

**Comment by nadouani** [comment]
This means you need to augment the size of allowed HTTP requests

```
play.http.parser.maxDiskBuffer: 50MB
```
