### ISSUE TITLE
Integrate TheHive, Cortex and MISP

### ISSUE THREAD

**Issue by alexrdz0** [TheHive-Project/TheHive#1855]
Perform the installation of the three applications via docker. I can not find the configuration files to make the settings as mentioned in the guide [](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#6-cortex)

That is, I can't find where docker stores the files for these applications. 
Thanks

**Comment by nadouani** [comment]
https://github.com/TheHive-Project/Docker-Templates/tree/main/docker/thehive4-cortex3-misp-shuffle
