### ISSUE TITLE
[Bug] Importing the ATT&CK library fails on 4.1

### ISSUE THREAD

**Issue by aim4r** [TheHive-Project/TheHive#1862]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu Server 20.04
| TheHive version / git hash   | 4.1
| Package Type              | DEB

### Problem Description
Importing the ATT&CK library fails on 4.1 with the error message : `AttackPatternImportCtrl: Request Entity Too Large`

### Complementary information
Screenshot :
![Error](https://user-images.githubusercontent.com/764189/111919823-2d992d80-8a8c-11eb-8908-ed0b7e84e56d.png)

**Comment by dtokkk** [comment]
By default the value of "play.http.parser.maxDiskBuffer" in the config file application.conf it is set to 10MB and the enterprise attack is about 16MB. You can set this option to a bigger value.  After that restart thehive.

**Comment by nadouani** [comment]
@To-om could you please increase the default value of `play.http.parser.maxDiskBuffer`?

**Comment by jeromeleonard** [comment]
https://github.com/TheHive-Project/docs/commit/74b3e7655e0b12241c80497eea0028afff309883

**Comment by jeromeleonard** [comment]
https://github.com/TheHive-Project/docs/commit/9e5c1d67172109450c6cd7dc8de31f0c63fd48c6 

-> https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/misc/
