### ISSUE TITLE
[Question] Enisa Incident Classification Taxonomy

### ISSUE THREAD

**Issue by Litie78** [TheHive-Project/TheHive#1867]
### Request Type

Question

### Question

Does TH support somehow "Case Management" with Enisa  Incident Classification Taxonomy ? (https://www.enisa.europa.eu/publications/reference-incident-classification-taxonomy/ )

**Comment by jeromeleonard** [comment]
Yes, the taxonomy described in the ENISA document is in MISP taxoniomies: https://github.com/MISP/misp-taxonomies/blob/master/ecsirt/machinetag.json and use the namespace "ecsirt".
