### ISSUE TITLE
[Bug] After migration from 4.0.5 to 4.1.0 old tasklogs are not returned by "/api/v1/query?name=case-task-logs" query

### ISSUE THREAD

**Issue by birigli** [TheHive-Project/TheHive#1875]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu, 18.04.5
| OS version (client)       | Win 10
| TheHive version / git hash   | 4.1.0-1
| Package Type              | DEB

### Problem Description
After upgrading from 4.0.5 to 4.1.0 (even from a fresh 4.0.5 instance) the tasklogs created in the older version do not show up in the GUI, as the underlying query: _"/api/v1/query?name=case-task-logs"_ returns only the logs, created in the new version. The older tasklogs however can be retreived through the query used by thehive4py as well: *"/api/case/task/log/_search"*.

### Steps to Reproduce
1. Install fresh 4.0.5
2. Create a case with a task and create a tasklog
3. Upgrade to 4.1.0

### Complementary information
The following is the output of the "/api/v1/query?name=case-task-logs" query: 

```
[
{'_id': '~8440', '_type': 'Log', '_createdBy': 'xxxx@yyyy', '_createdAt': 1616506014677, 'message': 'tasklog2', 'date': 1616506014677, 'owner': 'xxxx@yyyy', 'extraData': {'actionCount': 0}}
]
```
while this is a simple call of the _get_task_logs_() function in thehive4py:

```
[
{'_id': '~8440', 'id': '~8440', 'createdBy': 'xxxx@yyyy', 'createdAt': 1616506014677, '_type': 'case_task_log', 'message': 'tasklog2', 'startDate': 1616506014677, 'status': 'Ok', 'owner': 'xxxx@yyyy'},
{'_id': '~28816', 'id': '~28816', 'createdBy': 'xxxx@yyyy', 'createdAt': 1616500458934, '_type': 'case_task_log', 'message': 'tasklog', 'startDate': 1616500458934, 'status': 'Ok', 'owner': 'xxxx@yyyy'}
]
```

**Comment by nadouani** [comment]
Are all your indexes ok? Check it from the Administration > Platform Status

**Comment by birigli** [comment]
Yes, I've already checked them. Each index is green, I clicked "reindex" on Log, which has 2 entries  according to that screen (and actually in fact). As now it is night here (CET), I can attach screenshot tomorrow, if you will.

**Comment by nulltiply** [comment]
Having the same issue with older task logs not showing. Platform status is showing all ok. 2 servers running Cassandra/HDFS on Debian and 1 server for TheHive on Debian as well.

**Comment by To-om** [comment]
After the upgrate to TheHive 4.1.2, logs will reappear.

**Comment by birigli** [comment]
Well, tasklogs reappeared, many thanks!

**Comment by birigli** [comment]
And once I had a fresh 4.0.5 snapshot, I tested again, and attachments are there as well.
