### ISSUE TITLE
[Bug] Query from TheHive 4.1.0-1 -> Cortex 3.1.1-1 invalid API 

### ISSUE THREAD

**Issue by mihdim777** [TheHive-Project/TheHive#1876]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)      | Debian
| OS version (client)       | 10
| Cortex version             | 3.1.1-1
| TheHive version          | 4.1.0-1
| Package Type              | from source
| Browser type & version    | Chrome

### Problem Description
Hello!
I observed the following error when I try to run an analyzer through TheHive. The analyzer runs and it returns the result but it throws this error at the beginning.

I noticed if I query for **id: /api/analyzer/5fa29adc5dde26e14c49bab4b9efa57b** instead of **analyzerDefinitionId: /api/analyzer/VirusTotal_GetReport_3_0** it returns ok.

**GET /api/analyzer/VirusTotal_GetReport_3_0 returned 404**

![image](https://user-images.githubusercontent.com/81242256/112153917-7667f800-8bec-11eb-9d6e-977821c2398d.png)

Thank you!

**Comment by mihdim777** [comment]
For anyone that have this problem, the RCA is that TheHive to be backward compatible with Cortex 1, it queries first with **analyzerDefinitionId** and if it gets 404, it queries again with **id** to be compliant with Cortex 2. 
So it does 2X queries to order to solve X problems

**Comment by nadouani** [comment]
We will remove this INFO log. This is expected. And yes we want to keep the backward compatibility

**Comment by nadouani** [comment]
if you want better logging in production, just set the log level to WARNING.

**Comment by mihdim777** [comment]
@nadouani Thank you! I will log level to WARNING.
