### ISSUE TITLE
Dashboards - custom fields 

### ISSUE THREAD

**Issue by stacsirt** [TheHive-Project/TheHive#1877]
Hi, 

In previous versions we were able to use metrics as counters within cases and import those in to dashboards. However, we seem to have lost this feature when discontinuing metrics.

I have set the custom field as integer and added it to a case template. Upon selecting custom field there seems to be no way to define specifically which one or to sum it. 

Example in previous version; 

<img width="591" alt="Screenshot 2021-03-23 at 15 25 00" src="https://user-images.githubusercontent.com/39764781/112171667-f2157500-8beb-11eb-9af8-4feb95d99319.png">

Regards,

StaCSIRT

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.1-1
| Package Type              | DEB
| Browser type & version    | If applicable

**Comment by nadouani** [comment]
Hello, how does the current version look like, comparing to the new one?

**Comment by stacsirt** [comment]
Hi, the current view we have in this version is below:
<img width="898" alt="Screenshot 2021-03-24 at 11 05 32" src="https://user-images.githubusercontent.com/39764781/112300652-ff386f80-8c90-11eb-8e47-1ce4e958d4b4.png">

As you can see, there is not option in the drop down list to select our custom metrics field.

**Comment by stacsirt** [comment]
> Hello, how does the current version look like, comparing to the new one?

Hi, the current view we have in this version is below:

<img width="898" alt="Screenshot 2021-03-24 at 11 05 32" src="https://user-images.githubusercontent.com/39764781/112304848-e2eb0180-8c95-11eb-9977-fa2f36d6b7bd.png">

As you can see, there is not option in the drop down list to select our custom metrics field.

**Comment by nadouani** [comment]
I get it!

**Comment by stacsirt** [comment]
Hello,

Unfortunately having upgraded and gone to test this today, we see that we are continuing to experience issues, this time with the data itself not being returned to us in any format, particularly in a line graph:

<img width="901" alt="Screenshot 2021-04-20 at 14 35 13" src="https://user-images.githubusercontent.com/39764781/115405240-fa120600-a1e5-11eb-976a-414011f66ad3.png">

<img width="1438" alt="Screenshot 2021-04-20 at 14 34 46" src="https://user-images.githubusercontent.com/39764781/115405175-ed8dad80-a1e5-11eb-8fb2-0e23d9e604a0.png">

We are certain the data is in there having confirmed this by testing a few different metrics fields with nothing being returned.

Any other ideas? Thanks :)
