### ISSUE TITLE
[Question] Observables export and responders

### ISSUE THREAD

**Issue by mihdim777** [TheHive-Project/TheHive#1883]
Hello!

I have 2 questions:

1. Is there any way to export only new observables from a case to an existing event in MISP?
2. The responders for an observable are custom made? I get a notification that is no responder available.

Thank you!

**Comment by nadouani** [comment]
1 - The export pushes all the observables flagged as IOC
2 - Check the TLP, the PAP of the case. Cortex returns the list of responders based on that

**Comment by mihdim777** [comment]
@nadouani Yes, I know it pushes all the observables flagged as IOC. 

For example I exported one case to MISP, after that I want to add more observables to that case and export **ONLY** the new observables flagged as IOC to the same **EXISTING** event in MISP created before.
