### ISSUE TITLE
How to solve the user admin locked out?

### ISSUE THREAD

**Issue by selimkarauzum** [TheHive-Project/TheHive#1885]
### Request Type

Admin account is locked by accidentally. Is there a way to unlock it,  if I have complete access to TheHive back-end, but are unable to log into the web UI?

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS, RedHat
| OS version (client)       | CentOS, RedHat
| TheHive version  | 3.2.1-1

**Comment by rriclet** [comment]
https://github.com/TheHive-Project/TheHive/issues/1539

**Comment by To-om** [comment]
@selimkarauzum you can have a look at #233

**Comment by selimkarauzum** [comment]
Actually I think I can reset the password of admin. But, when i try to login fron webUİ, I still get Authentication Failure. I am sharing succes log at the below.

{"_index":"the_hive_13","_type":"user","_id":"admin","_version":5,"result":"updated","_shards":{"total":2,"successful":1,"failed":0}}

**Comment by To-om** [comment]
You need to adapt the query and change the index name. If you use the default index name, it should be `the_hive_14` instead of `the_hive_13`. You can list the index in Elasticsearch with `curl http://127.0.0.1:9200/_cat/indices`.

**Comment by selimkarauzum** [comment]
Actually I have tried both 13 and 14. Both was successful. To be sure, if admin password is reset, will admin account unlock by the way?

I am sharing output of 14.
{"_index":"the_hive_14","_type":"user","_id":"admin","_version":5,"result":"updated","_shards":{"total":2,"successful":1,"failed":0}}

**Comment by To-om** [comment]
Actually no. You can update `status` to `Ok`.
```
curl -XPOST "$es/$index/user/$user/_update" -d '{
    "doc" : {
        "status" : "Ok"
    }
}'``

**Comment by selimkarauzum** [comment]
It worked, thanks a lot.
