### ISSUE TITLE
[Bug] Dependency issues when building Docker image

### ISSUE THREAD

**Issue by illuminate-gardepe** [TheHive-Project/TheHive#1895]
# Dependency issues when building Docker image

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)               | CentOS
| OS version (client)                | 7
| TheHive version / git hash   | 4.1.1
| Package Type                       | Docker

### Problem Description
While running "docker build" using the Docker file in ../package/docker I'm getting various which seem to suggest some missing dependencies or mismatched dependency versions. I'm attaching the Dockerfile and build.sbt I'm using and the output from when I try to build. 

### Steps to Reproduce
1. git clone https://github.com/TheHive-Project/TheHive.git
2. Navigate to TheHive/package/docker
3. Run "docker build ."

### Possible Solutions
1) I noticed adding an import at the top of build.sbt for play.api.libs.json.Json._ helped get rid of some of my build errors. I'm assuming there's a deeper but simpler issue at play though. 

### Complementary information
[docker_build_out.txt](https://github.com/TheHive-Project/TheHive/files/6207502/docker_build_out.txt)
[Dockerfile.txt](https://github.com/TheHive-Project/TheHive/files/6207503/Dockerfile.txt)
[build.sbt.txt](https://github.com/TheHive-Project/TheHive/files/6207504/build.sbt.txt)

**Comment by To-om** [comment]
You need to do `git submodule init && git submodule update` after git clone.

**Comment by illuminate-gardepe** [comment]
Thank you, it worked!
