### ISSUE TITLE
Integrat CORTEX and THEHIVE

### ISSUE THREAD

**Issue by alexrdz0** [TheHive-Project/TheHive#1903]
I have an error, when I edit the configuration file, I save it. I restart the service and it gives me the error

Service error
![image](https://user-images.githubusercontent.com/80977110/112697213-592d6680-8e44-11eb-8734-153fa7d56f65.png)

### application.conf
![image](https://user-images.githubusercontent.com/80977110/112697349-95f95d80-8e44-11eb-8871-cf58d0e892b6.png)

### applicacion.log
![image](https://user-images.githubusercontent.com/80977110/112697646-42d3da80-8e45-11eb-8e65-115626c280a1.png)

**Comment by nadouani** [comment]
This is sounds like a misconfiguration, except if the logs say something else.

Please refer to the documentation:
https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/connectors-cortex/

**Comment by alexrdz0** [comment]
He seguido la guia como lo indica la documentacion: https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/connectors-cortex/
Pero sigo presentando problemas. 

![image](https://user-images.githubusercontent.com/80977110/112872689-84e36300-9075-11eb-88ac-36c9fafbe7c8.png)
![image](https://user-images.githubusercontent.com/80977110/112872761-9b89ba00-9075-11eb-803d-f3a0c43a2432.png)
![image](https://user-images.githubusercontent.com/80977110/112874988-777ba800-9078-11eb-9096-4c6c02e983fd.png)
