### ISSUE TITLE
[Question]  TheHive4.1.x Indexes Does Elastic configuration support authentication?

### ISSUE THREAD

**Issue by Canon88** [TheHive-Project/TheHive#1904]
### Request Type

Question

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 4.1.1-1
| Package Type              | DEB

### Question

I have an Elastic cluster, but used x-pack for account authentication as well as certificate verification. I don't see the relevant configuration in TheHive configuration. Is Elastic authentication supported?

**Comment by To-om** [comment]
Basic authentication can be enabled by adding the following lines in application.conf:
```
index.search.elasticsearch.http.auth.type=basic
index.search.elasticsearch.http.auth.basic.username=httpuser
index.search.elasticsearch.http.auth.basic.password=httppassword
```

If you want to SSL, add:
```
index.search.elasticsearch.ssl.enabled=true
index.search.elasticsearch.ssl.truststore.location=/path/to/your/truststore.jks
index.search.elasticsearch.ssl.truststore.password=truststorepwd
```
The file trustsore.jks must contain the certificate authority used to sign your ES certificate. It must be a JKS file (built with java keytool).

You can also use client certificate for mutual authentication:
```
index.search.elasticsearch.ssl.keystore.location=/path/to/your/keystore.jks
index.search.elasticsearch.ssl.keystore.storepassword=keystorepwd
index.search.elasticsearch.ssl.keystore.keypassword=keypwd
```

More settings and details are available in the [Janusgraph documentation](https://docs.janusgraph.org/index-backend/elasticsearch/)

**Comment by Canon88** [comment]
> Basic authentication can be enabled by adding the following lines in application.conf:
> 
> ```
> index.search.elasticsearch.http.auth.type=basic
> index.search.elasticsearch.http.auth.basic.username=httpuser
> index.search.elasticsearch.http.auth.basic.password=httppassword
> ```
> 
> If you want to SSL, add:
> 
> ```
> index.search.elasticsearch.ssl.enabled=true
> index.search.elasticsearch.ssl.truststore.location=/path/to/your/truststore.jks
> index.search.elasticsearch.ssl.truststore.password=truststorepwd
> ```
> 
> The file trustsore.jks must contain the certificate authority used to sign your ES certificate. It must be a JKS file (built with java keytool).
> 
> You can also use client certificate for mutual authentication:
> 
> ```
> index.search.elasticsearch.ssl.keystore.location=/path/to/your/keystore.jks
> index.search.elasticsearch.ssl.keystore.storepassword=keystorepwd
> index.search.elasticsearch.ssl.keystore.keypassword=keypwd
> ```
> 
> More settings and details are available in the [Janusgraph documentation](https://docs.janusgraph.org/index-backend/elasticsearch/)



> Basic authentication can be enabled by adding the following lines in application.conf:
> 
> ```
> index.search.elasticsearch.http.auth.type=basic
> index.search.elasticsearch.http.auth.basic.username=httpuser
> index.search.elasticsearch.http.auth.basic.password=httppassword
> ```
> 
> If you want to SSL, add:
> 
> ```
> index.search.elasticsearch.ssl.enabled=true
> index.search.elasticsearch.ssl.truststore.location=/path/to/your/truststore.jks
> index.search.elasticsearch.ssl.truststore.password=truststorepwd
> ```
> 
> The file trustsore.jks must contain the certificate authority used to sign your ES certificate. It must be a JKS file (built with java keytool).
> 
> You can also use client certificate for mutual authentication:
> 
> ```
> index.search.elasticsearch.ssl.keystore.location=/path/to/your/keystore.jks
> index.search.elasticsearch.ssl.keystore.storepassword=keystorepwd
> index.search.elasticsearch.ssl.keystore.keypassword=keypwd
> ```
> 
> More settings and details are available in the [Janusgraph documentation](https://docs.janusgraph.org/index-backend/elasticsearch/)

Thanks. Last question
My Elastic cluster is ssl enabled, but it doesn't have what you said **keystore.jks**

Here is my **elasticsearch.yaml** configuration
```
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: /etc/elasticsearch/certs/elasticsearch/elasticsearch.key
xpack.security.transport.ssl.certificate: /etc/elasticsearch/certs/elasticsearch/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: [ "/etc/elasticsearch/certs/ca/ca.crt" ]
```

Does it support loading `ca.crt` certificates?

**Comment by Canon88** [comment]
> > Basic authentication can be enabled by adding the following lines in application.conf:
> > ```
> > index.search.elasticsearch.http.auth.type=basic
> > index.search.elasticsearch.http.auth.basic.username=httpuser
> > index.search.elasticsearch.http.auth.basic.password=httppassword
> > ```
> > 
> > 
> > If you want to SSL, add:
> > ```
> > index.search.elasticsearch.ssl.enabled=true
> > index.search.elasticsearch.ssl.truststore.location=/path/to/your/truststore.jks
> > index.search.elasticsearch.ssl.truststore.password=truststorepwd
> > ```
> > 
> > 
> > The file trustsore.jks must contain the certificate authority used to sign your ES certificate. It must be a JKS file (built with java keytool).
> > You can also use client certificate for mutual authentication:
> > ```
> > index.search.elasticsearch.ssl.keystore.location=/path/to/your/keystore.jks
> > index.search.elasticsearch.ssl.keystore.storepassword=keystorepwd
> > index.search.elasticsearch.ssl.keystore.keypassword=keypwd
> > ```
> > 
> > 
> > More settings and details are available in the [Janusgraph documentation](https://docs.janusgraph.org/index-backend/elasticsearch/)
> 
> > Basic authentication can be enabled by adding the following lines in application.conf:
> > ```
> > index.search.elasticsearch.http.auth.type=basic
> > index.search.elasticsearch.http.auth.basic.username=httpuser
> > index.search.elasticsearch.http.auth.basic.password=httppassword
> > ```
> > 
> > 
> > If you want to SSL, add:
> > ```
> > index.search.elasticsearch.ssl.enabled=true
> > index.search.elasticsearch.ssl.truststore.location=/path/to/your/truststore.jks
> > index.search.elasticsearch.ssl.truststore.password=truststorepwd
> > ```
> > 
> > 
> > The file trustsore.jks must contain the certificate authority used to sign your ES certificate. It must be a JKS file (built with java keytool).
> > You can also use client certificate for mutual authentication:
> > ```
> > index.search.elasticsearch.ssl.keystore.location=/path/to/your/keystore.jks
> > index.search.elasticsearch.ssl.keystore.storepassword=keystorepwd
> > index.search.elasticsearch.ssl.keystore.keypassword=keypwd
> > ```
> > 
> > 
> > More settings and details are available in the [Janusgraph documentation](https://docs.janusgraph.org/index-backend/elasticsearch/)
> 
> Thanks. Last question
> My Elastic cluster is ssl enabled, but it doesn't have what you said **keystore.jks**
> 
> Here is my **elasticsearch.yaml** configuration
> 
> ```
> xpack.security.transport.ssl.enabled: true
> xpack.security.transport.ssl.verification_mode: certificate
> xpack.security.transport.ssl.key: /etc/elasticsearch/certs/elasticsearch/elasticsearch.key
> xpack.security.transport.ssl.certificate: /etc/elasticsearch/certs/elasticsearch/elasticsearch.crt
> xpack.security.transport.ssl.certificate_authorities: [ "/etc/elasticsearch/certs/ca/ca.crt" ]
> ```
> 
> Does it support loading `ca.crt` certificates?

I got it done, need to merge **elasticsearch.crt** & **elasticsearch.key** into **elasticsearch.pfx** and then convert from **elasticsearch.pfx** to **elasticsearch.jks**.
