### ISSUE TITLE
[Bug] Cases created under wrong organization

### ISSUE THREAD

**Issue by martinr103** [TheHive-Project/TheHive#1906]
When a user is assigned to two organizations, the Case creation does not work as expected.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 10
| TheHive version / git hash   | 4.1.1
| Package Type              | Binary (running in Docker)
| Browser type & version    | Firefox 87.0

### Problem Description
We plan to use the multi-tenancy capability.
After initial migration (into 1 organization, let's call it "A"), manually created a second organization ("B").
In the second organization created a user, that already existed in org. "A"  , providing the same email address, and the same password in both organizations.
The user can log on, and as expected he does have access to Cases of both organizations. The org context can be switched
by the upper-right corner icon.
However, when the organization context is switched to Org "B" , and a new Case is manually added - then the new Case gets saved under organization "A". And is not visible under org "B".
Furthermore, right after clicking the "Create Case" button, the view gets switched to be displaying list of Cases or Org "A" (where the newly created case appears), even though the upper-right corner switch button, still displays org "B" !

### Steps to Reproduce
1. migrate data from 3.4.x to 4.0.5 (using some default organization), then upgrade TH to 4.1.1  
1. create an additional organization
1. in the second organization (from step 2) - create a user account (role analyst) that has the same email address and password as one of the users in the default organization (from the migration step)
1. log in to Thehive as the user account created in step 3
1. switch organization context to the second organization (as created in step 2)
1. manually create a new ("dummy") Case

**Comment by To-om** [comment]
Is it reproducible ?
You confirm that the organisation switching has been effective (you see the cases of the new org) ?

**Comment by martinr103** [comment]
I have to say that I just re-tested.   And I cannot reproduce it on our 4.1.4 instance.

It _was_ definitely reproducible back at the time, when I filed the bug using 4.1.1

Not sure if any related code changed in the meantime, or if the issue was only intermittent (due to upgrade).
It seems to be gone now.

**Comment by To-om** [comment]
Ok, thanks for your feedback. I close this issue, reopen it if you have more info.
