### ISSUE TITLE
[Bug] Attachments links broken in task logs

### ISSUE THREAD

**Issue by torsolaso** [TheHive-Project/TheHive#1909]
### Request Type
Bug

### Problem Description
i finish the migration to 4.1.1 version but when i click on task and navigate to a task log attachment and click on the icon to download i get 

`{"type":"NotFoundError","message":"Attachment fe67cf099eda34544e35f2b32d6bee5308218f33efbae0a22a514ef443321659 not found"}`

This error occurs on all files attachment previous the migartion. If i attach a new file, i can download it without problems.

### Code related

Maybe code below is related because chunkcode is not getting properly during the migration.

https://github.com/TheHive-Project/TheHive/blob/ce20ee3241767157f829d045938c2d105959becf/migration/src/main/scala/org/thp/thehive/migration/th3/Input.scala#L64

**Comment by nadouani** [comment]
Fixed in 4.1.2
