### ISSUE TITLE
Hello this is a mis configuration issue: `unable to find valid certification path to requested target`

### ISSUE THREAD

**Issue by alexrdz0** [TheHive-Project/TheHive#1910]
Hello this is a mis configuration issue: `unable to find valid certification path to requested target`

Please refer to the documentation:
https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/connectors-misp/

_Originally posted by @nadouani in https://github.com/TheHive-Project/TheHive/issues/1902#issuecomment-809058912_

### Request Type
Integrate MISP-THEHIVE

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian |
| OS version (client)        |     |
| TheHive version / git hash | 3.x           |
| Package Type               | DEB |
| Browser type & version     | If applicable                         |

### Problem Description
I continue with problems, I have edited the MISP integration as indicated in the documentation.

### Complementary information
![image](https://user-images.githubusercontent.com/80977110/112881594-bd3c6e80-9080-11eb-8bef-9d504a948c6b.png)
![image](https://user-images.githubusercontent.com/80977110/112881636-c9283080-9080-11eb-9536-67f6eb3aa2fc.png)
![image](https://user-images.githubusercontent.com/80977110/112881741-e826c280-9080-11eb-8826-e8342e76a50d.png)

**Comment by nadouani** [comment]
Hello @alexrdz0, nothing says in the logs that your MISP connection fails, and the logs don't say why is TheHive failing to start. The stack traces you see here are expected, as they are simple authentication errors.

Please use https://chat.thehive-project.com for troubleshooting.

**Comment by pariiiiiisa** [comment]
hi , if you want to integrate thehive & misp , you need to execute this configuration :
play.modules.enabled += org.thp.thehive.connector.misp.MispModule
misp {
  interval: 1 hour
  servers: [
    {
      name = "MISP Server"     
      url = "https://IP Or URL"
      auth {
        type = key
        key = "Authr key From your misp server "               
      }
      wsConfig {
      ssl.loose.acceptAnyCertificate = true
      }
      //tags = ["tag1", "tag2", "tag3"]
      
      caseTemplate = "misp"
      max-attributes = 1000
      max-age = 7 days
      includedTheHiveOrganisations = ["Organisation Name from thehive"]
      excludedTheHiveOrganisations = [""]
      
    }
  ]
}



it woks for me , thehive version "4.1.12"
