### ISSUE TITLE
[Bug] Alert counter refresh not working

### ISSUE THREAD

**Issue by mrobertsonris** [TheHive-Project/TheHive#1911]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian |
| OS version (client)        | ubuntu 16.04 |
| TheHive version / git hash | 4.1.1 |
| Package Type               | 4.1.1 deb |
| Browser type & version     | Chrome/Safari |

### Problem Description
Alerts/Notification numbers don't seem to be updating unless a page refresh is done. For instance, if I import an alert to a case it will still show the same alert number, until after a page refresh is done for the browser. Attempted on multiple browsers with the same result.

### Steps to Reproduce
1. Have alerts > 0, Alerts = (N)
2. Mark an alert as read
3. Alert does not clear immediately, and when it does clear the alert number is not updated with (N-1)

**Comment by mrobertsonris** [comment]
Bug Submit

**Comment by nadouani** [comment]
Ok, so the alert counter in the navbar reacts to `alert` events, and  merging alert into a case produces a `case creation` event
