### ISSUE TITLE
[Bug] Cannot linking multiple organisation

### ISSUE THREAD

**Issue by rafalszymanek** [TheHive-Project/TheHive#1918]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | CentOS Linux release 8.2.2004 (Core)   |
| OS version (client)        | MacOS           |
| TheHive version / git hash | 4.0.1-1               |
| Package Type               | Binary |
| Browser type & version     | Safari v.14.0.3                         |

### Problem Description
When I try to link several organisations togehter, then some connections (created before) disappears.

### Steps to Reproduce
1. Create three ostanisations
2. Link 1-st organisation to 2-nd and 3-rd
3. Link 2-nd organisation to 3-rd
4. Link between 1-st and 2-nd disappears

### Complementary information
Img from step 2 (connected "Linia A" with "Linia B" and "Linia D")
<img width="476" alt="Screenshot 2021-03-31 at 13 08 55" src="https://user-images.githubusercontent.com/30106887/113135625-9d44b080-9222-11eb-8c3f-9e75a13f55fd.png">

Img from step 3 (no connection between "Linia A" and "Linia D")
<img width="433" alt="Screenshot 2021-03-31 at 13 09 17" src="https://user-images.githubusercontent.com/30106887/113135634-9f0e7400-9222-11eb-9c6b-2c8bbd81ace1.png">

**Comment by mcoreia** [comment]
I'm using Thehive-4.1.1 and it is working fine, try to update from 4.0.1-1 to 4.1.1 or 4.1.2. But i don't recommend for prod environments coz it have some bugs. 

Before I update to 4.1.1, I was using 4.0.5 and if I'm not wrong it was working fine on 4.0.5 too.

**Comment by To-om** [comment]
This issue has already been fixed by #1773
