### ISSUE TITLE
[Bug] Editing case template tasks incorrectly removes tasks 

### ISSUE THREAD

**Issue by H2Cyber** [TheHive-Project/TheHive#1926]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu Server 20.04   |
| TheHive version / git hash | 4.1.2               |
| Package Type               | DEB |

### Steps to Reproduce
1. Create a new case template with three tasks : `Task 1`, `Task 2` and `Task  3`.
2. Open the case template for editing, go to tasks and Edit the second task `Task 2` :
![1](https://user-images.githubusercontent.com/764189/113424791-a8d1dc00-93c8-11eb-9089-a43a04a6c6d7.png)
3. Make any modification in the task title, then click `Update task`:
![2](https://user-images.githubusercontent.com/764189/113424817-b5563480-93c8-11eb-9a3e-ed04de2fe6df.png)
4. Notice how `Task 1` is gone, and replaced by the old `Task 2` !
![3](https://user-images.githubusercontent.com/764189/113424833-b9825200-93c8-11eb-9f98-41d42a40ff24.png)

**Comment by aim4r** [comment]
Unfortunately I can replicate the same issue in my test environment (using the exact steps described above). 
Do let me know if I can provide any further information to help troobleshot the root cause.

**Comment by bs255** [comment]
Same bug here, very frustrating as we screwed half of our case templates before realising tasks were being removed.

**Comment by bs255** [comment]
Is there a fix planned for this bug please ?
