### ISSUE TITLE
[Bug] Task "Take" Button not working

### ISSUE THREAD

**Issue by GoJonnyGo970** [TheHive-Project/TheHive#1931]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu  |
| OS version (client)        | Ubuntu 20.04.2 LTS.            |
| TheHive version / git hash |4.1             |
| Package Type               | DEB|
| Browser type & version     | IFirefox   87.0                      |

### Problem Description
In the Task menu, nothing happens when you click on a "Take" button.

**Comment by jkb-s** [comment]
Upon clicking the `Take` button, developer console shows following error:
![image](https://user-images.githubusercontent.com/80353249/113998264-31cd9500-9859-11eb-907f-db8642d259ea.png)
