### ISSUE TITLE
[Bug] Imported filter does not show alerts which are associated to removed cases

### ISSUE THREAD

**Issue by H2Cyber** [TheHive-Project/TheHive#1940]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu Server 20.04   |
| TheHive version / git hash | 4.1.2               |
| Package Type               | DEB |

### Steps to Reproduce
1. Import any alert into a case :
![Screenshot from 2021-04-06 20-52-46](https://user-images.githubusercontent.com/764189/113770661-4a836100-971a-11eb-9c38-0bfefd37741b.png)

2. Remove the case :
![Selection_020](https://user-images.githubusercontent.com/764189/113770902-a1893600-971a-11eb-8616-97e843a16ffe.png)

3. Back to the Alerts menu, apply `Imported = false` filter, and observe how the alert does not appear :
![Selection_021](https://user-images.githubusercontent.com/764189/113771200-fdec5580-971a-11eb-9ed1-67fcb58c5e28.png)

P.S: the alert does not get deleted, but is no longer visible when applying the `Imported = false` filter.

**Comment by nadouani** [comment]
Hello @aim4r I know that the `imported` filter has been changed twice after 4.0.2. Can you please check this with 4.1.2?

**Comment by aim4r** [comment]
> 
> 
> Hello @aim4r I know that the `imported` filter has been changed twice after 4.0.2. Can you please check this with 4.1.2?

I'm on 4.1.2 indeed. Sorry for the typo in the `Work Environment` section, I'll fix it.

**Comment by nadouani** [comment]
@To-om do you know if the `imported` filter fix in 4.1.3 covers this ?

**Comment by aim4r** [comment]
> @To-om do you know if the `imported` filter fix in 4.1.3 covers this ?

I have updated to `4.1.3` and made some tests, this issue is unfortunately not fixed.
