### ISSUE TITLE
[Thehive service is down]

### ISSUE THREAD

**Issue by tarekkilani** [TheHive-Project/TheHive#1943]
Hello,
Please i installed TheHive 3.5.0+ using DEB package in Ubuntu 18.04.
After installation i did :
```
$ sudo systemctl start thehive
$ sudo systemctl enable thehive
```

The service is sutting down automatically after a short time.
What could be the problem?

**Comment by jkb-s** [comment]
Million things could be the problem.  
If you want help with finding the solution, you need to provide some logs, screen shots etc.  
Community here is strong and developers are responsive. None are clairvoyant though.

**Comment by nadouani** [comment]
Thanks @jkb-s for the comment, you're right.

Troubleshooting must be done on chat.thehive-project.org, except if you have a clear problem description, logs, context etc... and if you think it's a real bug that you investigated. In that case it deserves a github issue?

**Comment by tarekkilani** [comment]
Sorry but i followed the official documentation for the installation (DEB installation).
I tryed it with ubuntu 18.04 and 20.04 with two fresh and new VMs and i does'nt work.
I'm having tha same issue with both TheHive and Cortex services.
Please find attached TheHive application.log file.
Also, the only documentation that i followed and ended with success is using Docker containers => TheHive and Cortex are up and running. But the problem here is how to add Cortex analyzers?
[application.log](https://github.com/TheHive-Project/TheHive/files/6278128/application.log)

**Comment by tarekkilani** [comment]
Sorry but i followed the official documentation for the installation (DEB installation).
I tryed it with ubuntu 18.04 and 20.04 with two fresh and new VMs and i does'nt work.
I'm having tha same issue with both TheHive and Cortex services.
Please find attached TheHive application.log file.
Also, the only documentation that i followed and ended with success is using Docker containers => TheHive and Cortex are up and running. But the problem here is how to add Cortex analyzers?
