### ISSUE TITLE
[Bug] Display statistics for Additional information dashboards

### ISSUE THREAD

**Issue by kiz1** [TheHive-Project/TheHive#1947]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version / git hash | 4.1.2-1|
| Package Type               |DEB |

### Problem Description
Display statistics for Additional information dashboards

![image](https://user-images.githubusercontent.com/56864274/114055484-7d079800-9899-11eb-9077-6f817d9c1d5d.png)

**Comment by nadouani** [comment]
Hello @kiz1 I don't understand the problem

**Comment by nadouani** [comment]
Sounds like a duplicated of #1921

**Comment by kiz1** [comment]
> Sounds like a duplicated of #1921

mmm... Yes, didn't find this issue. Sorry to bother.
