### ISSUE TITLE
[Bug] Enabled or Disabled Taxonomies doesn't work

### ISSUE THREAD

**Issue by azgaviperr** [TheHive-Project/TheHive#1957]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | CentOS, ...   |
| OS version (client)        | Fedora, 10           |
| TheHive version / git hash | 4.1.3
| Package Type               | RPM, DEB, Docker, Binary, From source |
| Browser type & version     | Chrome, Firefox, Edge                        |

### Problem Description
When trying to add tage using the from library option, all the taxonomies are listed even if their status are disabled. 
Tried with linked or not Organisation with different role. Issue is the same. 
Didn't try it yet with a fresh install.

Issue is also occuring on case creation and on alerts/observables. 

### Steps to Reproduce
1. Import Taxonomies
1. Enable a few
1. See that all the taxonomies are available

### Possible Solutions
(keep this section if you have suggestions on how to solve the problem. **Otherwise delete it**)

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

![image](https://user-images.githubusercontent.com/7451354/114457899-d98eee00-9bde-11eb-8cec-c3bf010f1811.png)

![image](https://user-images.githubusercontent.com/7451354/114457989-f3c8cc00-9bde-11eb-99e0-23f77fe37d97.png)

**Comment by azgaviperr** [comment]
Forced a full reindexation and seems working now

**Comment by azgaviperr** [comment]
THis morning issue is back

**Comment by nadouani** [comment]
This sounds like a UI issue, investigating.
