### ISSUE TITLE
[Bug] Observable dont refresh automatically when adding new one.

### ISSUE THREAD

**Issue by torsolaso** [TheHive-Project/TheHive#1975]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version / git hash | 4.1.4               |

### Problem Description
The UX when adding observables is not good, because when you add and obs you must change tab or refresh the browser.

### Steps to Reproduce
1. Create case
1. Go to observables tags an create an observable

![image](https://user-images.githubusercontent.com/52453216/114868514-49c38c80-9df6-11eb-99b2-899deb3ff834.png)

1. Move to details tab and go back on observable details. Note (1 of 0)

![image](https://user-images.githubusercontent.com/52453216/114868605-64960100-9df6-11eb-9c0d-6a8e87c1de5c.png)

1. Refresh browser. Note (1 of 1)

![image](https://user-images.githubusercontent.com/52453216/114868647-711a5980-9df6-11eb-8410-be540beed9b2.png)

### Possible Solutions
Refresh observable listing on adding feature.

**Comment by nadouani** [comment]
Hello @torsolaso what's your index component? ES or Lucene?

**Comment by torsolaso** [comment]
Hello, sorry i forgot add that info. I am unsing ES.

**Comment by azgaviperr** [comment]
Hello, I had the issue prior to 4.1.4 with Lucene index. 
Last update helped on this matter, at least for the creation part, deletion of observable doesn't refresh however.

**Comment by torsolaso** [comment]
@azgaviperr  i am in 4.1.4 and the behaviour is the same. But i am using ES i think this is probably the reason

**Comment by nadouani** [comment]
Hello guys, the list is supposed to be refreshed of course, so if it doesn't then we need to investigate. All lists on TheHive react to what happens on the stream, including "a new observable has been created".

Let me troubleshoot this and I'll let you know.

**Comment by nadouani** [comment]
Quick question: do you see a new an event popping in the right side live feed or not when you add a new observable?

**Comment by torsolaso** [comment]
Hi nadouani,

Let me attach screenshots with right side.

When i add a new observable i can see the adding operation on the live feed but my list only has 1 observable

![image](https://user-images.githubusercontent.com/52453216/121513283-f97a3c80-c9ea-11eb-9a22-37acf8f99756.png)

**Comment by nadouani** [comment]
It sounds like the exact same issue with the tasks and logs.

**Comment by torsolaso** [comment]
Hi @nadouani i repeat same screenshot that on tasks logs issue. 

![image](https://user-images.githubusercontent.com/52453216/121864114-d60e0500-ccfc-11eb-92db-b0ef0c0b5e68.png)


- /api/v1/query?name=observables only returns 2 obs

`[{"_id":"~680276024","_type":"Observable","_createdBy":"testUser@th.local","_createdAt":1620809183351,"dataType":"app","data":"ASDASD","startDate":1620809183351,"tlp":2,"tags":["ASD"],"ioc":false,"sighted":false,"reports":{},"message":"","extraData":{"seen":{"seen":0,"ioc":false},"permissions":["manageShare","manageAnalyse","manageTask","manageCaseTemplate","manageCase","manageUser","manageProcedure","managePage","manageObservable","manageTag","manageConfig","manageAlert","accessTheHiveFS","manageAction"],"shareCount":1},"ignoreSimilarity":false},{"_id":"~1539449016","_type":"Observable","_createdBy":"testUser@th.local","_updatedBy":"testUser@th.local","_createdAt":1618498480924,"_updatedAt":1620809173183,"dataType":"domain","data":"test","startDate":1618498480924,"tlp":2,"tags":[],"ioc":true,"sighted":false,"reports":{},"message":"test 2","extraData":{"seen":{"seen":1,"ioc":false},"permissions":["manageShare","manageAnalyse","manageTask","manageCaseTemplate","manageCase","manageUser","manageProcedure","managePage","manageObservable","manageTag","manageConfig","manageAlert","accessTheHiveFS","manageAction"],"shareCount":1},"ignoreSimilarity":false}]`

**Comment by nadouani** [comment]
> Hello, I had the issue prior to 4.1.4 with Lucene index.
> Last update helped on this matter, at least for the creation part, deletion of observable doesn't refresh however.

Refresh on delete has been fixed in #2076
