### ISSUE TITLE
[Bug] Task Log dont refresh automatically when adding new one.

### ISSUE THREAD

**Issue by torsolaso** [TheHive-Project/TheHive#1977]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version / git hash | 4.1.3             |
| DB | Cassandra |
| Index    | ES                         |

### Problem Description
The UX when adding a task log inside a case is not good, because when you write some note you must change tab or refresh the browser.

### Steps to Reproduce
1. Create ORG A
1. Create Case A
1. Create Task A
1. Click on "+Add new task log"
1. Write something and click in "Add log" and repeat

### Possible Solutions
Refresh task logs on add.

### Complementary information

https://user-images.githubusercontent.com/52453216/114903920-95d2f900-9e17-11eb-9af6-fc2fa6ff4079.mp4

**Comment by nadouani** [comment]
Hello @torsolaso could you please confirm this is still the case in 4.1.5?

**Comment by nadouani** [comment]
@torsolaso Quick question: do you see a new an event popping in the right side live feed or not when you add a new task log?

**Comment by torsolaso** [comment]
HI nadouni, 

i tested it again on 4.1.4 (havent got 4.1.5 yet). On the right side (live feed) i can see new task log posted but the task log only refresh when you post second task log.

let me explain what i am seeing.

1. Create Case
![image](https://user-images.githubusercontent.com/52453216/121511938-79070c00-c9e9-11eb-98d7-beebff347669.png)

2. Create task
![image](https://user-images.githubusercontent.com/52453216/121512024-920fbd00-c9e9-11eb-8278-8fa8656baf03.png)

I see the toast below "Task has been successfully added" and i can see it on the live feed but now shown. I refresh manually or change tab.
![image](https://user-images.githubusercontent.com/52453216/121512114-ae135e80-c9e9-11eb-8823-e18f55c68f45.png)

3. Add new task log

![image](https://user-images.githubusercontent.com/52453216/121512263-d26f3b00-c9e9-11eb-96cb-66bdd3cfe6ae.png)

I can see and it is shown.

4. Add other new task log

![image](https://user-images.githubusercontent.com/52453216/121512357-ea46bf00-c9e9-11eb-9b30-08c9ebfbca20.png)

I can see on live feed that new task log 2 is created but is not shown

5. Add new task log

![image](https://user-images.githubusercontent.com/52453216/121512484-0c404180-c9ea-11eb-811d-de3a21a8d510.png)


I can see previous tag log posted and on right (live feed) i can see "new task log 3"




i hope these screenshot will be useful

**Comment by nadouani** [comment]
Ok, thanks for the feedback.

Can you see a call t the `/api/query` API after the task creation? This is supposed to be called when the UI receives an event from the stream. The same event is used to display the live feed update.

**Comment by nadouani** [comment]
Are you using a single node or multi nodes TheHive instance?

**Comment by torsolaso** [comment]
Hi @nadouani when i write a task log i see following requests:

![image](https://user-images.githubusercontent.com/52453216/121863333-0acd8c80-ccfc-11eb-88a8-57b918a962ef.png)

- /api/v1/query?name=case-task-logs OUTPUT does not contains the object with "test3" comment that i can see on /api/case/task/~3083735176/log submit

`[{"_id":"~2156773544","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321719529,"message":"first","date":1623321719529,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~886972496","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321701678,"message":"12","date":1623321701678,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~927547504","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321696653,"message":"11","date":1623321696653,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~2633101328","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321670794,"message":"3","date":1623321670794,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~927363232","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321664902,"message":"2","date":1623321664902,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~2633089040","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321661055,"message":"1","date":1623321661055,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~927355040","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321635610,"message":"sdasdasd","date":1623321635610,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~764334184","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321630769,"message":"new task log","date":1623321630769,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~886935632","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321531281,"message":"asdsadasdasd","date":1623321531281,"owner":"testUser@th.local","extraData":{"actionCount":0}},{"_id":"~927477872","_type":"Log","_createdBy":"testUser@th.local","_createdAt":1623321526604,"message":"123123","date":1623321526604,"owner":"testUser@th.local","extraData":{"actionCount":0}}]`

**Comment by nadouani** [comment]
> Are you using a single node or multi nodes TheHive instance?

@torsolaso can you please tell us more about this?

**Comment by torsolaso** [comment]
single node. Only 1 ES + 1 Cassandra + 1 TH

**Comment by nicpenning** [comment]
Setup for us:
1 TH + 1 Cassandra + Robust 4 Node Elasticsearch Cluster

**Comment by To-om** [comment]
Can you try to add the following settings in configuration:
```
db.janusgraph.index.search.elasticsearch.bulk-refresh=wait_for
```

**Comment by nicpenning** [comment]
@To-om Good news! Adding the configuration item has allowed the Task Log and Observables to be shown as soon as they are added!
