### ISSUE TITLE
[Bug]Update from 4.1.2 to 4.1.3 fails

### ISSUE THREAD

**Issue by chberti** [TheHive-Project/TheHive#1978]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | CentOS   |
| OS version (client)        |  7  |
| Virtualized  Env.          | True                        |
| Dedicated RAM              | 32 GB                                 |
| vCPU                       |  8                       |
| TheHive version / git hash | 4.1.3             |
| Package Type               | RPM |
| Database                   | Cassandra        |
| Index type                 |  Elasticsearch                |
| Attachments storage        | Local  |
| Browser type & version     |  - |

### Problem Description
Hello, 

I tried to update my TheHive Instance from 4.1.2 to 4.1.3 and a persistent error prevents thehive instance to start up.
Some reindexing tasks complete well, TheHive reaches Elasticsearch and Cassandra properly according to success logs, but then I get into trouble.

I get the following error message :
"org.thp.scalligraph.traversal.TraversalOps in application-akka.actor.default-dispatcher : Uncaught error, not retrying org.thp.scalligraph.InternalError: Property dueDate doesn't exist."

I tried to restart the service several times but nothing changes.

A downgrade worked and now my instance is still running 4.1.2 version.

### Steps to Reproduce
1. From a running thehive 4.1.2 stop the service.
2. Update thehive from 4.1.2 to 4.1.3 (.RPM packages)
3. Start TheHive Service Back Again

I kept the same configuration file as the release notes did not seem to bring many changes.

Thank you in advance for your help.

**Comment by To-om** [comment]
This error message means that the database schema has been correctly set. Which version of TheHive 4 has created the database ? Did you start with a fresh install or migrate data from TheHive 3 ?

**Comment by chberti** [comment]
Hello,

I'm not the original creator of the instance but I think we have always been in 4.X
I decided to restart from a fresh install as the database of this specific instance was messed up...

Thank's for your time :)
