### ISSUE TITLE
[Bug] using quick-filter "shared with my org" takes arround 90 seconds

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1979]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)       | Debian
| OS version (client)       | 10
| Virtualized  Env.          | False                          |
| Dedicated RAM              | 64 GB                                 |
| vCPU                       | 8                        |
| TheHive version / git hash | 4.1.4          |
| Package Type               | DEB|
| Database                   | Cassandra |
| Index type                 | Lucene |
| Attachments storage        | Local    |

### Problem Description
Using Quick-filter "shared with my org" takes very log to load and all 8 CPUs are high CPU usage.
Some details:
/api/v1/query?name=cases.count
![image](https://user-images.githubusercontent.com/11610825/115000262-e3487800-9ea2-11eb-9888-1a81875fabc8.png)

`{"query":[{"_name":"listCase"},{"_name":"filter","_not":{"_like":{"_field":"owningOrganisation","_value":"myOrg2"}}},{"_name":"limitedCount"}]}
`
---
/api/v1/query?name=cases

![image](https://user-images.githubusercontent.com/11610825/115000439-0d019f00-9ea3-11eb-9598-0d5ea8502cf6.png)
`{"query":[{"_name":"listCase"},{"_name":"filter","_not":{"_like":{"_field":"owningOrganisation","_value":"myOrg2"}}},{"_name":"sort","_fields":[{"flag":"desc"},{"startDate":"desc"}]},{"_name":"page","from":0,"to":15,"extraData":["observableStats","taskStats","procedureCount","isOwner","shareCount","permissions","actionRequired"]}]}
`

**Comment by To-om** [comment]
The field "owningOrganisation" is not indexed. This is why the query is slow. This can be fixed in the next release.
