### ISSUE TITLE
[Feature Request] Add tags to alerts in web UI

### ISSUE THREAD

**Issue by mphbig** [TheHive-Project/TheHive#1984]
### Request Type

Feature Request

### Feature Description

Ability to add tags to alerts in the web UI.
On the summary of an alert the ability to add tags to an alert would be great to improve triage of alerts especialy to indicate if a small investigation is ongoing for this alert and avoid someone else to take the same actions.

This is the only use case I got, I request tags to avoid the limitation of a custom field or a owner field.

**Comment by Zarkrosh** [comment]
This would also be useful for marking alerts to track a certain tag, whether the alert is imported or not. For example, to make a retrospective at the end of the month and find them with ease.

**Comment by mphbig** [comment]
Added in 4.1.5
