### ISSUE TITLE
[Bug] Able to merge alert into closed case, even though it is not allowed

### ISSUE THREAD

**Issue by mphbig** [TheHive-Project/TheHive#1985]
### Request Type
Bug

### Work Environment

| Question                   | Awnser                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian 9   |
| OS version (client)        | Windows 10            |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       | 8                       |
| TheHive version / git hash | 4.1.2               |
| Package Type               | DEB |
| Database                   | Cassandra                |
| Index type                 | Lucene                |
| Attachments storage        | Local                  |
| Browser type & version     | Firefox and Chrome latest                         |

### Problem Description
Even when the option "Check this to disallow merging alerts into closed cases" is checked, it is still possible to merge alerts in closed cases using the "Merge Into Case" button.

### Steps to Reproduce
1. Get a new alert
2. Merge the alert in a closed case using the "Merge Into Case" button

### Possible Solutions
Ensure the "Merge Into Case" button searches on opened cases (rather than all cases) when the "Check this to disallow merging alerts into closed cases" is checked.

**Comment by nadouani** [comment]
This configuration option has in fact been create to disallow merging alerts in closed cases from the case similarity view in alert preview, but we should also use it in all the locations related to alert merge into cases.
