### ISSUE TITLE
[Bug] Unable to View new alerts in TheHive4 UI

### ISSUE THREAD

**Issue by lissymaria** [TheHive-Project/TheHive#1995]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | RedHat    |
| OS version (client)        | RedHat 7.9           |
| TheHive version / git hash | 4.1.0.1           |
| Package Type               | RPM |
| Database                   | Cassandra                 |

### Problem Description
When I try to create(curl -XPOST) or send new alerts to thehive4 via API key method,the new alerts are not showing in the UI , but we can see the alert and its details(curl -XGET) at the backend using API calls. We used the org admins API key with Manage Alert permission to connect with theHive4.
Also, we logged in to the server and create a new alert using the following code.

curl -XPOST -H 'Authorization: Bearer xxxxxxxx' -H 'Content-Type: application/json' http://127.0.0.1:9000/api/alert -d '{
  "title": "TEST",
  "description": "N/A",
  "type": "external",
  "source": "instance1",
  "sourceRef": "alert-ref12"
}'
 Is this because of any permission issue.?

**Comment by markus-nclose** [comment]
I have the same issue, I can see the new alerts in the Live Stream audit view but not in the alerts page. 

Question | Answer
-- | --
OS version (server) | Ubuntu 20.04
OS version (client) | Windows 10
TheHive version / git hash | 4.1.4-1
Package Type | Docker
Database | Cassandra

I tested by creating a test alert using the example thehive4py alert creation. Normal alerts via Elastalert also doesn't show up in Alerts page but shows in the Live Stream

**Comment by lissymaria** [comment]
The issue got resolved after the server reboot.
