### ISSUE TITLE
[Bug] Input validation in description field

### ISSUE THREAD

**Issue by nulltiply** [TheHive-Project/TheHive#1997]
### Request Type
Bug

### Work Environment

| Question                            | Answer                               |
| -----------------------------------|------------------------------------ |
| OS version (server)           | Debian                               |
| TheHive version / git hash | 4.1.4                                  |
| Package Type                    | DEB                                  |
| Database                           | Cassandra                        |
| Index type                          | Lucene                             |
| Attachments storage         | HDFS                                |

### Problem Description
When creating a case with an unequal amount of backticks it will cause the description to not be displayed.

### Steps to Reproduce
1. Create a case with description 
 ```     
      ````
      foo 
      ```
      bar
```

**Comment by nadouani** [comment]
Hello @nulltiply nice catch, however this is hard to troubleshoot as it means we need to fix the "markdown to html" component or you fix the makrdown value. 

Sorry but we easily vote for option 2 :)

With that being said, if you have this issue with valid Markdown, we could troubleshoot it.
