### ISSUE TITLE
[Question] Reset Local Credentials for TheHive4 User with Apache Cassandra

### ISSUE THREAD

**Issue by JustCodeIt4Head** [TheHive-Project/TheHive#2000]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        Debian
| OS version (client)        10
| Virtualized  Env.          True
| Dedicated RAM              12 GB
| vCPU                       4
| TheHive version / git hash 4.x
| Package Type               APT
| Database                   Cassandra
| Index type                 -
| Attachments storage        Local
| Browser type & version    -

### Question

For some Reason my KeePass did not save the Password for my Local Administrator Accout for TheHive4 and its changed from the standard secret one. I use Apache Cassandra as the Database, is there any way to Reset the Password for the admin@thehive.local Account or do i have to redo the whole Installation?
Could not find a Answer in the Documentation

**Comment by To-om** [comment]
The easiest way to reset admin password (for the time being) is to reconfigure the authentication providers (cf. [TheHive documenation](https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/authentication/#header)).
You can add a provider `header`:
```
auth.providers: [
  {name: session}
  {name: basic, realm: thehive}
  {name: local}
  {name: key}
  {name: header, userHeader: "X-User"}
]
```
and then reset your own password by providing the correct value in the HTTP header `X-User`:
```
curl -H 'X-User: admin@thehive.local' http://xxxxx/api/user/admin@thehive.local/password/set -d '{"password": "newPassword"}'
```

**Comment by To-om** [comment]
@mcabello91 You need to add `Content-type` header in your curl:
`curl -H 'X-User: admin@thehive.local' -H 'Content-type: application/json' http://xxxxx/api/user/admin@thehive.local/password/set -d '{"password": "newPassword"}'`

**Comment by mcabello91** [comment]
@To-om Muchas gracias!
