### ISSUE TITLE
How to send a specific event from MISP to the Hive as an alert. Not syncing all events

### ISSUE THREAD

**Issue by alienzoX** [TheHive-Project/TheHive#2002]
Hi,

I would like to know is there any way that we can only send a specific event from MISP to Hive as an alert and not sync all events from MISP to Hive ?

Thanks.

**Comment by To-om** [comment]
You can configure filters on MISP event, in particular `whitelist.tags` and `whitelist.organisation`. More information in [TheHive documentation](https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/connectors-misp/#configuration).

**Comment by alienzoX** [comment]
Great thanks.
