### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Sorakurai** [TheHive-Project/TheHive#2009]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| Virtualized  Env.          | Docker                          |
|Container | thehive4:latest (version 4.1.4-1)|
|Docker-Template|[thehive4-cortex31-nginx-https](https://github.com/TheHive-Project/Docker-Templates/tree/main/docker/thehive4-cortex31-nginx-https)|

### Problem Description

Techniques are missing from the "TTPs" overview

### Steps to Reproduce
1. Pull default images from docker hub
2. Log into TheHive web UI
3. Create case and select "TTPs"
4. Click the "Add TTP" button and select a Tactic
5. Techniques are missing

![image](https://user-images.githubusercontent.com/35373962/116671791-a51e7e80-a9a1-11eb-928e-3f76c63fa1b7.png)

**Comment by torsolaso** [comment]
You must load ATT&CK mitre JSON on admin UI before use them

**Comment by Sorakurai** [comment]
@torsolaso this fixed the issue indeed, is this documented somewhere?
