### ISSUE TITLE
[Feature Request] Security update to Splunk app

### ISSUE THREAD

**Issue by prizzo2** [TheHive-Project/TheHive#2011]
### Request Type

Feature Request: improve security of Splunk app such that the app passes validation for use with Splunk Cloud, per description below.

### Feature Description

#5329 2.1.0 - TA-thehive-cortex
Review fails vetting and cannot be installed.

Your app did not meet security and functionality requirements for Splunk Cloud for the following reasons:

Logging API key or password in plain text which is not allowed in Splunk cloud. Please remove such loggers.
File: bin/thehive.py Line Number: 118, 120

Logging API key in plain text which is not allowed in Splunk cloud. Please remove such loggers.
File: bin/cortex.py Line Number: 107

Logging additional parameter which contains sensitive information such as password and api key in plain text which is not allowed in Splunk cloud. Please remove such loggers.
File: bin/common.py Line Number: 107, 168

The application can be configured for unencrypted communication, which is not permitted in Splunk Cloud. Make sure all communication must be encrypted (HTTPS preferred).
File: bin/ta_thehive_cortex/aob_py3/thehive4py/api.py

### Possible Solutions

1. Remove plaintext API key or password in File: bin/thehive.py Line Number: 118, 120
2. Remove plaintext API key in File: bin/cortex.py Line Number: 107
3. Remove plaintext sensitive information (e.g. - password, API key) in File: bin/common.py Line Number: 107, 168
4. Require HTTPS communication in File: bin/ta_thehive_cortex/aob_py3/thehive4py/api.py

### Complementary information

N/A

**Comment by billmurrin** [comment]
I don't think that this org is responsible for the Splunk app.

https://github.com/LetMeR00t/TA-thehive-cortex

**Comment by To-om** [comment]
We are not the owner of this app.
