### ISSUE TITLE
[Bug] Case description edit button misplaced after description update

### ISSUE THREAD

**Issue by mphbig** [TheHive-Project/TheHive#2012]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian  |
| OS version (client)        | Windows 10        |
| Virtualized  Env.          | True                        |
| Dedicated RAM              | 32 GB                                 |
| vCPU                       | 12                       |
| TheHive version / git hash | 4.1.4           |
| Package Type               | DEB |
| Database                   | Cassandra               |
| Index type                 | Lucene            |
| Attachments storage        | Local                |
| Browser type & version     | Latest Chrome and Firefox                         |
| Bonus : screen resolution | 1920x1080    |

### Problem Description
It is possible to make the edit button for the description field of a case disappear by editing this description field with just a line break.

### Steps to Reproduce
1. Edit the description of a case
2. Empty everything
3. Add a line break (which should be the only thing in your description)
4. Save the description
5. The pencil is now reachable by just one pixel

### Complementary information
Before
![2021-05-03 17_26_47-TheHive - Case #175_ Double Two](https://user-images.githubusercontent.com/20475134/116897024-1b86df00-ac35-11eb-8f92-fb3b1efec872.png)
* * *
Editing the description with just a line break
![2021-05-03 17_27_12-TheHive - Case #175_ Double Two](https://user-images.githubusercontent.com/20475134/116897082-28a3ce00-ac35-11eb-9b65-62a7fe4fbf8b.png)
* * *
Final result (pencil accessible by just a tiny pixel)
![2021-05-03 17_27_43-TheHive - Case #175_ Double Two](https://user-images.githubusercontent.com/20475134/116897107-2e99af00-ac35-11eb-85fc-be3060025a37.png)

**Comment by nadouani** [comment]
I cannot replace your `  \n` with a `Not Specified` as it's specified actually. Saying the description is `blank` means we alter your data.

I don't find a valid fix for this :D

@mphbig what would be a good solution here ?

**Comment by mphbig** [comment]
An idea could be to make sure the div surrounding the case description is large enough (on the y axis) so the pencil is visible and clicable at all times.
Because it seems it is not working properly when filling the case description with only `\n`.

How ? Well, I have never touched UI stuff. I got no clue to help you here :(

**Comment by nadouani** [comment]
OK I see, and is the following, a valid use case:

> when filling the case description with only \n.

:D

**Comment by mphbig** [comment]
No, it is not a valid use case.
