### ISSUE TITLE
[Bug] Inconsistent Results/Page Refresh

### ISSUE THREAD

**Issue by mrobertsonris** [TheHive-Project/TheHive#2017]
### Request Type
Inconsistent results/page refresh when adding Case Notes or Observables. 

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian |
| OS version (client)        | ubuntu 16.04 |
| TheHive version / git hash | 4.1.4-1 |
| Package Type               | 4.1.4-1 deb |
| Browser type & version     | Chrome/Safari |

### Problem Description
When adding a New task log to case notes, or adding observables in a case there seems to be a considerable delay in the page refreshing and the added values showing up. This can be done immediately by refreshing the page, but on the prior version these would show almost immediately after being added. 

It's a bit inconsistent in that it doesn't happen every time but when it does it can take upwards of 30 seconds to a minute before the value shows, sometimes it won't update at all.

### Steps to Reproduce
1. Add Case Note/Observable
2. Verify if the Case Note/Observable is shown on the page
3. If Case Note/Observable is not showing, refresh the page

**Comment by nadouani** [comment]
Hello @mrobertsonris can you help us gather more details here:

- What's the result of your `/api/status` API call?
- Can you check the API call that takes 30+ seconds time to load?
- Do you see the object creation event popping up on the live feed?

Thanks

**Comment by To-om** [comment]
This duplicates #1975 #1977 #2085
