### ISSUE TITLE
[Bug] TheHive V4 API Errors "Operation Not Permitted"

### ISSUE THREAD

**Issue by Proc3ssor1** [TheHive-Project/TheHive#2018]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian 10   |
| OS version (client)        | Ubuntu            |
| Virtualized  Env.          | True                       |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 4 / 8 / 16 / 32                       |
| TheHive version / git hash | 4.0.0.1               |
| Package Type               | Docker |
| Database                   | Cassandra                |
| Attachments storage        | Local                  |
| Browser type & version     | N/A                       |

### Problem Description
I'm using TheHive 4.0.0.1 and curl POST gives me an "Operation not permitted error".

### Steps to Reproduce
1. curl -X POST -H 'X-Organisation: testorga' -H 'Authorization: Bearer It/7LqrPoc38NEENbdGScUjpNArss/T72nv' -H 'Content-Type: application/json' http://thehive.local/api/case/:112/artifact -d '{"dataType": "url", "data": "8.8.8.8"}'
Result : {"type":"AuthorizationError","message":"Operation not permitted"}

**Comment by joseluratm** [comment]
which profile is assigned to the user with which you are trying to create the artifact? Have you checked if the profile has been assigned the permissions to create observables?
In my organization the user to create things through the API has the profile ANALYST.

p.s: Try to make the title descriptive.

**Comment by Proc3ssor1** [comment]
Oops sorry, I forgot to put the title, I just fixed this error.

I tried to create observables with the following 2 types of profiles:
- org-admin
- analyst

The 2 profiles have the "manageObservable" permissions assigned to them. But, I still have the same error message.

**Comment by joseluratm** [comment]
Have you tried to create the observable directly from the web? do you have permissions?
If not, try creating another user and try again. And if the problem persists, try updating thehive to a newer version. I am currently working with 4.1.4-1 and I can confirm that it works.

**Comment by To-om** [comment]
The ID of the case is not correct. It should not start with `:`. If it is the case number, remove the colon. If it is a real ID, replace the colon by a `~`.

**Comment by nadouani** [comment]
@Proc3ssor1 how does it work after To-om's comment?

**Comment by Proc3ssor1** [comment]
After the update to 4.1, that's work.
Thank you.
