### ISSUE TITLE
Error message keeps popping up

### ISSUE THREAD

**Issue by evans656** [TheHive-Project/TheHive#2019]
We have thehive appearing to be working well but the error message keeps popping up...

![Screenshot 2021-04-26 at 11 38 50](https://user-images.githubusercontent.com/83817217/117439370-ab28d800-af2a-11eb-825d-5795ec7028db.png)
![Screenshot 2021-04-23 at 07 49 22](https://user-images.githubusercontent.com/83817217/117439380-ad8b3200-af2a-11eb-9364-802b738f9556.png)

We have found some references to the error but nothing seems to work..
Any pointers would be appreciated.

**Comment by To-om** [comment]
You need to increase timeout on your reverse proxy. TheHive uses long-polling for the stream thus response time of stream related request can be up to 1 minute (by default)
