### ISSUE TITLE
Issue still present in 4.1.4 as in Bug #1972

### ISSUE THREAD

**Issue by auslaender6** [TheHive-Project/TheHive#2032]
Hi,
we got exactly this issue in Version 4.1.4, so will this be fixed inm 4.1.5?

Issue: https://github.com/TheHive-Project/TheHive/issues/1972

cheers
Niko

**Comment by nadouani** [comment]
Hello @auslaender6 could you give a little bit more context? A sample observable details page for example. Are you sure the observable is likable?

**Comment by nadouani** [comment]
And can you please use the issue templates as we require all the context to be able to (1) understand (2) reproduce.

**Comment by auslaender6** [comment]
Strange... looks like after 24h it is gone. -> Can be closed.
