### ISSUE TITLE
[Bug] Issue to retrieve file with special characters in Name

### ISSUE THREAD

**Issue by ch0wm3in** [TheHive-Project/TheHive#2034]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu   |
| OS version (client)        | 10            |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 4                       |
| TheHive version / git hash | 4.1.3.1             |
| Package Type               | DEB |
| Database                   | Cassandra                |
| Index type                 | Lucene                |
| Attachments storage        | Local                 |
| Browser type & version     | If applicable                         |

### Problem Description
We have file where "ᴘᴀʏᴍᴇɴᴛ" charcode : 1d18 1d00 028f 1d0d 1d07 0274 1d1b
against "PAYMENT" charcode:  50 41 59 4d 45 4e 54
is in the name, this triggers an error when trying to download/retrieve the file from webgui thehive
{"type":"IllegalArgument","message":"Character 7448 cannot match AsciiSet because it is out of range"}

### Steps to Reproduce
1. Upload file observable with non-ascii name
2. Try to download.

### Possible Solutions
Sanitize or allow use of unicode in filenames.

**Comment by To-om** [comment]
The HTTP server used by TheHive doesn't seeam to accept non acsii chars in url (even encoded).
As workaround you can change the url to rewrite the filename. The URL looks like `https://xxx/api/datastorezip/30..40?name=ᴘᴀʏᴍᴇɴᴛ`, you can change the last parameter.
