### ISSUE TITLE
[Bug] Can't Delete Case Custom Field (contains [ character) After Migration

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/TheHive#2043]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu  |
| OS version (client)        | 18           |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 8                       |
| TheHive version / git hash | 4.1.4, hash of the commit               |
| Package Type               | DEB |
| Database                   | Cassandra              |
| Index type                 | Elasticsearch                |
| Attachments storage        | Local                |
| Browser type & version     | Chrome                        |

### Problem Description
When I try to delete a case custom field I get an error which is likely due to using a bracket "[" character.

![image](https://user-images.githubusercontent.com/5582679/119877464-b0a48d00-beee-11eb-8f99-e4176eb12f40.png)

![image](https://user-images.githubusercontent.com/5582679/119877680-f3666500-beee-11eb-8f87-ab45a0edfddd.png)

### Steps to Reproduce
1. Create a case custom field with a bracket in it ( "[" or "]")
2. Migrate to TheHive4 from TheHive3
3. Try to delete the custom field in TheHive4

### Possible Solutions
Change invalid characters on the migration to valid characters so they can be deleted in the new platform.

**Comment by nadouani** [comment]
@nicpenning updating the custom field names silently during the migration is not an option as it changes the data. We will try to find a way to bypass the special character constraint during the delete.

Recommendation: next time you create a custom field, use a `domain-password-reset-phishing` style. TheHive GUI will help you for it ;)

![Screenshot 2021-05-28 at 06 19 38](https://user-images.githubusercontent.com/21827/119928856-b21c9680-bf7c-11eb-89e1-86eca2e92b31.png)

**Comment by nadouani** [comment]
@To-om can you please help investigate the custom field deletion in this case. I was not able to reproduce as TheHive 4 doesn't allow the creation of such a name :)

**Comment by nadouani** [comment]
@To-om I'll try using the custom field's ID for deletion instead of the name, if possible.

**Comment by nadouani** [comment]
Well, let me answer myself: I can fix it by just using the custom field id instead of the internal name :)

**Comment by nicpenning** [comment]
That was fast, thank you! You would think I would have learned by now that I shouldn't use such characters when creating these things :)
