### ISSUE TITLE
[Bug] Unable to find case by Case Number

### ISSUE THREAD

**Issue by BlueJokerr** [TheHive-Project/TheHive#2044]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | CentOS   |
| OS version (client)        | 8           |
| Virtualized  Env.          | True                       |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       | 12                     |
| TheHive version / git hash | 4.1.4-1               |
| Package Type               | RPM |
| Database                   | Cassandra                |
| Index type                 | Lucene                |
| Disk| Local                 |
| Browser type & version     | Chrome                         |

### Problem Description
We are facing a random error when trying to search for some cases using their case number (#15611 for example) via WebGUI, TheHive fails to find it and returns an "Unable to find case with number...", but the case does exist, we try to do some debug and found that TheHive calls an api method (/api/case/_search) using the field "caseId". We try to simulate that api call and found that it returns an empty array as if the case doesn't exist.
If we search for the case manually in the case menu we can find it and the case number is OK, we also try to do an api call (/api/v1/query) with the real ID (DB ID) and in the result we can see that the case number is also correct.

This issue is really annoying because we use the case number for tracking purposes.

Maybe it could be an index issue?

### Steps to Reproduce
Random error

### Possible Solutions
N/A

### Complementary information
I'm attaching print screens of the error:
- WebGUI case search:
 ![1 web gui search case by ID error](https://user-images.githubusercontent.com/84862128/119890303-0c324300-bf0e-11eb-8324-ba07f706e7bf.jpg)

- API Call when WebGUI case search is executed returns null:
![2 api called when searching case ID fails returns null](https://user-images.githubusercontent.com/84862128/119890272-0177ae00-bf0e-11eb-91be-f7d50cf934c8.jpg)

- API Call by case number using POSTMAN returns null:
![3 api query by ID returns null](https://user-images.githubusercontent.com/84862128/119890273-0177ae00-bf0e-11eb-9bf1-d7280a65ce89.jpg)

- Searching manually in cases tab we can find the case with its corresponding case number:
![4 web gui case exists](https://user-images.githubusercontent.com/84862128/119890276-02104480-bf0e-11eb-8f6b-a06334ebf7cc.jpg)
![4 web gui case exists 2](https://user-images.githubusercontent.com/84862128/119890274-02104480-bf0e-11eb-9773-6fac4db2a58c.jpg)

- API call usind case ID returns correct case with corresponding case number:
![5 api query by DB ID](https://user-images.githubusercontent.com/84862128/119890278-02a8db00-bf0e-11eb-83c7-95d5a82c3a0c.jpg)

**Comment by nadouani** [comment]
Hello @BlueJokerr This is weird as I cannot see any reason for it. The case is listed, this means it exists in the index, and the number is correct. Do you see any error in logs when searching by number?

**Comment by BlueJokerr** [comment]
Hi @nadouani, thanks for your reply. Unfortunatly no errors are detected in logs, tried searching in cassandra and thehive logs and could only see that the search is performed and returns 200:
![image](https://user-images.githubusercontent.com/84862128/120013634-5cb1ab00-bfb7-11eb-91f0-795b78f9ac0d.png)

**Comment by nadouani** [comment]
Thanks for the logs, I'll try to fix the deprecated use of the filter firstly and check if there is any other reason.

**Comment by nadouani** [comment]
Trying a fix as I wasn't able to reproduce.

**Comment by B4mcruz** [comment]
Hi @nadouani, I don't think that the issue is related to the deprecated filter, because I've tried doing a post to the api using the field/value non-deprecated method and I couldn't find the case either.
