### ISSUE TITLE
[Bug] add TTP error message on the hive - 4.1.4-1

### ISSUE THREAD

**Issue by pares79** [TheHive-Project/TheHive#2045]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                [|](url)
| -------------------------- | ------------------------------------- |
| OS version (server)        | RedHat, 7   |
| OS version (client)        | window 10            |
| Virtualized  Env.          | True                         |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 4               |
| TheHive version / git hash | 4.1.4               |
| Package Type               | RPM  |
| Database                   | Cassandra                 |
| Index type                 | Elasticsearch                |
| Attachments storage        | Local                  |
| Browser type & version     | Chrome                         |

### Problem Description
After creating a case and any related task, by trying to add the TTP got error message 
'Add TTP: [Invalid format for patternId: FNull, expected string(string)]'

### Steps to Reproduce
1. step 1  > create case
1. step 2 > add task
1. step 3 > add TTP

Please see attachment
![ttp_error_message](https://user-images.githubusercontent.com/26585195/119985124-8ae8b800-bfc2-11eb-8340-b3166432ef7d.PNG)

**Comment by nadouani** [comment]
Hello @pares79 you didn't select any technique/sub technique here.
