### ISSUE TITLE
[Bug] max-attributes param not working for MISP

### ISSUE THREAD

**Issue by mamoedo** [TheHive-Project/TheHive#2050]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version / git hash | 4.1.4            |
| Package Type               |Binary |
| Database                   | Cassandra             |
| Index type                 |Elasticsearch                |
| Attachments storage        | Local                  |

### Problem Description
At least `max-attributes` config setting is not working as stated [here](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#7-misp). 

### Steps to Reproduce
1. Wait until you receive a MISP alert with more than `max-attributes` setting.
2. Filter didn't work

### Complementary information
```
{
            name = "Org"
            url = "https://misp.org.com"
            auth {
                type = key
                key = "XXXX"
            }
            purpose = ImportAndExport
            tags = ["Imported"]
            max-attributes = 2000
            max-size = 16 MiB
            max-age = 30 days
            exclusion {
              organisations = ["Org-two"]
            }
            includedTheHiveOrganisations = ["Org"]
        },
```

**Comment by nadouani** [comment]
@To-om it looks like `max-attributes` and `max-size` are not implemented in TheHive 4, can you please confirm?

**Comment by Shraddha10rathor** [comment]
max-attributes filter is not working in TheHive version 4.1.9
