### ISSUE TITLE
[Bug] Deleting observables doesn't produce audit log

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#2076]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version / git hash | 4.1.5               |
| Package Type               | From source |
| Database                   | BerlkelyDB                |
| Index type                 | Lucene |

### Problem Description
Deleting an observable doesn't:
- produce audit log entry
- produce stream events

**Comment by nadouani** [comment]
@To-om @vdebergue can this be handled in 4.1.6?

**Comment by vdebergue** [comment]
Seems a bit hard for my skills right now. 

From what I saw and guessed,  it seems like there is a visibility problem with the Audit entity in the case of a deletion of an Observable: before sending the audit to the user, we check if it's visible to the user. But as the observable was deleted, the audit is marked as not visible.

Maybe @To-om will know more how to fix this

**Comment by nadouani** [comment]
Makes sense, I think the issue is solved for the tasks, so it should be doable for observables as well
