### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Sshahar** [TheHive-Project/TheHive#2078]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu   |
| OS version (client)        | Ubuntu 18.04 |
| Virtualized  Env.          | True |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       | 8 |
| TheHive version / git hash | 4.x|
| Package Type               | DEB|
| Database                   | Cassandra |
| Index type                 | Lucene |
| Attachments storage        | Local|

### Question

How to configure TLS? 
Currently I use http://localhost:9000
I want to use: https:localhost:9000

**Comment by Sshahar** [comment]
Figuring out TheHive uses a Play Framework server I found this:
https://www.playframework.com/documentation/2.8.x/ProductionConfiguration#General-configuration

I tried configuring the server to use HTTPS by appending to `/etc/thehive/application.config` the following:
```
play {

  server {

    # HTTPS configuration
    https {

      # The HTTPS port of the server.
      port = ${?PLAY_HTTPS_PORT}

      # The interface address to bind to
      address = "0.0.0.0"
      address = ${?PLAY_HTTPS_ADDRESS}

      # The SSL engine provider
      engineProvider = "play.core.server.ssl.DefaultSSLEngineProvider"

      # HTTPS keystore configuration, used by the default SSL engine provider
      keyStore {
        # The path to the keystore
        path = ${?https.keyStore}

        # The type of the keystore
        type = "JKS"

        # The password for the keystore
        password = ""
        password = ${?https.keyStorePassword}
      }

      # HTTPS truststore configuration
      trustStore {

        # If true, does not do CA verification on client side certificates
        noCaVerification = false
      }

      # Whether JSSE want client auth mode should be used. This means, the server
      # will request a client certificate, but won't fail if one isn't provided.
      wantClientAuth = false

      # Whether JSSE need client auth mode should be used. This means, the server
      # will request a client certificate, and will fail and terminate the session
      # if one isn't provided.
      needClientAuth = false
    }
}
```

**Comment by torsolaso** [comment]
You can setup TLS/SSL using JKS on the play framework but usually is easier to deploy a reverse proxy.

`Last but not least, some users reported severe problems when they enabled TLS/SSL directly on TheHive without resorting to a reverse proxy such as NGINX. Blame that on the crappy TLS support in Play framework ;-). So we highly recommend using a reverse proxy for that purpose,`

Extracted from https://blog.thehive-project.org/2018/11/16/thehive-3-2-0-rc1-the-misp-love-edition/

You can find tutorials:

https://blog.agood.cloud/posts/2019/04/24/setup-reverse-proxy-for-thehive/

**Comment by nadouani** [comment]
We don't recommend configuring TLS directly on TheHive, please use a reverse proxy.

Thanks @torsolaso for the answers too.
