### ISSUE TITLE
[Bug] Task Log not displayed after hitting submit

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/TheHive#2085]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu   |
| OS version (client)        | 10            |
| Virtualized  Env.          | True                           |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 8                      |
| TheHive version / git hash | 4.1.6               |
| Package Type               | DEB |
| Database                   | Cassandra            |
| Index type                 | Elasticsearch                |
| Attachments storage        | Local                |
| Browser type & version     | Chrome 91.0.4472.101 (Official Build) (64-bit)                      |

### Problem Description
Task logs are no longer populating immediately after submission. The page needs to be refreshed before the new task log that was created can be seen.

### Steps to Reproduce
1. Go to tasks
2. Click Add New Task Log
3. Click Add Log
4. Watch the the log does not appear

### Possible Solutions
When the user clicks on add log then immediately display the task so the user knows that the task log was successfully added.

### Complementary information
Here is a demonstration of trying to create the task log and it not showing up. After about 5 seconds I click on the refresh button in the browser to then show that the task log was created.

![magic](https://user-images.githubusercontent.com/5582679/122132614-c5df4e00-ce00-11eb-854e-581ace7c4a5c.gif)

**Comment by nicpenning** [comment]
Ahh, looks like I am really late on this. This is a duplicate of:
#1977

This can be closed or deleted as needed.

**Comment by nadouani** [comment]
This is completely weird, as I don't reproduce it :( Let me try it again.

**Comment by nicpenning** [comment]
I have Elasticsearch 7.12.1.

Working on upgrading to 7.13.1.

This same behavior happened in 4.1.5.

Anything else you might need?

**Comment by nicpenning** [comment]
I figured out that if the Live Stream open the right hand side is open the task is shown right away when the task is added. However, if the Live Stream is not open on the right, then it will not show the task log after hitting complete.

**Comment by nicpenning** [comment]
@nadouani We have found that this same behavior occurs on adding observables as well. 

The observable does not show until you refresh the page. Or if you have the Live Stream open on the right, then it will immediately show when the observable gets created.

**Comment by nicpenning** [comment]
Also, I can confirm this same activity happens with Creating New Tasks in Cases.

**Comment by Canon88** [comment]
> Also, I can confirm this same activity happens with Creating New Tasks in Cases.

I had the same problem

**Comment by nicpenning** [comment]
This is resolved by a configuration change found here: https://github.com/TheHive-Project/TheHive/issues/1977#issuecomment-903869218

**Comment by nicpenning** [comment]
Closing as this is duplicate and it can be resolved by adding this configuration setting (as noted above in the original post):

db.janusgraph.index.search.elasticsearch.bulk-refresh=wait_for
