### ISSUE TITLE
[Bug] TheHive Service Stops after a certain period of time

### ISSUE THREAD

**Issue by Tyrell20** [TheHive-Project/TheHive#2087]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | RedHat 7.9  |
| Virtualized  Env.          | True |
| Dedicated RAM              | 4GB                                 |
| vCPU                       | 4                  |
| TheHive version / git hash | 4.1.6               |
| Package Type               | RPM |
| Database                   | Cassandra |
| Index type                 |  Elasticsearch                |
| Attachments storage        | Local|

### Problem Description
TheHive service stops after few minutes automatically.

### Steps to Reproduce
1. #service thehive start;
1. The application works correctly for a few minutes or hours;
1. The service goes down

### Complementary information
`# service thehive status
Redirecting to /bin/systemctl status thehive.service
● thehive.service - Scalable, Open Source and Free Security Incident Response Solutions
   Loaded: loaded (/usr/lib/systemd/system/thehive.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2021-06-16 18:22:23 CEST; 15h ago
     Docs: https://thehive-project.org
  Process: 9274 ExecStart=/opt/thehive/bin/thehive -Dconfig.file=/etc/thehive/application.conf -Dlogger.file=/etc/thehive/logback.xml -Dpidfile.path=/dev/null (code=exited, status=255)
 Main PID: 9274 (code=exited, status=255)
`

Attached the application.log
[application.log](https://github.com/TheHive-Project/TheHive/files/6668307/application.log)

**Comment by vdebergue** [comment]
Your application dies because of an out of memory error: `java.lang.OutOfMemoryError: Java heap space`

also in your logs there are multiple warnings:

```
[WARN] from akka.cluster.ClusterHeartbeat in application-akka.actor.default-dispatcher
-12 - Cluster Node [akka://application@127.0.0.1:15184] - Scheduled sending of heartbeat was delayed. Previous
 heartbeat was sent [3327] ms ago, expected interval is [1000] ms. This may cause failure detection to mark me
mbers as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispa
tcher, CPU overload, or GC.
```

It seems like your instance does not have enough memory/cpu to run correctly

**Comment by nadouani** [comment]
TheHive + Elasticsearch + Cassandra on the same machine with 4GB?

**Comment by Tyrell20** [comment]
The system worked without problem with these hardware resources before the 4.1.5 and 4.1.6 updates.

Can you indicate us what would be the ideal CPU and RAM resources for this type of installation?
Thank you

**Comment by Tyrell20** [comment]
With 8 CPU and 16GB of RAM the system seems stable.
Thank you
