### ISSUE TITLE
[Bug] Error when import pdf file in Task Logs

### ISSUE THREAD

**Issue by RomainSm** [TheHive-Project/TheHive#2112]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Red Hat  |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 32 GB                                 |
| vCPU                       |  8                       |
| TheHive version / git hash | 4.14.3             |
| Package Type               |  RPM |
| Database                   |  Cassandra                |
| Index type                 |  Elasticsearch                |
| Attachments storage        | Local                 |

### Problem Description
When users try to import pdf (or any) file in "New case > Tasks > "Personnal tasks created" > Task logs" this error occur ; 

taskDetails: /opt/thp_data/files/thehive/attachment/... [ a huge alphanumeric number)

When I try to access to this file, it seems to be crypted.

### Steps to Reproduce
1. Create new task
1. Create new case
1. Insert new pdf file in Tasks Logs display

### Possible Solutions
Maybe check file announced but with encryption, I can't see it.

### Complementary information
See in attachment
<img width="943" alt="2021-07-08_17h31_57" src="https://user-images.githubusercontent.com/84323187/124950237-85937a00-e012-11eb-80a9-2dc813b25508.png">

**Comment by nadouani** [comment]
Can you get the error logs related to this error, from `/var/log/thehive/application.log` ?

**Comment by RomainSm** [comment]
Hello, 

I find 2 logs with a lot of line number but the most relevant is : 

2021-07-26 09:24:44,910 [ERROR] from org.thp.scalligraph.models.Database in application-akka.actor.default-dispatcher-16 [00010ba0|05c660c8] Exception raised, rollback (/opt/thp_data/files/thehive/attachment/8dc3b3f63e0d995f51c10cc85e42990be0ce2f0271b4fe66d391e3c8a877e3ae)
2021-07-26 09:24:44,910 [ERROR] from org.thp.scalligraph.ErrorHandler in application-akka.actor.default-dispatcher-16 [00010ba0|05c660c8] Internal error
java.nio.file.AccessDeniedException: /opt/thp_data/files/thehive/attachment/8dc3b3f63e0d995f51c10cc85e42990be0ce2f0271b4fe66d391e3c8a877e3ae


We can see a Denied access exception.

The rights in /opt/thp_data/files/thehive/attachment/ are : 

-rw-r--r--. 1 root    root

I guess, I need to change rights to put "write" right to "other" group ?
Could you confirm me that or propose me another solution ?

**Comment by RomainSm** [comment]
Problem solve.
