### ISSUE TITLE
[Feature Request] Default case template when importing alert

### ISSUE THREAD

**Issue by Zarkrosh** [TheHive-Project/TheHive#2118]
### Request Type

Feature Request

### Feature Description

When creating a case from the 'Preview and import' modal dialog, the template option selected by default is the 'Empty case' value. It would be useful to have selected by default an specific template or maybe the last used template.

![imagen](https://user-images.githubusercontent.com/9593772/125774461-c0b523c8-0234-4deb-a1d5-33762b292f08.png)

### Possible Solutions

In the case template editor, add a checkbox to set the templated as the selected by default:

![imagen](https://user-images.githubusercontent.com/9593772/125773639-8a1d7d1f-8c8c-4b6c-ab1f-ee000744e350.png)

Also, show in the list which template is the selected as default:

![imagen](https://user-images.githubusercontent.com/9593772/125774314-c33a1afe-1b79-4287-8048-eea4d53c0566.png)

**Comment by nadouani** [comment]
When creating your alert, you can set `caseTemplate` field with the name of the default template you want, so it will be set as default in the Alert preview dialog instead of `Empty case` option
