### ISSUE TITLE
[Feature Request] Add the ability to update type of observable

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#2125]
### Request Type

Feature Request

### Feature Description
The user should be able to change the ObservableType of an observable (if he has manageObservable permission).
The target observableType must be compatible with the original one (identical value of `isAttachment`).
The API could be:
```
PATCH /api/v1/observable/<observableId>
{ "dataType": "newDataType" }
```

**Comment by nadouani** [comment]
Reopened for UI implementation

**Comment by nadouani** [comment]
Added the capability in observable bulk update modal
<img width="1005" alt="Screenshot 2021-10-06 at 07 52 49" src="https://user-images.githubusercontent.com/21827/136147880-1eff305d-9f53-410f-8d15-0e0894238def.png">
