### ISSUE TITLE
[Question][TheHive4][Synapse][Ews2Case] Curl problem "Operation not permitted"

### ISSUE THREAD

**Issue by IzusaE** [TheHive-Project/TheHive#2128]
### Request Type

Hello,
I am currently installing thehive4, and more specifically Synapse and Ews2case.
Only I am currently experiencing a problem. 

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)           | Debian |
| OS version (client)        | Windows 10 |
| Virtualized  Env.          | True                   |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       |  2                  |
| TheHive version / git hash | 4      |
| Package Type               | Debian |
| Database                   | Cassandra               |
| Index type                 | Lucene            |
| Attachments storage        | Local             |
| Browser type & version     | Firefox                  |

### Question

When I run my curl 127.0.0.1:5000/ews2case command, I have a success: false (I do the command on my Debian server, which contain theHive)
In my logs I have the following:

 2021-07-19 16:07:32,714 :: INFO :: workflows.Ews2Case.connectEws commence
 2021-07-19 16:07:32,714 :: INFO :: common.common.getConf commence
 2021-07-19 16:07:32,725 :: INFO :: objets.EwsConnector.  getAccount démarre
 2021-07-19 16:07:32,727 :: INFO :: objects.EwsConnector.scan commence
 2021-07-19 16:07:33,855 :: INFO :: objects.TheHiveConnector.connect commence
 2021-07-19 16:07:34,168 :: INFO :: objects.TheHiveConnector.searchCaseByDescription commence
 2021-07-19 16:07:34,455 :: INFO :: objects.TheHiveConnector.craftCase commence
 2021-07-19 16:07:34,456 :: INFO :: objects.TheHiveConnector.createCase commence
 2021-07-19 16:07:34,652 :: ERREUR :: Échec de la création du dossier
 2021-07-19 16:07:34,653 :: ERREUR :: Échec de la création du dossier à partir d'un e-mail
 Traceback (appel le plus récent en dernier) :
   Fichier "/root/Synapse/workflows/Ews2Case.py", ligne 55, dans connectEws
     createdCase = theHiveConnector.createCase(case)
   Fichier "/root/Synapse/workflows/objects/TheHiveConnector.py", ligne 82, dans createCase
     augmenter ValueError(json.dumps(response.json(), indent=4, sort_keys=True))
 Erreur de valeur : {
     "message": "Opération non autorisée",
     "type": "AuthorizationError"
 } 

And I can't seem to solve this problem.
To explain a little more the manipulations I was able to perform, here they are:
I created, on my tenant office 365, an account (eba) which has inside the mailbox a folder named TheHive (as requested in the configurations) in this folder, I have various unread emails that I want to transfer to thehive.
This famous folder, during the right click > permissions, I gave everyone the rights to read, modify, write, etc. to be sure that the problem does not come from there. Only that does not solve anything. Does anyone have any idea how to fix my problem?
Thank you in advance and good day

**Comment by IzusaE** [comment]
I also just noticed that one of the three mails went up in synapse, although at no time did I have a "success: true", but even keeping the configuration identical, it does not go back to me my other emails....

**Comment by nadouani** [comment]
Hello, questions related to Synapse, need to be handled in Synapse's repo.

AFAIK, Synapse has not been tested with TheHive 4, and we don't have hard commitment on it.

**Comment by nadouani** [comment]
In the meantime, you can check TheHive logs to understand the Authorization error's cause.
