### ISSUE TITLE
[Bug] Can't bulk mark as read more than 30 alerts 

### ISSUE THREAD

**Issue by Zarkrosh** [TheHive-Project/TheHive#2131]
### Request Type
Bug

### Work Environment

Not relevant.

### Problem Description

I can't bulk mark as read more than certain number of alerts (between 31 and 100).

### Steps to Reproduce
1. Go to alerts list.
2. Select the option to show 30 alerts per page.
3. Select all alerts and click on the dropdown menu for bulk actions.
4. Check that 'Mark as read' option is listed.
5. Change the option to show 100 alerts per page.
6. Select all alerts and click on the dropdown menu for bulk actions (not really necessary, it auto updates).
7. Check that 'Mark as read' option is not listed now.

### Complementary information

![imagen](https://user-images.githubusercontent.com/9593772/126296909-967d77ca-6470-4327-b828-dbcf6da6e300.png)

![imagen](https://user-images.githubusercontent.com/9593772/126295706-6b2fede1-d37a-4547-901c-1c42c348984b.png)

**Comment by nadouani** [comment]
This means in your selection you have an alert already marked as read that's why the option is not there.

If you select 30+ unread alerts, then you will get the option.

**Comment by Zarkrosh** [comment]
Yes, i've just checked and you're right. Thanks!
