### ISSUE TITLE
[Question] How to actually add new custom field definitions in TheHive 4?

### ISSUE THREAD

**Issue by nickbabkin** [TheHive-Project/TheHive#2145]
### Question

Hi. We're using latest version of TheHive 4, and the only thing we haven't figured out so far (compared to version 3) is how to add new definitions for custom fields.

In TheHive 3, it used to be in right in the Organization management panel. In version 4, we only have management of custom tags:

![image](https://user-images.githubusercontent.com/52065542/126783856-b3f44483-a053-4cdc-819c-e6f3b7175466.png)

Is there a way to actually add custom field via UI in TheHive 4?
Documentation is unfortunately empty:
https://docs.thehive-project.org/thehive/user-guides/administration/custom-fields/

Thanks.

**Comment by nadouani** [comment]
Custom fields management is available for super admin accounts.
