### ISSUE TITLE
[Question] How to add superadmin in TheHive 4?

### ISSUE THREAD

**Issue by nickbabkin** [TheHive-Project/TheHive#2148]
### Question

Hi!
I recently posted a question about creation of new Custom Fields in TheHive 4, and it looks like only users with superadmin role can create those (ref: https://github.com/TheHive-Project/TheHive/issues/2145)

However, none of my users is currently superadmin (after migration from TheHive3). I don't know whether it's a bug or how things should be. Unfortunately, org admins can't create a superadmin user. 

Is there any way to create a new user and assign a superadmin role to him via CLI? I have root access to the host where TheHive is installed.

Thanks!

**Comment by nadouani** [comment]
TheHive 4 comes with a default super admin user: `admin` with password `secret`.

Please feel free to use the discord channel to have a better response time for your questions: chat.thehive-project.org
