### ISSUE TITLE
[Question] How can TheHive 4 be configured to accept self-signed certificates for SSO?

### ISSUE THREAD

**Issue by architect00** [TheHive-Project/TheHive#2151]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu 16.04   |
| OS version (client)        | MacOSX            |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 2                      |
| TheHive version / git hash | 4.1.9-1               |
| Package Type               | Docker |
| Database                   | Cassandra                 |
| Index type                 | Lucene                 |
| Attachments storage        | Local               |
| Browser type & version     | Chrome                        |

### Question

We configured SSO for TheHive 4.1.9-1. Configuration in `application.conf`:
```yml
auth {
   providers = [
       {name: session}
       {name: basic, realm: thehive}
       {name: key}
       {name: local}
       {
           name: oauth2
           clientId: "<clientid>"
           clientSecret: "<secret>"
           redirectUri: "https://myhive.local/thehive4/api/ssoLogin" # we use /thehive4 as subpath, also set in the configuration
           responseType: "code"
           grantType: "authorization_code"
           authorizationUrl: "https://gitlab.local/oauth/authorize"
           authorizationHeader: "token"
           tokenUrl: "https://gitlab.local/oauth/token"
           userUrl: "https://gitlab.local/api/v4/user"
           scope: ["openid", "profile", "email"]
           userIdField: "email"
           defaultOrganisation: "<default org>"
       }
   ]
# I tried to place WSconfig in this context with the self-signed root CA
}
```

Docker Logs of TheHive Container:
```
[info] o.t.s.AccessLogFilter [00000016|] <ip> GET /thehive4/api/ssoLogin took 11ms and returned 302 0 bytes
[info] o.t.s.AccessLogFilter [00000017|] <ip> GET /thehive4/api/ssoLogin?code=<code>&state=<state> took 418ms and returned 303 0 bytes
[info] o.t.s.AccessLogFilter [00000018|] <ip> GET /thehive4?error=OAuth2+token+verification+failure+PKIX+path+building+failed%3A+sun.security.provider.certpath.SunCertPathBuilderException%3A+unable+to+find+valid+certification+path+to+requested+target took 1ms and returned 308 0 bytes
[info] o.t.s.AccessLogFilter [00000019|] <ip> GET /thehive4/index.html took 4ms and returned 200 1191 bytes
[info] o.t.s.AccessLogFilter [0000001a|] <ip> GET /thehive4/api/v1/user/current took 4ms and returned 401 65 bytes
[info] o.t.s.AccessLogFilter [0000001b|] <ip> POST /thehive4/api/v1/query?name=list-taxonomies-cache took 4ms and returned 401 65 bytes
[info] o.t.s.AccessLogFilter [0000001c|] <ip> GET /thehive4/api/config/organisation?path=ui took 2ms and returned 401 65 bytes
```

The error `OAuth2+token+verification+failure+PKIX+path+building+failed%3A+sun.security.provider.certpath.SunCertPathBuilderException%3A+unable+to+find+valid+certification+path+to+requested+target` seems to indicate an certificate validation error. This might be caused by our self-signed certificates for TheHive and Gitlab.

**Observable Behavior**

In the browser the user gets redirected to Gitlab Sign-In page. After signing in the redirection to the `redirectionuri` happens. The user is still not logged in and the user is not created in TheHive.

The SSO does not work with Gitlab. It might be due to self-signed certificates. So my question is:

**How can the TheHive 4 be configured to accept self-signed certicates for SSO?**

**Comment by legoguy1000** [comment]
We use an internal CA and update the java keystore with the CA cert.

**Comment by architect00** [comment]
I'm not sure, if I need to change anything in the TheHive configuration to tell TheHive about the new keystore.

Can you elaborate on how you did solve this problem?

**Comment by legoguy1000** [comment]
Use the `keytool` tool to add the CA to the default java keystore located at `JAVA_HOME/jre/lib/security/cacerts`. The hive should use that without any other changes needed.

**Comment by architect00** [comment]
Alright that seemed to work. I used `keytool` to import my certs into `JAVA_HOME/jre/lib/security/cacerts`. 

BTW: The default password for the keystore is `changeit`, if somebody is wondering.

Thanks!
