### ISSUE TITLE
[Feature Request] Full text search in cases

### ISSUE THREAD

**Issue by fonk0rn** [TheHive-Project/TheHive#2152]
### Request Type

Feature Request

### Feature Description

Could you, please, add a possibility to run a full-text search in cases, like in 3.x version
![Screenshot 2021-07-28 094330](https://user-images.githubusercontent.com/52647968/127276896-0b83c807-3c9c-49b0-baac-8e6bffbf9034.jpg)

**Comment by fonk0rn** [comment]
Already in 4.2 milestones

**Comment by illumiN8i** [comment]
As a workaround for free text search, I was able to search the title and description fields using wildcard filters like any of: `*keyword*` Does this help?

**Comment by JamesCullum** [comment]
This is not working anymore in 4.1.7-1 apparently

**Comment by hkelley** [comment]
@JamesCullum raises an important issue, given the prevalence of dots in FQDNs, usernames, IPs, etc.   Even if I manually escape the dot, \.  , I still can't get the search to work.
