### ISSUE TITLE
Cannot add free text tag to case

### ISSUE THREAD

**Issue by hkelley** [TheHive-Project/TheHive#2176]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        |  Ubuntu |
| OS version (client)        |  10          |
| TheHive Version          |  4.1.2-1|
| Browser type & version     | Chrome                        |

### Problem Description
Cannot set a free text tag

### Steps to Reproduce
Open a case.
Type in a free text tag.  Observe that tag appears initially but is not actually saved to case.  
Wait a few seconds for red error box to appear.

![image](https://user-images.githubusercontent.com/8828244/130235900-a5ed661c-0e1a-4321-bc76-0ad63d7e67f4.png)

**Comment by nadouani** [comment]
Please upgrade your instance to latest one. You are 7 versions behind the lated one. This is for sure already fixed in latest release

**Comment by hkelley** [comment]
I still receive the error:
```

Scalligraph
0.1.0-SNAPSHOT
TheHive
4.1.9-1
Play
2.8.7

```
