### ISSUE TITLE
[Bug] Everything disappears after a container redeploy in Kubernetes

### ISSUE THREAD

**Issue by pogao** [TheHive-Project/TheHive#2180]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu |
| OS version (client)        | MacOS           |
| Virtualized  Env.          | False                          |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       | 4                        |
| TheHive version / git hash |4.1.9-1               |
| Package Type               | DEB |
| Database                   | Cassandra               |
| Index type                 | Lucene                |
| Attachments storage        | Local                  |
| Browser type & version     | N/A                        |

### Problem Description
We've created our own The Hive Docker image using Ubuntu Focal as the base and installing The Hive from the APT repository (stable release). When we first deploy, things work just fine - we can create organizations, users, roles, etc. without a problem. But, when we redeploy the app to our Kubernetes cluster (using the exact same tools when we first deploy and things work) we can't see anything - the `admin` org doesn't show, the users and roles don't show up, etc. Nothing shows up in the web interface but we still have data in the Cassandra database. If, for example, we try to create an organization called `test`, then redeploy the organization won't show up but we aren't able to recreate it because The Hive says it already exists.

I'm not using the official Docker images because it apparently doesn't offer The Hive 4.

### Steps to Reproduce
1. Create your own The Hive image.
1. Deploy to your Kubernetes cluster and verify that everything works just fine.
1. Redeploy and see that nothing will show up in the web interface, as described above.

### Complementary information
I've tried the following:
* Send a SIGTERM to The Hive's process when a SIGTERM is received by the container (sent from Kubernetes). No deal.
* Change the deployment strategy to `Recreate` so that the old container would be deleted before creating and starting a new one. Still didn't work.
* Debug logs don't show any errors that could indicate what is causing this problem.
* This problem doesn't happen when The Hive is running on a VM (I've tried installing and configuring the app, then stopped the instance and restarted it and everything just worked).

**Comment by jkb-s** [comment]
> I'm not using the official Docker images because it apparently doesn't offer The Hive 4. 

I think you missed this (docker image with TheHive v4):
https://hub.docker.com/r/thehiveproject/thehive4
![image](https://user-images.githubusercontent.com/80353249/130698527-9b5e84c1-627c-4fdf-89a3-2faf698bffa2.png)

`docker pull thehiveproject/thehive4:4.1.9-1`

Also take a look at docker compose examples: 
https://github.com/TheHive-Project/Docker-Templates/tree/main/docker
