### ISSUE TITLE
[Bug] Editing Someone Else's Dashboard

### ISSUE THREAD

**Issue by KRUXLEX** [TheHive-Project/TheHive#2212]
### Request Type
Bug

### Problem Description
Can't edit shared dashboard even I'm org admin. 
Dashboard was shared but another user or admin can't edit it. Imported dashboard have the same issue.
This bug is inside of dashboard where someone can set a layout.

### Steps to Reproduce
Go And Try

### Possible Solutions
Adding permission on interface?

**Comment by nadouani** [comment]
Considering this in 4.1.11

**Comment by To-om** [comment]
this duplicates #2190
