### ISSUE TITLE
[Question] Issue Populating the customField data when creating a case using the API

### ISSUE THREAD

**Issue by jfrank1120** [TheHive-Project/TheHive#2254]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu, |
| OS version (client)        | 10, |
| Virtualized  Env.          | False                          |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       |16                       |
| TheHive version / git hash | 4.x, hash of the commit               |
| Package Type               | RPM, DEB, Docker, Binary, From source |
| Database                   | Cassandra          |
| Index type                 | Lucene              |
| Attachments storage        | Local             |
| Browser type & version     | If applicable                         |

### Question

When attempting to create a new case using the API at the `/api/case` endpoint using the following code:
` json_data = {
            'title': 'test_file',
            'description': 'test_description',
            'customFields.case-number.string': 'test_case_number'
   }`
 the customField data is not sent over to the case when it is created and not added to the UI. I have created the correct customField from the admin account and am able to populate it using the UI from the account that I am creating the case from, but the data never seems to be correctly sent over. Any idea where this issue might be stemming from?

**Comment by urban-moniker** [comment]
Try this format, works for me for tagging alerts on creation:-

  "customFields": {
    "string-type": {
      "string": "my string"
    },
    "integer-type": {
      "integer": 1
    }

**Comment by jfrank1120** [comment]
That gives me the following error: 
`RETURNED CODE: <Response [400]>
{"type":"AttributeCheckingError"
"message":"[Invalid format for customFields: FAny(List(case-number))
 expected customFieldValue (customFieldValue)]"
"errors":[{"name":"customFields"
"format":"customFieldValue"
"acceptedInput":["customFieldValue"]
"field":"FAny(List(case-number))"
"type":"InvalidFormatAttributeError"}]}`

**Comment by urban-moniker** [comment]
I just tested on my test rig and using the below raw JSON I was able to update a custom field in an existing case (id 12345678) (HTTP PATCH to endpoint https://<thehive_server>/api/case/~12345678):-
```
{
  "customFields": {
    "xdr-incident-updates": {
      "integer": 10
    }
  }
}
```

**Comment by urban-moniker** [comment]
Here's a simple Case Create sent (POST) to https://<thehive_server>/api/case/  that works for me (note that this is raw JSON, I'm not using Python etc).  Also note the 'order' attribute, that's not documented anywhere and allows you to control the display order of the fields which is quite nice when you have multiple fields:-
 
```
{
  "title": "Test Case",
  "description": "Description",
  "customFields": {
    "alert-type": {
      "string": "a test string",
      "order": 0
    }
  }
}
```

**Comment by jfrank1120** [comment]
Ah I see. For my situation I am parsing files in order to create cases, thus I am using Python to send the POST requests which gives me the error that I commented [above](https://github.com/TheHive-Project/TheHive/issues/2254#issuecomment-976732794).

**Comment by urban-moniker** [comment]
I know you've closed, but as a FYI, I did some testing and found that if I passed a numeric string to a customField that was defined as a string type I got an error, probably because my client was automatically converting to an integer.  I had to 'hard define' the numeric string in quotes to make sure it was sent as a string, not an integer.
