### ISSUE TITLE
Roll over Log file

### ISSUE THREAD

**Issue by dewiestr** [TheHive-Project/TheHive#2258]
### Request Type

Feature Request

### Feature Description

Is it possible to have the log file roll over daily ? Operating in 1 massive log seems very inefficient.

**Comment by To-om** [comment]
The configuration of log is in /etc/thehive/logback.xml file. You can modify it by using TimeBasedRollingPolicy instead of FixedWindowRollingPolicy. You can see documentation of logback [here](http://logback.qos.ch/manual/appenders.html#TimeBasedRollingPolicy).
