### ISSUE TITLE
[Bug] Fix index creation and rebuild

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#2265]
### Request Type
Bug

### Problem Description
The index creation is not correctly rebuilt after a database restore. Only one index should be used (managed by Elasticsearch or Lucene). All composite indices should be removed. When the index is not available, TheHive should refuse to start (`db.janusgraph.dropAndRebuildIndexOnFailure: false`) or remove the index and rebuild a new one (`db.janusgraph.dropAndRebuildIndexOnFailure: true`)

**Comment by azgaviperr** [comment]
Hello, where should be set db.janusgraph.dropAndRebuildIndexOnFailure: true ? 

I added it to the application.conf. 

Got currently an index issue after ugrading to 3.15.1 (forgot to change :latest ^^)

**Comment by To-om** [comment]
@azgaviperr Hello, what is your issue ?

**Comment by azgaviperr** [comment]
I fixed my issue with the index from the upgrade (container was restarting before finishing reindex). 

However I am not sure where to setup db.janusgraph.dropAndRebuildIndexOnFailure: true

**Comment by To-om** [comment]
this settings should not be set to true in normal use, otherwise TheHive will remove index and rebuild it if the index engine is not ready yet at startup (can occur when using docker-compose for example). If should be set to true if you known that the index need to be rebuilt.

To answer you question, `db.janusgraph.dropAndRebuildIndexOnFailure` is the full path of the config. You can set it in root section in application.conf. Or you can set `dropAndRebuildIndexOnFailure` under `db.janusgraph` section:
```
db.janusgraph {
  storage {
    backend: cql
    // [...]
  }
  index.search {
    backend: lucene
    // [...]
  }

  dropAndRebuildIndexOnFailure: false
}
    
```

**Comment by azgaviperr** [comment]
Happy I did pretty much understand this ^^

![image](https://user-images.githubusercontent.com/7451354/145404117-a5f05980-29d1-4ff7-8ad2-24ef7dd4a06e.png)

Thanks for the info.
