### ISSUE TITLE
[Bug] TheHive 4.15 unable to create index in ElasticSearch

### ISSUE THREAD

**Issue by jpferrero** [TheHive-Project/TheHive#2283]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Centos 7   |
| Virtualized  Env.          | True                           |
| Dedicated RAM              | 8 x 3 GB                                 |
| vCPU                       | 8 x 3                        |
| TheHive version / git hash | 4.15               |
| Package Type               | RPM |
| Database                   | Cassandra                |
| Index type                 |  Elasticsearch                |
| Attachments storage        | HDFS                  |

### Problem Description

Since update to 4.15, TheHive fails to create index in ElasticSearch. Switching to Lucene works fine. If there is no index create in ElasticSearch, TheHive fails to start with the following error:

![Screen Shot 2021-12-13 at 16 10 09](https://user-images.githubusercontent.com/15837740/145837487-192386e3-0330-446d-83f0-a8dead6c690a.png)

Although changing log level to debug, there is no more details of the error.

Thank you,

**Comment by jpferrero** [comment]
Hello,

It's not a bug because in other TH instance we updated to 4.15 and the 'imported' filter works fine, so it's related to the update process. The current schema version is 99 and we reindex all the data again but the problem persists. Any suggestions on what we can look at?

Thanks

**Comment by jpferrero** [comment]
Some progress: the elasticsearch index doesn't contain some fields like 'caseId__String' or 'label__String'. These are all the fields of an alert:

![Screen Shot 2021-12-10 at 16 36 50](https://user-images.githubusercontent.com/15837740/145600325-61386fba-596e-426c-b7f7-07c87e0241c0.png)



When the filter 'imported' is set to 'No' the triggered query contains the field 'caseId__String' so that seems the reason why the filter doesn't work:

{\"match\":{\"caseId__STRING\":{\"query\":\"\",\"operator\":\"AND\",\"prefix_length\":0

Any clue why those fields are not created when reindexing de data? Cassandra DB seems ok in the latest version:

![Screen Shot 2021-12-10 at 16 34 50](https://user-images.githubusercontent.com/15837740/145599883-94eb27e8-7365-40d7-8f25-fc2068ed4e6b.png)

**Comment by dominiksr** [comment]
I had the same problem, you can work around it manually. All you need to do is to create an index named "xxxx_global" where "xxxx" is the name of your index that I specified in thehive configuration file. You can use rest api for this: "curl -XPUT 'localhost:9200/xxxx_global'"

**Comment by dominiksr** [comment]
Then I did a restart of thehive4 and in my case it started working normally.

**Comment by jpferrero** [comment]
Thank you, that seem to solve de issue partially... now there is another issue: the 'imported' filter in alerts doesn't work.

Digging a little bit, the mapping of the elasticsearch index differs from a new install. This is the mapping of an index created in a fresh install of thehive:

`{
  "thehivetest_global" : {
    "mappings" : {
      "properties" : {
        "_createdAt" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "_createdBy" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "_createdBy__STRING" : {
          "type" : "keyword"
        },
        "_label" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "_label__STRING" : {
          "type" : "keyword"
        },
        "_updatedAt" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "_updatedBy" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "_updatedBy__STRING" : {
          "type" : "keyword"
        },
        "action" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "action__STRING" : {
          "type" : "keyword"
        },
        "all" : {
          "type" : "text"
        },
        "assignee" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "assignee__STRING" : {
          "type" : "keyword"
        },
        "attachmentId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "attachmentId__STRING" : {
          "type" : "keyword"
        },
        "caseId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "caseId__STRING" : {
          "type" : "keyword"
        },
        "caseTemplate" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "caseTemplate__STRING" : {
          "type" : "keyword"
        },
        "colour" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "colour__STRING" : {
          "type" : "keyword"
        },
        "contentType" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "contentType__STRING" : {
          "type" : "keyword"
        },
        "data" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "dataType" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "dataType__STRING" : {
          "type" : "keyword"
        },
        "data__STRING" : {
          "type" : "keyword"
        },
        "date" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "description" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "dueDate" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "endDate" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "flag" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "follow" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "group" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "group__STRING" : {
          "type" : "keyword"
        },
        "hashes" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "hashes__STRING" : {
          "type" : "keyword"
        },
        "ignoreSimilarity" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "impactStatus" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "impactStatus__STRING" : {
          "type" : "keyword"
        },
        "ioc" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "lastSyncDate" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "login" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "login__STRING" : {
          "type" : "keyword"
        },
        "mainAction" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "message" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "name" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "name__STRING" : {
          "type" : "keyword"
        },
        "namespace" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "namespace__STRING" : {
          "type" : "keyword"
        },
        "number" : {
          "type" : "integer",
          "copy_to" : [
            "all"
          ]
        },
        "objectId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "objectId__STRING" : {
          "type" : "keyword"
        },
        "objectType" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "objectType__STRING" : {
          "type" : "keyword"
        },
        "order" : {
          "type" : "integer",
          "copy_to" : [
            "all"
          ]
        },
        "organisationId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "organisationId__STRING" : {
          "type" : "keyword"
        },
        "organisationIds" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "organisationIds__STRING" : {
          "type" : "keyword"
        },
        "pap" : {
          "type" : "integer",
          "copy_to" : [
            "all"
          ]
        },
        "predicate" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "predicate__STRING" : {
          "type" : "keyword"
        },
        "read" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "relatedId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "relatedId__STRING" : {
          "type" : "keyword"
        },
        "requestId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "requestId__STRING" : {
          "type" : "keyword"
        },
        "resolutionStatus" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "resolutionStatus__STRING" : {
          "type" : "keyword"
        },
        "severity" : {
          "type" : "integer",
          "copy_to" : [
            "all"
          ]
        },
        "sighted" : {
          "type" : "boolean",
          "copy_to" : [
            "all"
          ]
        },
        "size" : {
          "type" : "long",
          "copy_to" : [
            "all"
          ]
        },
        "source" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "sourceRef" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "sourceRef__STRING" : {
          "type" : "keyword"
        },
        "source__STRING" : {
          "type" : "keyword"
        },
        "startDate" : {
          "type" : "date",
          "copy_to" : [
            "all"
          ]
        },
        "status" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "status__STRING" : {
          "type" : "keyword"
        },
        "summary" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "tags" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "tags__STRING" : {
          "type" : "keyword"
        },
        "taskId" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "taskId__STRING" : {
          "type" : "keyword"
        },
        "title" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "title__STRING" : {
          "type" : "keyword"
        },
        "tlp" : {
          "type" : "integer",
          "copy_to" : [
            "all"
          ]
        },
        "type" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "type__STRING" : {
          "type" : "keyword"
        },
        "value" : {
          "type" : "text",
          "copy_to" : [
            "all"
          ],
          "fielddata" : true
        },
        "value__STRING" : {
          "type" : "keyword"
        }
      }
    }
  }`


And this is the mapping created with my current data in thehive:

`{
  "mappings": {
    "_doc": {
      "properties": {
        "_createdAt": {
          "type": "date"
        },
        "_createdBy": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "_label": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "_updatedAt": {
          "type": "date"
        },
        "_updatedBy": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "action": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "assignee": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "attachmentId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "caseId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "caseTemplate": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "colour": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "contentType": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "contentType__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "data": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "dataType": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "date": {
          "type": "date"
        },
        "description": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "endDate": {
          "type": "date"
        },
        "flag": {
          "type": "boolean"
        },
        "follow": {
          "type": "boolean"
        },
        "group": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "hashes": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "ignoreSimilarity": {
          "type": "boolean"
        },
        "impactStatus": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "ioc": {
          "type": "boolean"
        },
        "lastSyncDate": {
          "type": "date"
        },
        "login": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "login__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "mainAction": {
          "type": "boolean"
        },
        "message": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "name__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "namespace": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "namespace__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "number": {
          "type": "long"
        },
        "objectId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "objectType": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "order": {
          "type": "long"
        },
        "organisationId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "organisationIds": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "pap": {
          "type": "long"
        },
        "predicate": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "predicate__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "read": {
          "type": "boolean"
        },
        "relatedId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "requestId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "resolutionStatus": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "severity": {
          "type": "long"
        },
        "sighted": {
          "type": "boolean"
        },
        "size": {
          "type": "long"
        },
        "source": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "sourceRef": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "startDate": {
          "type": "date"
        },
        "status": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "summary": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "tags": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "taskId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "title": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "title__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "tlp": {
          "type": "long"
        },
        "type": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "value": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "value__STRING": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}`


Both mappings are created with the same version of thehive (4.15.1). Maybe upstream can shine some light on the subject?

**Comment by jpferrero** [comment]
I've finally solved the issue. The whole issue was related to the tombstone_failure_threshold parameter of cassandra. In my case, the number of tombstone records exceeded this threshold, so janus graph couldn't create the index correctly. I had to increase that parameter in cassandra.yaml file an compact the database (nodetool compact thehive). Then I start TheHive with 'db.janusgraph.forceDropAndRebuildIndex: true' and recreate automatically the index with the correct mapping.

I close this issue.

**Comment by dominiksr** [comment]
Maybe it's better not to close this bug?
"- tombstone_failure_threshold
The tombstone failure threshold is reached when 100.000 tombstones are scanned by a single query. In this case the query will be aborted, meaning data from the affected table can no longer be queried.
Those threshold settings can be changed, but be aware that if you increase them it can lead to nodes running out of memory."

I wonder if it is safe to change this parameter.

**Comment by dominiksr** [comment]
Have you checked if it survives a full system reboot?

**Comment by jpferrero** [comment]
Hi dominiksr,

I reboot the full cluster without any issue and increase the value of tombstone_failure_threshold without any issue. Be sure to have enough memory in the server because cassandra may require a little bit more. This helps me a lot:

https://medium.com/de-bijenkorf-techblog/experiences-with-tombstones-in-apache-cassandra-7302092e7423

**Comment by dominiksr** [comment]
Thanks for the information. I am afraid to change this parameter because of the information that it may cause problems. I will wait and maybe the new version of thehive will solve this problem without making any changes in configuration. Great that you had no problems even after rebooting your cluster :D
