### ISSUE TITLE
Migrate hive3 to 4, migrate SSL error. Requesting SSL bypass option

### ISSUE THREAD

**Issue by glwallum** [TheHive-Project/TheHive#2356]
### Request Type

Way to bypass SSL inspection with migrate

### Feature Description

Old elasticsearch instance uses only HTTPS with self signed cert. Get SSL error when using migrate

### Possible Solutions

Add SSL bypass option to migrate

### Complementary information

(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

**Comment by To-om** [comment]
see https://github.com/TheHive-Project/TheHive/issues/2342#issuecomment-1088455366
