### ISSUE TITLE
[Bug] Prevent custom field creation if it already exists

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#2367]
### Request Type
Bug

### Problem Description
It is possible to create several custom fields with the same name.
CustomField name should be unique, TheHive should prevent creation if it already exists.

**Comment by martinr103** [comment]
How exactly does it work for the 'Case merge' operation ?
When the two merged cases contain a custom field with the same name but different values -> what will happen in the resulting (merged) case ? 
Still 2 custom fields with same name but 2 different values ?
1 custom field with 2 values ("miltivalue") ?
Or will the merge operation fail ?
