### ISSUE TITLE
[TTPs] Tactic, Technique and Procedure APIs

### ISSUE THREAD

**Issue by weird-oecophylla** [TheHive-Project/TheHive#2376]
Is there any endpoint allowing requesting TTPs from cases in TheHive ?

The documention online is present but empty: [http://docs.thehive-project.org/thehive/api/ttp/](http://docs.thehive-project.org/thehive/api/ttp/)

Is this feature available or is still in the roadmap.

The aim would be for exporting ttps of any case to any other tool using the API.

**Comment by To-om** [comment]
you can use:
`GET /api/v1/pattern/case/$caseId` to retrieve patterns of a case
`GET /api/v1/pattern/$patternId` to retrieve a pattern
`DELETE /api/v1/pattern/$patternId` to delete a pattern

You can add a pattern to a case by creating a procedure
`POST /api/v1/procedure` (https://github.com/TheHive-Project/TheHive/blob/main/dto/src/main/scala/org/thp/thehive/dto/v1/Procedure.scala#L7-L12)
Other API are available [here](https://github.com/TheHive-Project/TheHive/blob/4.1.19/thehive/app/org/thp/thehive/controllers/v1/Router.scala#L171-L174)
