### ISSUE TITLE
[Bug] Admin user gets corrupted upon initial configuration

### ISSUE THREAD

**Issue by kesh-stripe** [TheHive-Project/TheHive#2399]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Official Dockerhub Image   |
| OS version (client)        | MacOS Chrome           |
| Virtualized  Env.          | True                         |
| Dedicated RAM              | 8 GB                                 |
| vCPU                       | 2                       |
| TheHive version / git hash | 4.1.20-1               |
| Package Type               | Docker |
| Database                   | Cassandra                 |
| Index type                 | Elasticsearch                |
| Attachments storage        | S3                  |
| Browser type & version     | Chrome Version 103.0.5060.53                   |

### Problem Description
The `admin@thehive.local` superadmin gets corrupted (in a bad state) during just about any initial configuration. I've tested this almost 10x over the past few days, and even simple initial configuration changes cause the admin user to get into a corrupted state.

When this happens:

- Admin dropdown is missing
- Username is listed as `no org/Default admin user` (sometimes it will show `***/Default admin user`)

![Screen Shot 2022-06-29 at 12 03 29 PM](https://user-images.githubusercontent.com/52877349/176734393-0267d1ab-d05b-4dde-a390-b769ea206eb0.png)
![Screen Shot 2022-06-28 at 9 55 53 AM](https://user-images.githubusercontent.com/52877349/176734413-b0d6ec6d-fbdf-4ff4-8dbf-e9bca3326af9.png)

Once this user is corrupted, there is no way to access the super admin configurations which is a huge issue if this was rolled to a production environment. 

### Steps to Reproduce
Method 1:

1. Log in as admin user
2. Create a new org + new user within that org
3. Log in as new user and create some test data
4. Log back in as admin user - find it corrupted.

Method 2:

1. Log in as admin user
2. Create custom fields (from TheHive 3)
3. Run the full migration script
4. Log back in as admin user - find it corrupted.

### Complementary information
TheHive application logs or ES logs do not expose anything about these issues.

**Comment by kesh-stripe** [comment]
Sure @To-om , thanks for taking a look at this!

> when the superadmin is corrupted, can you share the content of `http://x.x.x.x:9000/api/v1/user/current` when you are logged with admin?

```
{"_id":"~41136","_createdBy":"system@thehive.local","_createdAt":1656553575887,"login":"admin@thehive.local","name":"Default admin user","hasKey":false,"hasPassword":true,"hasMFA":false,"locked":false,"profile":"admin","permissions":[],"organisation":"no org","organisations":[],"extraData":{}}
```

**Comment by To-om** [comment]
Your user was removed from the admin organisation (I don't know why yet), so you can access admin actions.
Can you share :
 - the log file (/var/log/thehive/application.log in docker container)
 - how do you run the docker container (command line)
 - the configuration file
 - the authentication provider to use

**Comment by vdebergue** [comment]
Hello @kesh-stripe,

One more question for you:  Are you running a single instance or several TheHive instances ?

**Comment by kesh-stripe** [comment]
> Hello @kesh-stripe,
> 
> One more question for you: Are you running a single instance or several TheHive instances ?

Hi @vdebergue - i've tested this with both a single node, and a cluster of 2 nodes. The same bug happens in either deployment, often after a restart.

**Comment by kesh-stripe** [comment]
> Your user was removed from the admin organisation (I don't know why yet), so you can access admin actions. Can you share :
> 
> * the log file (/var/log/thehive/application.log in docker container)

https://gist.github.com/kesh-stripe/2e5fac78ff7080d998cec1371aa7c8b8

> * how do you run the docker container (command line)

```
exec /opt/thehive/entrypoint --no-config --config-file /etc/thehive/application.conf
```

> * the configuration file

```
# Secret Key
# The secret key is used to secure cryptographic functions.
# WARNING: If you deploy your application on several servers, make sure to use the same key.
play.http.secret.key=XXX

cluster {
  name = xxx
}

## Webhook notification
notification.webhook.endpoints = [
  {
    name: thehiveNotificationSrv
    url: "http://xxx:10080/thehive"
    version: 0
    wsConfig: {}
    auth: {type: "none"}
    includedTheHiveOrganisations: ["*"]
    excludedTheHiveOrganisations: []
  }
]

# Authentication
auth {
	provider = [local]
    defaultUserDomain = "stripe.com"
}

# Maximum time between two requests without requesting authentication
session {
  warning = 10h
  inactivity = 11h
}

# Max textual content length
play.http.parser.maxMemoryBuffer= 1M
# Max file size
play.http.parser.maxDiskBuffer = 1G

# Maximum time a stream request waits for new element. Must be
# shorter that intfe's nginx request timeout (1m) to avoid 504s
stream.longpolling.refresh = 30s

# https://blog.thehive-project.org/2020/12/23/xmas-release-thehive-4-0-3/
storage {
  provider: s3
  s3 {
    bucket = <bucket name>
    readTimeout = 1 minute
    writeTimeout = 1 minute
    chunkSize = 1 MB
    endpoint-url = "https://s3.us-west-2.amazonaws.com"
    #accessKey = "xxx"
    #secretKey = "xxx"
    region = "us-west-2"
  }
}

## Database Configuration
db {
  provider: janusgraph
  janusgraph {
    ## Storage configuration
    storage {
      backend: cql
      hostname: [<cassandra IPs dynamically added on deploy>]
      ## Cassandra authentication (if configured)
      username: thehive       # login to connect to database (if configured in Cassandra)
      password: xxx
      cql {
        cluster-name: thehive-cass-db       # cluster name
        keyspace: thehive           # name of the keyspace
        # local-datacenter: datacenter1   # name of the datacenter where TheHive runs (relevant only on multi datacenter setup)
        replication-factor: 3 # number of replica
        read-consistency-level: ONE
        write-consistency-level: ONE
      }
    }
    ## Index configuration
    index {
      search {
        backend : elasticsearch
        hostname : [<es IP address>]
        index-name : thehive
      }
    }
  }
}
```

> * the authentication provider to use

As seen in the config, we are only using local right now.

**Comment by kesh-stripe** [comment]
I found a simple way for us to replicate this bug:

1. Log in with default user
2. Change credentials
3. Cycle/restart container
4. New creds no longer work
5. Log in with default creds, find user is bad state.

**Comment by vdebergue** [comment]
Hi,
I tried to reproduce your issue locally but I wasn't able to see the same problem.
I tested with a two nodes cassandra cluster (3 nodes were not starting on my laptop) and 1 ES node. And the latest version of the docker image: https://hub.docker.com/r/thehiveproject/thehive4/tags

(One thing I noted is that you must use for the login `admin@thehive.local` otherwise it will try to add your domain)

From your logs, it's clear that there is an issue with the database:
- it tries to read a vertex containing an `ObservableType` as a `User`

This issue may come from: 
- cassandra : vertex are overwritten by an other application ?
- elasticsearch: the index reports wrong vertices, and when reading the properties in cassandra, the data is wrong (when querying the user, a vertex id is returned by the index. But the index is not in sync with the data in cassandra)

Could you try again by:
- deleting all indexes in elasticseach and keyspace in cassandra
- using a stronger consistency when talking to cassandra: `read-consistency-level` and `write-consistency-level` to `QUORUM`

**Comment by kesh-stripe** [comment]
Confirming setting the cassandra read/write consistency level `QUORUM` has resolved this bug. Thank you @vdebergue !
