### ISSUE TITLE
[Bug] Database initialisation has failed

### ISSUE THREAD

**Issue by ghost** [TheHive-Project/TheHive#2422]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu |
| OS version (client)         | Ubuntu |
| Virtualized  Env.             | False |
| Dedicated RAM              | 4 GB |
| vCPU                              | 4  |
| TheHive version              | 4.24.1 |
| Package Type                 | Docker |
| Database                        | Cassandra |
| Index type                       | Elasticsearch |
| Attachments storage       | Local |
| Browser type & version   | Chromium 90 |

### Problem Description
We have a backup from Cassandra and want to restore it in a new environment via docker containers. But after starting the TheHive container it won't start and failed in the database initialization phase. We use Cassandra 3.11.11 and ES 7.17.6

### Steps to Reproduce
1. building a backup according to the following link: http://docs.thehive-project.org/thehive/operations/backup-restore/
2. starting ES container in the new environment
3. starting Cassandra container in the new environment
4. restoring backup inside the Cassandra container according to the following link: http://docs.thehive-project.org/thehive/operations/backup-restore/
5. starting the TheHive container in the new environment

### Complementary information
In the old environment, we virtualized TheHive and it's working fine without problems. But we want to migrate to a new containerized environment and we use the same version of TheHive and Cassandra in the new environment. The Cassandra and ES containers have no error logs during initialization.
In the attached file you can see all the TheHive container logs during initialization:
[logs.txt](https://github.com/TheHive-Project/TheHive/files/9648034/logs.txt)

**Comment by Keroseno101** [comment]
Hi, the solution is very simple: your index does not have the right information about your database backup, wenn thehive starts and ask the index for data, the index comunicate with the database asking for the wrong information.

You should add a line at the end of application.conf
db.janusgraph.dropAndRebuildIndexOnFailure: true

After that, thehive restarting and all will be good.

**Comment by ghost** [comment]
Tnx a lot @Keroseno101 
The issue is fixed by your config
