### ISSUE TITLE
[Question] How to harvest chosen MITRE ATT&CK tactics from the TTPs tab case?

### ISSUE THREAD

**Issue by L3zahA11derson** [TheHive-Project/TheHive#2423]
Hello,

I'm struggling to harvest tactics from my TheHive cases (TTPs tab). I found that it's possible to get MITRE ATT&CK techniques with GET /api/v1/pattern/case/$caseId to retrieve patterns of a case. But in the result we have all the tactics related to a technique ID (Initial Access, Defense Evasion, Persistence, Privilege Escalation for T1078.001) and not the tactic specified on the TheHive TTPs tab (Initial Access only).

I found what I was looking for with this GET /api/v1/procedure/$procedureId request but where is the prodecudeId field? I can't find it anywhere on patterns/cases results with GET /api/v1/pattern/case/$caseId or GET /api/v1/case/caseId.

Thanks for you help

**Comment by cyberpescadito** [comment]
Hello,
As discussed together, the solution is to make POST request on /api/v1/query?name=case-procedures with a payload such as:
```
{"query":[{"_name":"getCase","idOrName":case_id},{"_name":"procedures"},{"_name":"sort","_fields":[{"occurDate":"desc"}]},{"_name":"page","from":0,"to":15,"extraData":["pattern","patternParent"]}]}
```
