### ISSUE TITLE
can't download thehive repository package. (https://deb.thehive-project.org) [Question]

### ISSUE THREAD

**Issue by rezaei99m** [TheHive-Project/TheHive#2437]
### Request Type
Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu |
| OS version (client)        | 22.04.1 LTS |
| Virtualized  Env.          | True |
| Dedicated RAM              | 16 GB |
| vCPU                       | 12 |
| TheHive version / git hash | 4.x package |
| Package Type               | DEB |
| Database                   | Cassandra |
| Index type                 | Lucene  |
| Attachments storage        | Local |
| Browser type & version     | chrome |

### Question

When I want to install "TheHive" from DEB repository I encountered error for downloading this [package](https://deb.thehive-project.org/). I will post further the logs and the commands I entered for downloading "TheHive".
I followed documentation provided in this [link](https://docs.thehive-project.org/thehive/installation-and-configuration/installation/step-by-step-guide/#stable-versions).

#### Commands and associated logs
``` bash
root@mahdi:~# echo 'deb https://deb.thehive-project.org/ release main' | sudo tee -a /etc/apt/sources.list.d/thehive-project.list
deb https://deb.thehive-project.org/ release main
root@mahdi:~# sudo apt-get update
Hit:1 http://ir.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://ir.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://ir.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://ir.archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:6 https://deb.thehive-project.org/ release InRelease
Ign:5 https://www.apache.org/dist/cassandra/debian 311x InRelease
Ign:6 https://deb.thehive-project.org/ release InRelease
Ign:5 https://www.apache.org/dist/cassandra/debian 311x InRelease
Ign:6 https://deb.thehive-project.org/ release InRelease
Ign:5 https://www.apache.org/dist/cassandra/debian 311x InRelease
Err:6 https://deb.thehive-project.org/ release InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 5.196.134.249 443]
Err:5 https://www.apache.org/dist/cassandra/debian 311x InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 151.101.2.132 443]
Reading package lists... Done
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/311x/InRelease  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 151.101.2.132 443]
W: Failed to fetch https://deb.thehive-project.org/dists/release/InRelease  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 5.196.134.249 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Keroseno101** [comment]
The problem is in your server, because you can not reach deb.thehive-project.org, but neither apache.org. 

You should find help in Linux forum, not here, because the problem is not related with TheHive. 

Anyway, I would recommend you to check your proxy configuration, your dns configuration and your firewall configuration. 

If you work for a company, they should have a proxy to reach internet, that means, you should create a variable HTTP_PROXY in /etc/environment , something like:
vi /etc/environment
HTTP_PROXY=http://myproxy.net:8080
export HTTP_PROXY=http://myproxy.net:8080
HTTPS_PROXY=https://myproxy.net:8080
export HTTPS_PROXY=https://myproxy.net:8080

Check your /etc/resolv.conf file to configure also your nameserver.

**Comment by rezaei99m** [comment]
Thank you very much @Keroseno101.
I just want to make sure that packages are exist in debian repositories.
You are right I have to set HTTP_PROXY in order to install TheHive.
