### ISSUE TITLE
Is it possible de set multiple Webhooks ?

### ISSUE THREAD

**Issue by ghost** [TheHive-Project/TheHive#2453]
### Question

Hello,
I would like to know if it was possible to set multiple webhooks in one the instance.

I am trying something like :
```
notification.webhook.endpoints = [
  {
    name: local
    url: "<webhook>"
    version: 0
    wsConfig: {}
    auth: {type:"none"}
    includedTheHiveOrganisations: ["<myOrg>"]
    excludedTheHiveOrganisations: []
  },
  {
    name: local2
    url: "<webhook2>"
    version: 0
    wsConfig: {}
    auth: {type:"none"}
    includedTheHiveOrganisations: ["<myOrg>"]
    excludedTheHiveOrganisations: []
  }
]
```

but it doesn't seem to be working. Is it normal ? Is this featured implemented in TheHive 4 ?

Thanks !

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu   |
| OS version (client)        | 10            |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 4                       |
| TheHive version / git hash | 4.1.24-1               |
| Package Type               | Docker |
| Database                   | BerlkelyDB                |
| Index type                 | Lucene                |
| Attachments storage        | Local                  |

**Comment by nickbabkin** [comment]
@GGZ78 your configuration looks correct, I have the same one as yours, and it works fine for me.
Suggest enabling debug log in thehive and checking what's going in.

**Comment by ghost** [comment]
Hi, just an update for those who will maybe one day get through the same issue.
To make it work, you have to enable notifications (as explained here : [https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/webhooks/#1-define-webhook-endpoints](https://docs.thehive-project.org/thehive/installation-and-configuration/configuration/webhooks/#1-define-webhook-endpoints)) for all your Webhooks at the same time, not 1 by 1, or it will only enable the last one. For example, to enable 3 Webhooks :
```
curl -XPUT -u<user>:<password> -H 'Content-type: application/json' http://<ip>:9000/api/config/organisation/notification -d '
{
  "value": [
    {
      "delegate": false,
      "trigger": { "name": "AnyEvent"},
      "notifier": { "name": "webhook", "endpoint": "<name1>" }
    },
    {
      "delegate": false,
      "trigger": { "name": "AnyEvent"},
      "notifier": { "name": "webhook", "endpoint": "<name2>" }
    },
    {
      "delegate": false,
      "trigger": { "name": "AnyEvent"},
      "notifier": { "name": "webhook", "endpoint": "<name3>" }
    }
  ]
}'
```

Hope it will help.
