### ISSUE TITLE
File upload when /tmp is full

### ISSUE THREAD

**Issue by ninSmith** [TheHive-Project/TheHive#321]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu
| OS version (client)       |  Seven
| TheHive version / git hash   | 2.13.1
| Package Type              |  Binary
| Browser type & version    | Chrome 60

### Problem Description
When uploading a file as observable, from UI or TheHive4py, **and** ```/tmp``` is full, an empty file is uploaded as observable. Moreover, the user is not informed that its file upload actually failed.

### Steps to Reproduce
1. Full ```/tmp```
1. upload a file as observable
1. The sha256 would then be ```e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855```

**Comment by saadkadhi** [comment]
Nice catch @ninSmith. @To-om and @nadouani will look into it.

**Comment by To-om** [comment]
I've create an issue in PlayFramework project: playframework/playframework#7936

**Comment by nadouani** [comment]
This issue will be fixed by a PlayFramework version upgrade
