### ISSUE TITLE
Cuckoo URL Analysis Failed

### ISSUE THREAD

**Issue by rstgermain** [TheHive-Project/TheHive#406]
### Request Type
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | Win 10, Ubuntu
| TheHive version / git hash   | 3.0.2
| Package Type              | RPM
| Browser type & version    | Chrome 62.0.3202.94

### Problem Description
When running a Cuckoo URL analysis I receive this error: "Unexpected Error: 'list' object has no attribute 'keys'". The URL is sent for analysis as I can see it completed within Cuckoo. However, TheHive states that the analyzer failed. Full output shown on the bottom. 

### Steps to Reproduce
Runthe Cuckoo URL analyzer against a URL Indicator

### Complementary information
{
  "errorMessage": "Unexpected Error: 'list' object has no attribute 'keys'",
  "input": {
    "dataType": "url",
    "config": {
      "url": "http://192.168.175.154:1337",
      "max_tlp": 1,
      "check_tlp": true,
      "service": "url_analysis"
    },
    "tlp": 1,
    "data": "http://cnn.com"
  },
  "success": false
}

**Comment by rstgermain** [comment]
Forgot to mention, I am running Cuckoo 2.0.3. Same error occurs with Fine analysis.

**Comment by ilyaglow** [comment]
I think it would be more helpful to you if you open this issue here: https://github.com/TheHive-Project/Cortex-Analyzers

**Comment by rstgermain** [comment]
Thx for suggestion. Opened: https://github.com/TheHive-Project/Cortex-Analyzers/issues/162
