### ISSUE TITLE
RSA NetWitness Suite

### ISSUE THREAD

**Issue by novitski** [TheHive-Project/TheHive#413]
Hello,

First i wanna thanks for this great job.

I have question about integration TheHive with RSA NetWitness Suite, there is any script or plugin developed for this SIEM ?

Or how can i use Thehive api for send alert from the RSA SIEM to theHive ?

Thanks

**Comment by saadkadhi** [comment]
Hi @novitski. Thank you for your feedback. This kind of question is better suited for a thread on [our user forum](https://groups.google.com/a/thehive-project.org/forum/#!forum/users). I will start answering it here though and close the issue once done. If my answer isn't clear enough, feel free to join our user forum and start a thread so we can continue the discussion over there.

I am not aware of any script or plugin (which we call an `alert feeder` in our world) developed for RSA NetWitness Suite. I am not familiar with that SIEM. So depending on its capabilities, you can use 3 ways to create an `alert feeder` for it:

- develop an app that ressembles [Splunk's](https://splunkbase.splunk.com/app/3642/);
- configure your SIEM to send alerts by email then create a Python script that can poll a mailbox for new emails from your SIEM, parse them, package them for TheHive then send them through; [TheHive4py](https://github.com/TheHive-Project/TheHive4py/). The Python script can also poll for new emails coming for different other sources (user phishing reports, IDS/IPS, ....)
- make your SIEM interact directly with TheHive's REST API to raise alerts upon the occurence of certain events or indirectly by calling a Python script (which uses TheHive4py).

Happy cooking and if you are feeling generous, you may want to contribute your `alert feeder` to the community.

Regards,
