### ISSUE TITLE
The-Hive

### ISSUE THREAD

**Issue by setushastri93** [TheHive-Project/TheHive#415]
I am not able to create users accept the admin account. the application.conf file is with default settings, please guide me where I need to do changes? Need help as soon as possible.

**Comment by 3c7** [comment]
You can find the documentation regarding user management [here](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/admin-guide.md#1-user-management).

**Comment by setushastri93** [comment]
thanks.. I checked that before, but some how i got the solution. thanks again
