### ISSUE TITLE
App Lables Translation

### ISSUE THREAD

**Issue by hanabadler** [TheHive-Project/TheHive#416]
Hi thehive group

its a feature request (unless there is an option and i missed it on the doc section)
is there a way to translate all labels to other language in the app? is there some property file for locales or the labels are coded?

Thanks
Hana

**Comment by nadouani** [comment]
Hello,

TheHive doesn't support I18n yet. So the answer is No.
What "labels" you would like to translate?

**Comment by hanabadler** [comment]
Hi
Labels are:
all menu's - "Waiting Taks", "open case", "alerts"....
anther example:"List of cases"
"Quick Filters" on dropdown.

these are examples.
it will be nice if  there will be  support for I18n
