### ISSUE TITLE
Case metrics sort 

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#418]
### Request Type
Bug/Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.3
| Package Type              | DEB

### Problem Description
In the admin-dialog "Case-metrics" the metrics are not ordered by any value.
Please order by title, value or any other field.
If possible a sort button would be helpfull :)

**Comment by nadouani** [comment]
We will add sort capabilities to custom fields admin page
