### ISSUE TITLE
Username adn password default

### ISSUE THREAD

**Issue by nice9uy** [TheHive-Project/TheHive#425]
Please help me...
What is username and pasword as default, i can't login in this case.

<a href="http://tinypic.com?ref=2m81o8w" target="_blank"><img src="http://i65.tinypic.com/2m81o8w.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by 3c7** [comment]
Hey @nice9uy, there's no default username or password. The credentials are created when creating the Elastic Search index. If you get no "Update Database" button when starting TheHive the first time, the connection to Elastic Search fails.

**Comment by nadouani** [comment]
Can you check the list of your thehive users on your elasticsearch index?

**Comment by saadkadhi** [comment]
@nice9uy I am going to close the issue for the time being. Feel free to ask for help if you'd like to clear the DB and restart from scratch on Gitter or our user forum.

**Comment by hackdefendr** [comment]
How can I force the index to be recreated?  I installed via the debian method, but no index was created.

**Comment by jeromeleonard** [comment]
As @saadkadhi  said, we recommend you to come on  [Gitter](https://gitter.im/TheHive-Project/TheHive) to ask for help as it is not clear if you have ES successfully installed and started or not, what version  you are running,  if you already created account and forgot them, if you want to restart from scratch ... We need more context information.

If you want **to erase all your database** you can run (**all existing data will be lost**): 

```
curl -XDELETE http://<ES_IP>:9200/the_hive_12
```

where <ES_IP> is your ElasticSearch server IP address.  It will successfully erase the existing DB only if ElasticSearch is started. After that, reload your browser and you should get the "Update Database" button and be asked to create your first account.
