### ISSUE TITLE
Assign Tasks to users from the Tasks tab

### ISSUE THREAD

**Issue by billmurrin** [TheHive-Project/TheHive#426]
### Request Type
Feature Request

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Linux
| OS version (client)       | Multiple
| TheHive version / git hash   | 3.0.3
| Package Type              | 
| Browser type & version    | 

### Problem Description
When working with Case Tasks, it is tedious to open each task to assign tasks to a user. It would be ideal to assign tasks to users from the main Tasks page. 

### Steps to Reproduce
1. Open Case
1. Click on Tasks Tab
1. Try to add Task to an Assignee from the Tasks page.

**Comment by nadouani** [comment]
Ok fair enough. Don't forget to use the default task owners feature, if you use case template and if you know who usually handles each task

**Comment by billmurrin** [comment]
The commit was merged, completed.
