### ISSUE TITLE
Outlook auto case creation code by using hive4py sample case code 

### ISSUE THREAD

**Issue by setushastri93** [TheHive-Project/TheHive#429]
Hi,

could u please guide me, how can I create case with latest email of outlook's.
I already used below code for that but still 

#Fetch the latest email
outlook = win32com.client.Dispatch("Outlook.Application").GetNameSpace("MAPI")
inbox = outlook.GetDefaultFolder(6)
messages = inbox.Items
msg = messages.GetLast()

but getting error:
AttributeError: module 'win32com' has no attribute 'client'
 
please let me know the solution, or else any other code for the same.

**Comment by nadouani** [comment]
Hello, sorry, this not an issue related to TheHive at all.

**Comment by setushastri93** [comment]
ok.. then next I have error as below
![image](https://user-images.githubusercontent.com/34764104/34972305-ad11dbbc-faa6-11e7-873e-b24f37093d65.png)
what to do for these?
