### ISSUE TITLE
Docker: Access to Elasticsearch - Index not created

### ISSUE THREAD

**Issue by weslambert** [TheHive-Project/TheHive#431]
### Request Type
Bug / Problem

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 14.04
| OS version (client)       | Ubuntu 14.04
| TheHive version / git hash   | Latest
| Package Type              | Docker
| Browser type & version    | Chromium

### Problem Description
The Hive is not appearing to configure Elasticsearch properly when running Docker image.
After running with Docker, navigating to http://localhost:9000 results in a prompt to login, instead of an option to configure the DB and specify creds.

### Steps to Reproduce
sudo docker run -d --name=thehive --network=elasticsearch_network -p 9000:9000 -v   /etc/thehive/application.conf:/etc/thehive/application.conf certbdf/thehive

### Complementary information
`docker logs -f thehive`, returns:

Using secret: [secret]
Using elasticsearch host: ["172.18.0.2:9300"]
[info] o.r.Reflections - Reflections took 554 ms to scan 5 urls, producing 115 keys and 1140 values 
[info] module - Loading model class models.AuditModel
[info] module - Loading model class org.elastic4play.services.AttachmentModel
[info] module - Loading model class models.CaseModel
[info] module - Loading model class org.elastic4play.services.DBListModel
[info] module - Loading model class models.TaskModel
[info] module - Loading model class models.DashboardModel
[info] module - Loading model class models.ArtifactModel
[info] module - Loading model class models.AlertModel
[info] module - Loading model class models.LogModel
[info] module - Loading model class models.CaseTemplateModel
[info] module - Loading model class connectors.cortex.models.JobModel
[info] module - Loading model class connectors.cortex.models.ReportTemplateModel
[info] module - Loading model class models.UserModel
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[warn] application - /etc/thehive/application.conf: 4: play.crypto.secret is deprecated, use play.http.secret.key instead
[info] o.e.p.PluginsService - no modules loaded
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[info] i.n.u.i.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[warn] application - /etc/thehive/application.conf: 31: auth.type is deprecated, use auth.provider instead
[info] play.api.Play - Application started (Prod)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000

`application.conf`:
    `# Elasticsearch 
    search {
      # Index name.
      index = the_hive
      # ElasticSearch cluster name.
      cluster = es_cluster_name
      # ElasticSearch instance address.
      host = ["elasticsearch:9300"] 
      # Scroll keepalive.
      keepalive = 1m
      # Scroll page size.
      pagesize = 50
    }

`elasticsearch` here is aliased through the Docker network command (works with other containers trying to access and is resolved by TheHive during inside docker logs output) and curl'ing elasticsearch:9200 works from inside container.

`/etc/elasticsearch/elasticsearch.yml`
    cluster.name: "es_cluster_name" 
    network.host: 0.0.0.0
    transport.host: 0.0.0.0
    script.inline: on

ES is also run as a Docker container, exposing ports 9200/9300 with -p port:port

Also, is the index name in `application.conf` an index that is to already be created, or is that one that TheHive will create?

Thanks,
Wes

**Comment by deltajuliet** [comment]
I am running into the same issue. I found it interesting that when using ES's 9300 port that following errors are being given:

java.io.IOException: Invalid string; unexpected character: 253 hex: fd
        at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:372)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.<init>(ThreadContext.java:362)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.<init>(ThreadContext.java:352)
        at org.elasticsearch.common.util.concurrent.ThreadContext.readHeaders(ThreadContext.java:186)
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1372)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)

**Comment by treed593** [comment]
Are you using docker-compose? Here is the docker-compose.yml file I have had working locally, I have not seen that error when using Docker though, I did run into that with other install methods when running TheHive behind a ReverseProxy

`version: "2"
services:
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch
    environment:
       - http.host=0.0.0.0
       - transport.host=0.0.0.0
       - xpack.security.enabled=false
       - cluster.name=hive
       - script.inline=true
       - thread_pool.index.queue_size=100000
       - thread_pool.search.queue_size=100000
       - thread_pool.bulk.queue_size=100000
    volumes:
       - /home/ubuntu/elastic:/usr/share/elasticsearch/data
    ports:
       - "0.0.0.0:9300:9300"
   cortex:
    image: certbdf/cortex:latest
    command: --no-config
    volumes:
      - /home/ubuntu/cortex/application.conf:/etc/cortex/application.conf:ro
      - /home/ubuntu/cortex/Cortex-Analyzers/analyzers:/opt/Cortex-Analyzers/analyzers:ro
    ports:
      - "0.0.0.0:9001:9001"
   thehive:
     image: certbdf/thehive:latest
     command: --no-config
     volumes:
      - /home/ubuntu/theHiveConf/application.conf:/etc/thehive/application.conf:ro
     depends_on:
      - elasticsearch
      - cortex
     ports:
      - "0.0.0.0:9000:9000"`

**Comment by weslambert** [comment]
@treed593 ,

Just to confirm, you don't need Cortex for TheHive to work, correct?  It seems like the only difference here is that I am using Elasticsearch 5.6.5 and not running with the `--no-config` option.

I am not using `docker-compose`, as I already have an Elasticsearch instance available (with http.host, transport.host set as the same values as in your `docker-compose.yml`), and only wish to run the TheHive for the moment.

Thanks,
Wes

**Comment by weslambert** [comment]
@deltajuliet,

I haven't had a chance to look back into this yet -- were you able to make any progress?

Thanks,
Wes

**Comment by To-om** [comment]
Hi @weslambert 

If TheHive doesn't ask you to migrate the data, it means that the index already exists in ElasticSearch. In this case, you can remove it using `curl -XDELETE http://<ES_IP>:9200/the_hive_12` (if you don't want to keep existing data).

Cortex is not required to use TheHive but without it, you can't analyze observables.

**Comment by To-om** [comment]
I close this issue. Feel free to reopen it if you still have problem.
