### ISSUE TITLE
Add metadata to MISP event when exporting case from TheHive

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/TheHive#433]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.0.3

### Problem Description
When exporting a case from TheHive to MISP, there is not much information about the source in the MISP event. Having a reference of the MISP/TheHive link somewhere would help tracking the activity across those two tools.

### Possible Solutions
I am seeing three potential solutions:
1. When updating or creating the MISP event, add an attribute of type "Internal reference/text" containing the case number (something like "theHive#:caseNumber") and/or of type "Internal reference/link" with the TheHive case URL.
2. When updating or creating the MISP event, store in the case the id or link to the MISP event (may be using a tag if only storing the id, like "misp:id=:mispId")
3. Combining both of the above altogether

**Comment by srilumpa** [comment]
Sorry, I haven't seen this is partially a duplicate of #368

**Comment by saadkadhi** [comment]
We'll track this one in #366.
