### ISSUE TITLE
Feature Request: Ability to bulk upload files as observables.

### ISSUE THREAD

**Issue by mrod42** [TheHive-Project/TheHive#435]
Feature Request

### Problem Description
When working in a case with multiple binaries which need to be added as observables, there is no mechanism to bulk upload those files.

### Request
The ability to bulk upload like binaries as observables to a case.

**Comment by saadkadhi** [comment]
Hi @mrod42 

This is a duplicate of #327.

**Comment by mrod42** [comment]
thanks! i guess i did not read carefuly enough when trying to avoid a dupe
request!
