### ISSUE TITLE
default password

### ISSUE THREAD

**Issue by jfucanada** [TheHive-Project/TheHive#437]
I just brought the hive up on docker environment. What's the default uid/password for Web UI?

**Comment by nadouani** [comment]
You should have been asked for during the first launch. When running TheHive for the first time, if the user db is empty, the UI asks you to create a first user.

If you didn't get this question from the UI, you have to drop your thehive index on ES database and start again.

**Comment by xxdesmus** [comment]
Same problem -- running the exact instructions from here https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#docker -- and there's no prompt to create a user, just a login prompt.

**Comment by Rolinh** [comment]
@xxdesmus If you plan to run Elasticsearch on Docker, then, as the message hints, you need to adjust `vm.max_map_count` on you host machine. You can do it with this command:
```
# sysctl -w vm.max_map_count=262144
```
To make sure the change is permanent, you should update `vm.max_map_count` setting in `/etc/sysctl.conf`.

If you're using a single Elasticsearch node, as is often the case with Elasticsearch, you probably also want this in your Elasticsearch configuration:
```
discovery.type: single-node
```

I hope this helps.

**Comment by xxdesmus** [comment]
Thanks! That worked, looks like ES failing is indeed what caused the initial user creation issue that was reported here.

**Comment by kp625544** [comment]
I m facing this issue even when I m using default docker compose file

**Comment by AndreC10002** [comment]
I wasn't asked to create credentials either and my Elasticsearch is working properly.
For those in that situation, the default credentials are admin : secret

**Comment by olowoade** [comment]
> I wasn't asked to create credentials either and my Elasticsearch is working properly. For those in that situation, the default credentials are admin : secret

hey i tried this andrew i am in the am postion and i was told to do admin@thehive.local : secret    ; that didnt work, i just tried yours too and that also didnt work
