### ISSUE TITLE
Artifacts reports are not merged when merging cases

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/TheHive#446]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.0.3
| Package Type              |  DEB

### Problem Description
When merging two cases, the artifacts of the newly created case do not have any previously generated reports.

### Steps to Reproduce
1. Execute at least one analyzer on an artifact
2. Merge the case of the artifact with some other case
3. The associated artifact in the new case does not have any report and it is necessary to run analyzers again

### Possible Solutions
When merging two artifacts, the `case_artifact_job` objects associated to both artifacts should be found from the database, copied and linked to the newly created artifact. Recreating the short reports for the artifacts should be done by using for each analyzer the most recent report.

**Comment by srilumpa** [comment]
Was this fix included in the 3.0.10 version? I still see the issue.

**Comment by To-om** [comment]
Yes, this issue should be fixed is 3.0.10. Do you see error message in logs (something like "Fail to create job under artifact ...") ?

**Comment by srilumpa** [comment]
Sorry to anwser this late.

No I don't find errors of any kind in my instance logs. The reports seems to be accessible: after merging two cases I can read the full list of long reports for one specific artifact if I open it. But the mini-reports on the artifacts list are not displayed.

**Comment by srilumpa** [comment]
Any news on this? Have you been able to reproduce the bug? Do you need me to open a new issue for this?
