### ISSUE TITLE
Ability to disable "New Case" -> "Empty case"

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#449]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.3
| Package Type              | DEB

### Problem Description
Possibility to disable "empty case" button in "New case" menu entry.
We want this to force our SOC to always use a template and fill out metrics etc.

**Comment by nadouani** [comment]
This has now made possible through the `UI Settings` admin section. Check the option to hide the Empty Case option from the case template selector.

<img width="1122" alt="screen shot 2019-02-21 at 00 22 06" src="https://user-images.githubusercontent.com/21827/53132120-07cc9200-356f-11e9-8587-efa16db1aafb.png">

and then

<img width="1123" alt="screen shot 2019-02-21 at 00 24 44" src="https://user-images.githubusercontent.com/21827/53132144-1fa41600-356f-11e9-8d64-819dd8b18022.png">
