### ISSUE TITLE
Feature Request - Offline instances

### ISSUE THREAD

**Issue by geekscrapy** [TheHive-Project/TheHive#451]
### Request Type
Feature Request

What options would there be for running an offline copy of this to log notes in the field, then to sync them back up to the main instance when back online?

**Comment by nadouani** [comment]
Hello, 

what do you mean by `an offline of this`? If you are talking about TheHive, then I would say it is not designed to be used offline (it'd be nice to define what do you mean by offline too).

Thanks

**Comment by nadouani** [comment]
A possible solution would be to support Case import/export and use a personal instance, then export the cases, and import them back to the main instance. 

But for now, the case import/export is not something we planned.

**Comment by geekscrapy** [comment]
I was really asking for a suggestion of how this could be done.

Using TheHive offline as in standing up a seperate instance for work on site where conectivity back to a 'master' Hive isn't available. Therefore, writeup, upload of files, IOCs could be saved in the 'offline' instance and imported back into the 'master' Hive when back in the office.

I presume it is currently feasible to create a script using the API to 'export' and then 'import/creat' those same cases in the 'master' Hive?

**Comment by nadouani** [comment]
Well, technically, everything is based on API everyone can use. So, yes, writing a script that can "copy" a case from an instance into another one could be a possible solution. You will just loose the data coming from computed fields like: case number, createdAt and createdBy stuff etc... (some generated fields).

So, the answer is YES: you can make the export/import using APIs.
