### ISSUE TITLE
Type is not used when generating alert id

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/TheHive#457]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.0.3-1
| Package Type              | DEB

### Problem Description
Documentation says that an alert is uniquely identified with the tuple (type ; source ; sourceRef) (https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/alert.md#create-an-alert). It seems that the type is ignored when generating the alert id.

### Steps to Reproduce
1. Create a dummy alert with the following parameters: `{"type":"test", source":"test", "sourceRef": "test", ...}` (the first alert will be created)
2. Try to create a new alert by changing only the type, it will fail saying that there is a conflict version as the document already exists and it will serve the previously created alert

**Comment by nadouani** [comment]
Nice fail :)

Well this once needs a migration to fix all the existing alerts, because the alert's ID is used to check to existence of an alert
