### ISSUE TITLE
More than 20 users prevents assignment in tasks

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#459]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.3
| Package Type              | DEB

### Problem Description
If you have more than 20 active users defined, the userlist gets invisible withhin case tasks window.
Webpage is to short.

**Comment by nadouani** [comment]
This is bad :) Thanks for the issue

**Comment by nadouani** [comment]
This is valid for all drop down lists that contain a dynamic list of data, for example: casse custom fields or metrics, case assignee etc...
