### ISSUE TITLE
"too many substreams open" on alerts

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#462]
### Request Type
Bug

### Work Environment
TheHive version < 3.0.4

### Problem Description
If there are too many cases similar to an alert (more than 100), an error "too many substreams open" occurs.

### Possible Solutions
This issue has been solved for case similarity with another case by make the threshold configurable (#280). This setting should also be used for alert similarity.

**Comment by lsoumille** [comment]
It seens that this bug is not fixed is version 3.0.9. When I want to open an alert with more than 100 similar cases, I'm getting the "too many substreans open" error. Even if I put a higher value in maxSimilarCases param like 10000, I'm facing this issue.

Thanks in advance for your help
