### ISSUE TITLE
API: How to list all cases?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive#465]
Hi *,

Question about the API: How to list all cases (to extract all caseId's)?
Based on the API documentation, it's a "GET" of "/api/case".
When I do this, only the last created case is returned. Any idea?

/x

**Comment by nadouani** [comment]
Hello,

you can call it like this:

```
curl -H 'Authorization: Bearer **YOUR_API_KEY**' 'http://localhost:9000/api/case?range=all'
```

the `range` parameter can be `all` or something like `0-100` to fetch the first 100 rows

**Comment by xme** [comment]
Thanks! Did I miss it in the documentation or it's not mentioned at all?

**Comment by nadouani** [comment]
The docs are still weak, it's not your fault :)

We will a major effort on the documentation, after Cortex 2 release

**Comment by kachun55** [comment]
Hi , just want to ask after to list all the case, is it possible to delete any cases while the storage is full?
