### ISSUE TITLE
No reports available for "domain" type

### ISSUE THREAD

**Issue by LetMeR00t** [TheHive-Project/TheHive#469]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | -
| OS version (client)       | Ubuntu 16.04
| TheHive version / git hash   | 3.0.4
| Package Type              | DEB
| Browser type & version    | Firefox - v58.0.1

### Problem Description
As you can see on the following screen shots, I have no report available for the given domain whereas I have some reports available when I click on it.
![capture du 2018-02-07 16-44-50](https://user-images.githubusercontent.com/10530375/35925894-2c35101c-0c27-11e8-9f71-bc1aa30b79fc.png)
![capture du 2018-02-07 16-45-10](https://user-images.githubusercontent.com/10530375/35925899-2f1a74f2-0c27-11e8-8790-c738457e9008.png)

**Comment by nadouani** [comment]
Do you have the complete screenshot of the observable details page?

**Comment by znb** [comment]
I have a similar issue except it's for all types rather than just domains. 
All the results are there, they're just not being surfaced in the main UI. 

OS: Ubuntu 16.04
Hive Version: 3.0.4

If you need any more information, please let me know.

**Comment by saadkadhi** [comment]
@znb @LetMeR00t we'll prioritize this. Please provide the complete screenshot of the observable details page as requested by @nadouani.

**Comment by robertnixon2003** [comment]
I am not see any report tags either after the upgrade to 3.0.4

**Comment by robertnixon2003** [comment]
![image](https://user-images.githubusercontent.com/20773170/35941782-71756628-0c21-11e8-8a68-4668c9676269.png)
![image](https://user-images.githubusercontent.com/20773170/35941811-8cb95944-0c21-11e8-8293-2e612cb3caae.png)

**Comment by znb** [comment]
@saadkadhi Not sure if it's related, but I'm seeing this error in my application.log file

https://gist.github.com/znb/db509c60f17832d9924033039270f702

Looks like I'm getting a 500 back from Elasticsearch.

**Comment by LetMeR00t** [comment]
![capture du 2018-02-08 08-57-36](https://user-images.githubusercontent.com/10530375/35961612-85420570-0cae-11e8-82ab-a5aa7af80bf8.png)
![capture du 2018-02-08 08-57-43](https://user-images.githubusercontent.com/10530375/35961613-856e63ea-0cae-11e8-9719-28a9df63992f.png)
Hope it will be sufficient :)

**Comment by garanews** [comment]
same issue here

**Comment by nadouani** [comment]
Question: do you see the mini reports on the observable details page?

**Comment by nadouani** [comment]
Well, this question is useless, the observable details page displays the same mini reports as the observables list. So it's the same issue, you should not see them in the details page.

This is a regression from #409

**Comment by garanews** [comment]
![immagine](https://user-images.githubusercontent.com/16938405/35962821-19d61312-0cb3-11e8-97b5-a814dd6b043d.png)
![immagine](https://user-images.githubusercontent.com/16938405/35962836-24ab0824-0cb3-11e8-86a4-8e53d73411d5.png)
![immagine](https://user-images.githubusercontent.com/16938405/35962846-2d452a46-0cb3-11e8-8128-ad9db4d26059.png)

**Comment by nadouani** [comment]
I know, the jobs are listed, but I can also see that the "mini reports" that are supposed to be displayed below the observable name, and above the "metadata" bloc, are not display, which is a bug coming from the same reason of the original issue.

**Comment by LetMeR00t** [comment]
![capture du 2018-02-08 09-36-50](https://user-images.githubusercontent.com/10530375/35963079-da349be2-0cb3-11e8-8ff8-ccefe493d6a0.png)
You mean this one ;)

This is an example before the update :)

**Comment by nadouani** [comment]
Yes :)

**Comment by To-om** [comment]
This issue is a regression introduced by #409. It is solved by Elastic4play 1.4.4 (TheHive-Project/elastic4play#49)

**Comment by tosto92** [comment]
After the last update I have the same behaviour on every Observable.
No reports in the observables tab but if I click the observables then I find the reports.
