### ISSUE TITLE
Cortex reports empty?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive#473]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | OSX
| TheHive version / git hash   | 3.0.1
| Package Type              | Docker
| Browser type & version    | Chrome

### Problem Description
Cortex reports are suddenly empty...
Connection with Cortex is ok, analyzers are executed, results available as coloured tags but when I click on one of them to display details, the report is empty...

### Steps to Reproduce
1. Select observable
2.Action -> Run Analyzers
3. Select one
4. Click on the results -> Window opens but no content?

**Comment by saadkadhi** [comment]
Hi @xme,  this might be related to #409. Can you update to 3.0.5 and tell us if this fixes your problems?  Thx.

**Comment by xme** [comment]
Upgraded my docker to 3.0.5 but the problem remains. Here is a screenshot that explains:
https://xfer.truesec.net/uRiUR/Screen%20Shot%202018-02-09%20at%2010.17.36.png
I'm not sure if it's coming from TheHive or Cortex...

**Comment by saadkadhi** [comment]
That's pretty unusual. I guess you have loaded all the corresponding report templates?

**Comment by xme** [comment]
Next time we meet, I owe you a beer... :)
I forgot to re-import templates after re-creating my container... Shame on me!

**Comment by nadouani** [comment]
This has already been fixed, and default report template is displayed if not custom template has been specified
