### ISSUE TITLE
Password Change possible if user logs in with LDAP

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#474]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.5
| Package Type              | DEB

### Problem Description
If the user logs in with LDAP credentials there is a checkbox for password change.
This is unexcpeted. Or is this PW change performed on the LDAP?

**Comment by nadouani** [comment]
This is a  password performed on the LDAP. This is not a bug.
