### ISSUE TITLE
Error during "Update Database" after inital login

### ISSUE THREAD

**Issue by nealkeating** [TheHive-Project/TheHive#475]
### Request Type
Bug 

### Work Environment
| Question                           | Answer
|----------------------------|--------------------
| OS version (server)            | CentOS, 7.4.1708 (Core)
| OS version (client)             | Windows 10
| TheHive version                | thehive-3.0.5-1
| Package Type                   | RPM
| Browser type & version    | Chrome 64.0.3282.140

### Problem Description
After finishing the install guide,  I went to http://172.1.1.1:9000 and got the login page. I entered the default credentials.  I was brought to a page with an orange box that states "TheHive needs to update its database" and a "Update Database" button (http://%domain%/index.html#/maintenance). I clicked the button but nothing appeared to happen. Reverted the snapshot and ran it again (with firebug running)  and noticed I was receiving a 400 Error response for the HTTP POST request "./api/maintenance/migrate" with the response body containing: '{"type":"IllegalArgument", "message":"Rejecting mapping update to [the_hive_13] as the final mapping would have more than 1 type: [dblist, data, case_artifact_job, caseTemplate, case_task, reportTemplate, case_task_log, alert, audit, case_artifact, user, dashboard, case]"}'. Tried several additional times with same result.  Same result on IE & Edge also.

 I pulled the logs and I am pretty sure the problem lies in these two lines, but I have no idea how to start fixing it. 

 _"Feb  8 21:39:36 ip-172-1-1-1 thehive: org.elasticsearch.transport.RemoteTransportException: [M72ZUh4][127.0.0.1:9300][indices:admin/create]
Feb 8 21:39:36 ip-172-1-1-1 thehive: Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [the_hive_13] as the final mapping would have more than 1 type: [dblist, data, case_artifact_job, caseTemplate, case_task, reportTemplate, case_task_log, alert, audit, case_artifact, user, dashboard, case]"_

### Steps to Reproduce
1.  I followed the RPM installation guide(/installation/rpm-guide.md)
2. Then followed the elastic search installation guide(/installation/elasticsearch-guide.md)
3. Then the configuration guide (/admin/configuration.md)
4. Take snapshot of Virtual Machine
5. Went to the Server on port 9000
6. Entered the default credentials admin@test.com/admin
7. Clicked the "Update Database" button
8. Encounter 400 Error on POST request

### Complementary information
Screenshot of Firebug:
![thehive_400error](https://user-images.githubusercontent.com/6666685/36055902-d8c42d34-0dcd-11e8-8789-518a1af2f471.PNG)

-----
Logs:

_Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-11 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - no modules loaded
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Create a new empty database
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 2
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 3
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 4
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 5
Feb  8 21:39:36 ip172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 6
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 7
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 8
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 9
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 10
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 11
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 12
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[37minfo#033[0m] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 13
Feb  8 21:39:36 ip-172-1-1-1 thehive: [#033[31merror#033[0m] o.e.s.MigrationSrv - Migration fail
Feb  8 21:39:36 ip-172-1-1-1 thehive: org.elasticsearch.transport.RemoteTransportException: [M72ZUh4][127.0.0.1:9300][indices:admin/create]
Feb  8 21:39:36 ip-172-1-1-1 thehive: Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [the_hive_13] as the final mapping would have more than 1 type: [dblist, data, case_artifact_job, caseTemplate, case_task, reportTemplate, case_task_log, alert, audit, case_artifact, user, dashboard, case]
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501)
Feb  8 21:39:36 172-1-1-1 thehive: at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353)
Feb  8 21:39:36 172-1-1-1 thehive: at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:277)
Feb  8 21:39:36172-1-1-1 thehive: at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:444)
Feb  8 21:39:36 172-1-1-1 thehive: at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
Feb  8 21:39:36 ip-172-1-1-11 thehive: [#033[37minfo#033[0m] o.e.ErrorHandler - POST /api/maintenance/migrate returned 400
Feb  8 21:39:36 ip-172-1-1-1 thehive: org.elasticsearch.transport.RemoteTransportException: [M72ZUh4][127.0.0.1:9300][indices:admin/create]
Feb  8 21:39:36 ip-172-1-1-1 thehive: Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [the_hive_13] as the final mapping would have more than 1 type: [dblist, data, case_artifact_job, caseTemplate, case_task, reportTemplate, case_task_log, alert, audit, case_artifact, user, dashboard, case]
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:277)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:444)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
Feb  8 21:39:36 ip-172-1-1-1 thehive: at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
Feb  8 21:39:36 172-1-1-1 thehive: at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)_

**Comment by To-om** [comment]
Hi,
You get this error because you use the wrong version of ElasticSearch (6.x). TheHive works only with ElasticSearch 5.x.

**Comment by nealkeating** [comment]
Thanks @To-om.  I changed the ElasticSearch to 5.6.5 and it is working fine now.  I appreciate the help.
