### ISSUE TITLE
Auto-refresh for Dashboards

### ISSUE THREAD

**Issue by cshanahan** [TheHive-Project/TheHive#476]
### Request Type
Feature Request

### Work Environment
| Question  | Answer
|---------------------------|--------------------
| OS version (server)  | Debian
| TheHive version  | 3.0.5
| Package Type  | DEB

### Problem Description
With the addition of an auto-refresh function on Dashboard pages, it would be easier for SOC/CERT managers and others to build a high-level dashboard that displays relevant information for security alerts and cases that refreshes automatically without user-interaction. You can find similar functionality in Kibana's Time Picker -- pictured below.

![image](https://user-images.githubusercontent.com/4239381/36075278-aa09f156-0f1a-11e8-9303-6aa163f52216.png)

**Comment by nadouani** [comment]
We will add the possibility to auto refresh a dashboard like above

![screen shot 2018-07-05 at 17 32 01](https://user-images.githubusercontent.com/21827/42332853-6678ab6e-8079-11e8-8b50-578ec835b752.png)
