### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by jcoignet** [TheHive-Project/TheHive#477]
# Search function not working

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04.3
| OS version (client)       | Windows 10
| TheHive version / git hash   | 3.0.5
| Package Type              | From source
| Browser type & version    | Firefox & Chrome

### Problem Description
The search function doesn't returns any results and throws a javascript error instead.

### Steps to Reproduce
Type anything in the search bar, press enter.

### Complementary information
Javascript error when searching :
Base64 is not defined
a.search@http://127.0.0.1:9000/scripts/scripts.0950ed7d.js:1:18930
fn@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js line 8 > Function:4:320
b@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:6:17435
e@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:9:1090
$eval@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:6:27590
$apply@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:6:27822
compile/</<@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:9:1140
dispatch@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:3:10990
add/q.handle@http://127.0.0.1:9000/scripts/vendor.6d2e1369.js:3:9034

**Comment by nadouani** [comment]
Hello, does a 

```
bower install
```

solve the issue?

**Comment by jcoignet** [comment]
Hello,
sadly it didn't

**Comment by nadouani** [comment]
@jcoignet Could you please ping me on Gitter?

https://gitter.im/TheHive-Project/TheHive

Thanks

**Comment by jcoignet** [comment]
Fixed with `bower install js-base64`. Thank you nadouani
