### ISSUE TITLE
Misp synchronization failed

### ISSUE THREAD

**Issue by kaustavbhattacharjee** [TheHive-Project/TheHive#479]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu, 
| OS version (client)       | 10,
| TheHive version / git hash   | 3.0.5
| Package Type              | training
| Browser type & version    | Chrome

### Problem Description
I am using the Hive Training VM with the following configuration

MISP user is given user role
Tags name is default "misp"
max date = 30 days
I have kept all the other config same as per the docs.
But still I am facing the following error (when checked from logs):

### Steps to Reproduce
1. download and install the hive training VM
2. change the conf file for linking it with MISP
3. Check the logs from /var/log/thehive/application.log

![36012432-145c9768-0d84-11e8-9815-52594a4ae3fa](https://user-images.githubusercontent.com/7832958/36121971-ce0a3206-106d-11e8-92d1-876d2c396f6b.png)

**Comment by nadouani** [comment]
> MISP user is given user role

The MISP user must have `sync` role

**Comment by kaustavbhattacharjee** [comment]
@saadkadhi  This is the MISP config part.
On deepdiving a little more, I found this error too:

![image](https://user-images.githubusercontent.com/7832958/36176159-b9df415c-1137-11e8-9fa6-1e5d1b3524db.png)

```
# MISP
# TheHive can connect to one or multiple MISP instances. Give each  MISP
# instance a name and specify the associated Authkey that must  be  used
# to poll events, the case template that should be used by default  when
# importing events as well as the tags that must be added to cases  upon
# import.

# Prior to configuring the integration with a MISP  instance,  you  must
# enable the MISP connector. This will allow you  to  import  events  to
# and/or export cases to the MISP instance(s).
play.modules.enabled += connectors.misp.MispConnector

misp {
  "MISP-SERVER-ID" {
    # URL of the MISP instance.
    url = "<url>"

    # Authentication key.
    key = "<key>"

    # Name of the case template in TheHive that shall be used to import
    # MISP events as cases by default.
    caseTemplate = "MISP_CASETEMPLATE"

    # Tags to add to each observable imported from an event available on
    # this instance.
     tags = ["frommisp"]

    # Truststore to use to validate the X.509 certificate  of  the  MISP
    # instance if the default truststore is not sufficient.

   ws.ssl.trustManager{
	stores =  [
    {
        type: "PEM"
        path: "/home/thehive/misp.local.pem"
	password: "<pass>"
   }
   ]
  }
  #  filters:
    max-attributes = 1000
    max-size = 1 MiB
    max-age = 30 days
  #exclusion{
   #   organisation = ["bad organisation", "other orga"]
    #  tags = ["tag1", "tag2"]
   # }
}
  # Interval between consecutive MISP event  imports  in  hours  (h)  or
  # minutes (m).
  interval = 5m
}
```

@nadouani I have changed the user role to sync. But it didn't help.
