### ISSUE TITLE
Whitelist of tags for MISP alerts

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/TheHive#481]
Feature Request

I would like a feature that whitelisted events that go to TheHive from MISP based on a tag or tags.

**Comment by saadkadhi** [comment]
Currently TheHive, starting from 3.0.4, implements a tag blacklist approach instead of a whitelist one as requested but a whiltelist approach can also be of great interest. What do you think @To-om?

**Comment by michaelschratt** [comment]
A whitelist would be much appreciated. The amount of MISP Events can be very overwhelming. We try to identify only relevant events and want to import those based on whitelist tags.

**Comment by saadkadhi** [comment]
@robertnixon2003 @michaelschratt we hear you. We will strive to implement in the next major version of TheHive (3.2).
