### ISSUE TITLE
Preserving Raw Log Evidence

### ISSUE THREAD

**Issue by doksu** [TheHive-Project/TheHive#483]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Red Hat Enterprise Linux 7
| OS version (client)       | N/A
| TheHive version / git hash   | 3.0.3
| Package Type              | N/A
| Browser type & version    | N/A

### Problem Description
The preservation of _raw_ log evidence (not from alerts) is important for legal reasons. Log events can be added as an observable, but the "value" field isn't designed for long and/or multiline values and automatically defangs the value. A log entry in a task could be used, however this is something of a work-flow workaround. One way to address this need might be to add a "raw" observable type that supports long multiline values that are not defanged?

**Comment by mpotgieter** [comment]
I understand the requirement to maintain raw logs, but I question whether the correct place to do this is in "attributes".  Putting long lines of text in the observable field will make searching less efficient, I guess one could then search but exclude "raw" observable types. I would say the logs should be maintained in the log management solution. 
Not saying this is a bad idea, just my thoughts.

**Comment by saadkadhi** [comment]
I second @mpotgieter. While the requirement makes sense, we won't implement a datatype for storing 'raw log' evidence as an observable per se. Since raw logs would need copy/paste anyway, I would suggest pasting them in a file (while proving to LE/auditors that they were not tampered with) or making an extract from the log management solution / source application / source device of the logs of interest and put them in a file which can be attached to a task log.

**Comment by saadkadhi** [comment]
I am going to close the issue but feel free to reopen it if you have complementary arguments that we should further consider.

**Comment by doksu** [comment]
Thanks for your feedback @mpotgieter and @saadkadhi. I agree regarding the issues around mechanics of implementation, but the raw events need to be in the case because the reports that are provided to third-parties require original event evidence. In addition, the way log management tools have retention implemented, many IR teams can't rely on them to retain evidence and so it has to be extracted. As you've mentioned, this could be done by copying the relevant events into a text file then attaching the file to a task, but this goes against the nature of incident response (relevant events are found one at a time over a typically significant period), necessitating the use of another interim tool. Furthermore, with such an approach individual events can't be viewed in relation to other items in the case (temporally speaking), nor can they be annotated to indicate their relevance to the case.
