### ISSUE TITLE
Description fields in case and/or observables does not support line breaks

### ISSUE THREAD

**Issue by jezkerwin** [TheHive-Project/TheHive#484]
### Request Type

Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | 10 
| TheHive version / git hash   | 3.03
| Package Type              | RPM
| Browser type & version    | Chrome 64

### Problem Description
When typing in the description field on either the case itself or the observable, entering a line break (Enter key) is shows the line break but when clicking 'preview' or saving the description it then shows it in one line.
Makes it rather hard to read.

### Steps to Reproduce
![2018-02-14 14_56_55-thehive](https://user-images.githubusercontent.com/1779665/36187174-75eae748-1197-11e8-8017-ee41662a41cf.png)
![2018-02-14 14_57_10-thehive](https://user-images.githubusercontent.com/1779665/36187175-761b8d44-1197-11e8-8fd0-ded61a1706a9.png)
![2018-02-14 14_57_22-thehive](https://user-images.githubusercontent.com/1779665/36187176-764d1332-1197-11e8-9225-229044d81b36.png)

**Comment by nadouani** [comment]
Hello, this is markdown, you need one of these:

- use two line breaks
- end your first line using 2 spaces + 1 line break

**Comment by jezkerwin** [comment]
Ahhh, okay, yeah still getting used to markdown.

Thanks.
