### ISSUE TITLE
Add sighted flag to API

### ISSUE THREAD

**Issue by ktneely** [TheHive-Project/TheHive#494]
# Add Sighted flag to API

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Version     | TheHive 3.x
| Component       | API

### RFE Description
Sightings were added with https://github.com/TheHive-Project/TheHive/issues/365.  These should have the capability to be toggled/updated via API.

**Comment by nadouani** [comment]
Hello,

this can already be updated by the update API, we probably didn't mention it on the API docs (will be re written soon).

That said, I'm not sure this field is supported by TheHive4Py
