### ISSUE TITLE
[Enhancement] Add start and close timestamps to tasks

### ISSUE THREAD

**Issue by WillieStevenson** [TheHive-Project/TheHive#498]
### Request Type: Enhancement

Thanks for the great work!

I would like to submit a PR that expands tasks to include two timestamps, startDate and closeDate (or related naming convention), so that, much like a full case, the time any given task is open can be tracked.  

Would this be a useful addition to the codebase?

**Comment by nadouani** [comment]
Hello,

there are a "startDate" and "endDate" attributes that represent what you are searching for.

Thanks
