### ISSUE TITLE
Debian REPO 404 Error

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/TheHive#500]
Err:18 https://dl.bintray.com/cert-bdf/debian any/main amd64 Packages
404 Not Found

Getting the error above on a fully patched Ubuntu 16 box. Any ideas?

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| Package Type              | DEB

**Comment by 3c7** [comment]
Related: https://github.com/TheHive-Project/TheHiveDocs/issues/36
Please download and install the deb-File manually. There went something wrong while publishing the file at bintray. It's being worked on.

**Comment by nadouani** [comment]
Guys, this is an known issue related to bintray where we host our packages. We are waiting for them to fix the problem :(

**Comment by To-om** [comment]
From JFrog support:

> We would like to update that our Dev-Team have also managed to reproduce this issue and they are working to resolve the issue.
We estimate that the solution for this issue will be delivered tomorrow.

**Comment by To-om** [comment]
The problem has just been solved.
