### ISSUE TITLE
Can't save case template in 3.0.6

### ISSUE THREAD

**Issue by rayschippers** [TheHive-Project/TheHive#502]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Docker image from Docker Hub
| OS version (client)       | Win10
| TheHive version / git hash   | 3.0.6
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
When updating case template you receive a popup that says: Templatectrl: undefined and in the application log you see:

```
3/5/2018 6:33:18 PM[info] o.e.ErrorHandler - PATCH /api/case/template/AWH1sxkFxQI0UIEc_0s7 returned 400
3/5/2018 6:33:18 PMorg.elastic4play.AttributeCheckingError: [Unknown attribute caseTemplate._version: {"type":"JsonInputValue","value":1}][Unknown attribute caseTemplate._id: {"type":"JsonInputValue","value":"AWH1sxkFxQI0UIEc_0s7"}][Unknown attribute caseTemplate._routing: {"type":"JsonInputValue","value":"AWH1sxkFxQI0UIEc_0s7"}][Unknown attribute caseTemplate._parent: {"type":"JsonInputValue","value":null}]
3/5/2018 6:33:18 PM	at org.elastic4play.services.FieldsSrv.$anonfun$parse$7(FieldsSrv.scala:30)
3/5/2018 6:33:18 PM	at org.scalactic.Bad.transform(Or.scala:1386)
3/5/2018 6:33:18 PM	at org.elastic4play.services.FieldsSrv.parse(FieldsSrv.scala:30)
3/5/2018 6:33:18 PM	at org.elastic4play.services.UpdateSrv.apply(UpdateSrv.scala:84)
3/5/2018 6:33:18 PM	at org.elastic4play.services.UpdateSrv.$anonfun$apply$1(UpdateSrv.scala:69)
3/5/2018 6:33:18 PM	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
3/5/2018 6:33:18 PM	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
3/5/2018 6:33:18 PM	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
3/5/2018 6:33:18 PM	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
3/5/2018 6:33:18 PM	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
```

### Steps to Reproduce
1. Install The Hive as per the docker instructions (it appear latest tag is a dev release, so documentation should probably not use that).
1. add a case template
1. Try and update the case template and then save it.

**Comment by rayschippers** [comment]
Reverted the docker image to 3.0.5 and the issue is not there, so appears to be new bug caused by 3.0.6

**Comment by saadkadhi** [comment]
@claptrapped this has been fixed. We will release 3.0.7 soonish (/cc @To-om and @nadouani).
