### ISSUE TITLE
PhishTank Cortex Tag is transparent

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/TheHive#535]
### Request Type

Bug

### Problem Description
Phishtank Cortex Tag is transparent

![image](https://user-images.githubusercontent.com/20773170/38563820-c7260644-3cab-11e8-8275-cd252663d046.png)

Had to drag over it to see it:

![image](https://user-images.githubusercontent.com/20773170/38563898-f81f539a-3cab-11e8-80db-6ac13677855a.png)

**Comment by nadouani** [comment]
Hello, what's the content of `summary` field of that job report in Cortex UI? Looks like the taxonomy has no `level`

**Comment by 3c7** [comment]
Problem:
```
if 'in_database' in raw and raw['in_database'] is True:
    ....
else:
    level = "unknown"
    value = "\"False\""
```

**Comment by nadouani** [comment]
Well, this needs to be fixed in both the analyzer and thehive (set a default color even if the level is unknown)
