### ISSUE TITLE
Start Task  - Button

### ISSUE THREAD

**Issue by neok0** [TheHive-Project/TheHive#540]
### Request Type
Feature Request

### Problem Description
As of now, a task within a case is automatically started when clicked. This leads to several unwanted behavior, if you e.g. just want to check the description of the task. 
Furthermore, it automatically assigns you the task which may break some workflow afterwards.

### Possible Solutions
Add a button to start this task within the task and make the task clickable without triggering the "Start" button. Therefore, you can easily brows the task without starting it.

**Comment by neok0** [comment]
any thoughts on this one?

**Comment by saadkadhi** [comment]
@neok0 I think it's a good feature request. Please go ahead and provide a PR and we'll gladly review your code for inclusion in an upcoming release. Thanks.
