### ISSUE TITLE
Could TheHive received events syslog and email?

### ISSUE THREAD

**Issue by santi10** [TheHive-Project/TheHive#545]
Hi,

I set docker pull certbdf/thehive-cortex. 

Can I sent via Syslog to TheHive? 

I have a source that I would send the events via syslog to TheHive, Thehive can show theses evets, is it true?

So , I want to chec via email too...is it possible too?

Regards
Santi

**Comment by nadouani** [comment]
Hello,

No, TheHive doesn't provide any native connector for Syslog nor Emails.

If you need to send alerts to TheHive, you have to write a middleware that reads Syslog or an email inbox, and call TheHive APIs to create Alerts.

**Comment by saadkadhi** [comment]
@santi10 for an example on how can this be done, get a look at [https://blog.rootshell.be/2018/02/05/feeding-thehive-emails/](https://blog.rootshell.be/2018/02/05/feeding-thehive-emails/).
