### ISSUE TITLE
Time Calculation for individual tasks

### ISSUE THREAD

**Issue by pottapitot** [TheHive-Project/TheHive#546]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Ubuntu
| OS version (client)       |  Seven, 10, 
| TheHive version    | 3.0.9
| Package Type              | DEB

### Problem Description

As of now we use 3 metrics - Detection, Investigation, Containment for statistics for management and internal use. Plan to further break it down in smaller components similar to Mandiant DRAIN metrics.

| Time              | Category
|---------------------------|--------------------
| Dwell       |  Detect
| Dwell       |  Review 
| Dwell    | Analyze
| Dwell           | Identify
| Dwell       |  Notify
| Containment       |  Collect 
| Containment    | Validate
| Containment              | React

As of now, we go to each task one by one and take the time taken by taking the difference between the task open and close time and add it to the below 3 metrics which we created

Detection Time
Investigation Time
Containment Time

These metrics helps us identify staffing is adequate, skillsets are satisfactory, tools are deployed properly

### Possible Solutions
It would be great if we could have the total time per task shown in the task tab itself when the task is closed (in minutes or hours). It would be faster to calculate. To identify what category each task belongs to, we are planning to placing the category name before the task name to help further.
eg. Containment: Block hash

**Comment by nadouani** [comment]
Ok, so a quick win here is to display the "EndTime - StartTime" for closed tasks right?

**Comment by pottapitot** [comment]
Yup. That would be it. On a similar note (if possible), is it doable to add a (CurrentTime - StartTime) for open tasks?
