### ISSUE TITLE
Sort related cases by related artifacts amount

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/TheHive#548]
# Sort related cases by related artifacts count

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.0.1
| Package Type              | DEB

### Problem Description
Currently, all related cases are sorted by creation date. It would be helpful to be able to sort this list by related artifacts amount.

For example, a phishing email case can be related to tens of other cases simply because of an email address. But among all those related cases, there is only one with same attachment (i.e. same filename and hash). Having this case on top of the list would save time and potentially reduce human errors.

It could also improved by taking in account that a related artifact is flagged as an IOC, either by giving more "weight" to the artifact when counting them or simply by adding a third sort based taking in account only the fact that the artifact is an IOC or not.

Having a dropdown list to select the kind of sort to be applied would be great.

**Comment by nadouani** [comment]
Are you talking about "Related cases" of a Case or of an Alert.

What page are you referring to?

**Comment by srilumpa** [comment]
I am talking about "related cases" of a case. The page is the "Related Cases" tab when opening a case details page.

![thehive_related_cases](https://user-images.githubusercontent.com/3243772/39520962-d4bf9974-4e0c-11e8-9a55-d8a24eaf6813.png)

**Comment by nadouani** [comment]
OK, so adding the sort capabilities to that list will save the issue
