### ISSUE TITLE
Support header variable authentication

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#554]
### Request Type
Feature

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.9
| Package Type              | DEB

### Problem Description
Currently authentication is only supported via Certificate, LDAP, AD and local.
This request is to support also header-variables as authentication mechanism.
This solves some inflexibilities e.g. related to certificate based authentication.

Authentication as MISP supports it, described here: https://github.com/MISP/MISP/issues/1620

**Comment by saadkadhi** [comment]
@sprungknoedl wrote in a separate FR now closed:

A mechanism to offload the authentication to a proxy server (like Apache, nginx) would help to leverage the existing authentication mechanisms that exits for these.

This is usually done by letting a trusted proxy server set a special header (e.g. X-Forwarded-User) and then trust that the proxy does the due dilligence.

Feature from other OSS that inspired this feature request:

[http://docs.grafana.org/tutorials/authproxy/](http://docs.grafana.org/tutorials/authproxy/)
[http://docs.graylog.org/en/2.4/pages/users_and_roles/external_auth.html#single-sign-on](http://docs.grafana.org/tutorials/authproxy/)

**Comment by crackytsi** [comment]
@To-om is it ok to close this fr?

**Comment by To-om** [comment]
yes, thanks
