### ISSUE TITLE
Question/Help:  Where do the case templates get stored?

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [TheHive-Project/TheHive#556]
### Request Type
Question/Help

### Work Environment

Docker deployment of TheHive, Cortex, Elastic

### Problem Description
Working on ensuring i have the proper configurations and setting in the config files and compose file.  Should the docker image go down, i want to ensure that 'case' templates are persistent across any docker images.

- Are they stored in elastic?  
- Or are they stored as a file in the structure of the image?
 - if so where?

**Comment by nadouani** [comment]
Case templates are stored on the Elasticsearch index as `caseTemplate` document type.

```
curl -XPOST 'http://localhost:9200/the_hive_13/caseTemplate/_search'
```

will list them
