### ISSUE TITLE
IOC analyzis automation [question]

### ISSUE THREAD

**Issue by franofcholet** [TheHive-Project/TheHive#561]
I have a script that creates cases with iocs in TheHive. TheHive is properly connected to Cortex.

I can display the iocs in TheHive and launch all the analyzers.

I would like to know whether it is possible to automatically launch the analyzers when an ioc is posted. So that I don't have to do it manually for each ioc.

**Comment by nadouani** [comment]
Hello, there is no option to run analysis automatically on IOC creation, but you can launch the analysis using the API for each IOC.
There are APIs to list the available analyzers.

Adding the automatic analysis is something we thought about but it's not yet planned on the roadmap

**Comment by franofcholet** [comment]
OK thanks that's perfect then !
