### ISSUE TITLE
Horizontal Scrolling and Word-Wrap options for Logs

### ISSUE THREAD

**Issue by Deastrom** [TheHive-Project/TheHive#573]
# Horizontal Scrolling and Word-Wrap options for Logs

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu - Docker
| OS version (client)       | Windows 10
| TheHive version / git hash   | 3.0.9
| Package Type              | Docker
| Browser type & version    | Chrome

### Problem Description
When entering in long logs, such as command results.  It gets formatted funny due to the word wrap or, if you do a table, and the table is sufficiently long, it runs off the screen without wordwrap.

### Steps to Reproduce
1. Create case
1. create task
1. create log with task
1. create fenced block for bash output
1. put in crazy long, but formatted'ish output from a command
1. save log...
1. create log with task
1. make a markdown table with a bunch of columns
1. save log...
1. ???
1. profit.

### Possible Solutions
Implement a horizontal scroll for logs and simply disable word wrapping for fenced code and tables.

### Complementary information
awesome product

**Comment by nadouani** [comment]
Hello,

is it possible to have a screenshot of this issue?

Thanks

**Comment by Deastrom** [comment]
![image](https://user-images.githubusercontent.com/26151340/39926829-08266a82-54f6-11e8-86a0-fbb88e876705.png)
All of the data in the screenshot is training data.

**Comment by Deastrom** [comment]
![image](https://user-images.githubusercontent.com/26151340/39926874-2dc22ede-54f6-11e8-8296-d6a77c9efdcf.png)
finally start seeing my scroll at 33% zoom out

**Comment by nadouani** [comment]
Ok, got it
