### ISSUE TITLE
Max Age Filter Not Working?

### ISSUE THREAD

**Issue by urban-moniker** [TheHive-Project/TheHive#577]
### Request Type

Bug

### Work Environment

Training VM

### Problem Description

I have deployed the training VM and a test version of MISP to test the integration.  To prevent a large number of events being pulled in I have applied a 7 day filter, but this seems to be ignored and all events in MISP are being ingested.

### Steps to Reproduce

Deploy new TheHive VM, enable MISP integration with max-age filter.  Tailing the logs shows this:-

![screenshot at 2018-05-13 19-09-33](https://user-images.githubusercontent.com/23149626/39970374-14a64cf8-56e2-11e8-920a-3e439788373a.png)

**Comment by saadkadhi** [comment]
Hi @urban-moniker. Do you confirm that you have MISP events that have been ingested which last publication date is > 7 days?

**Comment by urban-moniker** [comment]
I believe so - assuming I understand the import logic.  Here is an event in MISP that has not been updated since October 2014, but was pulled in as an alert.

I will say I've had a few other issues (Report Templates not importing, periodic crashes etc) so I may just need to build from scratch but I was trying to do some initial testing from the training VM being lazy!

![screenshot at 2018-05-19 00-44-04](https://user-images.githubusercontent.com/23149626/40262375-d1cfa534-5afe-11e8-8805-7fc1dcc26d9e.png)

**Comment by urban-moniker** [comment]
Confirmed - when building from installers there is no issue so this must be related to the training VM.
