### ISSUE TITLE
Rotate logs

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#579]
From TheHive-Project/Cortex#62

### Request Type
Enhancement

### Problem Description
Currently TheHive do not limit `application.log` file size, so it can became really huge, causing TheHive to freeze when no free space left.

### Possible Solutions
LogBack configuration file provided in TheHive package should contain a rotation of log file.

**Comment by pitrh** [comment]
Running TheHive 4.0.1-1 it appears that application.log is no longer rotated.

No changes made to the supplied logback.xml

How do I enable and/or debug the issue?
