### ISSUE TITLE
Merge case by ID brings red error message if not a number in textfield

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#583]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.0.9
| Package Type              | DEB

### Problem Description
I tried to merge a case by caseid, but this resulted in a strange red error message, if typed in text is not a number.

SearchSrv: failed to create query: { "query_string" : { "query" : "caseId:#5", "fields" : [ ], "use_dis_max" : true, "tie_breaker" : 0.0, "default_operator" : "or", "auto_generate_phrase_queries" : false, "max_determinized_states" : 10000, "enable_position_increments" : true, "fuzziness" : "AUTO", "fuzzy_prefix_length" : 0, "fuzzy_max_expansions" : 50, "phrase_slop" : 0, "escape" : false, "split_on_whitespace" : true, "boost" : 1.0 } }

**Comment by nadouani** [comment]
This is an issue similar to #584, fixed.
