### ISSUE TITLE
Observable type boxes doesn't line break on alert preview pane

### ISSUE THREAD

**Issue by mats-ch** [TheHive-Project/TheHive#593]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RHEL7
| OS version (client)       | RHEL7
| TheHive version / git hash   | 3.0.9
| Package Type              | RPM
| Browser type & version    | Chrome 66.0

### Problem Description
Alert preview pane:
Observable boxes doesn't float, so if you've got more than your display can present on one line you won't see all of them.

### Steps to Reproduce
1. Create an alert with lots of observable types (more than 15 on a 1920px wide display).
2. Open the alert preview pane.

### Possible Solutions
Add a float: left css entry for span on
 the oberservable type div class.

### Complementary information
![hive_cropped](https://user-images.githubusercontent.com/17121375/40615076-a17d7620-6285-11e8-9f3c-d936cc481a2a.png)

**Comment by saadkadhi** [comment]
### Possible Solutions
Collapse after a certain number of observable types and give the ability to expand as a list.
