### ISSUE TITLE
Allow exclusion of tags when filtering

### ISSUE THREAD

**Issue by itsnotapt** [TheHive-Project/TheHive#597]
### Request Type
Feature Request

We'd like to be able to create filters that exclude certain tags for alerts, for example in our instance we have a post process for suppressing.

![screenshot](https://user-images.githubusercontent.com/3096198/40845546-f0ed32aa-65ae-11e8-9297-5d4664ea9006.png)

One UX method I've seen for this is where you click the existing tag and it changes the colour and filters the tag with a "_not" query.

![screenshot2](https://user-images.githubusercontent.com/3096198/40845645-3f3ce4a0-65af-11e8-80e4-10e1c86b04a4.png)

**Comment by troal** [comment]
Any news on this Feature Request?
I would need such feature in order to filter out noisy servers alerts

**Comment by crackytsi** [comment]
With TheHive 4 this can be filtered :)
