### ISSUE TITLE
Authentication via Proxy Header

### ISSUE THREAD

**Issue by sprungknoedl** [TheHive-Project/TheHive#601]
# Authentication via Proxy Header
A mechanism to offload the authentication to a proxy server (like Apache, nginx) would help to leverage the existing authentication mechanisms that exits for these.

This is usually done by letting a trusted proxy server set a special header (e.g. `X-Forwarded-User`) and then trust that the proxy does the due dilligence.

Feature from other OSS that inspired this feature request:
* [http://docs.grafana.org/tutorials/authproxy/](http://docs.grafana.org/tutorials/authproxy/)
* [http://docs.graylog.org/en/2.4/pages/users_and_roles/external_auth.html#single-sign-on](http://docs.graylog.org/en/2.4/pages/users_and_roles/external_auth.html#single-sign-on)

### Request Type
Feature Request

**Comment by crackytsi** [comment]
Is this not the same as https://github.com/TheHive-Project/TheHive/issues/554 ?

**Comment by sprungknoedl** [comment]
Yes it is, sorry
(wrong search keywords)

**Comment by saadkadhi** [comment]
Will be tracked there then.
