### ISSUE TITLE
Is X-Pack enabled TLS for elasticsearch supported?

### ISSUE THREAD

**Issue by of13tch** [TheHive-Project/TheHive#611]
Feature Request

Is there support for TLS with X-Pack?

I've seen the latest X-Pack blog post which details x-pack user/password support (https://blog.thehive-project.org/2017/12/20/cerana-0-2-x-pack-auth-multi-source-dashboards/). However, it's not entirely clear from the post/docs if there is X-Pack enabled mutual TLS support for ES?

Thanks in advance!

**Comment by To-om** [comment]
This has been implemented by @srilumpa (cf. TheHive-Project/elastic4play#56) and will be included in the next release.
