### ISSUE TITLE
Removing a case through the API doesn't work

### ISSUE THREAD

**Issue by francoisihry** [TheHive-Project/TheHive#615]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.0.10
| Package Type              | Docker

### Problem Description
When I try to remove a case according to the documentation (https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/case.md) , it doesn't work.

### Steps to Reproduce
1.  create a case
2. `curl -X DELETE  -H 'Authorization: Bearer API_KEY' 'http://127.0.0.1:9000/api/case/CASE_ID'`
3. The case still exists

**Comment by To-om** [comment]
What is the HTTP response status code ?
Do you have any related logs ?

**Comment by mnmnc** [comment]
@francoisihry try `curl -X DELETE -H 'Authorization: Bearer API_KEY' 'http://127.0.0.1:9000/api/case/CASE_ID/force'` since that is exactly the call that the browser mades when you click on a `Remove` button.  
Notice the `StarWars`-like **Force** at the end or url.

**Comment by nadouani** [comment]
Didn't notice that the URL was missing the `/force` suffix. 

Thanks @mnmnc
