### ISSUE TITLE
Revamp the search section capabilities

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#620]
### Request Type
Feature Request

### Problem Description
In the current version, <3.1, the search capabilities provided by TheHive are limited to the free text search box located on the navigation bar, and to specific search forms by section (cases, observables, alerts).

The goal of this feature request is to create a global search page that uses the same filter forms used on dashboard creation dialogs.

![screen shot 2018-06-25 at 11 06 19](https://user-images.githubusercontent.com/21827/41841154-d8d8fa5c-7867-11e8-8837-2a12a06a52a7.png)

**Comment by nadouani** [comment]
Reopening the issue to fix the clickable dashboard donuts.

**Comment by crackytsi** [comment]
Really cool :)
Can searches be saved for reuse?

**Comment by nadouani** [comment]
> Can searches be saved for reuse?

Not for this version, but this can definitely be added in the future
