### ISSUE TITLE
Check Cortex authentication in status page

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/TheHive#625]
### Request Type
enhancement

### Work Environment
TheHive 3.0.x
Cortex 2.x

### Problem Description
If the key configured in TheHive to connect to Cortex is wrong, the "about" page says that the status is valid whereas TheHive can't use it.

### Possible Solutions
Add a new status "AUTH_ERROR" that indicates that network communication between TheHive and Cortex works but Cortex can't be used because the authentication key is invalid.

**Comment by saadkadhi** [comment]
@To-om @nadouani the status color should be `orange` (when multiple cortex instances are configured and at least one of them works perfectly) or `red` (when only one instance is configured and there is an `AUTH_ERROR`).
