### ISSUE TITLE
[Documentation] Permission Denied: Bad links

### ISSUE THREAD

**Issue by lliknart** [TheHive-Project/TheHive#629]
Hi,

In the installation guide, (http://thehive-doc.readthedocs.io/en/develop/installation/binary-guide.html)
some links redirect to .md file instead of .html file and we got the following answer:

**Permission Denied
You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.**

**Comment by nadouani** [comment]
Hello, this is not the documentation we promote, we never talked about this documentation. We will remove it.

Please refer to https://github.com/TheHive-Project/TheHiveDocs
