### ISSUE TITLE
Dashboards on Resolved cases are not correctly fetching all the data

### ISSUE THREAD

**Issue by norgalades** [TheHive-Project/TheHive#630]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04 LTS
| OS version (client)       | Windows 10 / Windows 8
| TheHive version / git hash   | 3.0.9 (issue reproduced also in TheHive QE version 3.0.10)
| Package Type              | Binary 
| Browser type & version    | Chrome 67.0.3396.99 (64-bit) and Firefox 61.0 (64-bit)

### Problem Description
Case statistics dashboard: Revolved cases by resolution 
Set period to Last 7 days  is not showing the Resolved cases even if they have been closed during the last 7 days (Current date 6 July, cases where closed the 3rd of July)

### Steps to Reproduce
Go to Dashboards
Go to Case statistics
Select Revolved cases by resolution
Set the period to last 7 days

### Complementary information
I've also tried to create other custom dashboards to display the number of Resolved cases during the last week (by using endDate value). It seems that the new closed cases are not fetched. 

![main_page](https://user-images.githubusercontent.com/30833739/42374193-ab26bfa0-8117-11e8-9fec-2eb727d0bc67.PNG)

![resolution_dashboard](https://user-images.githubusercontent.com/30833739/42374234-dc3e5c4c-8117-11e8-9d10-636d0ebd51b1.PNG)

**Comment by nadouani** [comment]
Hello, when did you open these closed cases? On the last 7 days? I guess before?

**Comment by norgalades** [comment]
They were opened before... So I guess that when I select 7 days it filters all the cases opened before 7 days. Got it. 

My issue is that I would like to have a dashboard that lists the number of cases closed during the last 7 days (even if they were opened before) and if I understood correctly the only way to see all of them is to set **All time** as period time (otherwise I risk to miss some old cases). 

Is there a better way to achieve this (in the same page I have other graphs that rely on the 7 days period) ?

**Comment by nadouani** [comment]
Hello,

the only way to make it is https://github.com/TheHive-Project/TheHive/issues/585 
we need to allow selecting the period criteria field

**Comment by norgalades** [comment]
Ok, got it. We can close the issue or mark as duplicate.

**Comment by nadouani** [comment]
Closing this issue, since the solution will be provided by #585
