### ISSUE TITLE
How do I export custom fields for cases?

### ISSUE THREAD

**Issue by infracritical** [TheHive-Project/TheHive#632]
I am new to this effort, and want to customize this for a custom historical incident repository for SCADA and industrial/process control systems.  I am not very good with Java (except when there's mocha cream in it).

I have used the training VM of TheHive, and so far, have enjoyed playing around with it.

I've created my custom fields that I will intend on using for this repository.  Now...*how* do I save off or export those fields without having to re-create them again, and again, and again...?

I saw some documentation about "curl -s blah, blah, blah..."; isn't there something that is easier than have a CLI syntax string a mile long???  Seriously???  

-rad

**Comment by nadouani** [comment]
`Seriously`, no :)

You can take a look to this tool: https://github.com/TheHive-Project/TheHive-Resources/tree/master/contrib/ManageConfig
