### ISSUE TITLE
Where do I customize the login screen?

### ISSUE THREAD

**Issue by infracritical** [TheHive-Project/TheHive#633]
Yes, I've seen that this was duped before, but whoever referred the case to the original case closed it off, and it really didn't say or show anything other than some text in bold.

Is this an RTFM issue, or do I need a seeing eye dog?

-rad

**Comment by nadouani** [comment]
Hello, TheHive doesn't have a built-in function to customize login page. So if you wanna do it, please go ahead, pull the sources and make the changes you want, and build the package you need.

What do you want to customize? The Look and feel? the Logo?
