### ISSUE TITLE
Custom fields in Alerts?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive#635]
### Request Type
Feature Request

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| TheHive version / git hash   | 3.0.9
| Package Type              | Docker
| Browser type & version    | n/a

### Problem Description
I would like to use custom fields within alerts (and populate them when the alert is created) via the API.
Is it possible? I can assign custom fields to case templates but how to populate them from the alert?
I'm a bit confused... Tx!

### Solution and tasks

- [x] Update the data model to add the `customFields` attribute to `Alert` doc type
- [x] Add the data migration code 
- [x] Update the Alert preview dialog to display the custom fields
- [ ] Update the case creation for alert to copy the custom fields into the case (c/o @To-om)

**Comment by nadouani** [comment]
Hello @xme 

Alerts currently don't have custom fields, but what you said is totally valid.
We will try to include this FR into 3.1.0 release.

Thanks

**Comment by xme** [comment]
Tx! Crossing fingers for a quick implementation ;-)
