### ISSUE TITLE
TheHive behind a reverse-proxy, timeouts?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive#636]
### Request Type
Bug? Config issue?

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | n/a
| TheHive version / git hash   | 3.0.9
| Package Type              | Docker
| Browser type & version    | n/a

### Problem Description
My instance is accessed via a reverse proxy (another docker container running Nginx). Sometimes, I've the following popup in TheHive:
<img width="342" alt="screen shot 2018-07-10 at 18 23 46" src="https://user-images.githubusercontent.com/480944/42523717-d54c1e06-846e-11e8-85a5-bd2732d7820d.png">
This is generated by Nginx but what could be the problem? I don't have performance issues with the server. I tried to debug this but no luck until now.

**Comment by ilyaglow** [comment]
Make sure you have `http2` in the listen directive and proper proxy timeouts are set.

Here's how `server` section could look like:
```nginx
server {
    listen 443 ssl http2 spdy;
    server_name thehive.com;

    location / {
        proxy_pass http://thehive/;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_connect_timeout   600;
	proxy_send_timeout      600;
	proxy_read_timeout      600;
	send_timeout		600;
    }
}
```

**Comment by nadouani** [comment]
@ilyaglow No need to have `http2` 
@xme you just need to set the proxy timeout, because of the long polling stream API. Let us know if the 'proxy_*` options of the sample above, is working.
