### ISSUE TITLE
Alert email when users are assigned

### ISSUE THREAD

**Issue by phildebav** [TheHive-Project/TheHive#637]
Alert email when users are assigned

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)        | Ubuntu 18-04 Desktop
| OS version (client)       | Win 7 64
| TheHive version / git hash   | 3.0.10

### Problem Description
We are testing TheHive and somebody asked me if it is possible, in any way, to alert users by email when they are assigned to a new task.

### Steps to Reproduce
1. Assign a new task to a user
2. The new task is assigned in the waiting tasks

**Comment by nadouani** [comment]
Hello,

theHive doesn't send email notification. You can achieve this by writing a middleware the listens to task assigning and sends the notifications you need.

We will open this issue if we plan to add built-in notification system.

**Comment by phildebav** [comment]
Thanks for your answer.

Philippe

**Comment by nadouani** [comment]
You can take a look to this repo as a good start for your middleware https://github.com/TheHive-Project/TheHiveHooks. This is a simple library that make consuming TheHive's webhooks an issue task
