### ISSUE TITLE
MISP-SERVER-ID - Unknown version (ERROR) in TheHive

### ISSUE THREAD

**Issue by SurajChennoju** [TheHive-Project/TheHive#638]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
(select Bug or Feature Request and **remove this part**)
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  CentOS
| OS version (client)       | 7
| TheHive version / git hash   | 3.0.10,, hash of the commit
| Browser type & version    | Chrome

### Problem Description
After Integrating TheHive and MISP I got this error
--Please find the attachment--

![hive](https://user-images.githubusercontent.com/31133189/42572010-4ed11908-8536-11e8-950f-d3c9c160760a.PNG)

**Comment by nadouani** [comment]
TheHive is not able to reach your MISP, so not able to get its version.

Please check your configuration

Thanks
