### ISSUE TITLE
TheHive - Cortex HTTPS API connection

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/TheHive#639]
Hi,
I have change cortex Docker 9001 to https from http. If I use http everything is working fine. 
If I change to https then TheHive -> Cortex connection does not work. From packet capture I have fatal error Certificate Unknown. 

For Cortex I create Self-signed cert with keytool. With keytool I also create TrustedStore.jks that I point to: theHive application.conf no luck and also in entrypoint 

bin/thehive -Dconfig.file=/opt/thehive/application.conf -Djavax.net.ssl.trustStore=/opt/thehive/myTrustStore.jts -Djavax.net.ssl.trustStorePassword="mysupersekritpassword"

What is the correct way and what’s the correct place to configure TrustStore so that TheHive can connect to cortex that’s listening on HTTPS inside Docker?

Thank you.

**Comment by Idriel** [comment]
I also have warn in logs
[info] c.c.s.CortexClient - new Cortex(cortex1, https://XXX.XXX.XXX.XXX:9001) authentication: connectors.cortex.services.CortexAuthentication$Key
[warn] p.a.l.w.a.AhcLoggerFactory$$xxxx$1 - validateStoreContainsPrivateKeys: No private key found for alias xxxxxxxxx, it cannot be used for client authentication
[warn] p.a.l.w.a.AhcLoggerFactory$$xxxx$1 - Client authentication is not possible as there are no private keys found in Some(/etc/thehive/truststore.jks)

**Comment by billmurrin** [comment]
If TheHive is going to be your client for Cortex, you need to define a Keystore for TheHive side that contains a private key. You have a truststore defined that has the Cortex self-signed cert, however, TheHive is initiating the connection to Cortex, not the other way around. So your Truststore on the Cortex side should have your public key from your certificate for TheHive.

You can expand on what you have for runtime arguments:
```
bin/thehive -Dconfig.file=/opt/thehive/application.conf -Djavax.net.ssl.trustStore=/opt/thehive/myTrustStore.jks -Djavax.net.ssl.trustStorePassword="mysupersekritpassword" Djavax.net.ssl.keyStore=/opt/thehive/myKeyStore.jks -Djavax.net.ssl.keyStorePassword="mysupersekritpassword"
```

You can test the connection in curl as well to ensure at least that the SSL side is setup correctly.
```
curl -k -E /path/to/cert --key /path/to/key -H "Authentication: Bearer API_KEY_GOES_HERE" https://cortex:9001/api/user/ADMIN_USER_NAME
```

**Comment by Idriel** [comment]
sudo curl -k -H "Authentication: Bearer PASTED__REVEALED_API_KEY_OF_apiuser" https://172.19.0.2:9001/api/user/apiuser
{"type":"AuthenticationError","message":"Authentication failure"}[11:32:38] [SERVER:/data/thehive/thehivedata]

sudo curl -k -E thehivesignedcert2.pem --key thehiveselfsigned.key -H "Authentication: Bearer PASTED__REVEALED_API_KEY_OF_apiuser" https://172.19.0.2:9001/api/user/apiuser
{"type":"AuthenticationError","message":"Authentication failure"}

**Comment by Idriel** [comment]
Hi, 
Just to inform that this was solved in configuration part of Cortex.ws.ssl where I create pointer to Root PEM file.
This Java call is for SSL to AD.
