### ISSUE TITLE
Session does not expire correctly

### ISSUE THREAD

**Issue by norgalades** [TheHive-Project/TheHive#640]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Windows 10, Windows 7
| TheHive version / git hash   | 3.0.9 and 3.0.10
| Package Type              | Binary
| Browser type & version    | Chrome Version 67.0.3396.99 (64-bit)

### Problem Description
After the session expires, the login page is shown. By just clicking on the **go back** arrow of the browser (to go on the previous page) you are able to get the page **without** inserting again the credentials. 

### Steps to Reproduce
1. Open TheHive and login
2. Wait fot some time without doing anything till the login page is prompted to you.
3. Instead of inserting the credentials, click on the Previous page arrow
4. You will be able to access again the platform even if you did not insert your credentials.

**Comment by norgalades** [comment]
In order to be sure about that, I have flushed the browser cache and tried again. I'm able to browse all the cases, see the new created ones etc... So it seems that even if I do not insert my credentials I can access everything.

**Comment by To-om** [comment]
I've identified the problem. I confirm the bug. It will be fixed in the next release.
