### ISSUE TITLE
Attachments with character "#" in the filename are wrongly proceesed

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#645]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven,
| TheHive version / git hash   | 3.0.10
| Package Type              | DEB
| Browser type & version    | Firefox, Chrome

### Problem Description
When I attache a file with the chracter "#" in the filename, during download it is trying to downliad a the filename replacing # with -. The contents is valid and complete, but the extension also disappears.

### Possible Solutions
Prevent this filename or if there is a solution handle it correct.

**Comment by To-om** [comment]
It occurs because `#` character is not correctly encoded.
@nadouani can you urlencode file name before send it to backend ?
