### ISSUE TITLE
Thehive proxy settings in application.conf

### ISSUE THREAD

**Issue by stacsirt** [TheHive-Project/TheHive#646]
Bug?

| OS version (server)       | Debian
| OS version (client)       | OS-X
| TheHive version / git hash   | 3.0.10
| Package Type              | DEB

We are trying to connect our Hive to a MISP instance. We have to do this through a proxy on the local network. The application.conf file has the following;

# HTTP client configuration, more details in section 8
    ws {
    proxy {http://valid_proxy:port}
    }

But we still get an error in the logs:

2018-07-24 13:27:58,957 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-7 - Synchronize MISP MISP-valid from Some(Thu Jan 01 01:00:00 GMT 1970) 
2018-07-24 13:28:00,073 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-3 - Misp synchronization failed 
java.net.ConnectException: Network is unreachable: misp.valid/IP:443

Which looks like the proxy isn't being picked up? We have tried other combinations of proxy configs in application.conf - but to no avail.

Anything we can try / supply to help look into this?

**Comment by To-om** [comment]
At TheHive startup, MISP configuration is written to log. It looks like:
```
2018-07-11 16:46:04,805 [INFO] from connectors.misp.MispConnection in play-dev-mode-akka.actor.default-dispatcher-7 - Add MISP connection local
  url:              http://192.168.56.101
  proxy:            None
  case template:    <not set>
  artifact tags:    
  filters:
    max age:        <not set>
    max attributes: <not set>
    max size:       <not set>
    excluded orgs:  
    excluded tags:  
```
Can you check values in your log file are valid ?

**Comment by stacsirt** [comment]
Interesting - thank you - I've checked and no, the proxy entry isn't there:

proxy:            None

(everything else looks correct)

Have I got the application.conf syntax wrong?

**Comment by To-om** [comment]
Where did you put the `ws` section ? Under `misp` section or under the misp server section ? It could be easier if you paste your complete misp configuration (anonymized of course).

**Comment by stacsirt** [comment]
This is the MISP configuration section of thehive application.conf:

misp {
  "MISP" {
    # URL of the MISP instance.
    url = "https://valid-misp-url"

    # Authentication key.
    key = "valid-key"

    # Name of the case template in TheHive that shall be used to import
    # MISP events as cases by default.
    caseTemplate = "MISP_Template"

    # Tags to add to each observable imported from an event available on
    # this instance.
    tags = ["misp"]

   # HTTP client configuration, more details in section 8
       ws {
         proxy {http://valid-proxy:port}
           }

**Comment by To-om** [comment]
According to the [documentation](https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#proxy) you should write:
```
[...]
  ws {
    proxy {
      host = <valid-proxy>
      port = <port>
    }
  }
```

**Comment by stacsirt** [comment]
Thank you, that works :-) . I got the example from;

https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md

Which is slightly different. I'll close this one (user issue)
