### ISSUE TITLE
Certificate based login does not work

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#647]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.1
| Package Type              | DEB
| Browser type & version    | Chrome, Internet Explorer

### Problem Description
I'm trying to get certificate based authentication to work. I thought I did all the steps as described in the document https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/certauth.md but it seems that TheHive even does not request certificates from my workstation (other wise I would be requested to type in the PIN of the smartcard certificate. )
 I only see this error message:

`
2018-07-24 10:10:02,025 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-8 - Authentication failure: session: AuthenticationError User session not found pki: AuthenticationError Certificate doesn't contain user information key: AuthenticationError Authentication header not found basic: AuthenticationError Authentication header not found init: AuthenticationError Use of initial user is forbidden because users exist in database`

**Comment by To-om** [comment]
Hi @crackytsi 
Can you execute the command `openssl s_client -connect 127.0.0.1:443` (replace IP and port with appropriate values) ?
You should see a section about client certificate (either `Acceptable client certificate CA names` or `No client certificate CA names sent`).
In the first case, check that your client certificate is issued by one of the listed CA. In the second case, it probably means a configuration error.

**Comment by crackytsi** [comment]
Result is:

...
No client certificate CA names sent
...

**Comment by To-om** [comment]
In log you should see `Client certificate authentication is ...`. Can you check that it is enable ?

**Comment by crackytsi** [comment]
no, it is not enabled...

**Comment by crackytsi** [comment]
does I have to mention "auth { Provider =[pki,ldap,local]" or something?

**Comment by To-om** [comment]
Client certificate authentication is enable if and only if `auth.method.pki` is true (cf. [ClientAuthSSLEngineProvider.scala:73](https://github.com/TheHive-Project/elastic4play/blob/develop/app/org/elastic4play/ClientAuthSSLEngineProvider.scala#L73))
Possible error can be: 1) TheHive read the wrong configuration file 2) value `auth.method.pki` is overwritten by another value 3) TheHive or Elastic4play is not up to date.

**Comment by crackytsi** [comment]
1) There is only one application.* file (application.conf) in /etc/thehive/ no other "readable" file. The start-script uses /etc/thehive/application.conf (Standard by the Debian package)

2. I renamed the "auth {Provider= ..." section to something gauth to ensure it is not used. Than I added "auth.method.pki = true" at first and at last line, nothing changed

3. TheHive Version is 3.0.10 installed from your Standard Debian package, I have no clue how to find out the Elastic4play Version.

**Comment by To-om** [comment]
This feature works only from TheHive 3.1.0. It was included in previous version of TheHive in beta and doesn't work as expected.
The issue description says "TheHive 3.1"

**Comment by crackytsi** [comment]
Sorry my fault. Thank you :)

**Comment by To-om** [comment]
no problem :)
