### ISSUE TITLE
Default value of custom fields are not saved

### ISSUE THREAD

**Issue by ivityc** [TheHive-Project/TheHive#649]
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)        |  Ubuntu 16.04, ...
| OS version (client)         |  Seven
| TheHive version            | 3.0.10  
| Package Type                |  DEB
| Browser type & version    | Chrome  67.0.3396.99

TheHive3.0.10
Elastic4Play1.4.6
Play2.6.7
Elastic4s5.6.0
ElasticSearch5.6.2
CORTEX
CORTEX-SERVER-ID - 2.0.4 (OK)

### Problem Description
We have a Case Template with 16 custom fields. 
Some of them are pre-populated with default values.
trying to add a default value to some  of the existing fields (currently not populated) we can correctly perform such action, save it, the notification of the save action appears and it confirm that the save has been done.
Refreshing the page and opening again the case template, the previously addedd default values are no longer present. (This occurs editing a single field or more than one at time) 
the problem is occurring only on boolean fields and only if the choosen value is = false.
choosing ''true'' the field is properly saved and visible while reopening the template.
while ''false'' value disappear.

### Steps to Reproduce
step 1 Open an existing  case template (in our case the problematic one has 16 custom fields)
step 2 add a default value for one or more boolean custom fields using ''false'' as value
step 3 save the template
step 4 reopen the case template and check if the populated value is still there

### Possible Solutions
none

**Comment by nadouani** [comment]
The `false` value is in fact wrongly saved
