### ISSUE TITLE
Tag Coloring 

### ISSUE THREAD

**Issue by cyberladysj** [TheHive-Project/TheHive#650]
### Request Type
Feature Request

### Problem Description
Case and observables tags have the same color highlighting which makes it hard to pick out similar tags in the list of cases or observables visually.

### Possible Solutions
Apply different highlighting colors for each tag in a list of cases or observables (similar to how it is done in MISP).

**Comment by s-knauer** [comment]
I would also love to have different colors for Tags, so you could for example have one color for attack techniques, one for the source (which is displayed in the alarm section but not in the case section) and so on.

**Comment by nadouani** [comment]
This feature request is part of TheHive 4.1 through the MISP taxonomies and free tags support
