### ISSUE TITLE
Display drop-down for custom fields sorted alphabetically

### ISSUE THREAD

**Issue by derDuffy** [TheHive-Project/TheHive#653]
### Request Type
Feature Request

### Complementary information
After a case is created there is the ability to still add additional custom fields via the plus sign on the top right corner. Once that is clicked you get a drop-down displaying all possible custom fields which have been configured for the instance of theHive.

If you have a lot of custom fields finding the right one is often difficult, especially since they seem to be randomly sorted. 

There are two possible solutions in my opinion.

1) As mentioned in the title of this request, simply display them sorted alphabetically
2) Make them searchable / jump to the letters typed.

**Comment by nadouani** [comment]
Hello, this will also be fixed for metrics
