### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by RANGERBEE** [TheHive-Project/TheHive#659]
Hello,

  Any dockerfile available to build from repo files?  The current docker compose pulls latest image, though not sure it includes the latest commits of fixes and enhancements.

Thank you!

**Comment by To-om** [comment]
Hi,
Have a look at #117 

Dockerfile is generated from information in [docker.sbt](https://github.com/TheHive-Project/TheHive/blob/master/docker.sbt) and looks like:
```
FROM openjdk:latest
LABEL MAINTAINER="TheHive Project <support@thehive-project.org>"
WORKDIR /opt/thehive
ADD opt /opt
ADD var /var
ADD etc /etc
RUN ["chown", "-R", "daemon:root", "/var/log/thehive"]
RUN ["chmod", "+x", "/opt/thehive/bin/thehive", "/opt/thehive/entrypoint"]
RUN ["chown", "-R", "daemon:root", "."]
EXPOSE 9000
USER daemon
ENTRYPOINT ["/opt/thehive/entrypoint"]
CMD []
```
