### ISSUE TITLE
Merge alerts to Cases where there are no common observables.

### ISSUE THREAD

**Issue by mpotgieter** [TheHive-Project/TheHive#665]
### Request Type - Feature Request

When previewing alerts, it is useful to merge alerts into existing cases. The option to do this is available when 1 or more observables in the alert match any case. At times the alert may be related to a case but not share any observables. In such cases the alert needs to first be imported as a separate case and then the case merged with the desired case.

It would be useful to have the ability to merge alerts into cases regardless of any common observables existing. I suggest the alert preview page has a "merge to case" button which then prompts for a case number or title and allows merging based on the search results. This is similar to how the merging of cases works.

**Comment by nadouani** [comment]
This has already been fixed by #271
