### ISSUE TITLE
Support for filtering Tags by prefix (using asterisk, % or something) in search dialog

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#666]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC1
| Package Type              | DEB

### Description
We want to filter on tags based on a prefix, e.g. WebZone* or WebZone%
So we want to see all results that contain Tags, have a starting text with WebZone.
Adding more and more tags for very similar actions makes operating to time-consuming.

**Comment by nadouani** [comment]
This will be introduced in 3.3.0-RC6 for testing. If it's ok we keep it
