### ISSUE TITLE
question: pre load observables / case templates

### ISSUE THREAD

**Issue by RANGERBEE** [TheHive-Project/TheHive#677]
Is there a way to pre-load my custom observables list and case templates?

**Comment by To-om** [comment]
What do you mean by "pre-load" ?

**Comment by RANGERBEE** [comment]
I mean;  Perhaps::

When docker-compose spins up the containers to perhaps mount a static file on host that then is mounted by the docker container for my "observables" as well as my "case templates".

It hurts to rebuild the containers and hand jam my 90 observables and 12 case files.  ;-)

Simply point me in the right direction, I can hammer out the rest....

thank you!

**Comment by nadouani** [comment]
Hello @RANGERBEE 

I've discussed that with @To-om and you look like you want to start a TheHive instance with a predefined configuration (case template, observable datatypes etc...)

There are two ways here:

1. Create a script that calls TheHive APIs to insert/create the configuration you need
2. Prepare an Elasticsearch index that contains that configuration data, and restore it when you want a new TheHive instance.

I'd vote for (1)

**Comment by RANGERBEE** [comment]
Thanks guys.
