### ISSUE TITLE
Remember task list configuration (grouped/list)

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#681]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC1
| Package Type              | DEB

### Description
If the tasks are shown in "Group mode" the Group is mentioned 2 times:
Once for a section, and for each task.

To save time space and make the dialoge more intuitive usable, the group column should not occour.

I also would prefere if TheHive remembers my configuration (Show as List or Show Groups) or shows groups by default.

**Comment by nadouani** [comment]
The "Group" columns allows editing the task group.

Yes, saving the config is something we will do

**Comment by crackytsi** [comment]
I got it. Makes sense :)
