### ISSUE TITLE
Sorting custom fields.

### ISSUE THREAD

**Issue by Dominator-3000** [TheHive-Project/TheHive#682]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version | 3.0.10

### Problem Description
Is it possible to structure custom fields in additional information (in Case)? I hoped that sorting is possible when creating a case template, but fields still unsorted?

-----

![screen1](https://user-images.githubusercontent.com/41053409/44472383-b5013480-a636-11e8-9d0b-0700a131efa2.PNG)

-----

![screen2](https://user-images.githubusercontent.com/41053409/44472389-ba5e7f00-a636-11e8-99b3-626045894367.PNG)

**Comment by nadouani** [comment]
This looks like a bug, we will check it. It should be ordered based on the order set on the case template

**Comment by crackytsi** [comment]
metrics are also unsorted... https://github.com/TheHive-Project/TheHive/issues/419

**Comment by nadouani** [comment]
This looks fixed on 3.1.0.

The custom fields and metrics order is the one defined on case templates. But if it's updated on a case template, it's not applied to the already created cases.

**Comment by nadouani** [comment]
@crackytsi can you please double check it, since you are using 3.1.0-RC1? Please reopen if still not working.

**Comment by crackytsi** [comment]
@nadouani Right, my fault. I will close #419 as well...

**Comment by Dominator-3000** [comment]
Sup, guys!

I updated from 3.0.1 to 3.1.0 RC3 and the problem still actual for me.

I trying to create new case template, but it's not working. 

Sort I specify in the template does not work...

![addfield1](https://user-images.githubusercontent.com/41053409/46013170-23249580-c0d4-11e8-8bd7-5526bb3289cd.PNG)
![addfield2](https://user-images.githubusercontent.com/41053409/46013177-261f8600-c0d4-11e8-84eb-e909a4b7319e.PNG)

**Comment by nadouani** [comment]
@Dominator-3000 when did you create this case? after or before updating your template? If the case is already created from the case template, it doesn't get updated when you update the template.

**Comment by Dominator-3000** [comment]
@nadouani after updating my template...

below are better screenshots...

![newscreen2](https://user-images.githubusercontent.com/41053409/46013765-d772eb80-c0d5-11e8-9558-fe79e930ada8.PNG)
---
![newscreen3](https://user-images.githubusercontent.com/41053409/46013776-de99f980-c0d5-11e8-9ee8-e7fa0d7bbdbd.PNG)

**Comment by nadouani** [comment]
@Dominator-3000 Can you get the JSON representation of the case template and the case using the APIs?

**Comment by Dominator-3000** [comment]
@nadouani 

Cases is created by curl:

`curl -XPOST -H 'Authorization: Bearer '${15}'' -H 'Content-Type: application/json' http://X.X.X.X:5601/api/case -d '{"template":"[XXX][FILE]['$Type']","title":"File '$1' requested from '$2' ('$3')","description":"File '$1' requested from: '$3':'$4' Requested to: '$5':'$6' URL: '$Object' Method: '$8' Referer: '$Referer' More information: '${10}' MD5: '${11}' SHA256: '${12}' FileName: '${13}' FileType: '${14}'", "customFields": {"category":{"string":"'$1'"},"sourceURL":{"string":"'${10}'"},"hostname":{"string":"'$2'"},"sourceIP":{"string":"'$3'"}, "sourcePort":{"number":'$4'}, "destinationIP":{"string":"'$5'"}, "destinationPort":{"number":'$6'}, "url":{"string":"'$Object'"}, "requestMethod":{"string":"'$8'"}, "referer":{"string":"'$Referer'"}, "md5":{"string":"'${11}'"}, "sha256":{"string":"'${12}'"}, "fileName":{"string":"'${13}'"}}}'`

Get cae information:

#curl -H 'Authorization: Bearer XXXX' -H 'Content-Type: application/json' http://X.X.X.X:5601/api/case/AWYQoE_9DMv9jpn-9bAB

{"startDate":1537877233658,"customFields":{"destinationPort":{"number":80},"referer":{"string":"null"},"fileName":{"string":"core_loader.js"},"sourcePort":{"number":39952},"sha256":{"string":"4e47f2ced1f1c5bd99624806571c3d237a4bcb7dd4a61886a1ca987faa9d623b"},"requestMethod":{"string":"GET"},"url":{"string":"http://www.infotexcenter.ru/bitrix/js/main/core/core_loader.js?v///=0.2.32"},"destinationIP":{"string":"37.140.192.148"},"hostname":{"string":"null"},"sourceIP":{"string":"X.X.X.X"},"sourceURL":{"string":"XXXX"},"category":{"string":"Trojan.JS.Miner.x"},"md5":{"string":"3c20a1f27616972094bb8a1da0c82b20"}},"pap":2,"description":"File Trojan.JS.Miner.x requested from: X.X.X.X:39952 Requested to: 37.140.192.148:80 URL: http://www.infotexcenter.ru/bitrix/js/main/core/core_loader.js?v///=0.2.32 Method: GET Referer: null More information: XXXX MD5: 3c20a1f27616972094bb8a1da0c82b20 SHA256: 4e47f2ced1f1c5bd99624806571c3d237a4bcb7dd4a61886a1ca987faa9d623b FileName: core_loader.js FileType: GeneralTxt","metrics":{},"owner":"robot","createdBy":"robot","flag":false,"status":"Open","title":"[XXX][FILE][Trojan] File Trojan.JS.Miner.x requested from null (X.X.X.X)","tags":["Trojan"],"caseId":7474,"createdAt":1537877233461,"severity":2,"tlp":2,"_type":"case","_routing":"AWYQoE_9DMv9jpn-9bAB","_parent":null,"_id":"AWYQoE_9DMv9jpn-9bAB","_version":1,"id":"AWYQoE_9DMv9jpn-9bAB"}

**Comment by nadouani** [comment]
So you are creating the cases without referring to the case template? Based on the curl commands above, the case is not created from the case template.

**Comment by nadouani** [comment]
can you please confirm that you have the issue when you create the case using the UI, from a given template?

**Comment by Dominator-3000** [comment]
@nadouani 

about referring to template... POST data in curl contains: **"template":"[XXX][FILE]['$Type']"** 

If I try to create case using UI fields are sorted successfully...

![newscreen4](https://user-images.githubusercontent.com/41053409/46015556-44d54b00-c0db-11e8-830b-9a3d8a81d4b9.PNG)

**Comment by nadouani** [comment]
In your curl call you specify the custom fields, so those coming from the case template are ignored, that's why you loose the order. If you want to keep the order, you have to set it like: 

```
...
"sourcePort":{"number":39952, "order": X}
...
```

Where `X` is a number.

**Comment by Dominator-3000** [comment]
@nadouani 

Thanks a lot. I try this.

**Comment by Dominator-3000** [comment]
@nadouani 

Yep, it works fine. ;)
