### ISSUE TITLE
POST API Unrecognized character escape '='. 

### ISSUE THREAD

**Issue by Dominator-3000** [TheHive-Project/TheHive#683]
### Request Type
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.0.10

### Problem Description
I have several bash scripts on different security systems that automatically create cases through API.

Sometimes I have problems with transfer URL parameter through API. This happens when input URL parameter contains constructions like "\\=". 

For example:
`http://evil.domain/bitrix/js/main/core/core_loader.js?v\\=0.2.31`
or:
`http://evil.domain/bitrix/js/main/core/core_loader.js?v\\\\\\\=0.2.31`

When this happens I get an error:

`A client error occurred on POST /api/case : Invalid Json: Unrecognized character escape '=' (code 61) at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@332ad5f1; line: 1, column: 281]`

It is possible to put this links via bash scripts? Or I need to use workaround solutions like:

`if grep -q '\\=' <<< "$MyURL"; then
        OutputURL=$(echo "$MyURL" | sed -e 's/\\/\//g')
fi`

Or it would be better to use python?

P.S. To create cases I use curl construction (and usually it works fine):

`curl -XPOST -H 'Authorization: Bearer XXXX' -H 'Content-Type: application/json' http://10.?.?.?:5601/api/case -d '{ here i have many parameters... }'`

**Comment by nadouani** [comment]
Hello, I honestly recommend to use [TheHive4py](https://github.com/TheHive-Project/TheHive4py) and write python scripts to play with TheHive APIs

**Comment by Dominator-3000** [comment]
@nadouani 
Thanks.
