### ISSUE TITLE
MISP Exports in livestream miss hyperlink to caseid

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#684]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC1
| Package Type              | DEB

### Description
If you share a case on MISP the timelime contains the case (as technical name).
![image](https://user-images.githubusercontent.com/11610825/44521171-80db5180-a6d2-11e8-96e0-b16046362b41.png)

Suggestion:
As with other timeline entries add the Link to the caseId.

![image](https://user-images.githubusercontent.com/11610825/44521264-c009a280-a6d2-11e8-9be6-2fc535eaca23.png)

**Comment by nadouani** [comment]
The first screenshot represents the flow item of the alert created because of the case export to MISP.

Alert flow items don't include case link

**Comment by crackytsi** [comment]
Ok. But as the caseId is there would it be conplex to have a link to the case?
I was missing the link and had to copy and paste the caseid to reach the case...
