### ISSUE TITLE
Add a search box to quickly search for case by caseId

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#685]
### Request Type
Feature Request

### Problem Description
After revamping the search page, we removed the free text search box, but as requested by @crackytsi searching for a case by `caseId` is useful.

**Comment by crackytsi** [comment]
I',m very happy :) :) 

TheHive and the team behind is definitive the best!!!  :1st_place_medal:

**Comment by nadouani** [comment]
This is a quick win so we do it :)
