### ISSUE TITLE
Filter on computedHandlingDuration in SearchDialog fails

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#688]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC2
| Package Type              | DEB

### Description
In Search Dialog:
ComputedHandlingDuration field is on Case, I would expect it on tasks, but there it is not available.
It seems not to work on cases.

At least most or even all computed* values seems not to work.
e.g. alert filter on computedObservableCount > 2 failes as well...

**Comment by nadouani** [comment]
We will take a look if it's possible to make them work as filter, otherwise we will remove them from the filters list
