### ISSUE TITLE
FEATURE REQUEST: BULK EXPORT CASE TEMPLATES

### ISSUE THREAD

**Issue by RANGERBEE** [TheHive-Project/TheHive#691]
Feature Request:

BULK EXPORT CASE TEMPLATES

~~~~

THANKS!

**Comment by nadouani** [comment]
What's the use case here? Copying the case templates from an instance A to an instance B?

If yes, please take a look to this tool, https://github.com/TheHive-Project/TheHive-Resources/tree/master/contrib/ManageConfig

Otherwise please reopen the issue and tell us more about the use case.
