### ISSUE TITLE
Data retention / DB Cleanup

### ISSUE THREAD

**Issue by jeffrey-e** [TheHive-Project/TheHive#697]
# Making it possible to have data retention and to clean / purge your data from The Hive for a clean slate.

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 9.4
| TheHive version / git hash   | 3.0.3
| Package Type              | DEB
| Browser type & version    | Not applicable

### Problem Description
When you have a lot of (test) data in your environment there is no option to remove some to reduce the footprint on disk.
Also it is useful to be able to remove data automatically after a certain amount of days (for example, after your corporate retention period has expired). This is not possible now.

### Steps to Reproduce
1. Generate a lot of data until disk is nearly full

### Possible Solutions
Provide an API endpoint to actually remove data. Maybe a purge option that deletes all the files that are marked as DELETED and need special permissions to perform.

To provide a retention timer you can use the same API endpoint to also allow providing a time format (ex. 1h, 2d, 1w, 2m). This can be connected to an internal setting where you can provide the time format for automatic cleanup. But a first step by adding it to a cronjob would already be nice.

**Comment by crackytsi** [comment]
I think removing options could be
a) Cases older as X days
b) Cases containing a specific tag/attribute

From the general design you benefit if you do not remove old data (e.g. to have links to old cases etc.). But based on GDPR there can be some motivations to physically remove specific cases.

**Comment by RANGERBEE** [comment]
+1

Perhaps check boxes of what we want to purge and drop downs for time
selection on the diagnostics page?  Under the hood an internal script could
kick off (server side) that performs the actions.
