### ISSUE TITLE
Sort "New Case" template list alphabetical

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#702]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC2
| Package Type              | DEB

### Description
Currently if you click new Case -> and want to select one case from the list, these cases are ordered by creation date. If you have multiple entries it is hard to find a specific one.

### Suggestion
Sort by name to make it easier to find a template from the list.

**Comment by nadouani** [comment]
This is obsolete because of the feature #769
