### ISSUE TITLE
thehive with the IE browser is freezing and stop working

### ISSUE THREAD

**Issue by Boreal34** [TheHive-Project/TheHive#704]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CENTOS 7
| OS version (client)       | Windows 7
| TheHive version / git hash   | 3.0.10-1
| Package Type              | RPM
| Browser type & version    | Internet explorer 11.0.9600.16428

### Problem Description
I first installed thehive on a CentOS 7 server without a problem. Then I installed it with the same configuration on two other servers under centos 7 for testing.

I don't know why, but when I do some tasks under thehive, typically when creating users under my admin session, thehive then "freeze" and I'm unable to get back the control of my browser (IE).

After creating someone's profil, for instance, I have a moving circle that appears next to the search bar and admin tab in the top right corner of the GUI.  It indicating numbers that are always changing 2,4,52,1025, etc. So, something like the page is loading forever.

And so... nothing more, I have to kill my IE process to get back on thehive. 

If someone could help me on this one... 
I will upload a pics in a few hours

### Steps to Reproduce
1. Install ElasticSearch with RPM, version 5.6.10 (because I can't have an internet connection on my computer, so no yum install).
2. install thehive 3.0.10-1 with RPM (because I can't have an internet connection on my computer, so no yum install).
3. configure a really simple application file for thehive and elasticsearch to have a basic working installation. (play secret key, elasticsearch.yaml basic lines provided by the specifications).
4. Connect to thehive as an admin, try to create an user as "orgadmin" under the admin configuration panel.
5. Anyway, with a remote connection, my browser freeze, and thehive indicates a moving circle on the top right corner with numbers that are constantly changing.

### Possible Solutions
Any ideas ?

**Comment by nadouani** [comment]
Hello, the number you can see on the top right corner is the number of http calls made by the UI to the backend APIs.

If this number is constantly changing, that means the something is not corking correctly and we need more logs to understand what happens.

**Comment by Boreal34** [comment]
Hello, and thank you for your really quick answer ! 
I have more information regarding this, in the application.log file, It's just after the moment I did a test, by connecting to the admin account and create an user throught the interface. Do you have any information regarding the last multiple lines : Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$

> 2018-09-04 13:09:39,829 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-94 - Authentication failure:
>         session: AuthenticationError User session not found
>         pki: AuthenticationError Certificate authentication is not configured
>         key: AuthenticationError Authentication header not found
>         basic: AuthenticationError Authentication header not found
>         init: AuthenticationError Use of initial user is forbidden because users exist in database
> 2018-09-04 13:09:39,830 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-94 - GET /api/user/current returned 401
> org.elastic4play.AuthenticationError: Authentication failure
>         at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:220)
>         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
>         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
>         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
>         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
>         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>        session: AuthenticationError User session not found
>         pki: AuthenticationError Certificate authentication is not configured
>         key: AuthenticationError Authentication header not found
>         basic: AuthenticationError Authentication header not found
>         init: AuthenticationError Use of initial user is forbidden because users exist in database
> 2018-09-04 13:09:39,830 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-94 - GET /api/user/current returned 401
> org.elastic4play.AuthenticationError: Authentication failure
>         at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:220)
>         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
>         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
>         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
>         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
>         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
>         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
>         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
>         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> 2018-09-04 13:09:47,169 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-95 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:47,240 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:47,245 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:47,245 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:47,245 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:47,245 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:48,099 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:48,108 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-94 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:09:48,110 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-94 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:10:05,450 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-117 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contai$
> 2018-09-04 13:10:06,362 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-138 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contai$
> 2018-09-04 13:10:06,372 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-98 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:10:06,375 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-96 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:10:06,381 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-95 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
> 2018-09-04 13:10:06,386 [WARN] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-98 - Illegal header: Illegal 'referer' header: requirement failed: Referer header URI must not contain$
>

**Comment by nadouani** [comment]
What's the value of the `referer` header? doesn't it contain a custom data?

**Comment by Boreal34** [comment]
Nadouani : how could I see this value on my side ? I'm sorry i'm not a specialist.

I compared this problematic instance of thehive with my previous one, on which I have not this "freezing" problem.
This lines seem to not be in cause, They are due to the use of HTTPS I think, but the problem is the same and still there with a connection without https, and only with http. 
I will provide you next two logs to compare the working, and the not working instance with only HTTP.
Thank you for your help.

**Comment by Boreal34** [comment]
Hi Nadouani,
I edited my previous posts cause I find more information regarding this issue. 
The bug appears only when I use a Windows 7 client with Internet explorer (version 11.0.9600.16428). No problem with chrome on Windows, I didn't test with FF on Windows 7 BTW.
I keep the issue open for you, it's not a problem for me, since I can use any browser types.

**Comment by nadouani** [comment]
TheHive and Cortex are not supporting IE in fact

**Comment by nadouani** [comment]
I'll close the issue, since we wont make any effort to support IE, at least for now.

Thank you
