### ISSUE TITLE
.sbt build of current git version fails with x-pack-transport error

### ISSUE THREAD

**Issue by smclinden** [TheHive-Project/TheHive#710]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type

Bug 
### Work Environment

| OS version (server)       | Ubuntu
| OS version (client)       | Windows 10
| TheHive version / git hash   | 7a4622d2db32952c1a89c8eb41632f79f3b10c70
| Package Type              | From Git source
| Browser type & version    | Chrome

### Problem Description

Error importing x-pack-transport

Explanation can be found, here https://github.com/sksamuel/elastic4s/issues/775 with the solution, from salvob41 changing the repository to maven.

### Steps to Reproduce
1. ./sbt clean stage

### Possible Solutions

See the above. Unsure where, best, to fix the toolchain.

### Complementary information
[error] (thehiveBackend / update) sbt.librarymanagement.ResolveException: unresolved dependency: org.elasticsearch.client#x-pack-transport;5.6.2: not found

**Comment by To-om** [comment]
The solution (add elastic.co resolver) has already been applied in [elastic4play](https://github.com/TheHive-Project/elastic4play/blob/master/build.sbt#L18) but not in TheHive.
