### ISSUE TITLE
3.1.0RC3: Browsing to negative case ids is possible

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#713]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC3
| Package Type              | DEB

### Description
When browsing to search case-id field, by using arrow keys you can browse to negative caseIds or caseId 0.

![image](https://user-images.githubusercontent.com/11610825/45158948-bfe6c800-b1e5-11e8-9df7-98764f410549.png)

**Comment by saadkadhi** [comment]
HAHAHA 🥇 

@nadouani I guess you own us some croissants

**Comment by crackytsi** [comment]
Haha

If you wouldn't be so far away I would owe you regular croissants.... :-)

What I forgot:
Actually typing in caseid and pressing enter applies a search.
I don't know if there is a special reason, but actually I would expect/prefere to jump directly to the case....

**Comment by nadouani** [comment]
> Actually typing in caseid and pressing enter applies a search.
I don't know if there is a special reason, but actually I would expect/prefere to jump directly to the case....

Yes, it's better to directly open the corresponding case, I agree
