### ISSUE TITLE
Renaming users

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#715]
### Request Type
Question

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.0 RC3
| Package Type              | DEB

### Description
How can I rename a user in TheHive?
As I want to change authentification mechanism I'm searching for a solution to change the usernames. How is this possible?
I guess this needs to be done on elasticsearch side, to ensure that auditlog and all other fields stay consistent.
But to be hones I have no clue how to do this and which attributes needs to be changed.

Renaming users could also be a valid scenario e.g. someone changes his/her name by marriage and  wants to keep liks to all cases that were created (and open tasks).

**Comment by nadouani** [comment]
Usernames are identifiers of the `User`document type and are not updatable (usernames are ids).

I don't think this is something we would support since the usernames are linked everywhere using `createdBy`, `updatedBy` and other user related fields.

Sadly, I don't think this will be fixed.

**Comment by crackytsi** [comment]
I what about if I create new userids. Can I script based reassign all cases/tasks on elasticsearch level?
