### ISSUE TITLE
Split lines in Alert description

### ISSUE THREAD

**Issue by MonaxGT** [TheHive-Project/TheHive#716]
### Request Type
Feature Request

Hi guys!
I want to split the lines in the description field in the Alerts. I try to use "/n", but this didn't work. How i can move the line to another line?

Example:
```
Host:example.ru
Ipaddress:8.8.8.8
www:google.com
etc.
```

**Comment by 3c7** [comment]
As description fields in TheHive using markdown, you need to double line break in order to get a normal linebreak or add two spaces at the end of the line, see: https://daringfireball.net/projects/markdown/syntax#p.
