### ISSUE TITLE
TheHive:Alerts don't send observables to Responders

### ISSUE THREAD

**Issue by sigalpes** [TheHive-Project/TheHive#725]
### Request Type
Bug & Feature Request

### Problem Description
I'm writing a responder that needs to parse observables before doing things.
Observables are not sent to Cortex from a responder in TheHive>Alerts menu.

### Steps to Reproduce
1. Create a responder named "Responder1"
2. From TheHive>Alerts menu, click on "Responder>Responder1"
3. Observables are not sent to the Responder

**Comment by To-om** [comment]
Only observables in alerts are affected by this issue.
