### ISSUE TITLE
TheHive-Cortex no full Integration

### ISSUE THREAD

**Issue by nut1lns** [TheHive-Project/TheHive#727]
Integration seems to be well 

![image](https://user-images.githubusercontent.com/43415404/45766393-10562080-bbfd-11e8-83c0-1e6e6d82db41.png)

![image](https://user-images.githubusercontent.com/43415404/45766429-2cf25880-bbfd-11e8-8e9e-f8bfec4376b0.png)

 but i cannot run any analyzer, cannot choose any cortex server
 
![image](https://user-images.githubusercontent.com/43415404/45766485-53b08f00-bbfd-11e8-994e-7fe845505ec8.png)

or see responders tab. 

![image](https://user-images.githubusercontent.com/43415404/45766539-7642a800-bbfd-11e8-8b3f-d25da867a67a.png)

**Comment by nadouani** [comment]
This is fixed on 3.0.7.

Your version is a bit outdated, you can update to TheHive 3.0.10, and wait for 3.1

**Comment by martinacen** [comment]
@nut1lns @nadouani sorry if I open this topic again, but, where can I find the window with "Select Cortex Server"? 
I searched everywhere on TheHive but nothing I found.
