### ISSUE TITLE
url category to MISP: poll for default

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/TheHive#732]
The default category for url type attributes is "external analysis":

![image](https://user-images.githubusercontent.com/16938405/46142048-f5fff080-c255-11e8-9c3d-3632b9326d1c.png)

Often the url is used to describe a "network activity":

![image](https://user-images.githubusercontent.com/16938405/46142120-2e073380-c256-11e8-93a3-e7de45a100d1.png)

What do you think to change the category for url attributes from "external analysis" to "network activity"?
The correct thing I suppose is to use the uri_path instead uri in The Hive.
Any thoughts?

**Comment by saadkadhi** [comment]
I do agree @garanews. @To-om any thoughts? URLs in the observable list are not links/references hence they should not be assigned to the *External Analysis* category as @garanews says.
