### ISSUE TITLE
UPN attribute is not correctly lowercased

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#736]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.1

### Problem Description
TheHive compares the extracted UPN
Firstname.Lastname@example.com with the internal useraccount (always lowercased) to firstname.lastname@example.com. This must fail.

### Steps to Reproduce
Use a certificate with Uppercase characters in UPN.

### Possible Solutions
Lowercase the UPN or any attribute that is compared with the usernames defined in TheHive.

**Comment by To-om** [comment]
Fixed by TheHive-Project/elastic4play#71
