### ISSUE TITLE
Observable Result Icons Not Displaying

### ISSUE THREAD

**Issue by urban-moniker** [TheHive-Project/TheHive#738]
### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server) | Ubuntu
| OS version (client) | Windows
| TheHive version / git hash   | 3.1.0
| Package Type              | DEB
| Browser type & version    | All Browsers

### Problem Description
After submitting an observable for analysis the result icons does not show when viewing the observable list.  If you view the observable details it does.

### Steps to Reproduce
1. Submit observable for analysis
1. When finished refresh the browser, no results are shown
1. View the details of the observable, results are visible inc. the 'mini-icons\short reports'

### Complementary information

Seemed to appear after 1) upgrading to 3.1.0 or after connecting MISP and updating report templates.
![thehive](https://user-images.githubusercontent.com/23149626/46223826-56715980-c34c-11e8-94fb-0d165301fdc8.jpg)

**Comment by nadouani** [comment]
This will be fixed with 3.1.1 release.

https://github.com/TheHive-Project/elastic4play/issues/70
