### ISSUE TITLE
Migration from ES

### ISSUE THREAD

**Issue by obikao** [TheHive-Project/TheHive#742]
### Request Type
Question

### Question

Per https://github.com/TheHive-Project/TheHiveDocs/blob/master/FAQ.md#do-you-support-elasticsearch-6x-or-later you mention that you will be moving away from ES altogether. We have adopted this code base pretty heavily internally and I was wondering what you would be moving to. Currently, upper management is using Kibana for reporting and we are thinking about purchasing support for X-Pack, however if the plan is to move away from ES, we obviously don't want to waste the time on this. 

What database are you thinking about moving to and is there a rough release time for this update (Cerana 2/3/etc)?

**Comment by To-om** [comment]
TheHive 4.0, planned for Q2 2019,  will use a graph database. The selection of engines hasn't been finalized yet. We currently evaluate JanusGraph, OrientDB and Neo4j.

**Comment by obikao** [comment]
This is great news! Thanks for the quick reply
