### ISSUE TITLE
Tags from cortex analysers missing

### ISSUE THREAD

**Issue by rayschippers** [TheHive-Project/TheHive#745]
### Request Type
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  Docker image
| OS version (client)       | Win10 Chrome
| TheHive version / git hash   | 3.1.0-1
| Package Type              |   Docker
| Browser type & version    | Chrome 69

### Problem Description
When running Cortex analyzers against observable  they continue to report "no reports available". When clicking on observable the results and tags are visible. 

### Steps to Reproduce
1. Add observable to case.
2. Run Cortex analyser
3. No results shown on observable list.

### Complementary information
![image](https://user-images.githubusercontent.com/688481/46521696-f5e59d80-c8b2-11e8-8a88-6f9ee22f8e34.png)
 
![image](https://user-images.githubusercontent.com/688481/46521717-131a6c00-c8b3-11e8-9bd7-cd06cd22a99c.png)

**Comment by 3c7** [comment]
Duplicate: https://github.com/TheHive-Project/TheHive/issues/738
Will be fixed in 3.1.1.
