### ISSUE TITLE
specifying Cortex server

### ISSUE THREAD

**Issue by DenWotton** [TheHive-Project/TheHive#758]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
Bug 

### Work Environment

| Question       
|---------------------------|--------------------
| OS version (server)       | Ubuntu 
| OS version (client)       | 16.04
| TheHive version / git hash   | 3.1.1
| Package Type              | DEB
|Cortex  |Version: 2.1.1
API key was created according to instruction 
![qweqwe](https://user-images.githubusercontent.com/23268478/46999840-7b791100-d12f-11e8-8249-e97c3acae3d1.PNG)

### Problem Description
Problem with specifying Cortex server

### Complementary information
Caused by: com.typesafe.config.ConfigException$WrongType: /etc/thehive/application.conf: 136: url has type STRING rather than OBJECT

Here is my config 
#########################
play.modules.enabled += connectors.cortex.CortexConnector

cortex {
  #"CORTEX-SERVER-ID" {
  url = "http://10.10.30.32:9001"
  key = "***************************"
  #HTTP client configuration (SSL and proxy)
  #  ws {}
  #}
}
#############################
Cortex is enabled and i use this machine for TheHive too.

**Comment by To-om** [comment]
you must put url and key in a Cortex instance section:
```
cortex {
 "myCortex" {
    url = "http://10.10.30.32:9001"
    key = "***************************"
  }
}
```

**Comment by DenWotton** [comment]
solution was on the surface? Thanks for the answer.
