### ISSUE TITLE
Cross site scripting on urls

### ISSUE THREAD

**Issue by selogreen** [TheHive-Project/TheHive#767]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04 LTS
| TheHive version / git hash   | 3.0.10
| Package Type              | DEB
| Browser type & version    | If applicable

### Problem Description
A security scanner on my network found that the web side of theHive allows scripts to be embedded into URIs, which can lead to xss attacks.

### Steps to Reproduce
1. Send a GET request to a hive web server with an embedded script in the URI
Ex: https://myhiveserver:8094/not_a_real_file.pl?"><script>alert(73541);</script>

**Comment by obikao** [comment]
Unable to reproduce
![image](https://user-images.githubusercontent.com/3343457/47188085-2fc79280-d2fc-11e8-8b6e-d59ad6fdbd61.png)

**Comment by nadouani** [comment]
This is a false positive. If you have more details please reopen.
