### ISSUE TITLE
Add tags to case tasks

### ISSUE THREAD

**Issue by vpiserchia** [TheHive-Project/TheHive#770]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | All
| OS version (client)       | All

### Problem Description
Add custom tags to case tasks in order to search for it

**Comment by nadouani** [comment]
As state by @saadkadhi on gitter, we don't think there is a valid use case for adding tags to tasks.
