### ISSUE TITLE
Feature Request: Import event from MISP "include" filter

### ISSUE THREAD

**Issue by jordisk** [TheHive-Project/TheHive#776]
# Feature Request: Import event from MISP "include" filter

### Feature Request

On the configuration file of The Hive it's possible to exclude some organizations or tags, to avoid them to create an alert on The Hive.
https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#73-event-filters

I would like to ask for a Feature to allow only to create an alert for events from some organizations or with an specific tags, like we can do with "exclusion".

Something like this:
```
    inclusion{
     organisation = ["super good organisation", "CIRCL"]
     tags = ["tag1", "tag2"]
    }
```

**Comment by michaelschratt** [comment]
Possible Duplicate - #481

**Comment by saadkadhi** [comment]
yes
