### ISSUE TITLE
Show tags of observables in Alert preview

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#778]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven using Chrome Browser
| TheHive version / git hash   | 3.1.2
| Package Type              | DEB

### Description
Currently Alerts does show the observables, but not their tags.
These tags gets only visible if a case is created from the alert.
In many situations the tags on alert-level help to get a better understanding of the alert, so make them visible would help the analyst.
The Userinterface should have enough space after the data field of the observable to make this field visible as well.

### Suggestion
Show observable tags after the data field in the alert preview

**Comment by nickbabkin** [comment]
I think this was not implemented properly and should be reopened, as I still don't see any observable tags in alert preview dialog in the latest 3.4.0 TheHive version - only type, data, and number of times it was seen in other cases is shown.
