### ISSUE TITLE
Update Docker images at the same time as TheHive

### ISSUE THREAD

**Issue by Xumeiquer** [TheHive-Project/TheHive#779]
### Request Type
Feature Request

### Problem Description
Docker images are not up to date with the TheHive version in the repository.

### Possible Solutions
Add a CI/CD to built images automatically when a new release is published.

**Comment by nadouani** [comment]
Hello, images are up to date here: https://hub.docker.com/u/thehiveproject 

Are you talking about the `latest`? are you encountering an issue with the `latest` tag?

**Comment by Xumeiquer** [comment]
Thanks for the replay. I've got the last version through the repository you pointed out.
