### ISSUE TITLE
How to force the style used in alerts description?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive#784]
The alert description support MarkDown but if we don't control the alert description (generated by a tool that don't allow me to add MD tags), is there a way to force a style?
Example to force the description to be displayed as a code block?

**Comment by nadouani** [comment]
Hello, unfortunately, we don’t do any preprocessing on alert data before saving it.

**Comment by xme** [comment]
Ok, I'll investigate a way to change this up front!
