### ISSUE TITLE
API Stream missing content-type

### ISSUE THREAD

**Issue by vousavez** [TheHive-Project/TheHive#788]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive version / git hash   | 3.x
| Package Type              | RPM, DEB, Docker, Binary, From source

### Problem Description
When login, it's made a POST request to /api/stream which doesn't specify the content-type.

### Steps to Reproduce
1. Just sniff the logon traffic and you'll see a POST request to /api/stream without content-type.

### Possible Solutions
Just specify a content-type in this request.

### Complementary information
![image](https://user-images.githubusercontent.com/32397584/47879443-61158780-ddff-11e8-8432-7f922d034019.png)
![image](https://user-images.githubusercontent.com/32397584/47879558-a934aa00-ddff-11e8-8759-3a7e5f7768e7.png)

**Comment by nadouani** [comment]
Hello, this POST request has no content, it just asks the server to create a stream that is polled by `GET /api/stream/STREAM_ID` after the stream creation.
