### ISSUE TITLE
Excluding observables imported from MISP

### ISSUE THREAD

**Issue by jeffrey-e** [TheHive-Project/TheHive#800]
# Excluding observables imported from MISP

### Request Type
Feature Request

### Problem Description
Currently it is possible to import MISP alerts based on different filtering options. But you cannot exclude certain observable types from MISP alerts. This feature would be especially interesting for the observable type "file", which can container malware samples. We prefer to prevent these from entering our Hive environment as these files can be downloaded by our Operations team.

**Comment by V1D1AN** [comment]
Yes, it's a good idea.. Excluding "other" for example.
Sometimes, you have a IOC in "other" like "39/45" .. it's a result of virustotal.. In the hive, i don't know if it is interesseting
