### ISSUE TITLE
automatic extraction of observables

### ISSUE THREAD

**Issue by mmyemailid** [TheHive-Project/TheHive#802]
Extracting data from the communication tab..

Currently my siem sends the alert details to hive which are considered as communication by hive and none of the observables are getting autodetected..(emlparser wont work as this comes in the body of the mail)...the contents of the mail have all the alarm fields including sourceip,hash etc:

Analyst have to copy this data(eg:srcip) then add a observable and then run the analyser.Is it some way i can directly identifiy these fields and add as observable...?

this is how the email body looks like:
alarmid:333
date:1/1/2018
sourceip:1.1.1.1
dip:2.2.2.2

**Comment by nadouani** [comment]
How is the Alert created in TheHive? The script that created is have to parse the observables, because TheHive doesn't extract them for you.

Thanks

**Comment by mmyemailid** [comment]
I use sumala to read from the outlook and create albert in hive

**Comment by nadouani** [comment]
Can you give an example of what is sent to TheHive Alert API?
