### ISSUE TITLE
application.conf question - fresh install

### ISSUE THREAD

**Issue by RANGERBEE** [TheHive-Project/TheHive#804]
### Request Type
Qustion - clarification

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | 2012
| TheHive version / git hash   | 3.1.0-RC3 
| Cortex | 2.1.0-RC1
| Package Type              | Docker on both

### Problem Description
After all configurations I receive alerts and observables are recognized to my case templates. Cortex is also configured per the docs - for an Org and user - with analyzers configured to auto-extract. ::  Problem is when alerts come in observable are not analyzed. The Circle around Cortex is RED.
I looked into the container of theHIVE and see there is no application.conf. 
Although - In the raw build files - in Git Repo I see there is a application.sample in /conf

### Steps to Reproduce
1. Build docker build by the compose file - as per getting started docs.

### Possible Solutions
Do I need to configure the application.sample and save as application.conf and leave it within the /conf folder?

### Complementary information
Seems I have everything configured , there is simply a disconnect somewhere between theHive and Cortex to do the work.  Your help is appreciated to this new build environment!!

**Comment by RANGERBEE** [comment]
Seems I may be missing the section in docs to troubleshoot the Cortex connectivity.  Any pointers welcome.

Found this - chasing the rabbit...
![image](https://user-images.githubusercontent.com/15255470/49096539-aa23f480-f262-11e8-9157-d39660acc7fa.png)


Thanks again guys for good work on the entire framework.

**Comment by nadouani** [comment]
This means the `api key`you set in your application.conf when declaring your cortex instance in thehive is not correct

**Comment by RANGERBEE** [comment]
found it...

You can specify a custom TheHive configuration file (application.conf) by adding the following lines in the thehive section of your docker-compose file:
```yaml
volumes:
    - /path/to/application.conf:/etc/thehive/application.conf
```

Not sure how I missed it.  :-/     Thx!

**Comment by RANGERBEE** [comment]
THis was actually the most up to date solution.   

[https://github.com/TheHive-Project/TheHive/issues/568](url)

Add the api key to argument in the command segment within the compose file.
