### ISSUE TITLE
need to set uid=username attribute to authenticate using openldap

### ISSUE THREAD

**Issue by edlopez95112** [TheHive-Project/TheHive#809]
### Request Type
Bug

### Problem Description
an attirbute for username is needed in order to authenticate using openldap.  For openldap uid=username

**Comment by crackytsi** [comment]
uid is the user-attribute for the username....
Adding the username to the filter happens during login process.
Sorry, I don't understand your issue...

**Comment by nadouani** [comment]
@edlopez95112 is this still an issue?

**Comment by nadouani** [comment]
Closing the issue, since there is no updates
