### ISSUE TITLE
Extend Case Description Field

### ISSUE THREAD

**Issue by vertroa** [TheHive-Project/TheHive#81]
# Extend Case Description Field

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  CentOS
| OS version (client)       | OSX
| TheHive version / git hash   | 2.9.1
| Package Type              | Binary
| Browser type & version    | Chrome

### Problem Description
The description field only extends halfway across the case window which limits the space to write a detailed description. This is even more noticeable when working with images or tables. 

### Possible Solutions
Extend the description section across both columns of the cases window below the metrics field.

### Complementary information
<img width="951" alt="hive" src="https://cloud.githubusercontent.com/assets/1800335/21826208/792d80ec-d73b-11e6-957e-733dc12eca8e.png">
.)

**Comment by nadouani** [comment]
Hello @vertroa, this will be part of the UI revamping we plan to introduce in the future.
Note that in case you have metrics and related cases, the "white space" you can see in the image attached above, will no be empty.

That said, we can rearrange the layout of this page and make it more "vertical" (one section per row):

- Basic Details
- Metrics
- Related cases
- Attachments (quick access to files attached to task logs)

**Comment by BrevilleBro** [comment]
Hi, it would also be able to nice to be able to write-up the summary of the case before closing the case, as sometimes we would like to include information from within the case in the summary. At the moment, we are using an external tool (like Notepad or similar) to write the summary for the case and then copy and paste it in when we are ready to close. Ideally, this would all be done within TheHive.

**Comment by woifi** [comment]
+1 - agreed, we would also love to have the description field using the full width!

**Comment by crackytsi** [comment]
@saadkadhi Isn't this feature implemented with 3.1 RC2?

**Comment by nadouani** [comment]
Yes, This has been fixed in 3.1 RC2 in fact. Closing this one
