### ISSUE TITLE
Tag order is reversed if a case is created from an alert

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#810]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.2
| Package Type              | DEB

### Problem Description
If I create a case from Alerts that have tags included, the tag order is reversed.

### Possible Solutions
Do not reverse the order or tags, that makes it more controlable which order is applied.

**Comment by To-om** [comment]
Fixed by thehive-project/elastic4play#76
