### ISSUE TITLE
Unable to see mailer responder in cases/tasks

### ISSUE THREAD

**Issue by SOCDev80** [TheHive-Project/TheHive#816]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Seven
| TheHive version / git hash   | 3.1.2
| Package Type              | Docker
| Browser type & version    | Chrome, IE 11

### Problem Description
After enabling the Mailer_1_0 responder in Cortex, alongside the Responders Config for Mailer, we are still unable to select/see the Mailer responder when selecting the 'Responders' drop down in a case/task.

The message states: "No responders available"

We are successfully using the analyzers so the Cortex integration seems to be working on that side - but we're despite numerous attempts are unable to get the Mailer responder to appear as an option.

Appreciate any advice/guidance.

### Steps to Reproduce
1. Complete Responders Config for Mailer in Cortex
2. Enabled Mailer_1_0 in Cortex 
3. Go to Hive Case, select 'Responders' in the UI - receive "No responders available" message.

**Comment by SOCDev80** [comment]
---RESOLVED---

It appears as though the responder was not being picked up when configured, for the first time, to not check the TLP or PAP flags. When amending the config in Cortex and setting the TLP/PAP checks to 'True'  this resolved the issue. 

Turning them back to 'False', I am still able to see the responder - appears to perhaps be a bug that the responder will not show if first enabled with TLP/PAP flags as 'False'.

**Comment by nadouani** [comment]
The responder will appear based on the TLP and PAP configuration you specify in Cortex. If the task's case isn't allowed because of the TLP/PAP, the responder will not be available
