### ISSUE TITLE
Feature Request: link to and from Hive to MISP

### ISSUE THREAD

**Issue by Kahuna01** [TheHive-Project/TheHive#820]
### Request Type
Feature Request

Hey guys, 

it would be great when sharing a hive case to MISP to get a link to the newly generated MISP event. So you don't have to open MISP manually and search that event, but that you can reach that event quicker via a direct link out of the hive.
The way vice versa would also be great, so that hive automatically generates a link attribute in the new created MISP event which leads back to the original hive case.

Greetings

**Comment by nadouani** [comment]
This is in fact a good idea

**Comment by nadouani** [comment]
Link in related alert section

![screen shot 2019-02-19 at 13 34 33](https://user-images.githubusercontent.com/21827/53015412-5c76ec80-344b-11e9-99e8-89580c0dc435.png)

Link in alerts list
![screen shot 2019-02-19 at 13 34 55](https://user-images.githubusercontent.com/21827/53015415-60a30a00-344b-11e9-8e38-cc9d611be754.png)

**Comment by nadouani** [comment]
This feature improves the MISP & TheHive integration
