### ISSUE TITLE
Potential Regression: Case templates cannot be exported in 3.2.0

### ISSUE THREAD

**Issue by saadkadhi** [TheHive-Project/TheHive#823]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Training VM
| TheHive version / git hash   | 3.2.0
| Package Type              | DEB
| Browser type & version    | Chrome 70

### Problem Description
It is not possible to export case templates.

### Steps to Reproduce
1. connect as an admin
1. go to *Admin > Case templates*
1. create a case template
1. save it
1. click on export

### Possible Solutions
This is probably a regression introduced sometime ago.

**Comment by nadouani** [comment]
I'm unable to reproduce the issue. Do you remember the structure of the case template you were not able to export?

**Comment by nadouani** [comment]
Well, this library changes the way it produces its deliverables: https://github.com/eligrey/FileSaver.js
