### ISSUE TITLE
Merge alerts directly to a case

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#826]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.2
| Package Type              | DEB

### Problem Description
When I want to merge an alert into a case the overlapping cases list is really cool :)
But sometimes we have no overlapping, but we know the case where we want to merge the alert to.
Of course we can create from the alert an empty case, and merge this with the existing case, but it would be nicer if there would be the "merge-case" dialog directly in the Alert Preview-Import Dialog.

### Possible Solutions
Add merge dialog under "similar cases" to merge the alert data/observables directly to an existing case.

**Comment by nadouani** [comment]
This feature has been fixed in `feature/merge-alert-in-case` branch, it needs to be merged into `develop` branch

**Comment by crackytsi** [comment]
Wowww!!! :)
