### ISSUE TITLE
Feature: Add "auto-completion" to the UI

### ISSUE THREAD

**Issue by vlabmichl** [TheHive-Project/TheHive#831]
### Request Type
Feature Request

### Description
An "auto-completion" feature would be great in the UI - especially for adding "tags" or generally when using text inputs in forms.

Would make using the app easier and more straight forward for new users.

;-)

**Comment by nadouani** [comment]
Hello, can you please list the locations/pages that needs auto-complete? In 3.3.0 we've added auto-complete on observable tags.

**Comment by crackytsi** [comment]
Hi, 
I think autocomplete is currently (3.3 RC2) only missing:
a) If I edit an existing observable to add a tag (called "Label"!?)
b) If I edit an on an existing case the Tags (called "Tags"!?)

There is also a strange thing:
If I try to edit the taglist on an observable (assume that there are 2 tags), type some text, then I decide NOT to add it, and click on the red x, ALL tags disappear and "Not Specified" appears unexepectedly. If I reload the page there are the 2 tags again...

**Comment by nadouani** [comment]
> If I try to edit the taglist on an observable (assume that there are 2 tags), type some text, then I decide NOT to add it, and click on the red x, ALL tags disappear and "Not Specified" appears unexepectedly. If I reload the page there are the 2 tags again...

I'm not able to reproduce this one

**Comment by crackytsi** [comment]
Did you try it on the tags of obersables

> > If I try to edit the taglist on an observable (assume that there are 2 tags), type some text, then I decide NOT to add it, and click on the red x, ALL tags disappear and "Not Specified" appears unexepectedly. If I reload the page there are the 2 tags again...
> 
> I'm not able to reproduce this one

Did you try this on the taglist of observables? Or on cases? Because the taglist of cases works correct (as expected)

**Comment by nadouani** [comment]
I tried it on observable details page

**Comment by crackytsi** [comment]
Hmm strange. In my test I already had a tag:
![image](https://user-images.githubusercontent.com/11610825/52728003-be040a80-2fb6-11e9-887b-cc55fa833dd0.png)
Now I add a tag:
![image](https://user-images.githubusercontent.com/11610825/52728033-d07e4400-2fb6-11e9-9a7a-36a362f1bd2c.png)
Now clicking on the x results in this view:
![image](https://user-images.githubusercontent.com/11610825/52728071-e7bd3180-2fb6-11e9-8147-9b499b87a836.png)

**Comment by nadouani** [comment]
![observable-tag](https://user-images.githubusercontent.com/21827/52736693-b9e1e800-2fca-11e9-8326-5bf88f50b69a.gif)

**Comment by nadouani** [comment]
@crackytsi I was able to reproduce it on another platform. I'll take a look then
