### ISSUE TITLE
Long-running Cortex analyzers time out and fail

### ISSUE THREAD

**Issue by InsanesTheName** [TheHive-Project/TheHive#835]
### Request Type
Bug

### Work Environment

| Question              | Answer |
|---------------------------|--------------------|
| OS version (server)       | Ubuntu |
| TheHive version / git hash   | 3.1.2-1 |
| Package Type              | from source |

### Problem Description
When a Cortex analyzer takes a long time to complete, TheHive seems to time out and report it as failed. The following error is logged in `/var/log/thehive/application.log` on timeout:
```
[ERROR] from connectors.cortex.services.CortexAnalyzerSrv in application-
akka.actor.default-dispatcher-16 - Request of status of job <job-id> in cortex 
CORTEX01 fails and the number of errors reaches the limit, aborting
```
This causes the job to show as terminated/failed in TheHive, even though Cortex accurately shows that it is still in progress (and ultimately successful).

### Steps to Reproduce
1. Create a case, add an observable
1. Run Cortex analyzer on the observable
1. See error

### Possible Solutions
A way to configure the timeout (or perhaps slow down the status update mechanism) should solve the issue.

**Comment by nadouani** [comment]
There is already a way to customize the timeout, please refer to https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#6-cortex
