### ISSUE TITLE
Related artifacts: IOC/not IOC

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/TheHive#838]
### Request Type
Feature Request

### Problem Description
Analyst adds an observable, system tells him that there is a related artifact, but doesn't tell him if the related artifact is marked as IOC or not, so analyst doesn't know if that observable was already put in block for example.

### Steps to Reproduce
1. create case 1
2. add observable A
3. create case 2
4. add observable A
5. mark as IOC
6. create case 3
7. add observable A
8. you will see that observable A in case 3 has 2 related artifacts but actually you don't know if is marked as IOC in some other case. (in this example yes, in case 2)

### Possible Solutions
1. change the color of the eye
2. add a new icon in the observable view links

### Complementary information
![image](https://user-images.githubusercontent.com/16938405/50274886-09c28980-0436-11e9-97a4-6ba0f7c40637.png)
![image](https://user-images.githubusercontent.com/16938405/50275155-a2f1a000-0436-11e9-8f67-61c4df14e6f7.png)

**Comment by nadouani** [comment]
I guess the second screenshot can be made easily, and the first one requires probably some backend changes. We'll take a look on it

**Comment by garanews** [comment]
For the first if is hard change color of the icon, I created #839 (tought was easier) but you answerd already also that one is hard...
Up to you to choose the less hard one ;)
