### ISSUE TITLE
Add filter for related observables

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/TheHive#839]
### Request Type
Feature Request

### Problem Description
It would be useful to have a filter for related observables. 

### Steps to Reproduce
1. create case A
2. add 50 observables
3. create case B
4. add 100 observables where 50 are same of case A
5. want to work in case B only over not related observables.

### Possible Solutions
Add the filter related/not related

### Complementary information
![image](https://user-images.githubusercontent.com/16938405/50275921-82c2e080-0438-11e9-80d6-b22938a23ada.png)

**Comment by nadouani** [comment]
This is a bit tricky because the Related/Not Related information is not something stored on the observable details, but is computed using a specific elasticsearch query.
