### ISSUE TITLE
Feature Request: Ability to run an analyzer using the rest API

### ISSUE THREAD

**Issue by DarrenSykes** [TheHive-Project/TheHive#841]
When creating a case, I’d like to be able to automatically run some analysers and import observables generated.

Since that’s not a feature, I’d planned to add the functionality in my code when it’s  generating the case. 

However, it doesn’t appear there’s a way to do that using the API; I.e there isn’t a way to run an analyser or query the result.

I could use Cortex and do it that way, but it feels like I’d be losing the visibility afforded by the auditing and UI of the product.

**Comment by nadouani** [comment]
Hello, are you talking about REST APIs or TheHive4py?

If you want to use the REST APIs, please refer to https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/connectors/cortex/job.md

If you want use [TheHive4py](https://github.com/TheHive-Project/TheHive4py), use the `run_analuzer` method
