### ISSUE TITLE
Export case list as CSV with observables

### ISSUE THREAD

**Issue by axpatito** [TheHive-Project/TheHive#846]
# Export case list as CSV with observables

### Request Type
Feature Request

### Description
I would like to be able to select cases from the cases list and be able to get the case details with observables in a CSV file.

I've tried to create the API endpoint on thehive-backend but had no success. I think it should be solved as follows:

- Get a list of case ids and send it to the api endpoint.
- Map each ids to get the case using the CaseSrv.
- Map each case to get the artifacts using the ArtifactSrv.
- Merge all of the information and buld the csv/excel/json response.

@To-om do you think it's possible? Am I overvieweing something?

**Comment by nadouani** [comment]
I've been discussing the idea or exporting a JSON object including all the date of a given case, using only endpoint. The API could be used by the reporting feature, export/import between TheHive instances etc...

If you already made something about it, please tell us where we can take a look on it ;)

**Comment by axpatito** [comment]
Sure thing! Pls note that it's a WIP. https://github.com/axpatito/TheHive/tree/export_cases

**Comment by veeral-patel** [comment]
@axpatito Hey - just to be clear, is your goal to export all of a case's observables to a CSV, or is it to export case details plus its observables to a CSV?

What's your use case, also?

**Comment by axpatito** [comment]
I wanted to be able to export a list of all cases with it's observables. Time flew and we pivoted elsewhere.

**Comment by veeral-patel** [comment]
@axpatito thanks!
