### ISSUE TITLE
Error with the Observable on thehive

### ISSUE THREAD

**Issue by angelmorales2812** [TheHive-Project/TheHive#847]
I have a problem, when running the observable shows me the following error message, check the configuration files Thehive and Cortex and do not see any difference
![thehive](https://user-images.githubusercontent.com/33816123/50854600-4104c600-1364-11e9-8173-5b65bd83c0ba.PNG)

**Comment by nadouani** [comment]
Hello, what are the available analyzers for that observable, on the observable details page?

**Comment by angelmorales2812** [comment]
hello, thank you for your prompt response I could solve the problem, make a modification in the configuration file cortex enabling this configuration:
method.basic = true
I restarted the Cortex service and it worked without a problem, I really didn't know if this was the problem.
![thehive](https://user-images.githubusercontent.com/33816123/50921328-812c7d00-1426-11e9-97cf-facc8e179975.PNG)
