### ISSUE TITLE
Scope http.address to HTTP protocol

### ISSUE THREAD

**Issue by blainedw** [TheHive-Project/TheHive#850]
### Request Type
Feature Request

### Problem Description
Currently adding http.address to either Cortex or theHive configuration makes both http and https run on the given address. Create a new setting called https.address to provide flexibility. The current use case is that I have to enable http only between processes on the same box. So setting http.address to 127.0.0.1 would be ideal. While leaving users to come in via the UI as the normal network port.

I know I can configure iptables to accomplish the same thing but thought it would be useful in the app itself.

**Comment by nadouani** [comment]
Hello,

The `http.address` is a setting managed by Play Framework and Akka, it's not something that TheHive tweaks.

If you need to configure your instances, and manage custom access rules, I recommend to use a reverse proxy, and enable HTTP and HTTPS as you wish. For example use HTTP locally between the applications, and just expose a HTTPS access via the reverse proxy to the UI.

I hope this is an option for you.

Thanks
