### ISSUE TITLE
Send email when case is opened

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/TheHive#852]
Hi,
We modified Mailer so the configuration is simple and with Rcpt_to filed + few extra parameters in email body. 

Action is currently when analyst push manually "responder" that will send email. 

Is there some way how we can automate that TheHive runs automatically responder when case is Opened or Close?

**Comment by blainedw** [comment]
I started looking at webhooks to do this same thing. I was able to email based on case creation and case close so far.

Nabil pointed me to his very helpful doc on webhooks

https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/webhooks.md


DAVID BLAINE, GCIA, CISSP
Information Security Section Manager
General Dynamics Land Systems

6000 East 17 Mile Road, MZ: 435-01-16, Sterling Heights, MI 48313

GDLS Security | p: 586.825.8437 | m: 586-215-4174 | f: 586.825.8606 | blainedw@gdls.com | www.gdls.com



.

----------------------------------------------------------------------
This is an e-mail from General Dynamics Land Systems. It is for the intended recipient only and may contain confidential and privileged information.  No one else may read, print, store, copy, forward or act in reliance on it or its attachments.  If you are not the intended recipient, please return this message to the sender and delete the message and any attachments from your computer. Your cooperation is appreciated.

**Comment by Idriel** [comment]
Tnx for answer.
