### ISSUE TITLE
Forcing the location of bower_components in .bowerrc

### ISSUE THREAD

**Issue by szymoc** [TheHive-Project/TheHive#855]
.bowerrc is checked in forcing everyone to use the same location for bower_components, could this be removed from the project?

**Comment by nadouani** [comment]
I don't know what's the idea behind the question, but you can update your .bowerrc as you need.

**Comment by szymoc** [comment]
In effect other developers are being forced to use the bower component location as set in the configuration file. If one would want to use a different location and contribute a PR to the project, that developer's settings would be scheduled for merge. Would you then accept the merge?

Checking in local tooling configuration files is a bad idea - it is a practice that should be avoided in any project. 

Is there any reason this file is checked in?

**Comment by nadouani** [comment]
I honestly don't think this could block a PR :)

I don't what could disturb a developer if the bower folder is call `bower_components` or `lib` or even `blabla`

**Comment by szymoc** [comment]
It is not so much the name of the folder as the location that should always be developer env specific.
