### ISSUE TITLE
Feature Request: Add Additional Fields to Observables

### ISSUE THREAD

**Issue by chrissommer** [TheHive-Project/TheHive#858]
### Request Type
Feature Request

Hi,
it would be awesome if you could add the possibility to add additionals fields (like in the Case) to observables. This would give us much more options to manage the observables (f.e. with TI Models, Sharing, Grouping, Searching, Adding to MISP, ...)

Thx & BR
Chris

**Comment by nadouani** [comment]
Hello, this is in fact a very interesting feature that we call Observable Template, already requested by #571
