### ISSUE TITLE
Move UI from jar to files

### ISSUE THREAD

**Issue by bsploit** [TheHive-Project/TheHive#859]
Hi! there are two questions:
1) Is it possible somehow to extract UI part of TheHive to file system and say hive to use UI from directory?
I am asking becuase I made some changes to case view and controllers to support email sending directly from case details window and now it is needed to use apache which do proxy pass: all requests to thehive api are proxied to thehive backand and all static files are served by apache. If it would be possible to say thehive to use directory with static files of UI part it will be much easier to perform customization of UI.
2) Is it possible to add some api to thehive which could be used to get some extra settings from application.conf? Forexample If i make some customization of UI which works with external services (like service which sends email) I need to place somewhere link to web service. Right now webservice which sends email from case details view is located on the same host where apache with thehive lives so apache proxypass solves this issue

**Comment by nadouani** [comment]
Hello,

serving the front end without TheHive is already something you can do, you need to build the front end code from sources, as described header and deploy the content of `TheHive/ui/dist` on your favorite web server, and proxify the `/api` calls to TheHive backend.

For the second point, you can either create a FR or a PR for it, to add something like `/api/config` ai or enrich the `/api/status` API.

Thanks
