### ISSUE TITLE
[BUG] Audit trail for alert ignore

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#863]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.1

### Problem Description
When an alert is marked as ignored there is no audit log of it being marked `ignored` there is just `update of alert` and if you expand the details the status change is not part of those details.  However when i just mark an alert as read then unread - I see no audit log of that.

These logs would be important to know who marked alerts as read and ignored them. 

### Steps to Reproduce
1. Generate Alert
1. Mark alert as read
1. Look at audit log
1. Mark alert as unread 
1. Look at audit log

**Comment by zpriddy** [comment]
So in looking into other issues, I found that if you do an audit search for the user, and not the sourceRef of the Alert, you can see that the user updated the status of an alert to `Ignore` or `New` but you cant see what alert the action was taken on.. (only the Title)

**Comment by nadouani** [comment]
> So in looking into other issues, I found that if you do an audit search for the user, and not the sourceRef of the Alert, you can see that the user updated the status of an alert to `Ignore` or `New` but you cant see what alert the action was taken on.. (only the Title)

What details you need us to add ?

**Comment by nadouani** [comment]
This should be fine I guess?

![screen shot 2019-02-12 at 14 53 24](https://user-images.githubusercontent.com/21827/52640084-fc75c880-2ed5-11e9-8997-b873a5cea843.png)
