### ISSUE TITLE
Long case title rendering

### ISSUE THREAD

**Issue by david-neal-ms** [TheHive-Project/TheHive#876]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| TheHive version / git hash   | 3.2.1-1
| Package Type              | From source
| Browser type & version    | Chrome

### Problem Description
Very long case title causes rendering problems on the case list and case title screens. 

### Steps to Reproduce
1. Create a new case.
1. Enter a very long case title.
1. View the case list screen : elements which normally sit to the right of the title are pushed out (severity, tasks, observables, assignee, date and actions).
1. Select this case, on the case details screen the title overflows the space allowed for it.

### Possible Solutions
Limit the length of the case title text displayed on the case list and detail screens.

**Comment by david-neal-ms** [comment]
Hi @saadkadhi ,
I am happy to take this issue on.
Can you assign it to me please?

**Comment by nadouani** [comment]
Can you please share a screenshot of that?

**Comment by david-neal-ms** [comment]
Sure

![case_list_render_error](https://user-images.githubusercontent.com/42211305/53007674-ab168d80-342f-11e9-9d82-580c5d660abe.png)
![case_detail_render_error](https://user-images.githubusercontent.com/42211305/53007703-b7024f80-342f-11e9-936c-83ca1add0216.png)

reenshots attached.

**Comment by nadouani** [comment]
Well, I'll try a fix, but this is really not a real world title ;)

**Comment by david-neal-ms** [comment]
You might be surprised... we didn't go looking for this...    :)
It's assigned to me. I'm happy to do the fix.

**Comment by nadouani** [comment]
Fair enough, you need to make a PR to provide a fix, so if you want to work on it, please feel free. I'll remove this issue from 3.3 RC3, since it's supposed to be released today or tomorrow. If your PR comes before, then I'll be happy to merge it.

**Comment by david-neal-ms** [comment]
Sounds good. Thanks.
