### ISSUE TITLE
Filter observables based on matching analyzers?

### ISSUE THREAD

**Issue by xme** [TheHive-Project/TheHive#883]
Context: I have a case with 1200+ observables (hashes).
I'm executing Cortex analyzers against them and would like to display only observables that "match" (read: with "non-green" analyzers output).
Is there a way to achieve this? I did not find anything relevant in the documentation...

**Comment by mnmnc** [comment]
I think you can use thehive4py.query to build query that will check if report taxonomy.level is / is not benign/malicious.
```json
"reports": {
      "VirusTotal_GetReport_3_0": {
        "taxonomies": [
          {
            "predicate": "Score",
            "namespace": "VT",
            "value": "0 detected_url(s)",
            "level": "safe"
          }
        ]
      },
      "OTXQuery_2_0": {
        "taxonomies": [
          {
            "predicate": "Pulses",
            "namespace": "OTX",
            "value": "0",
            "level": "info"
          }
        ]
      }
    },
```
Its not an easy to build query but I think its possible. For the found observables - add a tag.

**Comment by robertnixon2003** [comment]
Just to clarify on this old one: there is no way of doing this in the GUI and no plans to add the functionality for it?
