### ISSUE TITLE
Hide Empty Case Button Broken

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#890]
### Request Type
BUG

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3.0-RC3

### Problem Description
Enabling Hide Empty Case Button doesn't seem to work. However when trying to click the button hidden selected or not I get the following console error:

```
vendor.5591ec60.js:6 Error: [$injector:unpr] Unknown provider: aProvider <- a
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=aProvider%20%3C-%20a
    at vendor.5591ec60.js:4
    at vendor.5591ec60.js:5
    at Object.d [as get] (vendor.5591ec60.js:5)
    at vendor.5591ec60.js:5
    at d (vendor.5591ec60.js:5)
    at e (vendor.5591ec60.js:5)
    at Object.g [as invoke] (vendor.5591ec60.js:5)
    at vendor.5591ec60.js:12
    at Object.d [as forEach] (vendor.5591ec60.js:4)
    at Object.resolve (vendor.5591ec60.js:12)
```

I am not sure if this is a build error or a different problem. I didnt see any errors while building TheHive.

**Comment by crackytsi** [comment]
Hi,
Unfortunately I can confirm that.
I installed the standard debian 9 package but after enabling the "Hide Button" the new-case button does not work at all. 
So if I try to click on it, there is no reaction and now window is popping up.

regards
Chris

**Comment by nadouani** [comment]
Yes I agree, next time I’ll not push code after some glasses of wine ^^

**Comment by nadouani** [comment]
We will release a RC4 euther today or monday. But now I have to include another gift in it :)

**Comment by nadouani** [comment]
Yes, some angular service injection stuff is not visible in dev mode, so it works in dev but fails on runtime from the built front end. 

Thanks for the support @crackytsi

**Comment by crackytsi** [comment]
@nadouani Would it make sense not to offer "empty case" if I import an alert to case if this configuration option is set?

**Comment by nadouani** [comment]
I've added this already in 3.3 RC4. The only case where Empty Case is possible, independently from the UI Config, is when you don't have any case templates defiend
