### ISSUE TITLE
Search results not visible

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#895]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.3.0 RC4
| Package Type              | DEB

### Problem Description
If I search for a string in "ALL" i sometimes get results, but I can't see them.
e.g. search for "SIT*"

![image](https://user-images.githubusercontent.com/11610825/53258730-af5fd680-36cd-11e9-8bbd-7d9e8dd438f1.png)

**Comment by nadouani** [comment]
@crackytsi This behavior means that the search query returns data that the UI doesn't expect to display. The search page knows how to render results of:
- cases
- tasks
- task logs
- observables
- jobs
- alerts
- audit logs

I think that the 302 results you've got are something else.

Can you take a look to the JSON response and tell me what's the type of the returned rows/items?

**Comment by nadouani** [comment]
Those undisplayed results are most certainly responder jobs. I'll exclude them

**Comment by crackytsi** [comment]
@nadouani WoW!!! You are hard working. As it was weekend I would say to hard.
I checked the json results and as far as I could see they were all of the type "Audit"
```
		"_routing": "AWcroje9Qq32H1xMNCiK",
		"rootId": "AWKVDz4VufoPl6Jhh4eZ",
		"_type": "audit",
		"objectType": "case_task_log",
		"createdAt": 1542625310618,
		"_parent": null,
```

**Comment by crackytsi** [comment]
Great, works now fine with RC5 :)
In some rare situation i get the red message about something unhandled. After that the click on donuts in dashboard does not correctly add the filter to the searches, but I need to find a way to reproduce that.
Thanks a lot @nadouani  :+1:
