### ISSUE TITLE
Mouseover text for alert preview

### ISSUE THREAD

**Issue by twingbat** [TheHive-Project/TheHive#897]
### Request Type
Feature Request

After our last upgrade, we noticed an awesome feature that when you mouseover an observable in a case (without opening the observable), it displays a pop-up with the observable's description.
Can you add a similar feature to the alert preview view?
Basically, when previewing an alert, can you make it so if you hover over the observable, the description appears (just like in a case). This would allow for putting more details about observables in the description field and enable its use for triaging alerts.

In a case:
![image](https://user-images.githubusercontent.com/12577413/53260811-106cb780-3698-11e9-9418-58ef6c7fb708.png)

Alert preview:
![image](https://user-images.githubusercontent.com/12577413/53260867-3c883880-3698-11e9-93b7-cf33d19576e3.png)

**Comment by nadouani** [comment]
Sure thing, this not a big deal.
