### ISSUE TITLE
DOS issue: Firefox crashing TheHive 

### ISSUE THREAD

**Issue by frikky** [TheHive-Project/TheHive#899]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | ...
| OS version (client)       | ...
| TheHive version / git hash   | 3.3-RC2
| Package Type              | Docker
| Browser type & version    | Firefox 65.0.1

### Problem Description
When you click a case TheHive 3.3-RC2 from Firefox 65.0.1, it automatically makes the server use all available CPU. I'm guessing this is an infinite loop issue in Angular. This is specific to Firefox 65.0.1, and was not reproducable with e.g. firefox 60. (Didn't test inbetween 64, 63 etc.). This does not occur on earlier versions of TheHive either (e.g. 3.2.1). Not tested without Docker.

### Steps to Reproduce
1. Set up TheHive version 3.3-RC2
2. Download and set up Firefox 65.0.1
3. Login to thehive
4. Click any case (Doesn't matter if closed or open)

**Comment by nadouani** [comment]
Hello, is there anyway to take a look to what the browser does, like for example, from the developer console, take a look to the network tab?

**Comment by frikky** [comment]
I tried, but what happened was that you get a reply on the first request, but all subsequent requests  (ctrl+shift+R) don't work.

**Comment by nadouani** [comment]
Tried that on a Mac OS and it works fine. What client OS are you using?

**Comment by frikky** [comment]
Tried on Windows and Debian versions :)

**Comment by nadouani** [comment]
Tested on Ubuntu, works fine.

Do you have any logs? The response of the requests that fail?

**Comment by frikky** [comment]
Hmm, I'm starting to think this is something I've done myself, since we have some custom things. I'll get back to you 👍 

I couldn't find any relevant logs, as it just seems to DOS itself immediately after the first request.

**Comment by crackytsi** [comment]
Could'nt this linked with the button issue? Why didn't you upgrade to 3.3 RC4?

**Comment by nadouani** [comment]
Yes try even RC5 so we can test on the same version

**Comment by frikky** [comment]
Oh, my current custom build is on RC2 (we don't have internet access on servers, so upgrading in general is a hassle, aka I don't do it for every minor upgrade). I'll try, thanks!

**Comment by nadouani** [comment]
So your version is custom version of TheHive?

**Comment by frikky** [comment]
It's basically the normal TheHive with some things like extra severity fields etc. which hasn't broken anything before (been running for a year), hence I thought it might be something happening to everyone. I'll upgrade and test some more before I update you again.

**Comment by frikky** [comment]
I finally got around to doing the upgrade from RC-2 to RC-5. Everything seems to be working fine now! Problem is I don't really know why.. 

Thanks for the help :)
