### ISSUE TITLE
Empty case still available when disabled

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#901]
### Request Type
Bug / Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3.0-RC5

### Problem Description
If an alert is created without a template field and the disable empty case is selected then when importing the alert to a case the first selected option for templates is blank, if this is not changed it imports it as an empty case

### Possible Solutions
Have a default template option in the admin ui settings. For example i have a case template named `default` and when alerts are generated they should come in using default case template if not using a custom template.

**Comment by nadouani** [comment]
The `Empty Case` should not be displayed if you have at least one case template, and you have disabled the option from the UI settings page.

If this is not working, the it's a bug. I'll verify

**Comment by zpriddy** [comment]
Here are screenshots of what im talking about. If you don't pick one then it will import it as an empty case.

![screen shot 2019-03-04 at 2 33 47 pm](https://user-images.githubusercontent.com/1858679/53767427-a370d300-3e8a-11e9-88f9-bcb67ba08fcc.png)
![screen shot 2019-03-04 at 2 33 56 pm](https://user-images.githubusercontent.com/1858679/53767428-a370d300-3e8a-11e9-9770-5b47e91f0dce.png)

**Comment by nadouani** [comment]
Will disable the button to force users to select a template in that case
