### ISSUE TITLE
force/remove "http" from all urls

### ISSUE THREAD

**Issue by garanews** [TheHive-Project/TheHive#911]
### Request Type
Feature Request

### Problem Description
It happened that an url was added in 2 different times with and without http.
The system doesn't show that second indicator is already present.

### Steps to Reproduce
1. add an url
2. add same url starting with http://
3. see that urls are not matching

### Possible Solutions
1. remove/add http(s?) in all url observables
2. force url to start with http(s)
3. match urls with/without http(s) at DB side

### Complementary information
![immagine](https://user-images.githubusercontent.com/16938405/53871083-cd95d280-3ffb-11e9-9c69-e9b094d35a06.png)

**Comment by nadouani** [comment]
1. `www.google.com` is not a URL :) 
1. `http://www.google.com` and `https://www.google.com` are different URLs, so different observables
1. URL can start with other protocols than just `http(s)` :) 

In general, in these cases, you just need to clean up the data a little bit. We can probably think of features that can help this cleaning.

**Comment by garanews** [comment]
Do you think to add the input type validator?
In this case was not same person adding data in different times and often insert is copy/paste from different sources.
A validator type or a cleaning feature would be appreciated.

**Comment by nadouani** [comment]
Cleaning features are best, because the creation of observables can be made through the APIs too

**Comment by veeral-patel** [comment]
@garanews what are some other validators that you'd like? Off the top of my head, I can think of:

- validating observables in a case are unique, like you mentioned
- validate IP addresses, file hashes, etc
- defang all IP addresses (or un-defang defanged IP addresses)
