### ISSUE TITLE
Hide Locked Users

### ISSUE THREAD

**Issue by RtKelleher** [TheHive-Project/TheHive#916]
# Hide Locked Users from View

### Request Type
Feature Request

### Request
Due to the original deployment without AD, when we moved to AD for login we were left with accounts that needed to be locked to prevent use. Given that we can't remove users due to audit can we find a way to hide them from active viewing to make interaction with those accounts easier?

# #

**Comment by nadouani** [comment]
I think the best way to do that is adding filters to the users list, which is something planned. We need to keep showing the locked users to allow you to unlock them, but yes I agree that this list should allow filtering to display only active users by default
