### ISSUE TITLE
Job statistic : Failed to fetch data, please edit the widget definition

### ISSUE THREAD

**Issue by Lyro1** [TheHive-Project/TheHive#919]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Centos 7 (localhost)
| OS version (client)       | Centos 7
| TheHive version / git hash   | 3.2.1-1
| Package Type              | RPM
| Browser type & version    | Google Chrome 72.0.3626.121 (Official build) (64 bits)

### Problem Description
When I open the *Dashboard* page and wants to open the *Job statistics* page, I get the same error message for all the widgets : **Failed to fetch data, please edit the widget definition**

### Steps to Reproduce
1. Open Dashboard
2. Open Job statistic

### Complementary information
I can't succed to install MISP on my Centos 7 environnement, could it be the problem?

**Comment by nadouani** [comment]
Do you have Cortex enabled? The jobs dashboard uses the Cortex connector APIs, that are only available if you have enabled Cortex. 

Please reopen the issue if needed.
