### ISSUE TITLE
UserSrv: undefined

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/TheHive#920]
Hi, 
When we log in into TheHive we got red error in the bottom of the page UserSrv:Undefined

In log I have info that is maybe related with this pop-up
`[info] o.e.ErrorHandler - GET /api/user/Red%20category returned 404
org.elastic4play.NotFoundError: user red category not found
        at org.elastic4play.database.DBGet.$anonfun$apply$2(DBGet.scala:38)
        at scala.Option.fold(Option.scala:158)
        at org.elastic4play.database.DBGet.$anonfun$apply$1(DBGet.scala:38)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
`

**Comment by vakinola** [comment]
If this is related to Synapse in thehive. I experienced this error when i changed the Fullname of the Synapse user in the admin. 
Try changing the Fullname back to how it was when you created the user

**Comment by nadouani** [comment]
@Idriel your usename is `red category`?

**Comment by vakinola** [comment]
@Idriel just like @nadouani is asking, ensure you have the username  categorized

follow this page for more help incase you have not see it
https://github.com/TheHive-Project/Synapse/blob/master/docs/workflows/Ews2Case.md

**Comment by Idriel** [comment]
Hi, I don't have error any more. :(

**Comment by nadouani** [comment]
Did you fix anything, or the error has just gone? :)

**Comment by vakinola** [comment]
@Idriel can you post the solution, if there was one to help others who might stumble upon such

**Comment by Idriel** [comment]
It's like a ghost. Last week I had this error, now I don't have. It does not happen every day. :D

**Comment by Idriel** [comment]
And I recreate it. I didn't have it, but when I switch to page two of incident's. Error is back. So it depends about some case.

**Comment by SteelCrow** [comment]
Error caused by lack of user "syanpse" in TheHive DB.

So if you assign case to any existing user you woudn't see any error but otherwise...

```
if esCaseId is None:
    #no case previously created from the conversation
    caseTitle = str(msg.subject)
    caseDescription = ('```\n' +
        'Case created by Synapse\n' +
        'conversation_id: "' +
        str(msg.conversation_id.id) +
        '"\n' +
        '```')
    if msg.categories:
        assignee = msg.categories[0]
    else:
        assignee = 'synapse'
```
