### ISSUE TITLE
Display 'My Task' Number in Browser Tab

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/TheHive#921]
# Display current Tasks assigned to you in Browser Tab

### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | N/A
| OS version (client)       | N/A
| TheHive version / git hash   | N/A
| Package Type              | N/A
| Browser type & version    | Chrome, Firefox, Edge?

### Problem Description
Having a notification number of 'My Tasks' in the tab of the browser will allow analysts to freely move from tab to tab and see how many tasks they have. 

### Steps to Reproduce
1. The analyst opens TheHive open in a browser
2. User opens new tab to a different website.
3. A new task gets assigned to the analyst.
4. The Tab for where TheHive is open shows the 1 new task, or X number of tasks they have.

### Complementary information
This will be a great way of knowing when you get a new task assigned to you thus adding the ability to quickly see how many tasks you have without browsing to TheHive.

I was thinking of something like how gittr shows "unread" messages. Something like this:
![image](https://user-images.githubusercontent.com/5582679/54327940-0c1e2500-45da-11e9-88c7-15a58858ecc6.png)

**Comment by zpriddy** [comment]
I have been working on a chrome extension for the number of open cases, this could be an option for number of tasks for a user. It also has a pop-up notification when a new case is created

**Comment by nicpenning** [comment]
That is a pretty cool idea as well. Driving task completion it would be good to see how many tasks I have open.

**Comment by crackytsi** [comment]
@zpriddy Another interesting thing would be to show (the number or the existence) of new alerts...

**Comment by nicpenning** [comment]
Stale request.
