### ISSUE TITLE
Cortex AddArtifactToCase AssignCase

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#922]
### Request Type
Feature Request

### Problem Description
It would be very useful to be able to have cortex add an artifact to a case. My use case would be cortex responder parse out a username and then launch a bot to contact user, but at the same time would be nice if I could add the username as an artifact.

**Comment by zpriddy** [comment]
Also adding AssignCase

**Comment by veeral-patel** [comment]
@zpriddy by artifact you mean observable, right?

https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/artifact.md

the terms seem to be used interchangeably here, for some reason!
