### ISSUE TITLE
Owner is case-sensitive on api calls

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#928]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3.0-RC6

### Problem Description
When setting the owner of a case through the API the owner is case-sensitive and does not convert to lowercase. I only notice this problem because i set the case owner to SecurityBot and everything looks fine... but when you do a filter of Security Bot (securitybot) there are no results. Only when doing filters is this noticeable.

**Comment by nadouani** [comment]
What's the username in the DB? `SecurityBot` or `securitybot`? I guess it's lowercase right? That means that the API is in fact not lower casing the username.

**Comment by crackytsi** [comment]
Usename gets automatically lowercased, if you create it or if you try to Login using the GUI.
This is inconsistent, should happen on API as well ;)

**Comment by zpriddy** [comment]
> What's the username in the DB? `SecurityBot` or `securitybot`? I guess it's lowercase right? That means that the API is in fact not lower casing the username.

Correct @crackytsi is correct, the API is not lowercasing the name when the post is called.
