### ISSUE TITLE
/api/alert/{}/createCase does not use caseTemplate

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#929]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3.0-RC6

### Problem Description
/api/alert/{}/createCase does not use caseTemplate from the alert and creates empty case

**Comment by nadouani** [comment]
I confirm that the `/api/alert/{}/createCase` doesn't take into account the `Alert.caseTemplate` field. We will fix this

**Comment by nadouani** [comment]
Actually, the API expects a JSON POST defining the `caseTemplate` which is something that the UI support, but not TheHive4py. The REST API supports it BTW just add a request body `{"caseTemplate": "XXX"}` to the API call
