### ISSUE TITLE
Different analyzer results between manually built instance and trainingVM.

### ISSUE THREAD

**Issue by k41zen** [TheHive-Project/TheHive#934]
### Request Type
Bug

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| TheHive version / git hash   | 3.2.1-1
| Package Type              | DEB
| Browser type & version    | N/A

### Work Environment
N/A

### Description
I originally downloaded the training VM to test. Now tested, I've manually built a hive/cortex instance using Ubuntu 16.04 and the latest version of Cortex (2.1.3-1) and theHive (3.2.1-1). Training VM is running theHive 3.30-RC5.

The issue is different analyzer results between manually built instance and trainingVM.

### Steps to Reproduce
When I submit an example IP (111[.]230[.]247[.]243) to the training VM I get these results:

<img width="981" alt="Screenshot 2019-03-19 at 11 38 51" src="https://user-images.githubusercontent.com/43755140/54619103-00a87f00-4a5c-11e9-9c25-e337f1afde13.png">

When I submit the same IP to the manually built Ubuntu instance I get these results:

<img width="1042" alt="Screenshot 2019-03-19 at 11 38 35" src="https://user-images.githubusercontent.com/43755140/54619124-056d3300-4a5c-11e9-84f9-d3d88ebed2c0.png">

Also, the tags aren't populating automatically within the observable. I have to click on the Observable tab (which shows me all observables) to then watch the tags come rolling in.

Also, when I click on an observable that has reported something I don't see to report at the bottom beneath the analyzers list like this (screenshot from the working VM. I see nothing in the Ubuntu instance):

<img width="1087" alt="Screenshot 2019-03-19 at 12 16 41" src="https://user-images.githubusercontent.com/43755140/54619143-0bfbaa80-4a5c-11e9-9888-bc002e6ab689.png">

**Comment by k41zen** [comment]
Just upgraded theHive to 3.3.0-1 and still the same. Here's the same issue again with another observable. No tags being pulled in and shown just underneath the observable:

<img width="830" alt="Screenshot 2019-03-19 at 15 39 23" src="https://user-images.githubusercontent.com/43755140/54620125-9ee91480-4a5d-11e9-8907-513cc8e9e7ad.png">

Tags shown when run in the VM:

<img width="984" alt="Screenshot 2019-03-19 at 15 40 45" src="https://user-images.githubusercontent.com/43755140/54620148-a7414f80-4a5d-11e9-94e5-0fed1062971f.png">

When clicking on the URLHaus link to show the report at the bottom and gap appears but the report isn't displayed:

<img width="1079" alt="Screenshot 2019-03-19 at 15 39 15" src="https://user-images.githubusercontent.com/43755140/54620214-bb854c80-4a5d-11e9-95f0-b38dc1db6a71.png">

Click on the URLHaus link in the training VM and it shows the report at the bottom of the screen:

<img width="1056" alt="Screenshot 2019-03-19 at 15 40 56" src="https://user-images.githubusercontent.com/43755140/54620243-ca6bff00-4a5d-11e9-9ce3-ada61d430ee1.png">

**Comment by crackytsi** [comment]
Hi @k41zen 
The order of tags depend on the order the analyzers are executed.
The classification happens by the analyzer or the service behind it.
What I'm wondering if I compare the first 2 screenshots that greynoise is missing.
Did you execute it?

I don't really fully understand what your issue is, except that it "looks different".
Can you please describe more precise?

**Comment by crackytsi** [comment]
Ah, the "shortreport-tags" depend on the imported report-templates.
Are you sure you always imported the latest version?
Because this might also change the visualization.

**Comment by k41zen** [comment]
Hey @crackytsi,

Doh! Thank you. Updating them and all works the same. Much appreciated.
