### ISSUE TITLE
Reduce unnecessary audit-logs for no-changes

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#935]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.3.0-1
| Package Type              | RPM, DEB, Docker, Binary, From source
| Browser type & version    | Chrome

### Problem Description
If you click on edit a field (lets say Severity) and after that you don't want to edit it, so you select the same value as is currently set, this generates an update (see livestream).
This could be prevented to reduce auditlogs / unncessary stream entries

### Possible Solutions
Check if new selected value is different than existing and only update if there is a difference.

**Comment by nadouani** [comment]
This can be improved on the UI, but the backend must continue making an audit-log entry for any PATCH call.

**Comment by crackytsi** [comment]
Hi!
Understood, so I think this does not make sense, we can close it ;)
