### ISSUE TITLE
computed.* stats don't work

### ISSUE THREAD

**Issue by davinerd** [TheHive-Project/TheHive#936]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu (AWS)
| OS version (client)       | Ubuntu (AWS)
| TheHive version / git hash   | 3.2.1
| Package Type              | DEB
| Browser type & version    | N/A

### Problem Description
computed case metrics don't work.

### Steps to Reproduce
1. Open Dashboards
1. Open Case Statistics
1. The preloaded widget named "Case over time" shows no data and a red dialog pop up

### Complementary information
Looking at the API calls, this is the body of the POST request:
```
{"query":{"_between":{"_field":"createdAt","_from":1545350400000,"_to":1553212799999}},"stats":[{"_agg":"time","_fields":["createdAt"],"_interval":"1w","_select":[{"_agg":"avg","_name":"agg_1","_query":{"_field":"status","_value":"Resolved"},"_field":"computed.handlingDurationInHours"},{"_agg":"count","_name":"agg_2","_query":{}}]}]}
```

And this is the response from server:
```
{"type":"SearchError","message":"Invalid search query ([<redacted>][<redacted>:9300][indices:data/read/search])"}
```
I've tried to use any other `computed.*` with no luck.

I've dug into the code but when arrived here https://github.com/TheHive-Project/elastic4play/blob/ae79375ab85e2ac3a1970c61bb046ca12dd03138/app/org/elastic4play/models/ModelDef.scala I was unable to go further (I've no Scala knowledge).

**Comment by nadouani** [comment]
Hello, sounds like you elasticsearch instance doesn't allow inline scripts.

Please take a look to this https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#24-configure-and-start-elasticsearch

The configuration I'm talking about is `script.inline: true`

Please check and close the issue if this solves the problem.

**Comment by davinerd** [comment]
Yep that was it, thanks!
