### ISSUE TITLE
Raw Alert

### ISSUE THREAD

**Issue by zpriddy** [TheHive-Project/TheHive#945]
### Request Type
Feature Request

### Problem Description
It would be very useful to have a Raw Alert Data field. Right now I often dump json to the description field BJ it that gets very messy. It would be really nice to have a separate AlertData field that is plaintext (no links) where you could dump raw alert data to reference during an investigation. 

Thoughts about this? I know.it would take some changes to the DB and connector too..

**Comment by nadouani** [comment]
You can put it as a `other` observable, or create a dedicated observable datatype for it.

**Comment by zpriddy** [comment]
I didnt really want hive to try to find related events for each alert. I feel like that might put some stress on Hive
