### ISSUE TITLE
Cortex - A client error occurred on GET /index.html 

### ISSUE THREAD

**Issue by martinacen** [TheHive-Project/TheHive#948]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04.2 LTS
| TheHive version / git hash   | Unknown
| Package Type              | From source
| Browser type & version    | Mozilla 66.0.2

### Problem Description
Cannot access Cortex at http://127.0.0.1:9001 because message "A client error occurred on GET /index.html : Resource not found by Assets controller" occurs.

### Steps to Reproduce
1. In _opt/cortex_ I did _sudo bin/cortex -Dconfig.file=/etc/cortex/application.conf_ and no errors occurred.
2. sudo systemctl enable cortex
3. sudo systemctl start cortex

### Complementary information
After point 3 I checked the service using _sudo systemctl status cortex_ and the response was:

```
cortex.service - cortex
 Loaded: loaded (/usr/lib/systemd/system/cortex.service; enabled; vendor prese
 Active: failed (Result: exit-code) since Fri 2019-04-05 12:12:10 CEST; 23min 
 Docs: https://thehive-project.org
 Process: 3079 ExecStart=/opt/cortex/bin/cortex -Dconfig.file=/etc/cortex/appli
 Main PID: 3079 (code=exited, status=203/EXEC)

apr 05 12:12:10 martina-X555DG systemd[1]: Started cortex.
apr 05 12:12:10 martina-X555DG systemd[3079]: cortex.service: Failed to execute 
apr 05 12:12:10 martina-X555DG systemd[3079]: cortex.service: Failed at step EXE
apr 05 12:12:10 martina-X555DG systemd[1]: cortex.service: Main process exited, 
apr 05 12:12:10 martina-X555DG systemd[1]: cortex.service: Failed with result 'e
```

Here is my application.conf 
`play.http.secret.key="Lt4N6S16pfoh7KiruM7FfqrjNSo..."
host=["127.0.0.1:9300"]`

I hope you can help me to solve the issue, I need to use Cortex for my thesis.
Thank you very much!

**Comment by crackytsi** [comment]
Hi.
Your build from sourcecode has failed.
Did you build it as root? You need to be not root but a build user....

**Comment by nadouani** [comment]
This is not a TheHive issue. Please ask Cortex questions on the Cortex repo. Thanks
