### ISSUE TITLE
Import a File artifact from a Cortex job in Hive

### ISSUE THREAD

**Issue by david-neal-ms** [TheHive-Project/TheHive#949]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat
| OS version (client)       | Seven, 10
| TheHive version           | 3.2.1-1
| Cortex version           | 2.1.3-1
| Package Type              | From source
| Browser type & version    | Chrome

### Problem Description
Hive has the ability to import observables to a case that are returned by the results of a cortex job.
This functionality seems to be buried/broken for file types.
The desire is to be able to have an analyzer download a file, attach it to the report as an artifact, and have it be importable from hive.

### Complementary information
The issue would be for both TheHive and Cortex since Cortex would need to include the file observable in the report and TheHive would need to be able to import the file observable from the report.

**Comment by david-neal-ms** [comment]
Anyone in the community have any thoughts on this?
is is likely to be picked up or can you share your thoughts on how we should implement this?

Thanks

**Comment by nadouani** [comment]
Hello, didn't notice this FR, so we created a new one #982.

Closing this one as duplicate, because the git history comments refer to the other one.

**Comment by cndycc** [comment]
Hello,
it seems this feature has been implemented. However, so far I have not been able to find any references in the documentation or example code. Can anybody provide more information about importing cortex analyzer artifacts/results into a case?
