### ISSUE TITLE
Problem send event from MISP to The Hive

### ISSUE THREAD

**Issue by dimanchezzz** [TheHive-Project/TheHive#950]
### Problem Description
Describe the problem/bug as clearly as possible.
Hi guys, I set up The Hive tied to the cortex and the MISP, what should I do next so that the events from the MISP come to The HIve,  i didn't find tutorial, Help me pls, what should I do so that I receive notifications in The Hive??

**Comment by crackytsi** [comment]
What is your intension exactly?
Do you want to push observables to misp or receive alerts from misp?
Did you read the documentation here? https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#7-misp

**Comment by dimanchezzz** [comment]
yes, i create connections cortex, the hive, misp. 
as usual, after asking a question I found some solution. I receive alerts from MISP. It remains to understand how to send events to Cortex and receive answers?
 my analyzer cortex 
![Capture1](https://user-images.githubusercontent.com/31654635/55827767-a14a0600-5b13-11e9-9b7f-b288e3749928.PNG)

**Comment by crackytsi** [comment]
Great :)
TheHive polls MISP in regularly intervals as configured.

If you are in a case, there is a SHARE button, that pushes the data to a MISP System.

**Comment by dimanchezzz** [comment]
> Great :)
> TheHive polls MISP in regularly intervals as configured.
> 
> If you are in a case, there is a SHARE button, that pushes the data to a MISP System.

I should send data to Cortex on my fingers?
Or if The Hive connect to Cortex? he  auto send  for check to Cortex? 
Simple example : I enable virusTotal analyzer on Cortex, then I create job(Check domain), when this job Seccess, i see Cod(down below)
My question: I can get info from cortex, which  I send  from Thehive ?
Thx, this is last step on my job, it is important.
![Capture](https://user-images.githubusercontent.com/31654635/55871088-9bdfd080-5b92-11e9-9208-51c99d3b6d7f.PNG)

**Comment by dimanchezzz** [comment]
> Great :)
> TheHive polls MISP in regularly intervals as configured.
> 
> If you are in a case, there is a SHARE button, that pushes the data to a MISP System.

and further, what be result if i click this button?
![Capt1ure](https://user-images.githubusercontent.com/31654635/55872503-de56dc80-5b95-11e9-9717-e9333f85f1f6.PNG)
![Capture](https://user-images.githubusercontent.com/31654635/55872504-de56dc80-5b95-11e9-8569-c674ed147ffa.PNG)

**Comment by dimanchezzz** [comment]
I managed

**Comment by sikandar94iqbal** [comment]
> > Great :)
> > TheHive polls MISP in regularly intervals as configured.
> > If you are in a case, there is a SHARE button, that pushes the data to a MISP System.
> 
> I should send data to Cortex on my fingers?
> Or if The Hive connect to Cortex? he auto send for check to Cortex?
> Simple example : I enable virusTotal analyzer on Cortex, then I create job(Check domain), when this job Seccess, i see Cod(down below)
> My question: I can get info from cortex, which I send from Thehive ?
> What can I do with connection (The Hive-Cortex)?
> Thx, this is last step on my job, it is important.
> ![Capture](https://user-images.githubusercontent.com/31654635/55871088-9bdfd080-5b92-11e9-9208-51c99d3b6d7f.PNG)

can you please share what solution you have?
I am also having this issue and not able to import MISP events to HIVE.
Help would be appreciated!
