### ISSUE TITLE
Have AlertFilter for "New&Updated"

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#952]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.3.0-1
| Package Type              | RPM, DEB, Docker, Binary, From source
| Browser type & version    | Chrome

### Problem Description
Sometimes I want to filter for only new or only updated Alerts.
Then I want to search for New and Updated, but there is no filter in the QuickFilters.
Could we have this filter too?

**Comment by crackytsi** [comment]
@nadouani I'm not sure but I think this is solved by case #925

**Comment by nadouani** [comment]
In fact, thanks for catching this.
