### ISSUE TITLE
Suggestion: Marge cases on the oldest and close the newest as duplicated

### ISSUE THREAD

**Issue by mgabriel-silva** [TheHive-Project/TheHive#960]
I don't know about the other users, but for my organization is very common to find duplicates and merge cases.
Creating a new one every time is:
- taking away the accomplishment of the first one to treat that case, because the merged case owner is the one who merged, not the first to report it
- unproductive for other reports and sistems that have case numbers
- not inheriting custom fields from the original cases (this could be another issue by itself)
- closing both as duplicates, when I believe only the second is a duplicate (generating questionable duplicate count)
- when merging more than two cases, generating lots and confusing merged cases

Is there a reason not to just merge using the first case and adding the additional information?

**Comment by rriclet** [comment]
https://github.com/TheHive-Project/TheHive/pull/1798

**Comment by nadouani** [comment]
This is part of the new case merge feature in 4.1
