### ISSUE TITLE
MISP-Warninglists analyzer reported as outdated but is up to date

### ISSUE THREAD

**Issue by k41zen** [TheHive-Project/TheHive#970]
MISP-Warninglists analyzer reported as outdated but is up to date

### Request Type
Bug

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10
| TheHive version / git hash   | 3.3.0-1
| Package Type              | DEB
| Browser type & version    | Chrome

### Problem Description
When analyzing an observable the smart tags and the detailed report for MISP-warninglists shows "outdated". However, when I look at the date/timestamps they are up to date. When I also do a "git pull" its also up to date.

### Steps to Reproduce
An an IP as an observable and analyze.

**Comment by nadouani** [comment]
Hello, can you please move this issue to the [Cortex-Analyzers](https://github.com/TheHive-Project/Cortex-Analyzers/issues) repository. Thanks a lot
