### ISSUE TITLE
bintray repo for deb packages not signed

### ISSUE THREAD

**Issue by dharshanduck** [TheHive-Project/TheHive#976]
### Request Type
Bug?

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 10
| TheHive version / git hash   | 3.3.1
| Package Type              | DEB
| Browser type & version    | If applicable

### Problem Description
Attempting a sudo apt update says the below
```
E: The repository 'https://dl.bintray.com/thehive-project/debian-stable any Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps to Reproduce
1. Just run sudo apt update from system with previous version

**Comment by nadouani** [comment]
Hello @dharshanduck can you please check again, we did a refresh of the package metadata. Thanks

**Comment by dharshanduck** [comment]
Awesome it works now. Thanks @nadouani 
Just for me to understand, what happened exactly?

**Comment by nadouani** [comment]
The packages are deployed on Bintray, and sometimes it, the metadata refresh fails

**Comment by jwilczek** [comment]
I'm seeing this same issue today.

**Comment by zecchino1** [comment]
Just do:
sudo apt-key add <keyfile>
You can get the key file from here:
https://github.com/TheHive-Project/TheHive/blob/master/PGP-PUBLIC-KEY
