### ISSUE TITLE
Issues with Case-Filtering using Filters

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#977]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Seven
| TheHive version / git hash   | 3.3.1
| Package Type              | DEB
| Browser type & version    | Chrome

### Problem Description
I have a very strange issue:
Therea are several cases assigned to user "Username.User@example.com"
That can be seen in the case list, all are in Status "Open"

If I manually set filters in the case list to filter for all open cases:
Asignee=Username.User@example.com

I just get 3 (very old) cases and not the new ones.
But I am sure tha new ones exist and they even have assignes.
I tried to compare them by using the API-Call to retrieve the cases, the only difference I can see is that 
-old case has attribut u'_version': 1
-new case has attribut u'_version': 4

Can you help me?

### Steps to Reproduce
I have no idear to to reproduce that.

**Comment by crackytsi** [comment]
@To-om I checked several other cases: only cases with version=1 are visible, cases with version>1 are invisible. Is this a bug in TheHive or should I open an issue in Elastic4Play?

**Comment by To-om** [comment]
Hi @crackytsi 

Version doesn't affect the search. It used to prevent concurrent access to the same document and give information on how many this document has been updated.

Can you find the HTTP query which fails to find cases and give me the body (the search query) ? You can use the web developer console for that.
Can you also provide the case that should be returned by the search in JSON ?
You can anonymize the data but make sure there is no typo.

**Comment by crackytsi** [comment]
search is going to: /api/case/_search?range=0-10&nparent=10
{"query":{"_and":[{"_field":"owner","_value":"username.useri@example.com"},{"_and":[{"_not":{"status":"Deleted"}},{"_not":{"_in":{"_field":"_type","_values":["dashboard","data","user","analyzer","caseTemplate","reportTemplate","action"]}}}]}]}}

**Comment by To-om** [comment]
it seems correct

**Comment by crackytsi** [comment]
This was doing a search for all cases with owner=username.user@example.com

If I just do filtering in the case list the filter is this:
{"query":{"_and":[{"_string":"(owner:\"username.user@example.com\")"}]}}
which seems to also correct.

Correct is not the response, because it lacks of some cases.

**Comment by crackytsi** [comment]
The general case list (without a filter) shows the cases that were assigned to the owner without any issue.
Other filters seeems to work also correct.
If I retrieve a case found by that filter and a case not found by the filter, the only difference to me was the version field.

**Comment by crackytsi** [comment]
```
{
	u'startDate': 1541019842000,
	u'caseId': 13297,
	u'updatedAt': 1541074959154,
	u'owner': u'user.username@example.com',
	u'id': u'AWbL8LzalInpCZ8Y5V5H',
	u'createdAt': 1541019842871,
	u'pap': 2,
	u'_routing': u'AWbL8LzalInpCZ8Y5V5H',
	u'severity': 2,
	u'title': u'title1',
	u'_parent': None,
	u'customFields': {
		u'field1': {
		
			u'string': u'field1value'
		},
		u'field2': {
			u'order': 1,
			u'string': u'field2value'
		},
		u'field3': {
			u'order': 2,
			u'string': u'field3value'
		}
	},
	u'status': u'Open',
	u'_type': u'case',
	u'description': u'description',
	u'tags': [
		u'tag1',
		u'tag2',
		u'tag3',
		u'tag4'
	],
	u'metrics': {
		u'metric1': -1,
		u'metric2': -1,
		u'metric3': 5
	},
	u'flag': False,
	u'createdBy': u'user',
	u'updatedBy': u'user',
	u'tlp': 2,
	u'_version': 1,
	u'_id': u'AWbL8LzalInpCZ8Y5V5H'
}
```


And the new (inivisble case) is:

```
{
	u'startDate': 1558424220000,
	u'caseId': 24779,
	u'updatedAt': 1558424288130,
	u'owner': u'user.username@example.com',
	u'id': u'AWrZU3KGM31j2evBS_ul',
	u'createdAt': 1558424285489,
	u'pap': 2,
	u'_routing': u'AWrZU3KGM31j2evBS_ul',
	u'severity': 2,
	u'title': u'title2',
	u'_parent': None,
	u'customFields': {
		u'field1': {
			u'string': u'field1value'
		},
		u'field2': {
			u'string': u'field2value',
			u'order': 3
		},
		u'field3': {
			u'string': u'field3value',
			u'order': 1
		}
	},
	u'status': u'Open',
	u'_type': u'case',
	u'description': u'<fillhere>',
	u'tags': [
		u'tag1',
		u'tag2'
	],
	u'metrics': {
		u'metric1': -1,
		u'metric2': -1,
		u'metric3': -1
	},
	u'flag': False,
	u'createdBy': u'user.username@example.com',
	u'updatedBy': u'user',
	u'tlp': 2,
	u'_version': 3,
	u'_id': u'AWrZU3KGM31j2evBS_ul'
}
```

**Comment by To-om** [comment]
The related elasticsearch query is:
```
curl http://127.0.0.1:9200/the_hive_14/case/_search -d '
{
  "from" : 0,
  "query" : {
    "bool" : {
      "must" : [
        {
          "term" : {
            "owner" : {
              "value" : "user.username@example.com",
              "boost" : 1.0
            }
          }
        },
        {
          "bool" : {
            "must" : [
              {
                "bool" : {
                  "must_not" : [
                    {
                      "term" : {
                        "status" : {
                          "value" : "Deleted",
                          "boost" : 1.0
                        }
                      }
                    }
                  ],
                  "disable_coord" : false,
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              },
              {
                "bool" : {
                  "must_not" : [
                    {
                      "terms" : {
                        "_type" : [
                          "dashboard",
                          "data",
                          "user",
                          "analyzer",
                          "caseTemplate",
                          "reportTemplate",
                          "action"
                        ],
                        "boost" : 1.0
                      }
                    }
                  ],
                  "disable_coord" : false,
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              }
            ],
            "disable_coord" : false,
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      ],
      "disable_coord" : false,
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "version" : true,
  "stored_fields" : [
    "_source",
    "_routing",
    "_parent"
  ],
  "sort" : [
    {
      "_uid" : {
        "order" : "desc"
      }
    }
  ]
}
```
Can you run it and tell me if you the "invisible" cases appear ?

**Comment by crackytsi** [comment]
It is missing.

**Comment by To-om** [comment]
let's try a simpler query:
```
curl http://127.0.0.1:9200/the_hive_14/case/_search -d '
{
  "query": {
    "term": {
      "owner": {
        "value": "user.username@example.com",
      }
    }
  }
}
```

**Comment by crackytsi** [comment]
Hi,
The problem is, that the username is once uppercase and once lowercase.

**Comment by crackytsi** [comment]
value": "user.username@example.com" ==> Gives the older results
value": "User.Username@Example.com" ==> Gives the newer results
I have no clue how this was possible. Might be related that I use authentication using header variable on proxy. 

But what can I do now :-(

**Comment by crackytsi** [comment]
Oh no. My fault. I'm so sorry. Case can bei closed.
