### ISSUE TITLE
 There is no synchronization with MISP after setting application.conf

### ISSUE THREAD

**Issue by 1623664** [TheHive-Project/TheHive#981]
Question | Answer
-- | --
OS version (server) | CentOS 7
TheHive version / git hash | 3.3.0-1

**Problem Description**
There is no synchronization with MISP after setting application.conf

**application.conf**
```
misp {
  "MISP-SERVER-ID" {
    url = "https://misp...."
    key = "key"

    max-attributes = 1000
    max-size = 1 MiB
    max-age = 7 days
    exclusion {
     organisation = ["bad organisation", "other orga"]
     tags = ["tag1", "tag2"]
    whitelist.tags = ["whitelist-tag1", "whitelist-tag2"]
    purpose = ExportOnly
  }
  statusCheckInterval = 1 minute
  interval = 1h
}
  }
  statusCheckInterval = 1 minute
  interval = 1h
}

```

**Comment by 1623664** [comment]
![Снимок экрана от 2019-05-28 12-07-34](https://user-images.githubusercontent.com/18025686/58466352-2d56d200-8142-11e9-846a-bab84ab41ff1.png)

**Comment by 1623664** [comment]
What am I doing wrong?

**Comment by garanews** [comment]
what do you see in /var/log/thehive/application.log ?
Do you see something like:
```
2019-05-28 09:28:01,556 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-30 - Update of MISP events is starting ...
2019-05-28 09:28:01,572 [INFO] from connectors.misp.MispSynchro in application-akka.actor.default-dispatcher-25 - Last synchronization of MISP misp-instance-1 is Tue May 28 09:22:33 UTC 2019, synchronize from Tue May 28 09:22:33 UTC 2019


```

**Comment by 1623664** [comment]
![Снимок экрана от 2019-05-28 12-30-21](https://user-images.githubusercontent.com/18025686/58467770-efa77880-8144-11e9-8e68-773eda1be5b3.png)

**Comment by 1623664** [comment]
maybe the MISP connector must be enabled?

**Comment by garanews** [comment]
do you have this row in /etc/thehive/application.conf :
`play.modules.enabled += connectors.misp.MispConnector`

**Comment by 1623664** [comment]
no

**Comment by garanews** [comment]
add it :)

**Comment by 1623664** [comment]
![Снимок экрана от 2019-05-28 14-02-24](https://user-images.githubusercontent.com/18025686/58473721-056f6a80-8152-11e9-9fd8-061f57205750.png)

**Comment by 1623664** [comment]
thank!!! Now there are problems with synchronization

**Comment by 1623664** [comment]
/etc/thehive/application.conf 

```
play.modules.enabled += connectors.misp.MispConnector
misp {
  interval = 1h
  "MISP" {
    url = "https://misp..."
    key = "key"
    tags = ["misp"]
    max-attributes = 1000
    max-size = 10 MiB
    max-age = 7 days
    purpose = ExportOnly
  }
}
```

**Comment by 1623664** [comment]
version MISP by MISP 2.4.100

**Comment by garanews** [comment]
what kind of problems?

**Comment by nadouani** [comment]
Hello, please describe your problem, otherwise nobody could help :)

**Comment by nadouani** [comment]
`ERROR` means TheHive is not able to rich MISP, or there is an issue fetching the MISP status. Please double check the MISP URL and API Key, and make sure the MISP user has `sync` role in MISP user management.

**Comment by 1623664** [comment]
Thanks for the quick response

**Comment by 1623664** [comment]
![Снимок экрана от 2019-05-28 17-26-43](https://user-images.githubusercontent.com/18025686/58486328-555c2a80-816e-11e9-84a2-7cf2a02a2ad5.png)
 Key and URL are correct

**Comment by 1623664** [comment]
[A new task has been opened](https://github.com/TheHive-Project/TheHive/issues/989)
