### ISSUE TITLE
Ver 3.3.0-1 - issue with export multiple alerts into a case 

### ISSUE THREAD

**Issue by antonyimmanuvell** [TheHive-Project/TheHive#984]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
Bug 

If we select multiple alerts and select " New case from selection " then none of the alerts are getting exported into the case . 

If we select one alert and use " New case from selection "  then I see alerts are visible in the case 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu, 
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive version  Ver 3.3.0-1 

TheHive.  3.3.0-1
Elastic4Play. 1.10.0
Play. 2.6.21
Elastic4s. 5.6.6
ElasticSearch. 5.6.9

| Package Type              | RPM, DEB, Docker, Binary, From source
| Browser type & version    | If applicable

### Problem Description
If we select multiple alerts and select " New case from selection " then none of the alerts are getting exported into the case . 

If we select one alert and use " New case from selection "  then I see alerts are visible in the case

### Steps to Reproduce
1. step 1. Select Multiple alerts under alerts section 
1. step 2 select " " New case from selection "
1. step 3... click on create case .. 

Alerts are not displaying in the case 

### Possible Solutions
We assume its a bug in the current version

**Comment by crackytsi** [comment]
HI,
I cannot reproduce that issue with 3.4 RC1.

I can see "related alerts" and the observables of the alerts are imported (so for me it works as expected).
Can you give us more details/screenshots etc?

**Comment by antonyimmanuvell** [comment]
Currently we are using 3.3.0-1 and we are waiting for the binary release for 3.4 
may be we will upgrade the see if the issue still exist 
Regards, Anto 

    On Thursday, June 13, 2019, 6:15:06 PM GMT+2, crackytsi <notifications@github.com> wrote:  
 
 
HI,
I cannot reproduce that issue with 3.4 RC1.

I can see "related alerts" and the observables of the alerts are imported (so for me it works as expected).
Can you give us more details/screenshots etc?

**Comment by crackytsi** [comment]
Hmm, but I don't think that anything has changed there. I was using this also with 3.3.
Can you make some screenshots?

**Comment by nadouani** [comment]
Yes, 3.4.0 doesn't introduce changes to this feature, so I don't think it will solve the issue if it happens to you in 3.3.0. Do you have any logs?

**Comment by rriclet** [comment]
Please feel free to reopen if needed.
