### ISSUE TITLE
Run responder failed due too long task description

### ISSUE THREAD

**Issue by i223t** [TheHive-Project/TheHive#986]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04 4.4.0-142
| OS version (client)       | 10
| TheHive version / git hash   | 3.3.0-1
| Package Type              | Binary

### Problem Description
Run responder on case ask failed due too long task description.

### Steps to Reproduce
1. Create a case with a very long description (more than 32766)
2. Create any task or observable
3. Try to run responder on it

### Complementary information
TheHive log:

2019-05-29 16:07:31,884 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-5 - POST /api/connector/cortex/action returned 500
connectors.cortex.services.CortexError: Cortex error on http://192.168.1.1:9999/api/responder/d3c23a0b82fd230af9f1048afb44fcd1/run (500)
{"type":"CreateError","message":"Document contains at least one immense term in field=\"data\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[123, 34, 102, ...', original message: bytes can be at most 32766 in length; got 63505","object":{"createdAt":1559120928412,"pap":2,"...

**Comment by nadouani** [comment]
This will be fixed by Cortex 3.0.0 (because it's a Cortex bug, and Cortex 3.0.0-RC3 is still in Beta) and TheHive 3.4.0 that adds support to Cortex 3.

I'll close this issue for now, and please feel free to test this and reopen the issue if the versions above don't fix the issue.

Thanks

**Comment by nadouani** [comment]
To be precise, it's fixed by https://github.com/TheHive-Project/Cortex/issues/178
