### ISSUE TITLE
Failure to load datatypes

### ISSUE THREAD

**Issue by joseluratm** [TheHive-Project/TheHive#988]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| TheHive version / git hash   | 3.3.0
| Package Type              |  Binary
| Browser type & version    | Chrome

### Problem Description
I have noticed that if in Observables, in the view of "Observable datatypes management" if we add a datatype and it is repeated, when we click on a case in the 'Add observables' button, the elements do not appear in the dropdown list. And in the browser console we receive this message:

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: type in types, Duplicate key: string:cookie, Duplicate value: cookie
```

### Steps to Reproduce
1. Repeat observable DataType
1. Go to Add observable in a case
1. The dropdown doesnt show nothing

### Possible Solutions
- Avoid that a datatype that exist doesnt can create.

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

**Comment by nadouani** [comment]
How did you add a duplicate datatype? This is not allowed by TheHive
