### ISSUE TITLE
MISP - Unknown version (ERROR) 

### ISSUE THREAD

**Issue by 1623664** [TheHive-Project/TheHive#989]
Question | Answer
-- | --
OS version (server) | CentOS 7
TheHive version / git hash | 3.3.0-1

**Problem Description**
There is no synchronization with MISP after setting application.conf

**application.conf**
```play.modules.enabled += connectors.misp.MispConnector
misp {
  interval = 1h
  "MISP" {
    url = "https://misp...."
    key = ".........."
    tags = ["misp"]
    max-attributes = 1000
    max-size = 10 MiB
    max-age = 7 days
    purpose = ExportOnly
  }
}
```

**Comment by 1623664** [comment]
![Снимок экрана от 2019-05-28 14-02-24](https://user-images.githubusercontent.com/18025686/58636229-7d779500-82f8-11e9-85e7-09442b42ff73.png)
![Снимок экрана от 2019-05-28 17-20-25](https://user-images.githubusercontent.com/18025686/58636230-7e102b80-82f8-11e9-8698-10bbb000dc1b.png)
![Снимок экрана от 2019-05-28 17-26-43](https://user-images.githubusercontent.com/18025686/58636231-7e102b80-82f8-11e9-8161-3e969f19ea03.png)

**Comment by 1623664** [comment]
![Снимок экрана от 2019-05-30 16-28-26](https://user-images.githubusercontent.com/18025686/58636253-8cf6de00-82f8-11e9-8e47-d34e54cea6d9.png)

**Comment by github-pba** [comment]
Can't confirm, works for me.

MISP Config in theHive's application.conf:

`
play.modules.enabled += connectors.misp.MispConnector
misp {
interval = 1h
  "MY-MISP" {
      url = "https://mymisp.domain.com"
      key = "...."
      caseTemplate = "MISPimport"
      max-attributes = 1000
      max-size = 1 MiB
      max-age = 7 days
}}
`
In MISP, I have a user of type "sync user" and the organsation I want to import IOCs into. This users AuthKey is used.

You might want to review the URL. This is the URL where the MISP is reachable from the web.

**Comment by 1623664** [comment]
Thank you very much, but your example did not help me.

**Comment by crackytsi** [comment]
Are you Sure the certificate Of misp instance is trusted?

**Comment by 1623664** [comment]
Thank you all for the help.
The problem was in the certificate
