### ISSUE TITLE
Java 11 build crash

### ISSUE THREAD

**Issue by siisar** [TheHive-Project/TheHive#990]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18
| TheHive version / git hash   | last version
| Package Type              | From source

### Problem Description
When trying to build the project from the doc section "Build it Yourself", it crashes when executing:
./sbt clean stage
The errors are related to VM options that are no longer supported in Java 11 (for instance UseConcMarkSweepGC, UseParNewGC)

### Steps to Reproduce
Try to build from source, with java 11, with the command ./sbt clean stage

### Possible Solutions
Please adjust the VM options to java 11

**Comment by To-om** [comment]
Can you provide more details ? What is the output ?

**Comment by siisar** [comment]
$ ./sbt clean stage
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

After trying removing the VM option UseParNewGC, the error persists this way:

OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error occurred during initialization of VM
Multiple garbage collectors selected

So the VM options need reviewing and being adjusted to java 11
