### ISSUE TITLE
[Bug] Case Template API - tasks order attribute not functional

### ISSUE THREAD

**Issue by defensivedepth** [TheHive-Project/TheHive#999]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| TheHive version / git hash   | 3.3.0-1
| Package Type              | Docker

### Problem Description
Using the guidance from here:
https://github.com/TheHive-Project/TheHiveDocs/issues/63#issuecomment-416849288

The task `order` attribute appears to not be functioning - no matter what I set it to, the tasks do not change order in the UI.

### Steps to Reproduce

1)
`curl 'https://address/thehive/api/case/template/xxxxxxx' -X PATCH -H 'Content-Type: application/json;charset=utf-8'  -H 'Authorization: Bearer xxxxxxx' --data @casetasks.json`

casetasks.json = 

`{"tasks":[{"order":2,"title":"Step 2","description":"Step 2 Description"},{"order":1,"title":"Step 1","Step 1 description":""}]}`

2) View the case template in the UI - Step 2 is first and Step 1 is second. Swapping the `order` numbers has no effect.  The only way to change the order is to move Step 1 into the first position within the json itself.

**Comment by nadouani** [comment]
Are you sure you use a correct json content to update the template:

```
{
  "tasks": [{
    "order": 2,
    "title": "Step 2",
    "description": "Step 2 Description"
  }, {
    "order": 1,
    "title": "Step 1",
    "Step 1 description": ""
  }]
}
```

Your second task is weird, look at the description. Do you have error logs?

**Comment by rriclet** [comment]
Please feel free to reopen if needed.
